### ISSUE TITLE
s3fs POSIX permissions on Google Storage

### ISSUE THREAD

**Issue by cafarm** [s3fs-fuse/s3fs-fuse#1009]
Does s3fs support POSIX permissions uploaded to Google Storage with `gsutil cp -P`?

Or do you need to mount the bucket with s3fs and copy in the files to preserve file permissions?

**Comment by cafarm** [comment]
It looks like s3fs uses the metadata headers gid, mode, mtime, and uid, where `gsutil cp -P` uses the metadata headers goog-reserved-posix-gid, -mode, -uid, -file-mtime. Dang. 

Any chance s3fs can consider supporting gutil's metadata header names? `gsutil -m` is much faster at uploading a significant amount of data than s3fs.

**Comment by gaul** [comment]
It is possible to add a flag which uses these headers instead.  Pull requests welcome!

**Comment by mcafaro** [comment]
Ok, I’ll try to investigate what it would take.

**Comment by cafarm** [comment]
Ok great, I’ll investigate

**Comment by gaul** [comment]
@cafarm any updates?

**Comment by cafarm** [comment]
I ended up taking a different approach that did not require this feature, so I no longer have a use for it. This issue can be closed if you feel like the feature has limited interested.

**Comment by gaul** [comment]
Fixed by #1286.
