### ISSUE TITLE
Sub-object caching

### ISSUE THREAD

**Issue by cafarm** [s3fs-fuse/s3fs-fuse#1010]
Is s3fs capable of sub-object caching? Meaning if I have a large object and I only read a portion of it, can s3fs cache just that portion?

I've been doing a bit of experimenting but I've never seen anything show up in the cache folder even when I read an entire file.

**Comment by ggtakec** [comment]
If you open () and read () a file, s3fs will perform partial download according to the range.
And if you specify use_cache, partially downloaded content will be stored under that directory.
(The cache file is a file with "holes" using truncate)

**Comment by gaul** [comment]
I believe @ggtakec answered this.  Please reopen if I misunderstand.
