### ISSUE TITLE
Problem on mounting s3

### ISSUE THREAD

**Issue by lays147** [s3fs-fuse/s3fs-fuse#1018]
#### Version of s3fs being used (s3fs --version)
➜  ~ s3fs --version
Amazon Simple Storage Service File System V1.82(commit:unknown) with GnuTLS(gcrypt)

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Version: 2.9.7-1ubuntu1

#### Kernel information (uname -r)
4.15.0-47-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="KDE neon"
VERSION="Testing Edition"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon Testing Edition"
VARIANT="Testing Branches"
VERSION_ID="18.04"
HOME_URL="http://neon.kde.org/"
SUPPORT_URL="http://neon.kde.org/"
BUG_REPORT_URL="http://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

#### s3fs command line used, if applicable
```
s3fs mybucket ~/s3 -o use_cache=/tmp -o passwd_file=${HOME}/.passwd-s3fs

```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
### Details about issue
I am trying to mount my s3 bucket locally, but with that command, my folders aren't available for R/W. If I use umask=0022, I can R/W, but folders that have subfolders, are handled like objects and not folders so I can't access anything.
https://imgur.com/a/NTGxFAE

So any tips on how to mount my bucket successfully?

**Comment by lays147** [comment]
### Debug info
```
abr 19 12:26:56 lays-Latitude-3490 s3fs[5672]: s3fs: MOUNTPOINT directory /home/lays/s3 is not empty. if you are sure this is safe, can use the 'nonempty' mount option.
abr 19 12:27:02 lays-Latitude-3490 s3fs[5694]: s3fs.cpp:s3fs_init(3378): init v1.82(commit:unknown) with GnuTLS(gcrypt)
abr 19 12:27:02 lays-Latitude-3490 s3fs[5694]: Libgcrypt warning: missing initialization - please fix the application
```

**Comment by gaul** [comment]
Could you try with the latest 1.85?  This fixes behavior related to folders not created by s3fs.

**Comment by gaul** [comment]
I believe 1.85 fixes this issue.  Please reopen if symptoms persist.

**Comment by anastazya** [comment]
I have the same issue, and this is the version : 

Amazon Simple Storage Service File System V1.86 (commit:unknown) with GnuTLS(gcrypt)
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by gaul** [comment]
Please try with the latest version 1.89.  If this doesn't work, open a new issue with debug logs from `s3fs -f -d`.
