### ISSUE TITLE
Time problem with large files

### ISSUE THREAD

**Issue by DigitalCyberSoft** [s3fs-fuse/s3fs-fuse#1019]
This is using the latest built version of s3fs.

While uploading a very large file, it eventually starts throwing the following error until retries run out

```
[ERR] curl.cpp:RequestPerform(2273): HTTP response code 403, returning EPERM. Body Text: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too `large.</Message><RequestTime>20190425T030525Z</RequestTime><ServerTime>2019-04-25T03:20:29Z</ServerTime><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>6DF0BC81DF47A</RequestId><HostId>Bk0RsQE3gAMknO52Din1h13t0b57Vpphx6fTizHRlTspybFoIDCmvhbW+s6mEwz96EUybZcA=</HostId></Error>`

```
File size is 342,798,923,129 bytes and the error at around [start=342360064000][size=438859129][part=654]

For reference:

```
# ntpdate us.pool.ntp.org
24 Apr 20:23:53 ntpdate[4203]: adjust time server 74.117.214.2 offset -0.002418 sec

```

**Comment by gaul** [comment]
I wonder if the retry code updates `x-amz-date` and resigns the request?

**Comment by DigitalCyberSoft** [comment]
> I wonder if the retry code updates `x-amz-date` and resigns the request?

I assumed something like this, as the problem appears to have popped up 30-40 minutes after the upload started.

**Comment by gaul** [comment]
You can probably work around this by downgrading to version 1.84 until we can address this properly.
