### ISSUE TITLE
Amazon to Disable S3 Path-Style Access - Does it Matter to s3fs?

### ISSUE THREAD

**Issue by jamiejackson** [s3fs-fuse/s3fs-fuse#1029]
Is s3fs affected by this change? https://www.bleepingcomputer.com/news/security/amazon-to-disable-s3-path-style-access-used-to-bypass-censorship/

**Comment by gaul** [comment]
s3fs supports both host- and path-style access and defaults to the former.  If users opt-in to the latter with AWS they may experience issues.

**Comment by jamiejackson** [comment]
Ah, right, thanks: https://github.com/s3fs-fuse/s3fs-fuse/blame/master/README.md#L109-L119

Should new versions of s3fs emit some sort of deprecation notice?

**Comment by jamiejackson** [comment]
Oh, I see that there may be other S3 implementations besides AWS. I hadn't known that. I guess that those could continue to support the path style, so a deprecation notice might not be appropriate (or at least more complicated to implement).
