### ISSUE TITLE
Continuous increase of cpu and mem usage in ubuntu 18.04

### ISSUE THREAD

**Issue by substa** [s3fs-fuse/s3fs-fuse#1031]
#### Version of s3fs being used (s3fs --version)
V 1.82

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.7

#### Kernel information (uname -r)
4.15.0-48-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
Ubuntu 18.04.2 LTS

#### s3fs command line used, if applicable
```
s3fs -o allow_other,use_cache=/tmp bucket mountpoint
```

### Details about issue

Continuous increase of cpu and mem usage.

After 10 minutes:
  PID  PPID CMD                         %MEM %CPU
25006     1 s3fs -o allow_other,use_cac  4.9  6.7

After 20 minutes:
  PID  PPID CMD                         %MEM %CPU
25006     1 s3fs -o allow_other,use_cac  7.6  12.8

etc etc, cpu and mem usage continue to increase until the crash...

The problem started after the upgrade to current LTS ubuntu release.

Temporarily I'm fixing with a cron script that unmount and remount every N minutes...

(P.S.  already added bucket mountpoint to PRUNEPATHS in /etc/updatedb.conf)

**Comment by gaul** [comment]
Could you test with the latest version 1.85?  It includes many fixes and 1.82 is several years old.

**Comment by substa** [comment]
On my repo 1.82 is the latest.
Is there an alternative repo or I have to install manually?

**Comment by gaul** [comment]
I reported https://bugs.launchpad.net/ubuntu/+source/s3fs-fuse/+bug/1828849 to Ubuntu to upgrade their s3fs version but you should try [compiling from source](https://github.com/s3fs-fuse/s3fs-fuse/blob/master/COMPILATION.md) in the interim.

**Comment by substa** [comment]
Ok perfect, 
version 1.86 seems to have fixed the bug.

Thank you :)
