### ISSUE TITLE
Unable to Mount an S3 bucket to multiple EC2 instances using s3fuse

### ISSUE THREAD

**Issue by yashwanthkalva** [s3fs-fuse/s3fs-fuse#1034]
### Additional Information
Can we mount an S3 bucket to multiple ec2 instances using s3fuse ?

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_example: 2.9.4_

**Comment by gaul** [comment]
If you use s3fs to interact with static, read-only data sets it will work fine.  If you modify your data, please look at setting `-o stat_cache_expire` which limits the amount of stale data that s3fs to a specified time.
