### ISSUE TITLE
Limit Cache Size

### ISSUE THREAD

**Issue by Jafo232** [s3fs-fuse/s3fs-fuse#106]
Is there a way to limit the size of the cache, or somehow expire items in the cache after X amount of time?

**Comment by ggtakec** [comment]
Now s3fs does not have the function which is limiting cache size.
But there is sample script in test/sample_delcache.sh, maybe it helps to solve your problem.
This script searches files in cache directory and removing cache files by sorted atime.

Please try to use and modify the script.
Thanks in advance for your assistance.

**Comment by ggtakec** [comment]
#280(#269) supports ensure_diskfree option, it limits cache size on your disk.
I'm closing this issue, if you have a problem yet, please post new issue or reopen this issue.

Thanks in advance for your help.
