### ISSUE TITLE
interoperability / Permissions with other tools

### ISSUE THREAD

**Issue by nzjrs** [s3fs-fuse/s3fs-fuse#108]
Files uploaded with s3cmd / s4cmd are not readable by s3fs-fuse. Is this a bug or a permissions issue.

Both tools were using root credentials and no IAM stuff. The documentation here is quite poor to help understand this sort of problem.

**Comment by ggtakec** [comment]
I'm sorry for replying late.

I think that the problem maybe the reason that objects on S3 do not have a-amz-meta-*** headers.
s3fs uses a-amz-meta-*** headers, those points the file attributes about mode/uid/gid/mtime.

Then you could not access the objects, you can do two way.
One is that you set these header to all object, the other you run s3fs with umusk and uid and gid options.
If you run s3fs with umask/gid/uid and you modify the object(file/directory), these object will have those headers.
(When you modify the object through s3fs, then the object is set those header by s3fs.)

Last, I'm sorry about poor documentation about s3fs now.

If you find a bug/problem, please post new issue.

Thanks in advance for your assistance.

**Comment by nzjrs** [comment]
Ok thanks. I also filed this

https://github.com/bloomreach/s4cmd/issues/19

so maybe s4cmd will implement the necessary compatibility headers

**Comment by ggtakec** [comment]
@nzjrs Thanks a lot.
