### ISSUE TITLE
s3fs: specified unknown third option(–o).

### ISSUE THREAD

**Issue by sgdmediagroup** [s3fs-fuse/s3fs-fuse#1083]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
1.85

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.4

#### Kernel information (uname -r)
4.4.0-141-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
Ubuntu 16.04.5 LTS 

#### s3fs command line used, if applicable
s3fs nuevobucket /mnt/mybucket –o passwd_file=$HOME/.cos_creds -o url=https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints

#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
not working
### Details about issue
I get the following message after running the command mentioned above: 
s3fs: specified unknown third option(–o).

**Comment by gaul** [comment]
The first option flag uses –o instead of -o like the second one.  Use the second one.

**Comment by sgdmediagroup** [comment]
Thanks @gaul , that was it!
