### ISSUE TITLE
s3fs core due to fd_manager_lock 

### ISSUE THREAD

**Issue by liuyongqing** [s3fs-fuse/s3fs-fuse#1091]
#### Version of s3fs being used (s3fs --version)
s3fs 1.84, master branch source code compile

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
fuse 2.9.4

#### Kernel information (uname -r)
Linux 7e812c9e54b6 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
ubuntu 16.04

### Details about issue
the coredump call backtrace is:
![image](https://user-images.githubusercontent.com/5205797/61167134-52759780-a56c-11e9-9c46-74060f341059.png)

the crash was triggered by:
1. thread A call FdManager::Open and create a FdEntity
2. thread B call FdManager::Open and get  thread A created FdEntity and trying to call ent->Open
3. thread A call FdManager::Close and deleted the FdEntity
4. thread B continue ent->Open execute and then crashed due to "double free or corruption (out)"

**Comment by liuyongqing** [comment]
@ggtakec

**Comment by ggtakec** [comment]
@liuyongqing Thank you for the report. Earlier, your PR was merged.
Please let us know if you notice any problems in the future.
