### ISSUE TITLE
0 byte files

### ISSUE THREAD

**Issue by jonbev** [s3fs-fuse/s3fs-fuse#11]
We have a problem where we are getting 0 byte files written back to s3. I can seem to find a way to replicate as it seems to be quite random. We cant tell if it is a s3fs issue or something on our side.

I was wondering if there is a way of disallowing 0 byte files from being written?

Thanks.

**Comment by ggtakec** [comment]
I'm sorry about this Issue had been left at a long period of time.

s3fs makes 0 byte file before uploading new file(object), normally the object size is changed after uploading the object.
But that the file size is still 0 bytes means that it has failed to upload.

Latest codes are fixed about multipart uploading etc, please test latest codes.
Anf if you have a problem yet, please post new issue about latest codes.

I'm closing this issue now, thanks in advance for your help.

**Comment by KrzysztofMadejski** [comment]
Just noting as I have problem related to that: My provider of S3 don't like 0-byte files (soft refuses to upload it) and that stops me from being able to write to S3. I'll come back if I find any solution.

```
Dec 28 13:57:19 dp s3fs[23671]: curl.cpp:RequestPerform(1946): Body Text: <?xml version="1.0" ?>#012<Error>#012    <Code>EntityTooSmall</Code>#012    <Message>Your proposed upload is smaller than the minimum allowed object size.</Message>#012    <RequestId>78AA0895</RequestId>#012    <BucketName>resources</BucketName>#012    <KeyName>8f-d0cc-45bc-8a1f-6e1204793bb4</KeyName>#012    <HostId>f2:0</HostId>#012    <Date>Wed, 28 Dec 2016 12:57:18 GMT</Date>#012</Error>
```

**Comment by alperen66** [comment]
Hi Im really new to github just made a account to write here
Recently fuse is not working ı cant export anything it says 0kb everytime
ı also try to reinstall but never worked, even try to download it from other websites.
and today ı found the adobe fuse cc version and tried to export again but it didnt worked again
please ı really need to use this software if you know the solve of this problem what can ı do ?
