### ISSUE TITLE
Option to disable pages merging

### ISSUE THREAD

**Issue by fcand-anevia** [s3fs-fuse/s3fs-fuse#112]
### Use case
I need to have some softwares that do random access to parts of objects. I cannot wait for the whole object to be downloaded, when I just need to access the first megabyte of data.

The current implementation merges available pages and download the object to the end. If a software needs to read small piece of data it will need to wait for the download to complete.

It would be convenient to have an option that disables it. I have a patch for this, if you are interested in reviewing it ...

**Comment by ggtakec** [comment]
Hi,

I fixed two bug at #138 which made from issue #97.
One of bug is you know, s3fs try to load whole of file.
#138 fixed it, please try to use master branch codes.

If you find ugs, please post new issue.

Thanks for your assistance.

**Comment by fcand-anevia** [comment]
Nice :) i will try and check it out.
Regards
Le 8 mars 2015 13:25, "Takeshi Nakatani" <notifications@github.com> a écrit
:
