### ISSUE TITLE
fstab automount not working

### ISSUE THREAD

**Issue by lxknvlk** [s3fs-fuse/s3fs-fuse#1132]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
1.82

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.7

#### Kernel information (uname -r)
4.15.0-1044-aws

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

### Details about issue
i succesfully mount the s3 with next command 
>sudo s3fs bucket /home/ubuntu/s3photobucket -o allow_other -o uid=1000 -o passwd_file=/home/ubuntu/passwd-s3fs -o mp_umask=002 -o multireq_max=5 -o use_path_request_style -o url=https://s3.us-east-1.amazonaws.com

df -h shows correct mount and s3 files are accesible like expected.

then i try to put next line in fstab 
>s3fs#bucket /home/ubuntu/s3photobucket fuse _netdev,allow_other,umask=002,uid=1000,url=https://s3.us-east-1.amazonaws.com,use_path_request_style,passwd_file=/home/ubuntu/passwd-s3fs,multireq_max=5 0 0

All same options. After reboot df -h shows mount, but the files are not accesible.

I also tried without `_netdev` parameter, same. When trying to access file in s3 bucked, everything just hangs.

I also tried in the exact same order like in the working mount commant 
>s3fs#bucket /home/ubuntu/s3photobucket fuse allow_other,uid=1000,passwd_file=/home/ubuntu/passwd-s3fs,mp_umask=002,multireq_max=5,use_path_request_style,url=https://s3.us-east-1.amazonaws.com

Am i doing something wrong with the fstab command?

**Comment by lxknvlk** [comment]
The problem was in windows carriage returns in the script file.

The output error was like this:

'use: unknown option `curldbg

Actually it was trying to print our next error:

fuse: unknown option `curldbg<CR>'

So, there seems to be some problems with the error output.

**Comment by gaul** [comment]
Duplicate of #1139?

**Comment by lxknvlk** [comment]
same problem was here - CR line endings instead of unix new lines
