### ISSUE TITLE
Nothing happens after mounting

### ISSUE THREAD

**Issue by lonelyspoon** [s3fs-fuse/s3fs-fuse#1140]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
V1.85

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.4

#### Kernel information (uname -r)
4.4.0-1084-aws

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
16.04.5 LTS (Xenial Xerus)

#### s3fs command line used, if applicable
sudo s3fs aispeak-seoul-lg -o use_cache=/tmp -o allow_other -o uid=1000 -o mp_umask=002 -o multireq_max=5 /audiodata

#### /etc/fstab entry, if applicable
s3fs#aispeak-seoul-lg /audiodata fuse allow_other 0 0

#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)

Sep  3 10:16:10 ip-172-31-43-206 s3fs[28866]: init v1.85(commit:ae4bcd4) with OpenSSL
Sep  3 10:16:11 ip-172-31-43-206 s3fs[28866]: s3fs.cpp:s3fs_check_service(3864): Failed to connect by sigv4, so retry to connect by signature version 2.
Sep  3 10:16:11 ip-172-31-43-206 s3fs[28866]: s3fs.cpp:s3fs_check_service(3879): invalid credentials(host=https://s3.amazonaws.com) - result of checking service.

### Details about issue
I accidentally deleted my security credentials on AWS and tried to hook up the original bucket to the original directory but it didn't work. So I decided to create a new bucket with new policy, and a new directory but now it's returning invalid credentials even though the security credentials are correct.

**Comment by lxknvlk** [comment]
You probably have to create new AMI credentials and use them

**Comment by lonelyspoon** [comment]
Hey Alex. Yeah I did create a new set of credentials and double checked if
it's the right policy I'm using

**Comment by lxknvlk** [comment]
have you set new credentials in $ aws-configure ?

**Comment by lonelyspoon** [comment]
I did it in aws console.

Tried to do a brand new set of credential/bucket/ clean installation too

**Comment by lxknvlk** [comment]
I see that your fuse line does not have _netdev option, maybe try adding it.

**Comment by gaul** [comment]
Did you find a workaround?  This looks like a credential mismatch.

**Comment by gaul** [comment]
Please reopen if symptoms persist.
