### ISSUE TITLE
Readlink spams s3curl calls even when cache is specified

### ISSUE THREAD

**Issue by AgrawalAmey** [s3fs-fuse/s3fs-fuse#1148]
### Additional Information
I am creating a symlink within the mounted directory to a local directory. This local directory is used to store some application data and sees a lot of fs calls. From the logs, it appears that even though both file and stat cache are enabled the readlink call always makes a s3curl call to get the link target path.

#### Version of s3fs being used (s3fs --version)
1.85

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
3.6.2

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
CentOS/AMZ Linux

#### s3fs command line used, if applicable
```
s3fs <bucket> <local-dir> -f -d -d -o \
use_path_request_style,\
allow_other,\
use_cache=<cache_dir>,\
stat_cache_expire=30,\
iam_role=auto
```

**Comment by gaul** [comment]
Addressed by PRs.
