### ISSUE TITLE
 invalid credentials - result of checking service

### ISSUE THREAD

**Issue by flmuse** [s3fs-fuse/s3fs-fuse#1156]
### Additional Information
bucket = bucketfstwo

#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.79(commit:unknown) with GnuTLS(gcrypt)

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
fusermount version: 2.9.4

#### Kernel information (uname -r)
4.15.0-62-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

#### s3fs command line used, if applicable
echo AKIAIJP4VDSADOMC6V2:BN9qeZ5kd6uwq9X81fB/5kM2o+SNOzr/hI9FEnfO > /home/luca/pass10

cat /home/luca/pass10
AKIAIJP4VDSADOMC6V2:BN9qeZ5kd6uwq9X81fB/5kM2o+SNOzr/hI9FEnfO

chmod 600 pass10

mkdir fs10
s3fs -f bucketfstwo /home/luca/fs10 -o passwd_file=/home/luca/pass10

[CRT] s3fs_init(3294): init v1.79(commit:unknown) with GnuTLS(gcrypt)
[CRT] s3fs_check_service(3707): invalid credentials - result of checking service.

#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
### Details about issue
credentials saved to pass10, also tried ~/.passwd-s3fs and have resulted in same error.

resulting in " invalid credentials - result of checking service" error.

pls advise what needs to be done.

Thanks.

**Comment by mauricev** [comment]
I am seeing the same issue.

**Comment by gaul** [comment]
Could you test with the latest 1.85 version instead of 1.79?  The latter is 4 years old and has several authentication issues.

**Comment by mauricev** [comment]
I am using 1.85

**Comment by gaul** [comment]
Please test with `-o curldbg` and reopen if symptoms persist.
