### ISSUE TITLE
S3FS API calls

### ISSUE THREAD

**Issue by Lilitapudane** [s3fs-fuse/s3fs-fuse#1166]
#### Version of s3fs being used (s3fs --version)
1.85

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.2

#### Kernel information (uname -r)
_command result: 3.10.0-957.12.2.el7.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_command result: NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"

### Details about issue

Hi, 
We are interested in S3FS use, so now we are testing, if it's fits our needs. 
I have following question, how I can see S3FS API calls which are going to aws, for example when I'm trying to copy something from S3 bucket: aws s3 cp s3://bucket/file-name

I tried with tcpdump src <IP>, but it didn't showed me anything.

**Comment by AgrawalAmey** [comment]
@Lilitapudane check `curldbg` option.

**Comment by gaul** [comment]
`curldbg` is the easiest but if you want to use tcpdump you probably want to connect via http instead of https.

**Comment by mrPsycho** [comment]
perfect, thanks!
