### ISSUE TITLE
Transport endpoint is not connected and force to create new handler 

### ISSUE THREAD

**Issue by bigheh** [s3fs-fuse/s3fs-fuse#1167]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]:      [IAM role=qulp-testssm]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]: Pool empty: force to create new handler
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]:      [IAM role=qulp-testssm]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]: Pool empty: force to create new handler
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]:      [IAM role=qulp-testssm]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]: Pool empty: force to create new handler
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]:      [IAM role=qulp-testssm]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]: Pool empty: force to create new handler
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]:      [IAM role=qulp-testssm]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]: Pool empty: force to create new handler
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]:      [IAM role=qulp-testssm]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]: Pool empty: force to create new handler
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]:      [IAM role=qulp-testssm]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]: Pool empty: force to create new handler
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]:      [IAM role=qulp-testssm]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]: Pool empty: force to create new handler
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]:      [IAM role=qulp-testssm]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]: Pool empty: force to create new handler
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]:      [IAM role=qulp-testssm]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]: Pool empty: force to create new handler
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]:      [IAM role=qulp-testssm]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]: Pool empty: force to create new handler
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]:      [IAM role=qulp-testssm]
Oct 11 03:49:00 ip-10-123-72-84 s3fs[31710]: Pool empty: force to create new handler
Oct 11 03:49:00 ip-10-123-72-84 kernel: s3fs[31711]: segfault at 7ff4e09b5f00 ip 00007ff4e5359737 sp 00007ff4e09b5e20 error 6 in libc-2.26.so[7ff4e52fe000+1ad000]
Above is the problem log.

**Comment by Sheemon7** [comment]
The same thing happens to me

**Comment by Sheemon7** [comment]
Using a previous version as described in https://github.com/s3fs-fuse/s3fs-fuse/issues/1162 solves the issue for the time being for me.

**Comment by gaul** [comment]
Please try running s3fs under Valgrind or using gdb and attach a backtrace.

**Comment by gaul** [comment]
Please reopen if symptoms persist.
