### ISSUE TITLE
It is incompatible with curl v4.  I get an error "s3fs: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by s3fs)"

### ISSUE THREAD

**Issue by UnclAlDeveloper** [s3fs-fuse/s3fs-fuse#1177]
The current version of s3fs seems to rely on the legacy curl v3.  If I try to mount an S3 volume I get the following error "s3fs: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by s3fs)".  This only occurs if curl is upgraded to v4.  

In my case, I am using rstudio which gets totally uninstalled if I reinstall curl v3, but I am sure the legacy requirements would effect many situations.

**Comment by nikowitt** [comment]
Encountered the same issue with Debian Buster. There, libcurl.so.4.5.0 is being used. Using libcurl.so.4.4.0 works, so it seems that libcurl has removed some backward compatibility. Is there any update planned in the future? Thanks in advance.

**Comment by gaul** [comment]
It would be good if someone could research if there are any differences between libcurl3 and 4.  We would like to allow still-supported LTS distros like CentOS 6 and Ubuntu 16.04 to compile s3fs.  I found this reference but it's not clear to me:

https://askubuntu.com/questions/469360/what-is-the-difference-between-libcurl3-and-libcurl4

**Comment by gaul** [comment]
Can someone comment on the status of this issue?  Does the Debian package still work or is this a user-compiled s3fs?  My Debian-based system links s3fs against libcurl-gnutls.so.4.6.0 without any issues.

**Comment by nikowitt** [comment]
So basically, on a freshly installed Debian Buster 10, it works fine (having verision libcurl 4.5.0) - on a Debian 9 that has been migrated to Debian 10, this seems to be still an issue, but we haven't done any deep debugging.

**Comment by gaul** [comment]
Please reopen if symptoms persist.
