### ISSUE TITLE
Active Directory Authorization

### ISSUE THREAD

**Issue by ctr26** [s3fs-fuse/s3fs-fuse#1179]
I'm using an Hitachi HCP which requires AD Authorization instead of AWS. How would I get s3fs to pass this as a command?

Best

Craig

**Comment by gaul** [comment]
Do you have any references for how this works?

**Comment by ctr26** [comment]
curl -i -k -H "Authorization: AD lgreen@example.com:p4sswOrd"

Is how you do in using cURL 

https://knowledge.hitachivantara.com/Documents/Storage/Content_Platform/8.1.2/HCP_Management_API_Reference/Introduction_to_the_HCP_management_API/03_Access_and_authentication#Active_Directory_authorization_header

Best

Craig

**Comment by gaul** [comment]
Does this work for S3 requests or only management console requests?  The reference is unclear to me.  You can test this by issuing both requests:

```
curl -i -k -H "Authorization: AD lgreen@example.com:p4sswOrd" "Accept: application/xml" "https://admin.hcp.example.com:9090/"
curl -i -k -H "Authorization: AD lgreen@example.com:p4sswOrd" "Accept: application/xml" "https://admin.hcp.example.com:9090/mapi/tenants"
```

The first lists all the buckets and the second does some other subtentant query from the reference.
