### ISSUE TITLE
Can't access directory with space in name

### ISSUE THREAD

**Issue by sergiovl** [s3fs-fuse/s3fs-fuse#118]
I try to install on Amazon Linux AMI and show this error:

root@msxbox:/mnt/msx/ver/Great MSX Collection v1.02# ls -l
ls: reading the directory .: Operation not permitted
total 0

root@msxbox:/mnt/msx/ver/testram# ls -l
total 27
-rw-r--r-- 1 501 501  8448 Jan 31 01:35 testram.com
-rw-r--r-- 1 501 501 16384 Jan 31 01:35 testram.rom
-rw-r--r-- 1 501 501  1749 Jan 31 01:35 testram.txt

I build v1.77 and normal access the directory with space in name:

[root@msxbox Great MSX Collection v1.02]# ls -l
total 85
drwxr-xr-x 1 501 501     0 Jan 29 19:04 Almost MSX
.
.
.
drwxr-xr-x 1 501 501     0 Jan 29 19:54 Xtory MSX (1998)

**Comment by ggtakec** [comment]
#154 is merged to master branch.
It probably fixed this issue, please test it.

I closed this issue, but if you have a problem yet, please reopen this issue.
Thanks for your help.

**Comment by sergiovl** [comment]
Works now! Very Thanks...
