### ISSUE TITLE
connecting to swift - dont understand the error 

### ISSUE THREAD

**Issue by amitkertis17** [s3fs-fuse/s3fs-fuse#1182]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.82(commit:unknown) with GnuTLS(gcrypt)

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Package: fuse
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 104
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.9.7-1ubuntu1

#### Kernel information (uname -r)
_command result: 4.15.0-66-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_command result: cat /etc/os-release_

#### s3fs command line used, if applicable
```

sudo s3fs Amits3test /mnt/s3test2 -o passwd_file=/home/ccloud/.passwd-s3fs2 -o url=https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3 -o use_path_request_style -o dbglevel=info -f -o curldbg




#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
### Details about issue

hi 

i am trying configure connection to swift and i getting those error
can u please help and give me direction 

```
< HTTP/1.1 400 Bad Request
< Server: nginx/1.14.0
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Connection: keep-alive
< x-amz-id-2: tx0f3255727a46491f9f95e-005db056b0
< x-amz-request-id: tx0f3255727a46491f9f95e-005db056b0
< X-Trans-Id: tx0f3255727a46491f9f95e-005db056b0
< X-Openstack-Request-Id: tx0f3255727a46491f9f95e-005db056b0
< Date: Wed, 23 Oct 2019 13:33:36 GMT
< 
* Connection #0 to host objectstore-3.eu-nl-1.cloud.sap left intact
[INF]       curl.cpp:RequestPerform(1952): HTTP response code 400 was returned, returning EIO.
[ERR] curl.cpp:CheckBucket(2953): Check bucket failed, S3 response: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><RequestId>tx0f3255727a46491f9f95e-005db056b0</RequestId><BucketName>v1</BucketName></Error>
[WAN] s3fs.cpp:s3fs_check_service(3795): Could not connect, so retry to connect by signature version 2.
[INF]       curl.cpp:CheckBucket(2914): check a bucket.
[INF]       curl.cpp:prepare_url(4205): URL is https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3/Amits3test/
[INF]       curl.cpp:prepare_url(4237): URL changed is https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3/Amits3test/
* Found bundle for host objectstore-3.eu-nl-1.cloud.sap: 0x7ff75c13eae0 [can pipeline]
* Re-using existing connection! (#0) with host objectstore-3.eu-nl-1.cloud.sap
* Connected to objectstore-3.eu-nl-1.cloud.sap (147.204.33.18) port 443 (#0)
> GET /v1/AUTH_33d948979e5b445aa127ee1fbe346ec3/Amits3test/ HTTP/1.1
Host: objectstore-3.eu-nl-1.cloud.sap
User-Agent: s3fs/1.82 (commit hash unknown; GnuTLS(gcrypt))
Accept: */*
Authorization: AWS c2904cdf6e50413b89edb2d29e708f2c:3u7lfT4oFE6bH9XOjp31aMPiAlo=
Date: Wed, 23 Oct 2019 13:33:36 GMT
```

i also don't really understand what i need to put in the pass file 
MYKEY:MYSECRET

can u tell me from where i get those value in swift 
i see many video for aws can u please provide information for swift 
is it the same as 
application_credential_id = %APPLICATION_CREDENTIAL_ID%
application_credential_secret = %APPLICATION_CREDENTIAL_SECRET%

thanks for the help

**Comment by gaul** [comment]
The error message `<Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message>` suggests that your bucket name is invalid.  Perhaps the upper case letter confuse swift3?  Do you set `dns_compliant_bucket_names` to true?

The S3 credentials should be the Swift ones but you can probably override this.

**Comment by amitkertis17** [comment]
thanks for the help but even after i change the name i got the same error
the command i use is

sudo s3fs amittest /mnt/s3test2 -o passwd_file=/home/ccloud/.passwd-s3fs2 -o url=https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3 -o use_path_request_style -o dbglevel=info -f -o curldbg

BucketName = amittest

regarding "Do you set dns_compliant_bucket_names to true?"
do i need to do it ?

can u send me the command with all the flag that is needed
in the  debug print i see one more error that maybe this is the issue 

<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-nl-1'</Message><RequestId>tx2c540babbe3c43cc84645-005db3eacd</RequestId><Region>eu-nl-1</Region></Error>


here is the full print i got 

root@amitkertes02:/# sudo s3fs amittest /mnt/s3test2 -o passwd_file=/home/ccloud/.passwd-s3fs2 -o url=https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3 -o use_path_request_style -o dbglevel=info -f -o curldbg
[CRT] s3fs.cpp:set_s3fs_log_level(257): change debug level from [CRT] to [INF] 
[INF]     s3fs.cpp:set_mountpoint_attribute(4193): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
[CRT] s3fs.cpp:s3fs_init(3378): init v1.82(commit:unknown) with GnuTLS(gcrypt)
[INF] s3fs.cpp:s3fs_check_service(3754): check services.
[INF]       curl.cpp:CheckBucket(2914): check a bucket.
[INF]       curl.cpp:prepare_url(4205): URL is https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3/amittest/
[INF]       curl.cpp:prepare_url(4237): URL changed is https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3/amittest/
[INF]       curl.cpp:insertV4Headers(2267): computing signature [GET] [/] [] []
[INF]       curl.cpp:url_to_host(100): url is https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3
*   Trying 147.204.33.18...
* TCP_NODELAY set
* Connected to objectstore-3.eu-nl-1.cloud.sap (147.204.33.18) port 443 (#0)
* found 135 certificates in /etc/ssl/certs/ca-certificates.crt
* found 405 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: objectstore-3.eu-nl-1.cloud.sap (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=DE,ST=Baden-Wuerttemberg,L=Walldorf,O=SAP SE,OU=Infrastructure Automization,CN=objectstore-3.eu-nl-1.cloud.sap
* 	 start date: Wed, 05 Dec 2018 00:00:00 GMT
* 	 expire date: Fri, 06 Dec 2019 12:00:00 GMT
* 	 issuer: C=US,O=DigiCert Inc,CN=DigiCert SHA2 Secure Server CA
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /v1/AUTH_33d948979e5b445aa127ee1fbe346ec3/amittest/ HTTP/1.1
host: objectstore-3.eu-nl-1.cloud.sap:443
User-Agent: s3fs/1.82 (commit hash unknown; GnuTLS(gcrypt))
Accept: */*
Authorization: AWS4-HMAC-SHA256 Credential=c2904cdf6e50413b89edb2d29e708f2c/20191026/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=32c2b9eb1c5b897bc2b1ecc106817a996c26669d59040bcfc4e2137b10d1c3df
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20191026T064938Z

< HTTP/1.1 400 Bad Request
< Server: nginx/1.14.0
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Connection: keep-alive
< x-amz-id-2: tx0a80ff2bb4854717a985d-005db3ec83
< x-amz-request-id: tx0a80ff2bb4854717a985d-005db3ec83
< X-Trans-Id: tx0a80ff2bb4854717a985d-005db3ec83
< X-Openstack-Request-Id: tx0a80ff2bb4854717a985d-005db3ec83
< Date: Sat, 26 Oct 2019 06:49:39 GMT
< 
* Connection #0 to host objectstore-3.eu-nl-1.cloud.sap left intact
[INF]       curl.cpp:RequestPerform(1952): HTTP response code 400 was returned, returning EIO.
[ERR] curl.cpp:CheckBucket(2953): Check bucket failed, S3 response: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-nl-1'</Message><RequestId>tx0a80ff2bb4854717a985d-005db3ec83</RequestId><Region>eu-nl-1</Region></Error>
[CRT] s3fs.cpp:s3fs_check_service(3775): Could not connect wrong region us-east-1, so retry to connect region eu-nl-1.
[INF]       curl.cpp:CheckBucket(2914): check a bucket.
[INF]       curl.cpp:prepare_url(4205): URL is https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3/amittest/
[INF]       curl.cpp:prepare_url(4237): URL changed is https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3/amittest/
[INF]       curl.cpp:insertV4Headers(2267): computing signature [GET] [/] [] []
[INF]       curl.cpp:url_to_host(100): url is https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3
* Found bundle for host objectstore-3.eu-nl-1.cloud.sap: 0x7f933813eae0 [can pipeline]
* Re-using existing connection! (#0) with host objectstore-3.eu-nl-1.cloud.sap
* Connected to objectstore-3.eu-nl-1.cloud.sap (147.204.33.18) port 443 (#0)
> GET /v1/AUTH_33d948979e5b445aa127ee1fbe346ec3/amittest/ HTTP/1.1
host: objectstore-3.eu-nl-1.cloud.sap:443
User-Agent: s3fs/1.82 (commit hash unknown; GnuTLS(gcrypt))
Accept: */*
Authorization: AWS4-HMAC-SHA256 Credential=c2904cdf6e50413b89edb2d29e708f2c/20191026/eu-nl-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=c4d9afda780d191b69843ab1e8e5432aec1c6bdd960961d7e00fc1fb9a0a5753
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20191026T064939Z

< HTTP/1.1 400 Bad Request
< Server: nginx/1.14.0
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Connection: keep-alive
< x-amz-id-2: txf23430291f12434f9ff7e-005db3ec83
< x-amz-request-id: txf23430291f12434f9ff7e-005db3ec83
< X-Trans-Id: txf23430291f12434f9ff7e-005db3ec83
< X-Openstack-Request-Id: txf23430291f12434f9ff7e-005db3ec83
< Date: Sat, 26 Oct 2019 06:49:39 GMT
< 
* Connection #0 to host objectstore-3.eu-nl-1.cloud.sap left intact
[INF]       curl.cpp:RequestPerform(1952): HTTP response code 400 was returned, returning EIO.
[ERR] curl.cpp:CheckBucket(2953): Check bucket failed, S3 response: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><RequestId>txf23430291f12434f9ff7e-005db3ec83</RequestId><BucketName>v1</BucketName></Error>
[WAN] s3fs.cpp:s3fs_check_service(3795): Could not connect, so retry to connect by signature version 2.
[INF]       curl.cpp:CheckBucket(2914): check a bucket.
[INF]       curl.cpp:prepare_url(4205): URL is https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3/amittest/
[INF]       curl.cpp:prepare_url(4237): URL changed is https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3/amittest/
* Found bundle for host objectstore-3.eu-nl-1.cloud.sap: 0x7f933813eae0 [can pipeline]
* Re-using existing connection! (#0) with host objectstore-3.eu-nl-1.cloud.sap
* Connected to objectstore-3.eu-nl-1.cloud.sap (147.204.33.18) port 443 (#0)
> GET /v1/AUTH_33d948979e5b445aa127ee1fbe346ec3/amittest/ HTTP/1.1
Host: objectstore-3.eu-nl-1.cloud.sap
User-Agent: s3fs/1.82 (commit hash unknown; GnuTLS(gcrypt))
Accept: */*
Authorization: AWS c2904cdf6e50413b89edb2d29e708f2c:KH/F1vWHEX+vjV1ooR5ITleKpRA=
Date: Sat, 26 Oct 2019 06:49:39 GMT

< HTTP/1.1 400 Bad Request
< Server: nginx/1.14.0
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Connection: keep-alive
< x-amz-id-2: txb6239843ad2244258248a-005db3ec83
< x-amz-request-id: txb6239843ad2244258248a-005db3ec83
< X-Trans-Id: txb6239843ad2244258248a-005db3ec83
< X-Openstack-Request-Id: txb6239843ad2244258248a-005db3ec83
< Date: Sat, 26 Oct 2019 06:49:39 GMT
< 
* Connection #0 to host objectstore-3.eu-nl-1.cloud.sap left intact
[INF]       curl.cpp:RequestPerform(1952): HTTP response code 400 was returned, returning EIO.
[ERR] curl.cpp:CheckBucket(2953): Check bucket failed, S3 response: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><RequestId>txb6239843ad2244258248a-005db3ec83</RequestId><BucketName>v1</BucketName></Error>
[CRT] s3fs.cpp:s3fs_check_service(3807): Bad Request(host=https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3) - result of checking service.
[ERR] s3fs.cpp:s3fs_exit_fuseloop(3368): Exiting FUSE event loop due to errors

[INF] s3fs.cpp:s3fs_destroy(3441): destroy
[WAN] s3fs.cpp:s3fs_destroy(3445): Could not release curl library.
root@amitkertes02:/# 


again thanks for the help
waiting for your answer :)

**Comment by amitkertis17** [comment]
i look for this flag and i cant find it 
dns_compliant_bucket_names
what do u mean ? what i need to do ?

**Comment by amitkertis17** [comment]
ok , i change the url to be just url=https://identity-3.eu-nl-1.cloud.sap:443/
and not url=https://objectstore-3.eu-nl-1.cloud.sap:443/v1/AUTH_33d948979e5b445aa127ee1fbe346ec3

and the issue with the "InvalidBucketName" solved
not the only thing left is issue with credential and i open separate ticket for this 
https://github.com/s3fs-fuse/s3fs-fuse/issues/1187

thanks for the help
