### ISSUE TITLE
AuthorizationHeaderMalformed - the region 'us-east-1' is wrong; expecting 'eu-nl-1

### ISSUE THREAD

**Issue by amitkertis17** [s3fs-fuse/s3fs-fuse#1186]
#### Version of s3fs being used (s3fs --version)
v1.85

### Details about issue

[ERR] curl.cpp:CheckBucket(3423): Check bucket failed, S3 response: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-nl-1'</Message><RequestId>tx030fad750ef4436b8af60-005db5a5a1</RequestId><Region>eu-nl-1</Region></Error>

i try to connect swift and i get this error 
what can i do 
please help me :)

thanks 
amit

**Comment by gaul** [comment]
Can you share your s3fs options?  This might work if you specify `-o endpoint=eu-nl`.

**Comment by amitkertis17** [comment]
this is the command i am using

sudo s3fs aaa12345 /mnt/s3test2 -o passwd_file=/home/ccloud/.passwd-s3fs -o url=https://objectstore-3.eu-nl-1.cloud.sap:443/ -o use_path_request_style -o dbglevel=info -f -o curldbg

**Comment by amitkertis17** [comment]
i use this flag  "-o endpoint =   "  and its fix the problem 
thank u very much
