### ISSUE TITLE
S3 file cache issue

### ISSUE THREAD

**Issue by siddharthgowtham** [s3fs-fuse/s3fs-fuse#1192]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.85(commit:unknown) with OpenSSL

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.2-11.el7

#### Kernel information (uname -r)
3.10.0-957.10.1.el7.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"

#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
s3fs#test-bucket-infa-sid-without-versioning      /without_version      fuse    _netdev,allow_other,nonempty,uid=1000,gid=1000,umask=0007   0       0
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```

### Details about issue

I've mounted S3 bucket on my centos server. When i remove a file from the s3 bucket, i can't see the file is getting listed using ls -lrt. 

But am able to see the file when I fire the command "ls -lrt <deleted-file-name>". After that, I try to cat the file, but nothing displays. Post the cat command, the file doesn't list even for the command "ls -lrt <deleted-file-name>"

This happens on both Versioning enabled and not enabled buckets.

**Comment by gaul** [comment]
Sorry I don't understand -- you both can and can't see the file with `ls -lrt`?  In the former case if a file appears in the directory listing but cannot be read, it may be because s3fs caches metadata forever.  You can control this behavior via `-o stat_cache_expire`.  Please experiment with this and report back.

**Comment by gaul** [comment]
Please reopen if symptoms persist.
