### ISSUE TITLE
s3fs-fuse on EPEL8

### ISSUE THREAD

**Issue by juliogonzalez** [s3fs-fuse/s3fs-fuse#1194]
I created this card just in case someone wants to ask about the status.

I just submitted it: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-2d9d99fd01

Should get approved and released into EPEL8 in a few days:

- If nobody else test it, I think after 7 days.
- If three people test it and provide positive karma at the link above, then sooner.

I will close the card as soon as the package is released.

**Comment by gaul** [comment]
@juliogonzalez Thank you for staying on top of these RPM distros!  I hope that most users now consume these packages instead of compiling from source.

**Comment by ggtakec** [comment]
@juliogonzalez Thanks for your great help.
I would be pleased if I could distribute it in EPEL-8.
We are looking forward to the package being released.

**Comment by juliogonzalez** [comment]
Good news, s3fs-fuse v1.85 is finally released to EPEL-8: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-2d9d99fd01
