### ISSUE TITLE
comparison to s3fuse

### ISSUE THREAD

**Issue by joe42** [s3fs-fuse/s3fs-fuse#12]
Hi,

I have used s3fuse for a while (https://code.google.com/p/s3fuse/). Can you tell me any advantages of your project over s3fuse?
The other projects you link to cannot compete in maturity as far as I can say, but your project and s3fuse seem to be stable, and active. It says it is based on your project. 
Maybe you can share insight on why another project has been created, instead of them working together with you? The difference I see is that s3fuse also provides access to google storage. From a user perspective it seems to be a good idea to merge the projects.

Thanks for your great work,
joe

**Comment by ggtakec** [comment]
I'm sorry about this Issue had been left at a long period of time.

s3fuse is 

s3fuse seems to have stopped now activities.
And s3fs-fuse supports compatibility with other tools and additional feature, then it is heavy.
About google cloud strage, s3fs-fuse can support it. Please see wiki page: https://github.com/s3fs-fuse/s3fs-fuse/wiki/Google-Cloud-Storage

If you found a problem, please post issue.

Thanks in advance for your help.
