### ISSUE TITLE
 Create time of directory is reported as zero

### ISSUE THREAD

**Issue by Bkamau** [s3fs-fuse/s3fs-fuse#1202]
#### Version of s3fs being used (s3fs --version)
s3fs_fuse 1.85

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
alpine 3.9

#### s3fs command line used, if applicable
``` 
s3fs "$BUCKET" "$MOUNT_PATH" \
    -o ro \
    -o noatime \
    -o passwd_file="$S3CRED,use_path_request_style,url=$MINIO_ENDPOINT"
```

### Details about issue
Directories inside the mounted bucket has time set to 0 like this 
 drwxr-x--- 1 1000 1000 0 Jan 1 1970 PUBLIC

Files inside the PUBLIC directory has proper time set though
Close related to https://github.com/s3fs-fuse/s3fs-fuse/issues/771

**Comment by gaul** [comment]
Are these times zero for objects created from s3fs or from an external tool?

**Comment by Bkamau** [comment]
They are created by external tool. Please note that this applies to directories, not the objects inside that given directory.

**Comment by Wang-Kai** [comment]
> They are created by external tool. Please note that this applies to directories, not the objects inside that given directory.

Have you solve it ? i met the same issue .

**Comment by Wang-Kai** [comment]
I met the same issue, after executed `s3fs mydirectory ...`，the inode of `mydirectory` changed, and the create time is zero .

```
# stat mydirectory
  File: mydirectory
  Size: 0         	Blocks: 1          IO Block: 4096   directory
Device: 8eh/142d	Inode: 1           Links: 1
Access: (0700/drwx------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 1970-01-01 00:00:00.000000000 +0000
Modify: 1970-01-01 00:00:00.000000000 +0000
Change: 1970-01-01 00:00:00.000000000 +0000
 Birth: -
```

**Comment by gaul** [comment]
Could you test with the latest master?  It includes 059cc57ba6914229dbd7238b902ba76d87643c6e.

**Comment by gaul** [comment]
Please reopen if symptoms persist.

**Comment by Bkamau** [comment]
@gaul  Please re-open the issue as the problem is still visible with **v1.91**.

**Comment by gaul** [comment]
I misunderstood the symptom -- if you run:

```
s3fs bucket mnt/
echo data | aws_cli s3 cp - "s3://bucket/directory/file"
ls -ld mnt/directory
```

You will see the default permissions 750 and a default 0 atime/ctime/mtime.  This is intentional -- `directory` does not exist and s3fs must provide some value so it defaults to 0.  What do you expect to happen?

**Comment by bronger** [comment]
Does an S3 store save a timestamp for directories at all?
