### ISSUE TITLE
InvalidAccessKeyId Error while trying to connect to China Region

### ISSUE THREAD

**Issue by zhouyuncsu** [s3fs-fuse/s3fs-fuse#121]
Hello,

I clone the code 2015/2/12,  and we currently aren't able to connect to the S3 buckets of the new region (China).

The command I typed is following:
s3fs -f prd-isidsh-foco-s3-01 mnt

The error message provided is following:
set_moutpoint_attribute(3482): PROC(uid=500, gid=500) - MountPoint(uid=500, gid=500, mode=40775)
s3fs_init(2669): init
s3fs_check_service(3022): check services.
CheckBucket(2526): check a bucket.
RequestPerform(1588): HTTP response code 403
RequestPerform(1607): HTTP response code 403 was returned, returning EPERM
CheckBucket(2578): Check bucket failed, S3 response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId><Access Key Removed></AWSAccessKeyId><RequestId>4B5850D76A21EDF2</RequestId><HostId>WPnVNvZkM1MzbYQ4wsOct+IyTrC5CInwrrAZ2Xj8g5R1MWpAXVsXsT2INrQWVyH9</HostId></Error>

I also have seen the issue bellow.  But the error message is different, so I don't know is it the same problem.
https://github.com/s3fs-fuse/s3fs-fuse/issues/76

**Comment by ggtakec** [comment]
Hi,
Could you try to use latest master branch codes?
It is merged for AWS signature v4 logic as deafult(please see #76), I think it probably works for China Region. 
Thanks a lot.

**Comment by ggtakec** [comment]
I'm closing this issue, if you have a problem yet, please post new issue or reopen this issue.

Thanks in advance for your help.
