### ISSUE TITLE
Update to 1.85 not working 

### ISSUE THREAD

**Issue by furchtlos76** [s3fs-fuse/s3fs-fuse#1210]
Is it somehow possible to update to 1.85 on ubuntu 16.04 LTS? Since some weeks i get Transport endpoint not connected with this error segfault at 10 ip 00007fa592663031 sp 00007fa5277fd818 error 4 in libstdc++.so.6.0.21[7fa5925be000+172000]
As i read, the problem should be fixed with 1.85. Latest Version i could find in packages is 1.84 - But i am not able to compile - sorry i am a beginner - as make brings alot of errors like:

/usr/include/unicode/ucnv.h:1915:46: error: âUCharâ has not been declared
 ucnv_fixFileSeparator(const UConverter *cnv, UChar *source, int32_t sourceLen);

/usr/include/libxml2/libxml/encoding.h:138:3: error: âUCharâ does not name a type
   UChar      *pivot_source;

can anyone give me some advice please?

### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)

1.8.4

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_example: 2.9.4_

2.9.4

#### Kernel information (uname -r)
_command result: uname -r_

4.15.0-70-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_command result: cat /etc/os-release_

Ubuntu 16.04.6 LTS

#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```

**Comment by gaul** [comment]
I asked Ubuntu to upgrade their s3fs version about six month ago.  You can comment there:

https://bugs.launchpad.net/ubuntu/+source/s3fs-fuse/+bug/1828849

Maybe these instructions will help you compile locally:

https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes#tested-on-ubuntu-1404-lts

**Comment by furchtlos76** [comment]
Thanks alot for the reply, i did the instruction but i get those  âUCharâ does not name a type
UChar *pivot_source; errors in make. Well will upgrade to 18.04 in the next days maybe i manage to compile it there than. On 16.04. i used more than 2 days and could not get it compiled or find a conclusion with google. keep the great work on this!

**Comment by gaul** [comment]
Ubuntu 20.20 will include s3fs 1.85.

**Comment by tooler** [comment]
Hi @furchtlos76, did you manage to upgrade s3fs manually on Ubuntu 16.04.6 LTS? If so, could you please share some pointers how you did it? Thanks in advance.
