### ISSUE TITLE
Debian (stretch) package out of date 

### ISSUE THREAD

**Issue by zorino** [s3fs-fuse/s3fs-fuse#1211]
Hi would it be possible for you to update the debian package with the version that fix the memory leak issue (1.84 I believe) ? Thanks !

From debian stretch http.us.debian.org/debian mirror : 
```
> apt-cache policy s3fs
s3fs:
  Installed: 1.80-2
  Candidate: 1.80-2
  Version table:
 *** 1.80-2 500
        500 http://http.us.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by jeff1326** [comment]
Up ! I need this fix on one of my server who run out of memory.

**Comment by Twister42** [comment]
This is not handled by the developers of s3fs-fuse, but by the Debian maintainers. Moreover Debian has a 1.84 package. 
cf. https://packages.debian.org/source/sid/s3fs-fuse.

**Comment by gaul** [comment]
It appears that Debian stretch (9) has s3fs 1.80 and buster (10) has 1.84.  If you upgrade your disto you will get a more recent s3fs.
