### ISSUE TITLE
what is the meaning of is_only_c flag?

### ISSUE THREAD

**Issue by JiaoDean** [s3fs-fuse/s3fs-fuse#1213]
bool S3fsCurl::AddSseRequestHead(sse_type_t ssetype, string& ssevalue, bool is_only_c, bool is_copy)，in this function：
1、is_only_c  flag is false, when ssetype is SSE_S3 or SSE_KMS;
2、is_only_c flag is true, when ssetype is SSE_C;

what is the meaning of is_only_c flag?

**Comment by gaul** [comment]
I believe that this means using the customer-provided keys (SSE-C).
