### ISSUE TITLE
403 on glob of directory named with comma

### ISSUE THREAD

**Issue by ikolinahr** [s3fs-fuse/s3fs-fuse#123]
**** UPDATE ****

This seems to be the same problem as noted in issue #118. The problem with both space and comma in directory names was introduced in version 1.78. Version 1.77 works fine.

*********************

Assume the following files in your s3 bucket:

dir/dir1/file1
dir/dir,2/file2
dir/dir3/file,3

The following commands will succeed:

ls dir
ls dir/dir1
ls dir/dir3
ls dir/dir1/file1
ls dir/dir,2/file2
ls dir/dir3/file,3

However, this will fail with a 403 error from AWS:

ls dir/dir,2

This is important for use when mounting encfs on top of s3fs-fuse. Encfs will name files with commas.

**Comment by ggtakec** [comment]
#154 is merged to master branch.
It probably fixed this issue(as same as #118), please test it.

I closed this issue, but if you have a problem yet, please reopen this issue.
Thanks for your help.
