### ISSUE TITLE
Help with pom.xml path

### ISSUE THREAD

**Issue by tapanjo92** [s3fs-fuse/s3fs-fuse#1238]
### Additional Information
Have a pom.xml which has path for the bucket which was mounted via s3fs. Not sure what the path should be

### Details about issue

so this is my s3fs mouth path on ec2-ubuntu.
![tmp-s3fs](https://user-images.githubusercontent.com/49943773/73620595-c7cec400-4686-11ea-986f-829b72a2067f.png)

This is the path in pom.xml which I have to mention, not sure which it should be?
![pom-path](https://user-images.githubusercontent.com/49943773/73620614-d4ebb300-4686-11ea-9c02-a3164006bb82.png)

Thank You

**Comment by gaul** [comment]
s3fs works like a regular file system.  If you mount in /tmp then you should be able to write your webinar into /tmp and thus into S3.  However I would choose a different path since the system uses /tmp for other files.

**Comment by tapanjo92** [comment]
hi,
i have changed my path to recordings.
As you can see below via ps -ef grep
![s3fs-path](https://user-images.githubusercontent.com/49943773/73626592-8eee1980-469d-11ea-9f95-570f6893f565.png)
And I have updated the pom.xml file(/home/ubuntu/recordings) as well, but still i am not able to capture the recordings.
![recordingpath](https://user-images.githubusercontent.com/49943773/73626602-a1685300-469d-11ea-9bf6-7091825b28f6.png)

**Comment by gaul** [comment]
If you mount wcc-dev-webinar-recordings in /home/ubuntu/recordings/tmp, you must set webinar.recording.path to the same directory.  Again, s3fs works just like a regular file system so this should not be any different workflow.

**Comment by tapanjo92** [comment]
@gaul 
When you said 'webinar.recording.path to the same directory', can you please elaborate?

thank you

**Comment by gaul** [comment]
I'm sorry I don't think we can help you with your general IT issues.  s3fs works like a regular file system so I suggest experimenting with tools like ls an cp with your s3fs mount before redirecting your maven project.

**Comment by tapanjo92** [comment]
hi @gaul,
thank you for your help, I did a debug in my tomcat and found this error
![tomcat](https://user-images.githubusercontent.com/49943773/73896084-db239e80-48d5-11ea-9f5e-ef557a16529d.png)
But not able to identify the problem
thanks a lot
