### ISSUE TITLE
AWS EC2 instance role support?

### ISSUE THREAD

**Issue by sgleske-ias** [s3fs-fuse/s3fs-fuse#1261]
With EC2 instance roles you don't assign a role name to use or pass it as an argument.  Amazon grants access just by being on the instance and the instance having a role associated with it.

So far all of the support requests I've seen talk about credentials or passing in a role as an argument.  With an instance role you don't need to know the name, just use the S3 APIs and it should work if the role grants it.

Does s3fs-fuse work with instance roles?

**Comment by sgleske-ias** [comment]
Looks like #1138 answers my question.

Specifically https://github.com/s3fs-fuse/s3fs-fuse/issues/1138#issuecomment-527306746

**Comment by juliogonzalez** [comment]
If this is not clear at the doc right now (could be), I'd suggest you submit a PR :-)
