### ISSUE TITLE
s3fs does not show directories/subdirectories

### ISSUE THREAD

**Issue by Adspectus** [s3fs-fuse/s3fs-fuse#1264]
#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.82(commit:unknown) with GnuTLS(gcrypt)
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Package: fuse
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 104
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.9.7-1ubuntu1

#### Kernel information (uname -r)
Linux Caboto 4.15.0-1079-oem #89-Ubuntu SMP Fri Mar 27 05:22:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

#### /etc/fstab entry, if applicable
```
s3fs /mnt/S3/mybucket fuse.s3fs _netdev,bucket=mybucket,endpoint=eu-central-1,allow_other 0 0
```

### Details about issue
Directories created outside of s3fs are shown as plain files(?), i.e. (all entries supposed to be directories):
```
---------- 1 uwe  uwe     0 Mär 31 10:19 Linux
drwxrwxr-x 1 uwe  uwe     0 Apr 10 11:15 Test1/
---------- 1 uwe  uwe     0 Mär 30 21:35 Test2
---------- 1 uwe  uwe     0 Apr 10 11:30 Test3
```
Only the directory Test1 which have been created by s3fs shows up as directory.

I use other s3 clients, like S3 connector on Confluence, s3 plugin in Nextcloud, aws s3 command line tool and AWS Management console. In all clients I can create and see directories, only s3fs is not able to show them correctly.

**Comment by longwei66** [comment]
hello,
I have the same issue with version 1.86 on debian sid, using digital ocean spaces.

`
s3fs mydigitaloceanspacename ~/do -o url=https://ams3.digitaloceanspaces.com -o use_cache=/tmp -o allow_other -o use_path_request_style -o uid=1000 -o gid=1000 -o umask=027
`
Only the directory created with sfs3 are accessible as directory

**Comment by harold1505** [comment]
I have the same problem. No sub directories already existing in my bucket are displayed. I'm using Ubuntu 18.04.3 LTS.

**Comment by gaul** [comment]
Please provide steps to reproduce these symptoms.  I added a test that shows that this works when creating an implicit directory via AWS CLI.

**Comment by gaul** [comment]
Please reopen if you can provide the requested debugging info.

**Comment by Adspectus** [comment]
There is no debugging I could provide. It is just not working and therefore not usable. Just tested again.

**Comment by jonfryd** [comment]
@Adspectus: we had the same problem, but adding `-o complement_stat` solved it. Perhaps it works for you, as well.

**Comment by Adspectus** [comment]
Thanks for sharing this! Actually it works now when I create directories in AWS console or with S3 connector in Confluence. But still I got only a file shown when creating a directory with the S3 plugin in Nextcloud. Anyway, at least better than before.
