### ISSUE TITLE
Directories/files uploaded from s3cmd sync aren't readable by s3fs if they have parentheses in name

### ISSUE THREAD

**Issue by jsit** [s3fs-fuse/s3fs-fuse#127]
I *believe* this is a problem in combination with these two tools, s3cmd and s3fs. I don't know where to file the bug.

1) If I create a directory in my S3 bucket with parentheses in the name, it shows up just fine in s3fs.
2) If I create a local directory with parentheses in the name, then `s3cmd sync` to my S3 bucket, it shows up just fine in the S3 web interface.
3) Only when I mount a directory created with (2) using s3fs does the directory with parentheses become unreadable on the mounted S3 bucket.

**Comment by jsit** [comment]
Apologies -- Please excuse this issue; after some further testing it seems like it's not a matter of parentheses at all. Still diagnosing.

**Comment by Ishotihadus** [comment]
Same here. Have you already solved this problem?

**Comment by Ishotihadus** [comment]
I found that this problem occurs when the sigv2 option is enabled. Turn off the option to solve this problem.
