### ISSUE TITLE
Document mime types depenency

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#1270]
Someone on StackOverflow recently asked about the mime types dependency:

https://stackoverflow.com/questions/61207571/s3fs-could-not-load-mime-types-for-curl-library/61208047#61208047

Should this be a hard dependency?  Instead we could just warn about its absence since most users not require Content-Type.

**Comment by ggtakec** [comment]
https://github.com/s3fs-fuse/s3fs-fuse/blob/master/COMPILATION.md and https://github.com/s3fs-fuse/s3fs-fuse/wiki/FAQ#qwhat-do-i-need-to-know have a brief explanation.

However, it does not explain the required packages for each OS.
(Note that the package containing mime.types(mailcap) is not included in the dependency of the s3fs package and is an environmental problem.)

So, I would like to consider whether the recommended packages for each OS should be prepared in any of the documents.

**Comment by juliogonzalez** [comment]
> Should this be a hard dependency? Instead we could just warn about its absence since most users not require Content-Type.

Just so you know: on Debian, openSUSE/SLE and Fedora/EPEL the packages providing the mime types config file are `Requires`. So for the packages on the distributions, this is a runtime hard dependency (Debian had it, openSUSE/SLE had it, so I just did the same for Fedora/EPEL).

Also I am not 100% most users don't need it. I think most users *have* the file and they just don't know. Without it, any application using MIME will be confused. And as the MIME type is not defined during upload, and you never know who will be reading files from the bucket... that could be a problem.

But I admit I am not an expert on this area.

> https://github.com/s3fs-fuse/s3fs-fuse/blob/master/COMPILATION.md and https://github.com/s3fs- fuse/s3fs-fuse/wiki/FAQ#qwhat-do-i-need-to-know have a brief explanation.

Which FMPOV is OK. We don't tell the packages in other cases. Only the dependencies in terms of software that needs to be available.

> However, it does not explain the required packages for each OS.

Those packages are already at https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes and it seems they are right for all the Linux Distributions listed there (`mine-support` for Debian and Ubuntu, mailcap for RES/CentOS/Fedora and nothing for openSUSE/SLE (as it's part of the base system as part of `aaa-base` package).

**Comment by gaul** [comment]
I think packages should either require or recommend mime-types and the compilation instructions should suggest it but if the file is missing at run-time s3fs should warn once about this and continue.

**Comment by ggtakec** [comment]
The mime.types file is not needed when building s3fs, but it is only needed at runtime.
On current master, if the mime.types file does not exist, an error is output and s3fs cannot start.
Should I output this message with a little more detail?

**Comment by gaul** [comment]
The StackOverflow answer has attracted several votes and I suspect this new requirement is breaking users who compile master from source.
