### ISSUE TITLE
Allow ftp user to access particular folder of S3 Bucket

### ISSUE THREAD

**Issue by lalspicesresearch** [s3fs-fuse/s3fs-fuse#1275]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
_Version:V1.86 _

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Unknown option -qi

#### Kernel information (uname -r)
4.19.76-linuxkit

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
grep: /var/log/syslog,: No such file or directory
grep: or: No such file or directory
grep: journalctl: No such file or directory
grep: s3fs: No such file or directory
grep: outputs: No such file or directory
### Details about issue
I am able to mount s3fs fuse in docker but i want particular ftp user created by me to access particular folder of S3 Bucket. I am using vsftpd server too. Is there any way to make this happen ? When we mount using below command, it shows all folder and user can access all the folder.
s3fs bucket_name /home/lal/ftp/files -o passwd_file=/etc/passwd-s3fs
How can we limit the users folder access ? Please help me with any kind of references. Thank you for such wonderful package.

**Comment by gaul** [comment]
You can mount a path of a bucket via: `s3fs bucket:/path mountpoint`.

**Comment by lalspicesresearch** [comment]
@gaul i have mounted the whole bucket. Now what i have to do is give specific folder inside of that bucket permission to one user and another folder of bucket to another user. How can we acheive that ?

**Comment by gaul** [comment]
@lalspicesresearch if you found a solution to this please share it here to help future users.
