### ISSUE TITLE
Getting Error "s3fs: could not determine how to establish security credentials"

### ISSUE THREAD

**Issue by qspencer** [s3fs-fuse/s3fs-fuse#128]
1. Using an EC2 with Amazon linux
2. A file named ".passwd-s3fs" is in $HOME
3. The file contains one line with <accesskeyid>:<secretaccesskey>
4. Ran "chmod 600 .passwd-s3fs"
5. libcurl version is 7.40
6. issued command "tail -f /var/log/messages" but no s3fs messages 
7. tried "-f" option. Output was:

set_moutpoint_attribute(3482): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
s3fs: could not determine how to establish security credentials

Any solutions or suggestions of things to try would be greatly appreciated!

**Comment by ggtakec** [comment]
"s3fs: could not determine how to establish security credentials" message means that s3fs could not find any credential(/etc/passed-s3fs, $HOME/.passwd-s3fs etc...).
It seems that your procedure is no problem, but you got this message.
So I think that HOME environment is something wrong as possible.

If you can, you try to copy your $HOME/.passwd-s3fs to /etc/passwd-s3fs and cheek to run s3fs.

Regards,

**Comment by qspencer** [comment]
thank you, I tried what you suggested and it worked!

**Comment by jcomeauictx** [comment]
if you ran the `s3fs` command with `sudo`, but had the `.passwd-s3fs` file in your own account's `$HOME`, that could account for why it failed, and also why it mentioned `PROC(uid=0, gid=0)` in the output. it may have been looking for the file in root's home directory.

**Comment by railsfans** [comment]
把/etc/passwd-ossfs的权限改成你要启动的普通用户就行了。

**Comment by stormm2138** [comment]
Note that for me using fstab **didn't auto-remount on** reboot, likely due to networking services not being enabled at the time of the boot mount, so I'm creating a service to boot **after networking services** are enabled per https://github.com/s3fs-fuse/s3fs-fuse/issues/412

**Comment by blurayne** [comment]
You could use a bash wrapper script to support a custom credential file:
http://blog.evolution515.net/2018/08/31/autofs-indirect-user-automounter-for-aws-s3-using-either-s3fs-or-goofyfs/

**Comment by treii28** [comment]
my EC2 should have S3 permissions in it's default assumed role. is there any way to avoid this error when using such authentication?
