### ISSUE TITLE
I want to mount Spaces S3 in my DigitalOcean Droplet

### ISSUE THREAD

**Issue by shnehasishchandra** [s3fs-fuse/s3fs-fuse#1281]
I am using below command to mount Spaces s3 as folder in droplet ubuntu.

$echo ***********+********************** > ~/.passwd-s3fs

$mkdir -p /var/www/******

$s3fs ******* /var/www/********** -ourl=https://nyc3.digitaloceanspaces.com -ouse_cache=/tmp

But when I reboot the server the Spaces is getting unmounted automatically.

Please help in this,  it should not get unmounted after reboot server.

**Comment by gaul** [comment]
You need to mount s3fs via fstab.  See the README for examples:

https://github.com/s3fs-fuse/s3fs-fuse#examples
