### ISSUE TITLE
Folder is mounted as a file

### ISSUE THREAD

**Issue by LouisBertin** [s3fs-fuse/s3fs-fuse#1284]
### Details about issue
I'm facing with an issue to link Nextcloud with s3fs. The s3 bucket comes from Wasabi.
Everything works except one folder mounted as a file. This folder has a space in his name, maybe the error came from here? His name is **Projets clients**

![image](https://user-images.githubusercontent.com/22589554/80760036-8e4c0e80-8b38-11ea-931b-ee850588d6ff.png)

#### Version of s3fs being used
1.82

#### Version of fuse being used
 2.9.7

#### Kernel information (uname -r)
4.15.0-99

#### GNU/Linux Distribution
Ubuntu - 18.04.4 LTS

#### s3fs command line used
```
sudo s3fs nextcloud fs/ -o passwd_file=/home/louis/.passwd-s3fs -o url=https://s3.eu-central-1.wasabisys.com -o allow_other,umask=0000,uid=33,gid=33
```

**Comment by gaul** [comment]
Could you share the output of aws cli ls for this folder and especially the output from s3api head-object?

**Comment by gaul** [comment]
Please test with the latest version 1.86 which includes #885.
