### ISSUE TITLE
Can not mount a public_bucket

### ISSUE THREAD

**Issue by pourquoi42** [s3fs-fuse/s3fs-fuse#1287]
#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.79(commit:unknown) with GnuTLS(gcrypt)
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Package: fuse
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 104
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.9.4-1ubuntu3.1
Depends: libc6 (>= 2.14), libfuse2 (= 2.9.4-1ubuntu3.1), adduser, mount (>= 2.19.1), sed (>= 4)
Conffiles:
 /etc/fuse.conf 298587592c8444196833f317def414f2
Description: Filesystem in Userspace
 Filesystem in Userspace (FUSE) is a simple interface for userspace programs to
 export a virtual filesystem to the Linux kernel. It also aims to provide a
 secure method for non privileged users to create and mount their own filesystem
 implementations.
Homepage: http://fuse.sourceforge.net/
Original-Maintainer: Laszlo Boszormenyi (GCS) <gcs@debian.org>

#### Kernel information (uname -r)
4.10.0-35-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

#### s3fs command line used, if applicable
```
s3fs -o public_bucket=1 -o default_acl="" -f -d https://s3.eu-central-1.amazonaws.com/deutsche-boerse-xetra-pds /tmp/xetra

```
### Details about issue
I am trying to mount a public S3 bucket. Access Works fine with s3 client following https://github.com/Deutsche-Boerse/dbg-pds.

`
s3fs -o public_bucket=1 -o default_acl="" -f -d https://s3.eu-central-1.amazonaws.com/deutsche-boerse-xetra-pds /tmp/xetra

....

[INF]       prepare_url(4117): URL changed is http://https.s3.amazonaws.com//s3.eu-central-1.amazonaws.com/deutsche-boerse-xetra-pds/.Trash-1000_%24folder%24
[INF]       insertV4Headers(2069): computing signature [HEAD] [//s3.eu-central-1.amazonaws.com/deutsche-boerse-xetra-pds/.Trash-1000_$folder$] [] []
[INF]       url_to_host(99): url is http://s3.amazonaws.com
[INF]       RequestPerform(1760): HTTP response code 403 was returned, returning EPERM
[INF]   list_bucket(2408): [path=/.Trash-1000]
[INF]       ListBucketRequest(2682): [tpath=/.Trash-1000]
[INF]       prepare_url(4085): URL is http://s3.amazonaws.com/https?delimiter=/&max-keys=1&prefix=/s3.eu-central-1.amazonaws.com/deutsche-boerse-xetra-pds/.Trash-1000/
[INF]       prepare_url(4117): URL changed is http://https.s3.amazonaws.com?delimiter=/&max-keys=1&prefix=/s3.eu-central-1.amazonaws.com/deutsche-boerse-xetra-pds/.Trash-1000/
[INF]       insertV4Headers(2069): computing signature [GET] [delimiter=/&max-keys=1&prefix=/s3.eu-central-1.amazonaws.com/deutsche-boerse-xetra-pds/.Trash-1000/] [] []
[INF]       url_to_host(99): url is http://s3.amazonaws.com
[INF]       RequestPerform(1760): HTTP response code 403 was returned, returning EPERM
[ERR] list_bucket(2441): ListBucketRequest returns with error.
[ERR] directory_empty(1036): list_bucket returns error.

`

**Comment by gaul** [comment]
Could you test with the latest version 1.86?  1.79 is several years old.

**Comment by pourquoi42** [comment]
@gaul yes, worx with the version from master. Thanks!
