### ISSUE TITLE
curldbg should log some request and response bodies

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#1289]
It would be helped to log the request bodies for calls like `CompleteMultipartUpload` and the response bodies for calls like `ListObjects`.

**Comment by ggtakec** [comment]
@gaul I also agree with your opinion.

I think there are two ways to do that.
One is to implement `CURLOPT_DEBUGFUNCTION` to enable fine control.
The other is to output bodies as a debug message only for `CompleteMultipartUpload` and `ListObjects`.

I think that implementing the `DEBUG FUNCTION` will take some effort. Thus I think the second option is better.

In any case, I think we also need to upgreade the curldbg option.
If always dumping the body will make the debug log bigger than current.
Therefore, I think it seems better to divide the curl debug information into the current level and the level at which body is dumped.

For example, we prepare for three types curldbg: `curldbg`(no parameter: same as the current), `curldbg=normal`(same as no parameter for curldbg), `curldbg=deep`(with dumping bodies).
It means that new curldbg option can have a parameters(optional).

If there is no problem with this idea, I will make a PR for this issue.

**Comment by ggtakec** [comment]
Close this Issue.
If the problem remains, please reopen.
