### ISSUE TITLE
Support for OpenStack Identity API v3

### ISSUE THREAD

**Issue by ocafebabe** [s3fs-fuse/s3fs-fuse#1300]
Hi,

This is more a feature request than a bug: I'm currently using S3FS with an object storage that is S3 compatible (OpenStack Swift) and this works perfectly well. But my cloud provider (OVH) has warned me that support for the [Identity API v2](https://docs.openstack.org/keystone/pike/contributor/http-api.html) is going to be deprecated by June 23rd and replaced completely by [v3](https://docs.openstack.org/api-ref/identity/v3/index.html).

With v2, I didn't have to do anything special to make it work with S3FS, but I'm afraid that it'll stop working as soon as the new API is deployed...

I was wondering if there was a way to use the new API with S3FS, especially the new **domain** attribute that is now mandatory with the new version.

Thanks

**Comment by gaul** [comment]
Sorry I don't understand this request.  Does OVH have a different authentication scheme than signature v4?  If so it is not S3-compatible.

**Comment by ggtakec** [comment]
I don't think the difference between Openstack Identiy v2 and v3 affects s3fs.
If currently you can access swift (using identiy v2) with s3fs, I think that you are using `Access Key/Secret Access Key` of Identiy (Openstack) user.
If your openstack changes to Identiy v3 and the `Access Key/Secret Access Key` which you are currently using to access Swift is no longer available, I think you will have problems.
However, even if the authentication API changes, I believe that it does not affect the `Access Key/Secret Access Key`.
(Unfortunately, I have no deep knowledge of Openstack, so please forgive me if I made a mistake)

**Comment by ocafebabe** [comment]
> Sorry I don't understand this request. Does OVH have a different authentication scheme than signature v4? If so it is not S3-compatible.

No, they're S3 compatible with the v4 signature, I was talking about the identity system of OpenStack which is the one running underneath the compatibility layer...
