### ISSUE TITLE
s3fs mount with iam_role hangs bash

### ISSUE THREAD

**Issue by aufbakanleitung** [s3fs-fuse/s3fs-fuse#1307]
#### Version of s3fs being used (s3fs --version)
V1.86

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Fuse version 1.9.0

#### Kernel information (uname -r)
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
OSX 10.15.4

#### s3fs command line used, if applicable
`s3fs -o iam_role='admin' drupal-s3-fs ~/Code/s3-drive`
`mount` shows: `s3fs@osxfuse0 on /Users/herman/Code/s3-drive (osxfuse, nodev, nosuid, synchronous, mounted by herman)`

### Details about issue
The s3fs command doesn't give any feedback and any program that tries to access the mounted folder hangs. Reboot didn't help. The mount is eventually removed and s3fs is no longer visible in Activity monitor, then everything works again. The s3 bucket is accessible to the aws s3 cli.

**Comment by gaul** [comment]
Can you share logs when adding the debug flags `-d -o curldbg`?

**Comment by gaul** [comment]
Please reopen if symptoms persist.
