### ISSUE TITLE
s3fs uses the old endpoints/path of s3 instead of new one

### ISSUE THREAD

**Issue by doxa-holdings** [s3fs-fuse/s3fs-fuse#1308]
### Additional Information
I cannot connect to my s3 and realize that the url that s3fs used to connect with s3 is incorrect.

#### Version of s3fs being used (s3fs --version)
1.82

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.7

#### Kernel information (uname -r)
4.15.0-1065-aws

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

#### s3fs command line used, if applicable
s3fs server-stag1 mnt/server-stag1 -o passwd_file=.passwd-s3fs

#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
Jun 11 15:39:36 ip-11-0-1-162 s3fs[28927]: < x-amz-bucket-region: ap-southeast-1
Jun 11 15:39:36 ip-11-0-1-162 s3fs[28927]: < x-amz-request-id: 999DCD4C35BBCAA9
Jun 11 15:39:36 ip-11-0-1-162 s3fs[28927]: < x-amz-id-2: CygAI7PBmhGvwjdX/pluzh+f7c9yqhgKGYrnGkJ8h51lDEblvXj6ve2iNjnCIZHiysJz2LyjzlM=
Jun 11 15:39:36 ip-11-0-1-162 s3fs[28927]: < Content-Type: application/xml
Jun 11 15:39:36 ip-11-0-1-162 s3fs[28927]: < Transfer-Encoding: chunked
Jun 11 15:39:36 ip-11-0-1-162 s3fs[28927]: < Date: Thu, 11 Jun 2020 15:39:36 GMT
Jun 11 15:39:36 ip-11-0-1-162 s3fs[28927]: < Server: AmazonS3
Jun 11 15:39:36 ip-11-0-1-162 s3fs[28927]: <
Jun 11 15:39:36 ip-11-0-1-162 s3fs[28927]: * Connection #1 to host server-stag1.s3-ap-southeast-1.amazonaws.com left intact
Jun 11 15:39:36 ip-11-0-1-162 s3fs[28927]: s3fs.cpp:s3fs_check_service(3810): invalid credentials(host=https://s3.amazonaws.com) - result of checking service.
```
### Details about issue
The host is using `server-stag1.s3-ap-southeast-1.amazonaws.com `, however, aws change the host to another style: `s3-ap-southeast-1.amazonaws.com/server-stag1`.
Ref: https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

**Comment by gaul** [comment]
@doxa-holdings What is the resolution of this issue?  Do we need to update the examples or does some code have an issue?

**Comment by doxa-holdings** [comment]
Hello @gaul ,

I found resolution right after posting the thread.

In order to use the new naming convention of S3, we need to add url option. Example as below:
`s3fs sftp-stag1 mnt/sftp-stag1/ -o passwd_file=.passwd-s3fs -o curldbg -o url=https://s3-ap-southeast-1.amazonaws.com`

Please help us update the doc. Thank you.
