### ISSUE TITLE
File upload stat in /var/log/message

### ISSUE THREAD

**Issue by rsravanam** [s3fs-fuse/s3fs-fuse#1309]
### Details about the issue

_I have an s3 mount to the /folder in my CentOS7.6 machine. I have enabled the debug level as INFO. I have observed that 1GB file writes large number of log lines in /var/log/messages and i am unable to understand the file get uploaded or not._
__What i need exactly is, when a file get uploaded from s3 mount folder to s3-bucket it should log in  /var/log/messages be like "INFO: File /data/flow.json uploaded to BUCKET_NAME" Is there a way to get it, or do i need to do configure any in s3-fuse?_
_My team wants to read that line and keeps the history of file upload stats_
_Any help on this, please?_

My fs tab entry:
s3fs#my-s3-bucket /my-folder fuse _netdev,uid=owt,gid=owt,allow_other,use_cache=/tmp,mp_umask=022,dbglevel=info,retries=5, 0 0

**Comment by gaul** [comment]
s3fs sends objects to S3 during `fsync` and `close`.  If you application issues these calls, then it will be uploaded to S3.  There is currently no asynchronous flushing.
