### ISSUE TITLE
storage_class GLACIER for scaleway C14 Cold Storage

### ISSUE THREAD

**Issue by evantill** [s3fs-fuse/s3fs-fuse#1315]
According to [scaleway documentation](https://www.scaleway.com/en/docs/object-storage-glacier/) for [C14 Cold Storage (S3 Glacier alternative)](https://www.scaleway.com/en/c14-cold-storage/) I need to use `GLACIER` as the storage_class.

I was thinking to create a PR to add this special value but wouldn't it be better to let any text values in `storage_class`?

### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.86 (commit:unknown) with GnuTLS(gcrypt)
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_example: 2.9.4_

#### Kernel information (uname -r)
18.7.0

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
macOS Mojave 10.14.6

#### s3fs command line used, if applicable
```
s3fs bucket-instance-1 ~/Downloads/bucket-instance-1 -o passwd_file=~/passwd-s3fs -o url=https://s3.fr-par.scw.cloud -o endpoint=fr-par -o storage_class=GLACIER
```
#### s3fs outputs
```
s3fs: unknown value for storage_class: GLACIER
```

**Comment by gaul** [comment]
Adding Glacier might be reasonable even though its semantics don't work well with s3fs.  For example, users may want to create backups with this storage class even though restoring from them might require an additional step to change its storage class.  Could you test this to see how well it works in practice with Scaleway and AWS?

As for accepting arbitrary strings, it's just easier to add another constant since there are rarely changes to this.

**Comment by evantill** [comment]
simple test done on macos : (still waiting for restore to test reading restored file).

```
> cp README.md ~/Downloads/bucket-instance-1/

> ls -lisart ~/Downloads/bucket-instance-1/                                                                                                                                                                16:10:37
total 128
      1   0 drwx------    1 userXXX staff      0 jan  1  1970 ./
      4 116 -rw-r-----    1 userXXX staff 115814 jui 20 21:54 logo-gif-rp.png
1881327   0 drwx------+ 774 userXXX staff  24768 jui 22 13:01 ../
      3   4 -rw-r--r--    1 userXXX staff    856 jui 22 13:04 admin.png
      2   8 -rw-r--r--    1 userXXX staff   5490 jui 22 16:09 README.md

❯ find ~/Downloads/bucket-instance-1/ -ls                                                                                                                                                                  16:10:41
     1        0 drwx------    1 userXXX   staff                   0  1 jan  1970 /Users/userXXX/Downloads/bucket-instance-1/
     2       16 -rw-r--r--    1 userXXX   staff                5490 22 jui 16:09 /Users/userXXX/Downloads/bucket-instance-1//README.md
     3        8 -rw-r--r--    1 userXXX   staff                 856 22 jui 13:04 /Users/userXXX/Downloads/bucket-instance-1//admin.png
     4      232 -rw-r-----    1 userXXX   staff              115814 20 jui 21:54 /Users/userXXX/Downloads/bucket-instance-1//logo-gif-rp.png

❯ cat ~/Downloads/bucket-instance-1/README.md                                                                                                                                                              16:11:08
cat: /Users/userXXX/Downloads/bucket-instance-1/README.md: Input/output error



```
