### ISSUE TITLE
Stop recommending `s3fs#bucketname` in fstab

### ISSUE THREAD

**Issue by pxeger** [s3fs-fuse/s3fs-fuse#1321]
### Details about issue
In the README and other bits of documentation, you recommend to use this format of `fstab` listing:
```none
s3fs#bucketname /path/to/mountpoint fuse option1,option2 0 0
```
However, according to [`man 5 fstab`](https://helpmanual.io/man5/fstab), this is deprecated:
>  mount(8) and umount(8) support filesystem subtypes.  The subtype is defined by '.subtype' suffix.  For example 'fuse.sshfs'. It's recommended to use subtype notation rather than add any  pre‐fix to the first fstab field (for example 'sshfs#example.com' is deprecated).

Instead you should use
```none
bucketname /path/to/mountpoint fuse.s3fs option1,option2 0 0
```

**Comment by gaul** [comment]
@pxeger Could you submit a pull request for this?
