### ISSUE TITLE
Upgrade Travis macOS Builder

### ISSUE THREAD

**Issue by ggtakec** [s3fs-fuse/s3fs-fuse#1323]
I'll post this issue because we need to keep watching it in the future.  
This issue was first raised by @gaul in #1268.  
In addition, as a content related to this Issue, Travis CI build will be temporarily modified by #1322.

#### osxfuse and travis's image
The reason we are forced to use macOS 10.12 is that osxfuse changes an extension of macOS, and macOS image after 10.13 provided by travis  requires a reboot after osxfuse installation.  
We have to wait for the Travis macOS image to accommodate this.  

#### Homebrew supports
Homebrew's binary support for macOS 10.12 is already over, and we have to use 10.13(travis ci image: xcode9.4) or later.  
Also, awscli for macOS 10.12 can no longer be installed from Homebrew, so we must install it using pip(3).  

#### Python3
And if s3fs build run Homebrew tap without `HOMEBREW_NO_AUTO_UPDATE=1`, python3 cannot be installed(This may be temporary).  
The reason why it cannot be installed is because Homebrew fails to install sqlite, which has a dependency on python3.  
Currently, Travis macOS image(xcode9.2) fails to download the source package from sqlite.org site due to `No route` or `Timeout`.  
_The site has A and AAAA IP addresses, but both are in error._  

#### Test code by python3
The s3fs test code has tests that require python3.  
Currently some test cases only run when python3 is installed.  
However, this is an exceptional condition and we want to run it always.

**Comment by gaul** [comment]
Related issue: travis-ci/travis-ci/issues/10017.

**Comment by gaul** [comment]
Closing since we are moving to GitHub actions in #1488.
