### ISSUE TITLE
Do local files remain accessible offline?

### ISSUE THREAD

**Issue by yashgt** [s3fs-fuse/s3fs-fuse#1324]
If I mount a local directory and point it to an S3 bucket using s3fs, does it eventually receive the files stored in S3 and do the files remain accessible for reading even if S3 or internet is not accessible? Is there an alternative to s3fs that can serve the above requirement if s3fs does not serve it?

**Comment by ngbranitsky** [comment]
Answers inline.

Norman Branitsky

> On Jul 6, 2020, at 01:07, yashgt <notifications@github.com> wrote:
> If I mount a local directory and point it to an S3 bucket using s3fs, does it eventually receive the files stored in S3 and do the files remain accessible for reading even if S3 or internet is not accessible?
> 
I believe s3fs will display a transport error if the mount point is inaccessible.
> Is there an alternative to s3fs that can serve the above requirement if s3fs does not serve it?
> 
Perhaps this might meet your requirements.
AWS Storage Gateway with local caching:
https://aws.amazon.com/storagegateway/file/
I believe the File Gateway will still serve files while it tries to reconnect to S3 in the background.

**Comment by gaul** [comment]
s3fs is not intended as an offline file system.  However, metadata (`-o max_stat_cache_size`, `-o stat_cache_expire`) and data caching (`-o use_cache`) may allow s3fs to work offline in a limited capacity.

[catfs](https://github.com/kahing/catfs) also has an [open issue](https://github.com/kahing/catfs/issues/41) requesting offline support although this is not implemented.
