### ISSUE TITLE
9 tests failed for integration test during `make check`

### ISSUE THREAD

**Issue by JiaHong-Lee** [s3fs-fuse/s3fs-fuse#1330]
#### Version of s3fs being used (s3fs --version)
V1.86 (commit:bb20fc3) with OpenSSL

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Version: 2.9.7-1ubuntu1

#### Kernel information (uname -r)
4.15.0-109-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

#### s3fs command line used, if applicable
Not applicable

#### /etc/fstab entry, if applicable
Not applicable

#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
Not applicable

### Details about issue
Integration tests fails with `make test` during compilation.

test-suite.log can be found [here](https://github.com/s3fs-fuse/s3fs-fuse/files/4904328/test-suite.log) (it's very long).

**Comment by gaul** [comment]
One of the reasons this fails is that you don't have the AWS CLI or the xattr tools installed:

```
test-utils.sh: line 267: aws: command not found
test-utils.sh: line 36: setfattr: command not found
```

There are a few other strange errors:

```
s3fs: [ERR] curl.cpp:RequestPerform(2459): HTTP response code 416, returning EIO. Body Text: <?xml version='1.0' encodin
g='UTF-8'?><Error><Code>InvalidRange</Code><Message>The requested range is not satisfiable</Message><RequestId>4442587FB
7D0A2F9</RequestId></Error>
```

Note that we run these tests via Travis for every pull request and these pass so there may be something different about your environment.

**Comment by gaul** [comment]
Please install the required dependencies and reopen if symptoms persist.
