### ISSUE TITLE
Problem with curl above 7.29.0-42

### ISSUE THREAD

**Issue by xxdvxx** [s3fs-fuse/s3fs-fuse#1337]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
s3fs-fuse-1.86-2.el7.x86_64

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
fuse-2.9.2-11.el7.x86_64
fuse-libs-2.9.2-11.el7.x86_64

#### Kernel information (uname -r)
3.10.0-957.10.1.el7.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

#### s3fs command line used, if applicable
```
s3fs ecp-linkshortener /mnt/s3-logs/ -o passwd_file=~/.passwd-s3fs -o dbglevel=info -f -o curldbg
```
#### /etc/fstab entry, if applicable
```
s3fs#ecp-linkshortener                              /mnt/s3-logs                fuse    noatime,rw,uid=0,gid=0,allow_other,nonempty,mp_umask=002 0 0
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
Jul 21 14:05:18 hostname s3fs[9063]: curl.cpp:CheckBucket(3439): Check bucket failed, S3 response: <?xml version="1.0" encoding="UTF-8"?>#012<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>524708C0E2B5813B</RequestId><HostId>CpU0fOc4bElzQ2I+4mWPyooNi2NrCIh7EuO+QY7GW2p15Xvryn3I8LDKAlbv3I7m9fVG4lDEYIw=</HostId></Error>
```
### Details about issue
Hello! I resolve this issue but i think you need fix something.
I have problem when using curl+libcurl version above 7.29.0-42. Install version 7.29.0-42 fix my problem, but in future i cant get updates packaging.

**Comment by xxdvxx** [comment]
upd. curl-7.29.0-46 is working too

**Comment by gaul** [comment]
Since -42 fails but -46 works it seems like curl itself had a regression.
