### ISSUE TITLE
Transport endpoint not connected message when access zero bytes file from the /tmp cache folder

### ISSUE THREAD

**Issue by rahul9222** [s3fs-fuse/s3fs-fuse#1338]
#### Version of s3fs being used (s3fs --version)
_Amazon Simple Storage Service File System V1.85 (commit:0e815c2) with OpenSSL_

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_fuse: 2.9.4_

#### Kernel information (uname -r)
_command result: 4.14.173-106.229.amzn1.x86_64_

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_command result: 
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
_

#### s3fs command line used, if applicable
```
s3fs -o multireq_max=5 -o allow_other -o uid=500 -o gid=48 -o umask=0 -o use_cache=/tmp/cache s3bucketclient /home/ec2-user/html/userfiles/s3bucketclient

```

### Details about issue

We are using the above command to mount the S3 bucket to AWS EC2 machine.
As we have set `-o use_cache=/tmp/cache` parameter in the mount command.
It create cache of the file when we access using the UI application.

Sometime, s3fs generate zero byte file in the Cache folder where in S3 bucket the file is proper.
When application try to access that file again from the UI as s3fs try to find the file in cache first then look for the S3 bucket.
It disconnect from the S3 bucket with error `Transport endpoint is not connected`.

### Solution we are using right now
We move the zero bytes file from the /tmp/cache folder, 
then umount the bucket and mount it again.
And send an email about the bucket failure.

`/bin/find /tmp/cache -type f -size 0k -exec mv {} /home/ec2-user/movedtmp/  \;`
`umount /home/ec2-user/html/userfiles/s3bucketclient`
`s3fs -o multireq_max=5 -o allow_other -o uid=500 -o gid=48 -o umask=0 -o use_cache=/tmp/cache s3bucketclient /home/ec2-user/html/userfiles/s3bucketclient`

**Comment by gaul** [comment]
If you see "Transport endpoint is not connected." this means that s3fs exited, possibly crashing.  We need more logs to diagnose this further.  Please re-run s3fs using `-f -d` flags.

**Comment by rahul9222** [comment]
As we were facing the issue on the Production Server with s3fs.

To resolve we remove the config `-o use_cache=/tmp/cache` from the command.

New command is 
`s3fs -o multireq_max=5 -o allow_other -o uid=500 -o gid=48 -o umask=0 s3bucketclient /home/ec2-user/html/userfiles/s3bucketclient`

**Comment by gaul** [comment]
Please reopen if symptoms persist.
