### ISSUE TITLE
Latest commit did not pass checks (commit:cbd925c) -- please fix or revert ASAP.

### ISSUE THREAD

**Issue by hannah-steele** [s3fs-fuse/s3fs-fuse#1344]

**Comment by gaul** [comment]
Can you be more specific about the failure?  This commit passed in CI recently:

https://travis-ci.org/github/s3fs-fuse/s3fs-fuse/builds/712449945

**Comment by gaul** [comment]
Now I understand, the macOS builder fails due to a `stat(1)` incompatibility.  Please be more descriptive in future bug reports.
