### ISSUE TITLE
ls: reading directory  Input/output error on top level directory

### ISSUE THREAD

**Issue by chethanshetty110** [s3fs-fuse/s3fs-fuse#1350]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
 V1.86 

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
 2.9.7-1ubuntu1

#### Kernel information (uname -r)
5.3.0-1032-aws

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

#### s3fs command line used, if applicable
/usr/local/bin/s3fs -o allow_other -o gid=1000 -o umask=000 -o iam_role=role bucket_name /mnt/intermediate_bucket

#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
### Details about issue
We are able to list the subdirectories in the bucket but when we try to list root level directory it throws below error.

ls: reading directory  Input/output error

**Comment by gaul** [comment]
Could you run s3fs again with the `-f -d` flags?  This will help us debug the symptoms.

**Comment by chethanshetty110** [comment]
At the end of the logs we get the below message. Since this a corporate account, we can't share details of the bucket and contents of the bucket.

[INF]     s3fs.cpp:readdir_multi_head(2539): Could not find / file in stat cache.
[INF]     s3fs.cpp:readdir_multi_head(2539): Could not find /folder1 file in stat cache.
[INF]     s3fs.cpp:readdir_multi_head(2539): Could not find /folder2 file in stat cache.

**Comment by gaul** [comment]
Sorry, there has to be more context for us to investigate.
