### ISSUE TITLE
Will it work across system updates? 

### ISSUE THREAD

**Issue by gpow81** [s3fs-fuse/s3fs-fuse#1358]
Apologize if this is inappropriate place for questions like this. I am still figuring out github. 
We are starting to use s3fs-fuse in production on Redhat7. 
Unfortunately redhat doesn't support it yet and doesn't provide rpm for it so we have to download it from github and compile. 
Here is my concern - how much s3fs-fuse depends on specific versions of packages and libraries in the system? If we update for example rhel 7.7 to 7.8 can we assume that we don't need to touch s3fs-fuse or we actually should be certain that s3fs-fuse will need to be built again? 
Thank you very much. I will appreciate any thoughts.

**Comment by gaul** [comment]
s3fs should continue working after upgrading.  However, I recommend that you install the EPEL package instead of compiling from source:

https://github.com/s3fs-fuse/s3fs-fuse#installation

This ensures that you get the latest version.
