### ISSUE TITLE
The gid/uid of moved files is incorrect

### ISSUE THREAD

**Issue by ggtakec** [s3fs-fuse/s3fs-fuse#1360]
#### Version of s3fs being used (s3fs --version)
v1.86, v1.87

#### Related Issue
#1346 

### Details about issue
In addition to the mount point of s3fs, create a file larger than the size to be uploaded by multipart upload and move the file to the mount point or less.
After that, the owner and group of the original file will be incorrect.
This happens for the same reason as Issue #1346.

**Comment by gaul** [comment]
@ggtakec Can we add a test for this?

**Comment by ggtakec** [comment]
@gaul I think it's possible.
I will create a PR code, so please wait a while.

**Comment by ggtakec** [comment]
#1364 is merged for this issue.
