### ISSUE TITLE
Help me to mount my OVH bucket, please

### ISSUE THREAD

**Issue by inghoward** [s3fs-fuse/s3fs-fuse#1361]
### Additional Information
Need to know what are the values I need to mount my OVH bucket. 

#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.87 (commit:a23d029) with OpenSSL

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.9

#### Kernel information (uname -r)
5.4.0-40-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

#### s3fs command line used, if applicable

s3fs latam /home/me/musica -o use_cache=/tmp -o allow_other -o uid=1001 -o mp_umask=002 -o multireq_max=5 -o use_path_request_style -o url=https://s3.bhs.cloud.ovh.net -o passwd_file=${HOME}/ovh -o dbglevel=info -f -o curldbg

#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)

[CRT] sighandlers.cpp:SetLogLevel(168): change debug level from [CRT] to [INF]
[INF]     s3fs.cpp:set_mountpoint_attribute(4372): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
[INF] curl.cpp:InitMimeType(723): Loaded mime information from /etc/mime.types
[INF] s3fs.cpp:s3fs_init(3455): init v1.87(commit:a23d029) with OpenSSL
[INF] s3fs.cpp:s3fs_check_service(3800): check services.
[INF]       curl.cpp:CheckBucket(3527): check a bucket.
[INF]       curl.cpp:prepare_url(4831): URL is https://s3.bhs.cloud.ovh.net/latam/
[INF]       curl.cpp:prepare_url(4864): URL changed is https://s3.bhs.cloud.ovh.net/latam/
[INF]       curl.cpp:insertV4Headers(2863): computing signature [GET] [/] [] []
[INF]       curl.cpp:url_to_host(99): url is https://s3.bhs.cloud.ovh.net
[CURL DBG] *   Trying 142.44.227.102:443...
[CURL DBG] * TCP_NODELAY set
[CURL DBG] * Connected to s3.bhs.cloud.ovh.net (142.44.227.102) port 443 (#0)
[CURL DBG] * found 384 certificates in /etc/ssl/certs
[CURL DBG] * SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
[CURL DBG] *      server certificate verification OK
[CURL DBG] *      server certificate status verification SKIPPED
[CURL DBG] *      common name: storage.bhs.cloud.ovh.net (matched)
[CURL DBG] *      server certificate expiration date OK
[CURL DBG] *      server certificate activation date OK
[CURL DBG] *      certificate public key: RSA
[CURL DBG] *      certificate version: #3
[CURL DBG] *      subject: CN=storage.bhs.cloud.ovh.net
[CURL DBG] *      start date: Fri, 13 Mar 2020 00:00:00 GMT
[CURL DBG] *      expire date: Sat, 13 Mar 2021 23:59:59 GMT
[CURL DBG] *      issuer: C=GB,ST=Greater Manchester,L=Salford,O=Sectigo Limited,CN=Sectigo RSA Domain Validation Secure Server CA
[CURL DBG] > GET /latam/ HTTP/1.1
[CURL DBG] > Host: s3.bhs.cloud.ovh.net
[CURL DBG] > User-Agent: s3fs/1.87 (commit hash a23d029; OpenSSL)
[CURL DBG] > Accept: */*
[CURL DBG] > Authorization: AWS4-HMAC-SHA256 Credential=XzderY74sHk/20200814/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha2>
[CURL DBG] > x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[CURL DBG] > x-amz-date: 20200814T163342Z
[CURL DBG] >
[CURL DBG] * Mark bundle as not supporting multiuse
[CURL DBG] < HTTP/1.1 400 Bad Request
[CURL DBG] < x-amz-id-2: tx5e94cc4788304895a7e94-005f36bce6
[CURL DBG] < x-amz-request-id: tx5e94cc4788304895a7e94-005f36bce6
[CURL DBG] < Content-Type: application/xml
[CURL DBG] < X-Trans-Id: tx5e94cc4788304895a7e94-005f36bce6
[CURL DBG] < X-Openstack-Request-Id: tx5e94cc4788304895a7e94-005f36bce6
[CURL DBG] < Date: Fri, 14 Aug 2020 16:33:42 GMT
[CURL DBG] < Transfer-Encoding: chunked
[CURL DBG] < X-IPLB-Instance: 28795
[CURL DBG] <
[CURL DBG] * Connection #0 to host s3.bhs.cloud.ovh.net left intact
[ERR] curl.cpp:RequestPerform(2535): HTTP response code 400, returning EIO. Body Text: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'bh>
[ERR] curl.cpp:CheckBucket(3553): Check bucket failed, S3 response: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'bh>
[CRT] s3fs.cpp:s3fs_check_service(3834): Failed to connect region 'us-east-1'(default), so retry to connect region 'bhs'.
[INF] curl.cpp:ReturnHandler(341): Pool full: destroy the oldest handler
[INF]       curl.cpp:CheckBucket(3527): check a bucket.
[INF]       curl.cpp:prepare_url(4831): URL is https://s3.bhs.cloud.ovh.net/latam/
[INF]       curl.cpp:prepare_url(4864): URL changed is https://s3.bhs.cloud.ovh.net/latam/
[INF]       curl.cpp:insertV4Headers(2863): computing signature [GET] [/] [] []
[INF]       curl.cpp:url_to_host(99): url is https://s3.bhs.cloud.ovh.net
[CURL DBG] * Found bundle for host s3.bhs.cloud.ovh.net: 0x7ff660001bf0 [serially]
[CURL DBG] * Can not multiplex, even if we wanted to!
[CURL DBG] * Re-using existing connection! (#0) with host s3.bhs.cloud.ovh.net
[CURL DBG] * Connected to s3.bhs.cloud.ovh.net (142.44.227.102) port 443 (#0)
[CURL DBG] > GET /latam/ HTTP/1.1
[CURL DBG] > Host: s3.bhs.cloud.ovh.net
[CURL DBG] > User-Agent: s3fs/1.87 (commit hash a23d029; OpenSSL)
[CURL DBG] > Accept: */*
[CURL DBG] > Authorization: AWS4-HMAC-SHA256 Credential=XzderY74sHk/20200814/bhs/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-a>
[CURL DBG] > x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[CURL DBG] > x-amz-date: 20200814T163342Z
[CURL DBG] >
[CURL DBG] * Mark bundle as not supporting multiuse
[CURL DBG] < HTTP/1.1 403 Forbidden
[CURL DBG] < x-amz-id-2: tx2a83016dd3274cc1a55b7-005f36bce6
[CURL DBG] < x-amz-request-id: tx2a83016dd3274cc1a55b7-005f36bce6
[CURL DBG] < Content-Type: application/xml
[CURL DBG] < X-Trans-Id: tx2a83016dd3274cc1a55b7-005f36bce6
[CURL DBG] < X-Openstack-Request-Id: tx2a83016dd3274cc1a55b7-005f36bce6
[CURL DBG] < Date: Fri, 14 Aug 2020 16:33:42 GMT
[CURL DBG] < Transfer-Encoding: chunked
[CURL DBG] < X-IPLB-Instance: 28795
[CURL DBG] <
[CURL DBG] * Connection #0 to host s3.bhs.cloud.ovh.net left intact
[ERR] curl.cpp:RequestPerform(2540): HTTP response code 403, returning EPERM. Body Text: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your ke>
/latam/

host:s3.bhs.cloud.ovh.net
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20200814T163342Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</CanonicalRequest><CanonicalRequestBytes>47 45 54 0a 2f 6c 61 74 61 6d 2f 0a >
20200814T163342Z
20200814/bhs/s3/aws4_request
ceaed1e46a26bb70b2c8db6dfa0dd4864f31282f844844d53c80688a84c145e6</StringToSign><SignatureProvided>b8e1fbc850ce286e485df5a0b150a6e8599cd50777a8>
[ERR] curl.cpp:CheckBucket(3553): Check bucket failed, S3 response: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your ke>
/latam/

host:s3.bhs.cloud.ovh.net
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20200814T163342Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</CanonicalRequest><CanonicalRequestBytes>47 45 54 0a 2f 6c 61 74 61 6d 2f 0a >
20200814T163342Z
20200814/bhs/s3/aws4_request
ceaed1e46a26bb70b2c8db6dfa0dd4864f31282f844844d53c80688a84c145e6</StringToSign><SignatureProvided>b8e1fbc850ce286e485df5a0b150a6e8599cd50777a8>
[CRT] s3fs.cpp:s3fs_check_service(3855): Failed to connect by sigv4, so retry to connect by signature version 2.
[INF]       curl.cpp:CheckBucket(3527): check a bucket.
[INF]       curl.cpp:prepare_url(4831): URL is https://s3.bhs.cloud.ovh.net/latam/
[INF]       curl.cpp:prepare_url(4864): URL changed is https://s3.bhs.cloud.ovh.net/latam/
[CURL DBG] * Found bundle for host s3.bhs.cloud.ovh.net: 0x7ff660001bf0 [serially]
[CURL DBG] * Can not multiplex, even if we wanted to!
[CURL DBG] * Re-using existing connection! (#0) with host s3.bhs.cloud.ovh.net
[CURL DBG] * Connected to s3.bhs.cloud.ovh.net (142.44.227.102) port 443 (#0)
[CURL DBG] > GET /latam/ HTTP/1.1
[CURL DBG] > Host: s3.bhs.cloud.ovh.net
[CURL DBG] > User-Agent: s3fs/1.87 (commit hash a23d029; OpenSSL)
[CURL DBG] > Accept: */*
[CURL DBG] > Authorization: AWS XzderY74sHk:T3VXIRogi2rod0n9Dd/9BVQOTj0=
[CURL DBG] > Date: Fri, 14 Aug 2020 16:33:42 GMT
[CURL DBG] >
[CURL DBG] * Mark bundle as not supporting multiuse
[CURL DBG] < HTTP/1.1 403 Forbidden
[CURL DBG] < x-amz-id-2: tx7af7fbdbfd8f4e53b6408-005f36bce6
[CURL DBG] < x-amz-request-id: tx7af7fbdbfd8f4e53b6408-005f36bce6
[CURL DBG] < Content-Type: application/xml
[CURL DBG] < X-Trans-Id: tx7af7fbdbfd8f4e53b6408-005f36bce6
[CURL DBG] < X-Openstack-Request-Id: tx7af7fbdbfd8f4e53b6408-005f36bce6
[CURL DBG] < Date: Fri, 14 Aug 2020 16:33:43 GMT
[CURL DBG] < Transfer-Encoding: chunked
[CURL DBG] < X-IPLB-Instance: 28795
[CURL DBG] <
[CURL DBG] * Connection #0 to host s3.bhs.cloud.ovh.net left intact
[ERR] curl.cpp:RequestPerform(2540): HTTP response code 403, returning EPERM. Body Text: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your ke>

Fri, 14 Aug 2020 16:33:42 GMT
/latam/</StringToSign><SignatureProvided>T3VXIRogi2rod0n9Dd/9BVQOTj0=</SignatureProvided><AWSAccessKeyId>XzderY74sHk</AWSAccessKeyId></Error>
[ERR] curl.cpp:CheckBucket(3553): Check bucket failed, S3 response: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your ke>

Fri, 14 Aug 2020 16:33:42 GMT
/latam/</StringToSign><SignatureProvided>T3VXIRogi2rod0n9Dd/9BVQOTj0=</SignatureProvided><AWSAccessKeyId>XzderY74sHk</AWSAccessKeyId></Error>
[CRT] s3fs.cpp:s3fs_check_service(3870): invalid credentials(host=https://s3.bhs.cloud.ovh.net) - result of checking service.
[ERR] s3fs.cpp:s3fs_exit_fuseloop(3445): Exiting FUSE event loop due to errors

[INF] s3fs.cpp:s3fs_destroy(3513): destroy
[WAN] s3fs.cpp:s3fs_destroy(3517): Failed to clean up signal object.

### Details about issue

I have this OVH openrc.sh file

export OS_AUTH_URL=https://auth.cloud.ovh.net/v3
export OS_PROJECT_ID=458754589654785eb009ecce4545db4f
export OS_PROJECT_NAME="3254125489067792"
export OS_USER_DOMAIN_NAME="Default"
if [ -z "$OS_USER_DOMAIN_NAME" ]; then unset OS_USER_DOMAIN_NAME; fi
export OS_PROJECT_DOMAIN_ID="default"
if [ -z "$OS_PROJECT_DOMAIN_ID" ]; then unset OS_PROJECT_DOMAIN_ID; fi

unset OS_TENANT_ID
unset OS_TENANT_NAME

export OS_USERNAME="XzderY74sHk"

echo "Please enter your OpenStack Password for project $OS_PROJECT_NAME as user $OS_USERNAME: "
read -sr OS_PASSWORD_INPUT
export OS_PASSWORD=$OS_PASSWORD_INPUT

export OS_REGION_NAME="BHS"

if [ -z "$OS_REGION_NAME" ]; then unset OS_REGION_NAME; fi
export OS_INTERFACE=public
export OS_IDENTITY_API_VERSION=3

**Aditional Information**

I use to login on https://horizon.cloud.ovh.net/auth/login/ using this user name and password:
User XzderY74sHk
Password UhgR56FftSzCvgThnjUiA4bj2PJtBRra

Please, tell me what is the rigth command I have to use to mount my "latam" budget in my /home/me/musica folder. I've been unable to mount

s3fs latam /home/me/musica -o use_cache=/tmp -o allow_other -o uid=1001 -o mp_umask=002 -o multireq_max=5 -o use_path_request_style -o url=https://s3.bhs.cloud.ovh.net -o passwd_file=${HOME}/ovh -o dbglevel=info -f -o curldbg

my ovh file says something like this
XzderY74sHk:UhgR56FftSzCvgThnjUiA4bj2PJtBRra

**Comment by fabienli** [comment]
Hi @inghoward,
Here is what I did to mount an OVH object storage's container under ubuntu 20.04:
1. the container is created in the "Object Storage" tab (let's call it mycontainer)
2. you have created a user with the role to "ObjectStore operator" under "Users & Roles"
3. Download the openrc.sh file for your user, in the same tab
4. Create the credential via:
`source openrc.sh `
`openstack ec2 credentials create`
5. Note the access and secret values and store those credentials into a file
`sudo vi /etc/passwd-s3fs`
write in: 
> access-value:secret-value

`sudo chmod 600 /etc/passwd-s3fs`

6. prepare the folders for mounting:
`sudo mkdir /mnt/s3 /tmp/cache `
`sudo chmod 777 /mnt/s3 /tmp/cache `
7. and finally mount your container:
`sudo s3fs mycontainer /mnt/s3/ -o url=https://storage.gra.cloud.ovh.net/ -o endpoint=GRA -o passwd_file=/etc/passwd-s3fs -o use_path_request_style -o allow_other -o use_cache=/tmp/cache -o nonempty`

**Comment by gaul** [comment]
@inghoward Do these instructions work for you?

**Comment by inghoward** [comment]
> @inghoward Do these instructions work for you?

Hi,
Really don't tested cause the reply arrived some month after original request. I finnaly used rclone to mount my OVH bucket and is working as espected.

**Comment by gaul** [comment]
Glad that you found a solution.  Please reopen if you encounter these symptoms again.
