### ISSUE TITLE
url from fstab is not used

### ISSUE THREAD

**Issue by michagruner** [s3fs-fuse/s3fs-fuse#1367]
(At least) The url-option in fstab is not getting used on Alpine linux, while on the command-line it is getting used.

#### Version of s3fs being used (s3fs --version)
bash-5.0# s3fs --version
Amazon Simple Storage Service File System V1.86 (commit:unknown) with OpenSSL

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
fuse-2.9.9-r1

#### Kernel information (uname -r)
bash-5.0# uname -r
5.4.0-42-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
bash-5.0# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.0
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

#### s3fs command line used, if applicable
```
bash-5.0# s3fs docker -o url=https://s3.mydomain.de -o use_path_request_style /media/dockers3/
bash-5.0# ls -al /media/dockers3/
total 1393301
drwx------    1 root     root             0 Jan  1  1970 .
drwxr-xr-x    6 root     root             6 Apr 19 16:47 ..

```
#### /etc/fstab entry, if applicable
```
s3fs#docker          /media/dockers3 fuse.s3fs  _netdev,allow_other,umask=777,use_path_request_style,url=https://s3.mydomain.de/ 0 0
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
/var/log/messages when calling mount /media/dockers3:
Aug 18 08:44:54 docker user.info s3fs[934]: init v1.86(commit:unknown) with OpenSSL
Aug 18 08:44:55 docker user.crit s3fs[934]: s3fs.cpp:s3fs_check_service(3862): Failed to connect region 'us-east-1'(default), so retry to connect region 'ap-northeast-2'.
Aug 18 08:44:57 docker user.crit s3fs[934]: s3fs.cpp:s3fs_check_service(3883): Failed to connect by sigv4, so retry to connect by signature version 2.
Aug 18 08:44:57 docker user.crit s3fs[934]: s3fs.cpp:s3fs_check_service(3895): Bad Request(host=https://s3-ap-northeast-2.amazonaws.com) - result of checking service.
```

**Comment by gaul** [comment]
@michagruner I successfully mounted a GCS bucket via fstab:

```
bucket /path fuse.s3fs _netdev,allow_other,umask=777,use_path_request_style,url=https://storage.googleapis.com,profile=google 0 0
```

Perhaps something related to Alpine Linux?

**Comment by gaul** [comment]
Please reopen if symptoms persist.

**Comment by michagruner** [comment]
@gaul I'm not sure what happened in between, but it works on that system now after upgrading:
bash-5.0# s3fs --version
Amazon Simple Storage Service File System V1.87 (commit:unknown) with OpenSSL

Thanks to whoever fixed it! :)
