### ISSUE TITLE
vim settings

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#1369]
Currently most files have the trailer:

```
/*
* Local variables:
* tab-width: 4
* c-basic-offset: 4
* End:
* vim600: noet sw=4 ts=4 fdm=marker
* vim<600: noet sw=4 ts=4
*/ 
```

This seems incorrect, shouldn't the sw and ts be 2?  And also set expandtab?

**Comment by ggtakec** [comment]
@gaul Thanks, as you pointed out, this is wrong.
#1370 will be merged.
And there is another issue I would like you to consider together after this POST.
