### ISSUE TITLE
dcache.cpp:478:33: error: 'SEEK_HOLE' was not declared in this scope    int  hole_pos  = lseek(fd, 0, SEEK_HOLE);

### ISSUE THREAD

**Issue by akhanduri20** [s3fs-fuse/s3fs-fuse#1372]
https://github.com/s3fs-fuse/s3fs-fuse/blob/bcf6838e86284e68594f41091973ae7a11ac5677/src/fdcache.cpp#L478

**Comment by ggtakec** [comment]
@akhanduri20 
If you could build s3fs from source code, please wait for #1365 to be merged.
After it is merged, please build with the source code of master.
Thanks in advance for your assistance.

**Comment by akhanduri20** [comment]
Thank you for updates!
I forked master and created a branch on last successful commit and am using it. I will wait for said merger but generally master should always be stable!

Thanks...Anand

Sent from my iPhone

On Aug 20, 2020, at 6:08 AM, Takeshi Nakatani <notifications@github.com> wrote:

﻿

@akhanduri20<https://github.com/akhanduri20>
If you could build s3fs from source code, please wait for #1365<https://github.com/s3fs-fuse/s3fs-fuse/pull/1365> to be merged.
After it is merged, please build with the source code of master.
Thanks in advance for your assistance.

**Comment by gaul** [comment]
Marking as fixed.
