### ISSUE TITLE
S3fs update from 1.79 to 1.85 doesnt work via Terminal.

### ISSUE THREAD

**Issue by PhilipHoernschemeyer** [s3fs-fuse/s3fs-fuse#1380]
### Additional Information
I want to update to Version 1.85 minimum. Now I have  Version 1.79.
I have a Linux Ubuntu Aws machine. If i run sudo apt-get install s3fs for example, ubuntu tells me, that 1.79 is the newest version. 
Its LTS 16.04. How can I update easily from 1.79 to 1.85 ?  I want to update the package and dont want to install a new s3fs via git. 
Is there a solution?

#### Version of s3fs being used (s3fs --version)
1.79

#### Kernel information (uname -r)
_command result: uname -r_

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"

#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```

**Comment by gaul** [comment]
Legacy versions of Ubuntu do not upgrade all packages:

https://packages.ubuntu.com/search?keywords=s3fs&searchon=names

I recommend upgrading your distribution or you can compile from source:

https://github.com/s3fs-fuse/s3fs-fuse/blob/master/COMPILATION.md
