### ISSUE TITLE
Digital Ocean storage thrown Operation not allowed when I try to follow inside dir

### ISSUE THREAD

**Issue by shubaivan** [s3fs-fuse/s3fs-fuse#1386]
### Additional Information
I used digital ocean storage in my ubuntu 18.04 by standart library `s3fs` for mount my storage,
like this 

`s3fs minimoj-consumer /home/ivan/hosts/docker-symfony/symfony/do1 -o passwd_file=/home/ivan/hosts/docker-symfony/symfony/.passwd-s3fs -o url=https://ams3.digitaloceanspaces.com/ -o dbglevel=info -f -o curldbg`

And inside do appear directory, but when I try to execute `cd minimoj-consumer` I faced with error - `Operation not allowed`

what last what I had from `curldbg` console

```
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< x-amz-request-id: tx0000000000000830812d2-005f58aaad-ab90b1-ams3b
< Content-Type: application/xml
< Date: Wed, 09 Sep 2020 10:13:01 GMT
< Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
< 
* Connection #1 to host minimoj-consumer.ams3.digitaloceanspaces.com left intact
[INF]       curl.cpp:RequestPerform(1940): HTTP response code 200
[WAN] s3fs.cpp:append_objects_from_xml_ex(2575): contents_xp->nodesetval is empty.
[INF]   s3fs.cpp:readdir_multi_head(2346): [path=/][list=0]
[INF]       curl.cpp:Request(3970): [count=0]
[INF] s3fs.cpp:s3fs_getattr(812): [path=/minimoj-consumer]
[INF] s3fs.cpp:s3fs_getattr(812): [path=/]
[INF] s3fs.cpp:s3fs_getattr(812): [path=/]
[INF] s3fs.cpp:s3fs_getattr(812): [path=/minimoj-consumer]
[INF] s3fs.cpp:s3fs_access(3461): [path=/minimoj-consumer][mask=X_OK ]
[INF] s3fs.cpp:s3fs_access(3461): [path=/minimoj-consumer][mask=X_OK ]
```

How to manager all what I have in my bucket ? 

#### Version of s3fs being used (s3fs --version)
File System V1.82(commit:unknown)

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Unknown option -qi

#### Kernel information (uname -r)
4.15.0-117-generic

**Comment by gaul** [comment]
Could you try testing with the latest version 1.87?

**Comment by shubaivan** [comment]
ok, I will test

**Comment by shubaivan** [comment]
@gaul could you help, how to update this packeg in ubuntu 18.04 ?

**Comment by shubaivan** [comment]
I executed install but still had 1.82
sudo apt install s3fs awscli -y
System V1.82(commit:unknown)

**Comment by shubaivan** [comment]
The simplest way to compile this package is:

  1. `cd' to the directory containing the package's source code and type
     `./configure' to configure the package for your system.

/s3fs-fuse-1.87$ ./configure
file or dir was not found

**Comment by gaul** [comment]
Please file the compilation instructions at:

https://github.com/s3fs-fuse/s3fs-fuse/blob/master/COMPILATION.md

I have asked Ubuntu to upgrade its LTS s3fs packages before but they declined to do so.

**Comment by gaul** [comment]
Please reopen if symptoms persist.
