### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by ggtakec** [s3fs-fuse/s3fs-fuse#1415]
## Details about issue
Travis will close travis-ci.org on December 31st, 2020 as follows:
By then, move to travis-ci.com.

> In an effort to ensure that all of our users - whether you build open-source, public or private repositories - receive regular feature updates, security patches and UX/UI enhancements, we are announcing that travis-ci.org will be officially closed down completely on December 31st, 2020, allowing us to focus all our efforts on bringing new features and fixes to travis-ci.com and all of our awesome users like yourself on the travis-ci.com domain. 

Related URL: https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

**Comment by gaul** [comment]
Done: https://travis-ci.com/github/s3fs-fuse/s3fs-fuse

**Comment by ggtakec** [comment]
Thanks!

**Comment by ggtakec** [comment]
I found an error on travis-ci.com, it occurred on ppc64 about java loading.
```
$ sudo update-alternatives --set java /usr/lib/jvm/java-7-openjdk-ppc64el/jre/bin/java
update-alternatives: error: alternative /usr/lib/jvm/java-7-openjdk-ppc64el/jre/bin/java for java not registered; not setting
The command "sudo update-alternatives --set java /usr/lib/jvm/java-7-openjdk-ppc64el/jre/bin/java" failed and exited with 2 during .
```
