### ISSUE TITLE
Human error inadvertently clobbering s3fs-fuse meta and/or data?

### ISSUE THREAD

**Issue by socomsystems** [s3fs-fuse/s3fs-fuse#1417]
Case scenario:

- First **bucket named XYZ** with s3 like **provider A.**  This bucket's mount maps to: /var/s3-storage/**client/rodman**

- Second **bucket named XYZ** with s3 like **provider B**. This bucket's mount maps to: /var/s3-storage/**client/rodwoman**

- A Nextcloud or Owncloud module that facilitate access to s3 like "external storage" instances is created as type "local" dir /home/rodman/storage mapping to /var/s3-storage/**client/rodman**

- Four separate computers storage volumes have mirrors of the /home/rodman/storage directory and replicate via torrent app SyncThing. 

**_Mounts execute successfully, can anyone shred some light on what happens to the meta or other issues arising from this case?_** 

This case happened, nothing stopped it from happening and things went a foul - will post more info as soon as I can.  Posting to Github issues for Nextcloud, Owncloud and Syncthing as well.

Cheers,
Troy

**Comment by gaul** [comment]
Sorry I cannot parse this issue.  Please reopen if you have a more specific s3fs query.
