### ISSUE TITLE
Frequently unmounted the mount point which is mounted using s3fs

### ISSUE THREAD

**Issue by krishnakvk** [s3fs-fuse/s3fs-fuse#1419]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
_example: 1.00_
Amazon Simple Storage Service File System V1.86 (commit:unknown) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_example: 2.9.4_

#### Kernel information (uname -r)
_command result: uname -r_
4.14.35-1902.303.4.1.el7uek.x86_64
#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_command result: cat /etc/os-release_
NAME="Oracle Linux Server"
VERSION="7.8"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Oracle Linux Server 7.8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:8:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.8
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.8

#### s3fs command line used, if applicable
```
s3fs Brit_Data_1 /Backup -o passwd_file=${HOME}/.passwd-s3fs -o url=https://osdata.compat.objectstorage.us-ashburn-1.oraclecloud.com  -onomultipart -o use_path_request_style
```
#### /etc/fstab entry, if applicable
```
s3fs /Backup fuse.s3fs rw,nosuid,nodev,relatime,user_id=0,group_id=0 0 0
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
# grep s3fs /var/log/syslog
grep: /var/log/syslog: No such file or directory

]# journalctl | grep s3fs
Sep 21 09:54:33 ashhubnbkme07 kernel: s3fs[15634]: segfault at 21 ip 0000564661530a44 sp 00007fb9667fb850 error 4 in s3fs[5646614c0000+99000]
Sep 21 09:54:35 ashhubnbkme07 abrt-hook-ccpp[15635]: Process 26609 (s3fs) of user 0 killed by SIGSEGV - dumping core
Sep 21 13:22:53 ashhubnbkme07 s3fs[7483]: s3fs: unable to access MOUNTPOINT /Backup: Transport endpoint is not connected
Sep 21 13:23:46 ashhubnbkme07 s3fs[7728]: init v1.86(commit:unknown) with OpenSSL
Sep 21 13:33:16 ashhubnbkme07 s3fs[10414]: init v1.86(commit:unknown) with OpenSSL
Sep 23 08:22:11 ashhubnbkme07 kernel: s3fs[29668]: segfault at 21 ip 000055ea20391a44 sp 00007f8d877fd850 error 4 in s3fs[55ea20321000+99000]
Sep 23 08:22:12 ashhubnbkme07 abrt-hook-ccpp[29878]: Process 10414 (s3fs) of user 0 killed by SIGSEGV - dumping core
Sep 23 10:23:47 ashhubnbkme07 s3fs[31185]: init v1.86(commit:unknown) with OpenSSL
Sep 23 11:02:17 ashhubnbkme07 kernel: s3fs[9226]: segfault at 21 ip 000055ce7f330a44 sp 00007f14a1ffa850 error 4 in s3fs[55ce7f2c0000+99000]
Sep 23 11:02:17 ashhubnbkme07 abrt-hook-ccpp[9229]: Process 31185 (s3fs) of user 0 killed by SIGSEGV - ignoring (low free space)

```
### Details about issue
I have mounted the object storage bucket on to the Linux server.  it unmounting frequently. We are unable to find any logs and why it is unmounting. I have mounted the oracle cloud object storage bucket. Please let  me know the solution

**Comment by gaul** [comment]
`SIGSEGV` suggests a bug in s3fs.  Can you try upgrading to 1.87 which fixes many of these symptoms?  If this does not work, please connect `gdb` to `s3fs` and get a backtrace.  Thanks!

**Comment by krishnakvk** [comment]
Thanks for the update. Can you please provide the rpm of version 1.87 so that I can install using yum.  What is gdb?

**Comment by juliogonzalez** [comment]
@krishnakvk you can get it from the EPEL8 repository.

Or (I am not so familiar with Oracle Linux), maybe you can just add the EPEL8 repositoriy and then install the package.

**Comment by gaul** [comment]
s3fs does not provide rpms; instead it relies on distributions.  Oracle Linux supports EPEL but I have never used it:

https://blogs.oracle.com/wim/using-epel-repos-with-oracle-linux

It would be great if someone could add instructions for Oracle on the wiki:

https://github.com/s3fs-fuse/s3fs-fuse/wiki/Non-Amazon-S3

We cannot provide general software debugging advice but here is a starting point if upgrading doesn't help:

https://sourceware.org/gdb/onlinedocs/gdb/Backtrace.html

**Comment by gaul** [comment]
Please reopen if symptoms persist.
