### ISSUE TITLE
When using path 'Failed to access bucket'

### ISSUE THREAD

**Issue by petemill** [s3fs-fuse/s3fs-fuse#142]
When connecting to the root of a bucket, connection is successful, but when attempting to connect to a path, the error 'Failed to access bucket' is always encountered. Have tried different regions and buckets but always get the same issue.

With '-o curldbg' specified I can see that Amazon is giving a response of SignatureDoesNotMatch when performing a GET for the path.

**Comment by petemill** [comment]
note that this seems to be a newly introduced bug, as I went back a year and built the old v1.76 from source and it does not present this issue.

**Comment by ggtakec** [comment]
@petemill 
I'm sorry for replying late.
This issue is as same as a problem which is posted on google groups, and I merged #155 today which  fixed this problem.
Please try to use latest codes in master branch.

I closed this issue, and if you have a problem, please post new issue.
Thanks a lot.
