### ISSUE TITLE
New install. specified unknown third option error with Wasabi

### ISSUE THREAD

**Issue by ehelmrii** [s3fs-fuse/s3fs-fuse#1420]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.87 (commit:3c5b35b) with OpenSSL

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.2

#### Kernel information (uname -r)
3.10.0-1127.19.1.el7.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

#### s3fs command line used, if applicable
 s3fs s3-bucket-name /tmp/wasabi -o passwd_file=/etc/passwd-s3fs -o url=https://s3.wasabisys.com
```
#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
s3fs: specified unknown third option(url=https://s3.wasabisys.com).
```
```
### Details about issue
New install and getting the error above trying to mount via the Wasabi API. Not sure what to try next, looking for guidance. It has never worked, always get the "unknown third option" error.

**Comment by gaul** [comment]
@ehelmrii This works in my testing.  Are you sure that this is the exact command-line?  Sometimes there are whitespace or unicode issues.

**Comment by gaul** [comment]
Please reopen if symptoms persist.
