### ISSUE TITLE
1.87 - symlinks not working after remount

### ISSUE THREAD

**Issue by cris-b** [s3fs-fuse/s3fs-fuse#1427]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
1.87
#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.2

#### Kernel information (uname -r)

3.10.0-1127.18.2.el7.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)

NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"

When using 1.87:

create symlink
ls -l <symlink>
lrwxrwxrwx. 1 crisb crisb       6 Sep 29 10:13 cristest -> data
unmount s3fs
mount s3fs
ls -l <symlink>
lrwxrwxrwx. 1 crisb crisb       6 Sep 29 10:13 cristest -> 

Rolling back to 1.86 solves the issue.

I'm only using _netdev, passwd_file and url parameters to mount.

**Comment by gaul** [comment]
@ggtakec I bisected this to 1f796d432d767bdcfe476052fe890bdb5488a15c but this does not make sense to me.  Any ideas?

**Comment by ggtakec** [comment]
@gaul This is a bug, I probably found its reason in code, please wait PR.

**Comment by gaul** [comment]
Please test with the latest master.
