### ISSUE TITLE
Logging to dedicated (non-syslog) file?

### ISSUE THREAD

**Issue by thecosmicfrog** [s3fs-fuse/s3fs-fuse#1444]
#### Version of s3fs being used (s3fs --version)
`Amazon Simple Storage Service File System V1.87 (commit:unknown) with OpenSSL`

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
```
Name        : fuse
Version     : 2.9.4
Release     : 1.18.amzn1
Architecture: x86_64
```

#### Kernel information (uname -r)
`4.14.193-113.317.amzn1.x86_64`

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
Amazon Linux

#### /etc/fstab entry, if applicable
```
s3fs#storage:/backup /path/to/backup fuse _netdev,allow_other,iam_role=auto,endpoint=eu-west-1,umask=0007,uid=200,gid=200,dbglevel=debug 0 0
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
```
Oct  8 07:45:28 server-name rsyslogd-2177: imuxsock begins to drop messages from pid 2793 due to rate-limiting
Oct  8 07:45:32 server-name s3fs[1895]: [path=/]
Oct  8 07:45:34 server-name rsyslogd-2177: imuxsock lost 10944 messages from pid 2793 due to rate-limiting
```

### Details about issue
We are currently troubleshooting an issue with s3fs-fuse which is made difficult by the rsyslogd rate limiting, as seen in the `imuxsock begins to drop messages` log entry from `/var/log/messages` above.

Rather than increasing the rate limit, is it possible to have s3fs-fuse log to a dedicated file, e.g. `/var/log/s3fs-fuse/s3fs-fuse.log`?

Thanks - Aaron

**Comment by gaul** [comment]
This seems reasonable.  s3fs would need to grow a new flag and change `S3FS_LOW_LOGPRN` and related macros to use the global instead of `stdout`.  Could you try to add this @thecosmicfrog?

**Comment by ggtakec** [comment]
@gaul @thecosmicfrog I think that it is possible to prepare options or environment variables to switch the log output destination to syslog or a file. 
I will try to modify it, so please wait for a while.

**Comment by gaul** [comment]
@thecosmicfrog Please test with the latest master.
