### ISSUE TITLE
Updating from 1.86 to 1.87

### ISSUE THREAD

**Issue by goodband** [s3fs-fuse/s3fs-fuse#1451]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.86 (commit:unknown) with GnuTLS(gcrypt)

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_example: 2.9.4_

#### Kernel information (uname -r)
5.4.0-48-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"

#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
### Details about issue

Very stupid question. What's the best way to upgrade to 1.87 from 1.86 currently on ubuntu 20 as apt-get update / apt-get upgrade isn't pulling 1.87 down for install

**Comment by gaul** [comment]
Unfortunately Ubuntu does not upgrade s3fs after a given release.  You can either upgrade to Ubuntu 20.10:

https://packages.ubuntu.com/groovy/s3fs

Or compile from master:

https://github.com/s3fs-fuse/s3fs-fuse/blob/master/COMPILATION.md
