### ISSUE TITLE
[doc-enhanced] Add Oracle Cloud Object Storage as working environment

### ISSUE THREAD

**Issue by marcelo-ochoa** [s3fs-fuse/s3fs-fuse#1458]
I have implemented a [docker volume plugin](https://hub.docker.com/repository/docker/mochoa/s3fs-volume-plugin) using s3fs fuse driver and it works on Oracle Cloud Object Storage
See this guide for more details [Using Oracle Cloud Object Storage as Docker Volume](https://marcelo-ochoa.medium.com/using-oracle-cloud-object-storage-as-docker-volume-3ec7882f51b7).
Source [Docker Managed Volume Plugins](https://github.com/marcelo-ochoa/docker-volume-plugins/tree/master/s3fs-volume-plugin)

#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.86 (commit:unknown) with OpenSSL

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Name        : fuse
Version     : 2.9.4
Release     : 1.0.8.el7
Architecture: x86_64
Install Date: Thu Oct 22 12:42:19 2020
Group       : System Environment/Base
Size        : 228360
License     : GPL+
Signature   : RSA/SHA256, Thu Aug 27 07:45:47 2020, Key ID 72f97b74ec551f03
Source RPM  : fuse-2.9.4-1.0.8.el7.src.rpm
Build Date  : Thu Aug 27 07:45:09 2020
Build Host  : jenkins-172-17-0-2-03c67235-22a7-40a5-b87d-479739c99d88.appad3iad.osdevelopmeniad.oraclevcn.com
Relocations : (not relocatable)
Vendor      : Oracle America
URL         : http://fuse.sf.net
Summary     : File System in Userspace (FUSE) utilities
Description :
With FUSE it is possible to implement a fully functional filesystem in a
userspace program. This package contains the FUSE userspace tools to
mount a FUSE filesystem.

#### Kernel information (uname -r)
4.14.35-1902.8.4.el7uek.x86_64
5.4.0-51-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Oracle Linux Server"
VERSION="7.8"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Oracle Linux Server 7.8"

#### s3fs command line used, if applicable
Sample from command line:
```
# echo  "$AWSACCESSKEYID:$AWSSECRETACCESSKEY" > /root/.passwd-s3fs
# s3fs docker-shared-bucket /mnt -o url=https://[tenant-id].compat.objectstorage.[region-id].oraclecloud.com/ -o nomultipart -o use_path_request_style
# cat /etc/fstab
docker-shared-bucket /object-storage fuse.s3fs _netdev,allow_other,use_path_request_style,url=https://[tenant-id].compat.objectstorage.[region-id].oraclecloud.com/ 0 0
```

**Comment by gaul** [comment]
I am glad Oracle cloud works!  Can you add a section to:

https://github.com/s3fs-fuse/s3fs-fuse/wiki/Non-Amazon-S3

**Comment by marcelo-ochoa** [comment]
Done. Thanks @gaul for your quick reply. Marcelo.

**Comment by gaul** [comment]
Could you alphabetize this like the other providers?  Then please close this issue if there is no more work to do.

**Comment by marcelo-ochoa** [comment]
Ready.
