### ISSUE TITLE
S3FS Potential Flakiness and Troubleshooting

### ISSUE THREAD

**Issue by jamiejackson** [s3fs-fuse/s3fs-fuse#1459]
#### Version of s3fs being used (s3fs --version)

Amazon Simple Storage Service File System V1.87 (commit:unknown) with OpenSSL

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.2

#### Kernel information (uname -r)
3.10.0-1127.19.1.el7.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
```
# /etc/fstab
s3fs#redaced.myproject.com:/legacy_media_share/ /mnt/s3/files fuse _netdev,nonempty,iam_role,allow_other,use_path_request_style,url=http://s3.amazonaws.com,uid=root,gid=hudx_admin,umask=0002,rw 0 0
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)

```
Oct 04 20:10:07 prodstack s3fs[1189]: Loaded mime information from /etc/mime.types
Oct 04 20:10:07 prodstack s3fs[1204]: init v1.87(commit:unknown) with OpenSSL
```
### Details about issue

I am getting intermittent issues on a couple of servers, one of which is an SFTP server and another is a web server. Both of them use s3fs mounts as a back end.

I have two monitors:
* One which SFTP-uploads a file every 5 minutes (SFTP is configured to use the mount as its target.)
* One which HTTP requests a file through Apache HTTPD; the file lives on S3 and gets served through HTTPD via its S3FS mount.

I have a suspicion that S3, s3fs, or some connectivity issue is causing occasional flakiness. It's probably going to be too intermittent and short-lived for me to do any live debugging on it so I could use some pointers on how to prepare for investigation.

I imagine that the answer will involve enabling logging; if so, please supply the suggested log levels and any other relevant info.

**Comment by gaul** [comment]
What does flakiness mean?  Does the s3fs process exit?  If so attaching `gdb` and getting a backtrace will help.  Otherwise you can collect more logs with `-f -d`.

**Comment by jamiejackson** [comment]
I have an s3fs mount which is, in turned, served via HTTPD. I have an external monitor which hits one of these files' URLs. This intermittently reports failed requests.

The other use case I have is an SFTP server whose upload target folder is an S3 location (mounted on the SFTP server). I have another monitor that uploads a small file. That monitor also intermittently reports failed uploads.

**Comment by gaul** [comment]
Please reopen if symptoms persist.
