### ISSUE TITLE
s3fs requires directory object to exist to mount via path

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#1460]
Why does s3fs require this?  It can lead to user confusion:

https://stackoverflow.com/questions/64584917/s3fs-bucket-name-contains-illegal-character/64585933

**Comment by ValentinNikin** [comment]
Hello! In my case, on the contrary, it is required that an attempt to mount gives an error if the path does not exist in S3 bucket. Maybe there is some option to do this when trying to mount?

**Comment by ggtakec** [comment]
@ValentinNikin Thanks for the bug report.
It's an unexpected glitch with a series of fixes, so I posted PR #2114 to fix this bug.
Please wait a little longer until this is merged.
