### ISSUE TITLE
May support range cache?

### ISSUE THREAD

**Issue by fly3366** [s3fs-fuse/s3fs-fuse#1490]
If anyone(like ffprobe) need only a few parts of large file. A parted cache(with file offset) may better. PR?

**Comment by gaul** [comment]
Doesn't this already work?  What kind of behavior do you observe?  You can see what s3fs is fetching via `-f -o curldbg`.

**Comment by fly3366** [comment]
Sorry, My question:
1. Can `bucketname.stat` in cache dir shared between multi s3fs instance?
2. Can `bucket` in cache dir shared  between multi s3fs instance?
3. Can s3fs cache object with offset? If I open file's offset like 0-1024K, May s3fs only request with range 0-102400 with curl? But not all file(0 - file end).

**Comment by gaul** [comment]
1&2) are not possible and will lead to data corruption
3) should work this way already.  However s3fs will prefetch data equal to `multipart_size` * `parallel_count`.
