### ISSUE TITLE
mount bucket as list only???

### ISSUE THREAD

**Issue by iriakhov** [s3fs-fuse/s3fs-fuse#151]
Does anyone know if it is possible to mount amazons s3 bucket (containing <10 000 files) via s3fs to list contents only (without copying the actual files on the box? Kind of like S3 browser [for monitoring purposes]) ?

**Comment by ggtakec** [comment]
I think you may mount your S3 bucket in read mode.
When only listing objects in bucket, s3fs does not copy the contents of the object.
But if there are too many objects in bucket(or one directory), maybe you specify the large size value for stats cache.
Please try to use and set options.

Regards,
