### ISSUE TITLE
How to run s3fs with iam_role arn

### ISSUE THREAD

**Issue by mingmingdu** [s3fs-fuse/s3fs-fuse#1516]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
V1.82

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
V1.82

#### Kernel information (uname -r)
Linux ip-10-103-0-38 5.4.0-1029-aws #30~18.04.1-Ubuntu SMP Tue Oct 20 11:09:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_command result: cat /etc/os-release_
Ubuntu 18.04.5 LTS \n \l

#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
### Details about issue
I need run s3fs with iam_role,but I found it use the role in the local account.If I want to run the role in the other account ,it fails.
I can run aws s3 command ,in ~/.aws/config add this line "role_arn = arn:aws:iam::[accountID]:role/[rolename]"

**Comment by gaul** [comment]
Could you try testing with the latest version 1.87?  1.82 is so old that it is hard for us to help you.  Unfortunately Ubuntu 18.04 ships an older version.

**Comment by mingmingdu** [comment]
I have run it with goofys instead.
