### ISSUE TITLE
returning empty contents in bucket after some days of mounting s3fs

### ISSUE THREAD

**Issue by prasad-1729** [s3fs-fuse/s3fs-fuse#1524]
Hi all,

I mounted one bucket in my local system 2 weeks back..At that time it is working fine...
But when I give list,copy commands to that path...It is returning empty value..!
FYI I have nearly 10000 files in that bucket..

Is there any expiry of s3fs mounts? I didn't get what actually happing background..
can you please advise what to do?

Local system: Mac

Thanks!!

**Comment by gaul** [comment]
Can you ensure that s3fs is still running?  It might help to launch it in the foreground with `-f -d` to see what is happening.

**Comment by gaul** [comment]
Please reopen if symptoms persist.
