### ISSUE TITLE
Planning to use s3fs for our cloud ftp server. Maximum file size is 150GB

### ISSUE THREAD

**Issue by SameerSawla** [s3fs-fuse/s3fs-fuse#1527]
### Question
I am looking for the recommended way of using s3fs for a cloud ftp solution to cater files up to 150GB. 
I see there are couple questions about the same but it is not really clear on what's the recommended way to use it.

I will be glad if someone could answer so it could help me and/or other folks are looking for the same question.

**Comment by gaul** [comment]
s3fs can create large objects such as 150 GB, although there are temporary space and performance implications.  s3fs 1.87 and earlier could only create files as large as the amount of temporary space of the local host.  s3fs 1.88 added a feature to periodically flush uploads after a certain amount, controlled by `-o max_dirty_data` (default="5120").  This will issue a multipart upload after reaching the limit, limiting the local storage required.  s3fs uses the `mixupload` optimization to issue server-side copies to "append" to the immutable S3 object.  Unfortunately this causes extra IO on the S3 server so for a 150 GB object the server would do 5 + 10 + 15 + ... + 150 GB = 2,175 GB of IO.  You can reduce this overhead by increasing the `max_dirty_data` value.

**Comment by SameerSawla** [comment]
Thanks for the response @gaul. I was curious about the 64GB limit that is mentioned in the documentation of s3fs-fuse. How does it impact the interaction with the larger files such as a 150GB one?

**Comment by gaul** [comment]
There is no 64 GB limitation.  Can you show me where this is documented?  It should be corrected to 5 TB.

**Comment by gaul** [comment]
Searching Google for ["s3fs" "64GB"](https://www.google.com/search?q=%22s3fs%22+%2264GB%22) shows that both Fedora/Red Hat and Debian/Ubuntu document this incorrectly.  I submitted a pull request for the former but how can we fix the latter?

* https://github.com/juliogonzalez/s3fs-fuse-rpm/pull/16
* https://packages.debian.org/sid/s3fs

**Comment by gaul** [comment]
Submitted https://salsa.debian.org/debian/s3fs-fuse/-/merge_requests/3 for review.

**Comment by juliogonzalez** [comment]
PR accepted for the Fedora/EPEL packages, I will submit it together with 1.89 if it happens soon, or separately if it takes too long to get the new version.

I verified that https://build.opensuse.org/package/view_file/filesystems/s3fs/s3fs.spec?expand=1 does not contain any reference to the maximum file size.

@gaul I am not 100% sure, but it could be you also need to add a changelog entry at https://salsa.debian.org/debian/s3fs-fuse/-/blob/debian/debian/changelog for 1.88-2 (on paper we need it for Fedora/EPEL, but I will handle it later on my own as I think I need to rebase a rebuild entry from Fedora)

**Comment by gaul** [comment]
Both package descriptions PRs which should be the biggest source of confusion.  I noticed several other inaccurate blogs posts but I don't think there is anything we can do about this.
