### ISSUE TITLE
unable to access MOUNTPOINT /**/: No such file or directory

### ISSUE THREAD

**Issue by golfwanlop** [s3fs-fuse/s3fs-fuse#1529]
### Additional Information
I can't enable to access MOUNTPOINT /images/: No such file or directory
example command: s3fs mybucketv2 /images/ -o endpoint=us-west-2

#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.87 (commit:unknown) with GnuTLS(gcrypt)
 
#### Kernel information (uname -r)
_command result: unable to access MOUNTPOINT /images/: No such file or directory

MacOS v10.15.4

**Comment by gaul** [comment]
Do you have a `/images/` directory?  If not `mkdir /images`

**Comment by golfwanlop** [comment]
> Do you have a `/images/` directory?  If not `mkdir /images`

I think /image/ is directory on S3. Actually MOUNTPOINT is on local machine right?

**Comment by bhuiyanmobasshir94** [comment]
If anyone wants help for local folder mounting to s3 bucket, can go through this [stackoverflow.com/a/77369021/7195890](https://stackoverflow.com/a/77369021/7195890)
