### ISSUE TITLE
response codes print bypassed

### ISSUE THREAD

**Issue by Gilgamesh22** [s3fs-fuse/s3fs-fuse#157]
please look at of [curl.cpp](https://github.com/s3fs-fuse/s3fs-fuse/blob/master/src/curl.cpp#L1602)  as you can see the function returns before printing [response](https://github.com/s3fs-fuse/s3fs-fuse/blob/master/src/curl.cpp#L1612). 

Sorry for not fixing my self but I am new to Git Hub and I am not familiar with Git Hub customs.

**Comment by ggtakec** [comment]
Merged #170.
If you have more problem, please reopen this issue.
Regards,
