### ISSUE TITLE
Null values When application read file and create a new file in S3 bucket

### ISSUE THREAD

**Issue by raj-aws** [s3fs-fuse/s3fs-fuse#1574]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
V1.87

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_example: 2.9.4_

#### Kernel information (uname -r)
_command result: uname -r_:- 3.10.0-1160.11.1.el7.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
Red Hat Enterprise Linux Server release 7.9 (Maipo)

#### /etc/fstab entry, if applicable
s3fs#<<bucket name>> /<<Mount Name>> fuse passwd_file=/root/.passwd-s3fs,use_cache=/root/cache,allow_other,umask=0022,gid=3001,uid=5001 0 0

Hi, Our application has a functionality where user download the file from UI (actual file is in S3), updates it and check-in or upload it again, Actually application creates a new file, we observed that when application creates a new file some of the content is having NULL words 

I found similar issue in https://github.com/s3fs-fuse/s3fs-fuse/issues/435, we too have somewhat similar issue, Can you please help with this

**Comment by raj-aws** [comment]
It is impacting our production environment, Can someone please help with this issue at the earliest

**Comment by gaul** [comment]
Try upgrading to 1.88.  The most similar issue is #1453 -- try running without `-o use_cache` as a temporary workaround.

**Comment by gaul** [comment]
Should be fixed by #1579.  Please test with the latest master.
