### ISSUE TITLE
升级s3fs报错

### ISSUE THREAD

**Issue by zhangyn1** [s3fs-fuse/s3fs-fuse#1590]
```
make  all-recursive
make[1]: Entering directory `/tmp/s3fs-fuse-1.88'
Making all in src
make[2]: Entering directory `/tmp/s3fs-fuse-1.88/src'
g++ -DHAVE_CONFIG_H -I. -I..  -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -I/usr/include/libxml2      -g -O2 -Wall -fno-exceptions -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -MT fdcache_entity.o -MD -MP -MF .deps/fdcache_entity.Tpo -c -o fdcache_entity.o fdcache_entity.cpp
fdcache_entity.cpp: In member function ‘bool FdEntity::PunchHole(off_t, size_t)’:
fdcache_entity.cpp:1652:31: error: ‘FALLOC_FL_PUNCH_HOLE’ was not declared in this scope
         if(0 != fallocate(fd, FALLOC_FL_PUNCH_HOLE | FALLOC_FL_KEEP_SIZE, iter->offset, iter->bytes)){
                               ^
fdcache_entity.cpp:1652:54: error: ‘FALLOC_FL_KEEP_SIZE’ was not declared in this scope
         if(0 != fallocate(fd, FALLOC_FL_PUNCH_HOLE | FALLOC_FL_KEEP_SIZE, iter->offset, iter->bytes)){
                                                      ^
make[2]: *** [fdcache_entity.o] Error 1
make[2]: Leaving directory `/tmp/s3fs-fuse-1.88/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/s3fs-fuse-1.88'
make: *** [all] Error 2
```

**Comment by gaul** [comment]
Which operating system do you run on?  Did you run `autogen.sh` and `configure`?  It appears your system has `fallocate` but not the `FALLOC_FL_PUNCH_HOLE` and `FALLOC_FL_KEEP_SIZE` defines.

@ggtakec maybe the autoconf logic is incomplete?

**Comment by Navi2016** [comment]
Hi,

Having the same issue on CentOS 6.10 Kernel 2.6.32-754.35.1.el6.x86_64.

I did run autogen.sh and configure, followed this manual: (see step 5)
https://geektnt.com/how-to-instal-s3fs-fuse-on-centos-6-8.html

`g++ -DHAVE_CONFIG_H -I. -I..  -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -I/usr/include/libxml2      -g -O2 -Wall -fno-exceptions -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -MT fdcache.o -MD -MP -MF .deps/fdcache.Tpo -c -o fdcache.o fdcache.cpp
mv -f .deps/fdcache.Tpo .deps/fdcache.Po
g++ -DHAVE_CONFIG_H -I. -I..  -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -I/usr/include/libxml2      -g -O2 -Wall -fno-exceptions -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -MT fdcache_entity.o -MD -MP -MF .deps/fdcache_entity.Tpo -c -o fdcache_entity.o fdcache_entity.cpp
fdcache_entity.cpp: In member function â€˜bool FdEntity::PunchHole(off_t, size_t)â€™:
fdcache_entity.cpp:1656: error: â€˜FALLOC_FL_PUNCH_HOLEâ€™ was not declared in this scope
fdcache_entity.cpp:1656: error: â€˜FALLOC_FL_KEEP_SIZEâ€™ was not declared in this scope
make[2]: *** [fdcache_entity.o] Error 1
make[2]: Leaving directory `/usr/local/src/s3fs-fuse/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/src/s3fs-fuse'
make: *** [all] Error 2`

Thanks.

**Comment by gaul** [comment]
@ggtakec Can you add some autoconf magic for this?

**Comment by ggtakec** [comment]
Sorry for my late reply.
I issued PR #1628 for this bug.
Changed to define these undefined symbols in the file when there is no fallocate function or before Linux 2.6.38.
