### ISSUE TITLE
Unable to mv or cp big files to object storage, which is mounted with s3-fs

### ISSUE THREAD

**Issue by erki-karblane** [s3fs-fuse/s3fs-fuse#1592]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.89 (commit:unknown) with OpenSSL

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Version     : 2.9.2

#### Kernel information (uname -r)
3.10.0-1160.15.2.el7.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="CentOS Linux"
VERSION="7 (Core)"

#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
s3fs#application-backup /mnt/application-backup fuse _netdev,allow_other,url=https://s3.private.eu-de.cloud-object-storage.appdomain.cloud 0 0
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
Mar 03 08:14:59 amsssobbva.asc-hs.cloud yum[6456]: Updated: s3fs-fuse-1.89-1.el7.x86_64
Mar 03 08:17:06 amsssobbva.asc-hs.cloud s3fs[6756]: Loaded mime information from /etc/mime.types
Mar 03 08:17:06 amsssobbva.asc-hs.cloud s3fs[6757]: init v1.89(commit:unknown) with OpenSSL

```
### Details about issue
I am trying to move large files (over 80G) to object storeage, but I get I/O errors and the file size in the object storage is always  5368709120.
Tried with version 1.88 and 1.89

mv errors:
mv: preserving times for ‘/mnt/application-backup/xxx/test7.zip’: Operation not permitted
mv: preserving permissions for ‘/mnt/application-backup/xxx/test7.zip’: Operation not permitted
mv: failed to close ‘/mnt/application-backup/xxx/test7.zip’: Input/output error

cp errors:
cp: failed to close ‘/mnt/application-backup/xxx/test6.zip’: Input/output error

**Comment by gaul** [comment]
Can you run s3fs with `-f -o curldbg` which may reveal the cause?  Do you use AWS or some other object store?  If the latter, perhaps it does not support MPU CopyPart?  As a temporary workaround you might try setting `-o max_dirty_data=-1`.

**Comment by erki-karblane** [comment]
Thanks, the -o max_dirty_data=-1 seems to be working.

**Comment by gaul** [comment]
While this workaround may work, you may want to root cause it.  Again, do you use AWS or some other object store?  `-o nocopyapi` may be the more appropriate flag if you have a similar problem when renaming.

**Comment by erki-karblane** [comment]
IBM cloud Object Storage
