### ISSUE TITLE
Mount Root is available?

### ISSUE THREAD

**Issue by fly3366** [s3fs-fuse/s3fs-fuse#1603]
#### Version of s3fs being used (s3fs --version)
_example: 1.89

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.2

#### Kernel information (uname -r)
4.19

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
debian buster

#### s3fs command line used, if applicable
```
s3fs . 
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
curl_util.cpp:url_to_host(349): url is http://xxx.xxx.xxx
```
### Details about issue
I have use `s3fs .` (bucket name set as . , but not a bucket name), Is it mean i can use any bucket under this domain?
eg. /mount/ponit/for/s3fs/bucketA     ->  http://xxx.xxx.xxx/bucketA
     /mount/ponit/for/s3fs/bucketB     ->  http://xxx.xxx.xxx/bucketB?

**Comment by fly3366** [comment]
if not, may change "/:\\;!@#$%^&*?|+=" -> "/:\\;!@#$%^&*?|+=." ?

**Comment by gaul** [comment]
S3 bucket names are generally limited by DNS.  Some extended names are possible if you use `-o use_path_request_style`.  Does this resolve your issue?

**Comment by fly3366** [comment]
Sorry, It's not a problem,
