### ISSUE TITLE
Key/Secret not recognized when colon symbol (`:`) in password (error: s3fs: Not found access key/secret key in passwd file)

### ISSUE THREAD

**Issue by amurchick** [s3fs-fuse/s3fs-fuse#1606]
### Additional Information
Debian 

#### Version of s3fs being used
`1.84`

#### Version of fuse being used
`2.9.9-1+deb10u1`

#### Kernel information
`4.19.0-12-amd64`

#### GNU/Linux Distribution
```
$ cat /etc/debian_version 
10.6
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
```
s3fs: Not found access key/secret key in passwd file.
```
### Details about issue
If `:` (colon) in password - no way to work with this.

For example (not work):
```
login:some_password_with_:_symbol
```
```
bucket:login:some_password_with_:_symbol
```
```
bucket:login:some_password_with_:_symbol
```

**Comment by gaul** [comment]
Does AWS allow `:` in secret keys?  This reference suggests no:

https://summitroute.com/blog/2018/06/20/aws_security_credential_formats/#secret-keys

**Comment by dreyTee** [comment]
in my case a colon presented in access_key_id. 
it's not AWS itself, but AWS compatible cloud.
tried to use quotes and backslash escaping to no avail.

**Comment by gaul** [comment]
Can you use the AWS CLI-style credentials instead?  This looks like:

```
$ cat $HOME/.aws/credentials
[default]
aws_access_key_id = xxxxxxxxxxxxxxxxxxxx
aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by kozo2** [comment]
I also use s3 compatible storage (QNAP QuObjects) with a colon in the key_id.
(QuObjects key_id always have colon.)
I've confirmed that it gives the following error even in AWS CLI-style.
```
~$ s3fs xxxxx ~/s3fstest -o passwd_file=~/.aws/credentials -o dbglevel=info -f -o curldbg
[CRT] s3fs.cpp:set_s3fs_log_level(297): change debug level from [CRT] to [INF]
[INF]     s3fs.cpp:set_mountpoint_attribute(4400): PROC(uid=1000006, gid=1000000) - MountPoint(uid=1000006, gid=1000000, mode=40755)
s3fs: invalid line in passwd file, found a bracket "[" character.
~$ cat .aws/credentials
[default]
aws_access_key_id=xxxxx:xxxxxxxxxxxxxxxxxx
aws_secret_access_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
~$ s3fs --version
Amazon Simple Storage Service File System V1.86 (commit:unknown) with GnuTLS(gcrypt)
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by gaul** [comment]
s3fs automatically reads the `.aws/credentials` file -- you should not also specify `--passwd_file`.

**Comment by kozo2** [comment]
@gaul Thank you for the information.
I removed `--passwd_file` option, I ran s3fs with the following options (using AWS CLI-style credentials) and it mounted the bucket successfully (even if the credentials have colon symbol (:) in key[, not in passwd]).
```
~$ s3fs xxxxx ~/s3fstest -o allow_other,use_path_request_style,url=http://x.x.x.x:xxxx
```
However, in this case `mkdir` did not work as below. I will discuss this in another issue.
```
~$ mkdir -p s3fstest/kozo2/foo
mkdir: cannot create directory ‘s3fstest/kozo2/foo’: Input/output error
```

**Comment by gaul** [comment]
Tracking the new symptom in #1674.

**Comment by simoferr98** [comment]
Hi, I have the same problem.
I am using QNAP QObjects to expose the s3 bucket. I tried to use the credentials as indicated in the issue but it doesn't work. What could I do?
