### ISSUE TITLE
s3fs-fuse intsall in AIX 

### ISSUE THREAD

**Issue by prasad-1729** [s3fs-fuse/s3fs-fuse#1614]
Hi Team,

I need to install **s3fs-fuse** in our AIX server (version 7.2) -64 bit multiprocessor kernel  
can you please help to share commands, how to install it?

 Thanks!

**Comment by gaul** [comment]
Does AIX support FUSE?

**Comment by gaul** [comment]
Please reopen if and when AIX adds FUSE support.
