### ISSUE TITLE
Frankfurt not working

### ISSUE THREAD

**Issue by saschaarthur** [s3fs-fuse/s3fs-fuse#162]
Hey,

Could it be that in current release 1.78 S3-Frankfurt does not work?
It seems its unable to connect the socket for it

Greetings

**Comment by kahing** [comment]
frankfurt requires v4 authentication scheme which is only implemented in master and not yet released, I believe

**Comment by saschaarthur** [comment]
Well how can i pull th

**Comment by ggtakec** [comment]
No problem, so close this issue.
Regards,

**Comment by vladimirmartsul** [comment]
Hi!

Are there some ETA for Frankfurt in stable release? This location is more preferred than Ireland for Central Europe servers.

**Comment by ggtakec** [comment]
@vladimirmartsul 
s3.eu-central-1.amazonaws.com
s3-eu-central-1.amazonaws.com
Could you use these end poit?
