### ISSUE TITLE
Size of large file becomes zero after long write 

### ISSUE THREAD

**Issue by valdisvi** [s3fs-fuse/s3fs-fuse#1625]
### Additional Information
After long write of file (e.g. using [dar disk achiver](http://dar.linux.free.fr/)) size of file becomes zero. Please look at [recorded video here](https://github.com/Edrusb/DAR/issues/25#issuecomment-780754553).

#### Version of s3fs being used (s3fs --version)
[Standard package of Ubuntu 20.04](https://packages.ubuntu.com/focal/dar)
Amazon Simple Storage Service File System V1.86 (commit:unknown) with GnuTLS(gcrypt)

#### Version of fuse being used (pkg-config --modversion fuse)
2.9.9

#### Kernel information (uname -a)

Linux tools 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:04:23 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
Ubuntu 20.04.2 LTS

#### s3fs command line used, if applicable
```
dar -Q -c /home/s3/tools/valdis.dar -w -asecu -aSI -s 2G -D -R /home/valdis
```
#### /etc/fstab entry, if applicable
```
s3fs#bucket:/ /home/s3 fuse _netdev,rw,nosuid,nodev,uid=root,gid=root      0 0
```

**Comment by gaul** [comment]
s3fs 1.86 is several years old -- try with the latest 1.89 which fixes several data corruption bugs.  If this still does not work, please correlate your application behavior with the s3fs debug logs via the `-f -d` flags.  You should be able to observe individual system calls this way.  Also, video is not a good way to report bugs since it is not searchable.

**Comment by valdisvi** [comment]
Thanks! I couldn't install [newer prebuilt](https://launchpad.net/ubuntu/+source/s3fs-fuse) version due too many dependencies, but compilation and installation of [version 1.89](https://github.com/s3fs-fuse/s3fs-fuse/releases/tag/v1.89) from [source code](https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes) solved this issue.
