### ISSUE TITLE
Increase test robustness by adding LC_ALL=C

### ISSUE THREAD

**Issue by CarstenGrohmann** [s3fs-fuse/s3fs-fuse#1658]
Some test cases check the output of commands for English expressions. This may cause the test suite to fail for users with non-English locale settings.

I suggest to add `LC_ALL=C` at the beginning of `test_utils.sh` to address this problem.

I would open a PR, if you agree with this solution.

**Comment by gaul** [comment]
This makes sense.  Over the longer term hopefully we can move to finer-grainer errno handling, either via `pjdfstests.c` or Python unit tests.
