### ISSUE TITLE
Investigate GCS S3 multipart upload support

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#1661]
This is in public preview:

https://cloud.google.com/storage/docs/xml-api/post-object-multipart

This would vastly improve metadata mutations, e.g., `chmod`.

**Comment by ggtakec** [comment]
@gaul Thank you for the useful information.
Is there anything we should add as a test?

**Comment by gaul** [comment]
It seems like this is in a preview stage since my account does not have access to it.

**Comment by ggtakec** [comment]
We will test it when we are ready to access it.

**Comment by gaul** [comment]
I updated the wiki for the future s3fs 1.90:

https://github.com/s3fs-fuse/s3fs-fuse/wiki/Non-Amazon-S3#google-cloud-storage

I will update it again if GCS fixes their quirk.

**Comment by ggtakec** [comment]
@gaul Thanks for updating docs.
