### ISSUE TITLE
Look at GCS-specific headers

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#1662]
s3fs should have a GCS mode which uses headers like `x-goog-storage-class` instead of `x-amz-storage-class`:

https://cloud.google.com/storage/docs/xml-api/reference-headers#xgoogstorageclass

Related to #1613.

**Comment by ggtakec** [comment]
@gaul Should we switch to use `x-goog-meta-*` and `x-amz-meta*` properly?

**Comment by ggtakec** [comment]
Both look good. However, considering that there may be such differences in other parts in the future, I think the `--gcs` option seems to be better.

**Comment by gaul** [comment]
This bug may be invalid.  GCS supports `x-amz-storage-class` and it doesn't appear that the other headers provide any value, except for conditional PUT.  I think there are some other ETag sanity checks that we should do before looking at vendor-specific conditional PUT though.
