### ISSUE TITLE
./configure not working on manual install in Ubuntu 18.04

### ISSUE THREAD

**Issue by osprey3883** [s3fs-fuse/s3fs-fuse#1667]
#### Version of s3fs being used (s3fs --version)
V1.82

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
5.4.0

#### Kernel information (uname -r)

5.4.0-1045-aws

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
VERSION="18.04.5 LTS (Bionic Beaver)"

#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
### Details about issue

trying to follow the install instructions but they are not working as expected-
ubuntu@ip-10-20-15-217:~/s3fs-fuse-1.88$ sudo ./configure
sudo: ./configure: command not found
ubuntu@ip-10-20-15-217:~/s3fs-fuse-1.88$ ./autogen.sh
--- Make commit hash file -------
--- Finished commit hash file ---
--- Start autotools -------------
./autogen.sh: 38: ./autogen.sh: aclocal: not found
--- Finished autotools ----------
ubuntu@ip-10-20-15-217:~/s3fs-fuse-1.88$ ./configure
-bash: ./configure: No such file or directory

**Comment by gaul** [comment]
Did you follow the instructions at:

https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes#debian--ubuntu

Try running the `apt-get` command to get the required dependencies.

**Comment by osprey3883** [comment]
That did it, thanks!
