### ISSUE TITLE
CentOS7 tests may give std::bad_alloc

### ISSUE THREAD

**Issue by ggtakec** [s3fs-fuse/s3fs-fuse#1677]
### Related Issue (PR)
#1672 , #1673

### Detail
In the `test_concurrent_directory_updates` test of CentOS7, it seems that the following error is occasionally displayed.
```
terminate called after throwing an instance of 'std::bad_alloc'
   what():std::bad_alloc
```
There is a possibility that memory fragmentation has occurred, or that a large memory area is reserved.
However, it is possible that the process that caused this is not just s3fs, but other programs running at the same time.

**Comment by gaul** [comment]
I think this may be due to memory corruption if s3fs clobbers some of the malloc metadata.

**Comment by ggtakec** [comment]
It may be the cause you pointed out.
I think that it will take some time to investigate the cause.
(In the build after merging just before, the CentOS 7 test passed without any problems.)

**Comment by ggtakec** [comment]
@gaul Thanks.
