### ISSUE TITLE
trying to mount s3 bucket - fuse: device not found, try 'modprobe fuse' first 

### ISSUE THREAD

**Issue by fabianober** [s3fs-fuse/s3fs-fuse#1686]
I installed fuse on my VPS running CentOS but mounting my s3-bucket doesn't work. 
Neither with a s3fs command nor with moun -a in fstab...
But I am quite sure, that I installed fuse and all its dependencies correctly and I am not using Docker on the VPS.

My VPS is hosted by hostinger and I asked them about fuse and they said that it is supported on their VPSs.

### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)

Amazon Simple Storage Service File System V1.89 (commit:unknown) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
**1.** 
2.9.2

**2.** 
Das Paket fuse, ist nicht installiert
Das Paket dpkg ist nicht installiert
Name        : fuse
Version     : 2.9.2
Release     : 11.el7
Architecture: x86_64
Install Date: Fr 18 Jun 2021 16:00:38 UTC
Group       : System Environment/Base
Size        : 223297
License     : GPL+
Signature   : RSA/SHA256, Mo 12 Nov 2018 14:25:34 UTC, Key ID 24c6a8a7f4a80eb5
Source RPM  : fuse-2.9.2-11.el7.src.rpm
Build Date  : Di 30 Okt 2018 21:32:35 UTC
Build Host  : x86-01.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Vendor      : CentOS
URL         : https://github.com/libfuse/libfuse
Summary     : File System in Userspace (FUSE) utilities
Description :
With FUSE it is possible to implement a fully functional filesystem in a
userspace program. This package contains the FUSE userspace tools to
mount a FUSE filesystem.
normal        /etc/fuse.conf
normal        /usr/bin/fusermount
normal        /usr/bin/ulockmgr_server
normal        /usr/sbin/mount.fuse
normal        /usr/share/doc/fuse-2.9.2
normal        /usr/share/doc/fuse-2.9.2/AUTHORS
normal        /usr/share/doc/fuse-2.9.2/COPYING
normal        /usr/share/doc/fuse-2.9.2/ChangeLog
normal        /usr/share/doc/fuse-2.9.2/FAQ
normal        /usr/share/doc/fuse-2.9.2/Filesystems
normal        /usr/share/doc/fuse-2.9.2/NEWS
normal        /usr/share/doc/fuse-2.9.2/README
normal        /usr/share/doc/fuse-2.9.2/README.NFS
normal        /usr/share/man/man1/fusermount.1.gz
normal        /usr/share/man/man1/ulockmgr_server.1.gz
normal        /usr/share/man/man8/mount.fuse.8.gz

#### Kernel information (uname -r)
3.10.0

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

#### /etc/fstab entry, if applicable
```
# /cyberpanel.swap swap swap sw 0 0
s3fs#ober-cdn /mnt/s3 fuse _netdev,rw,nosuid,nodev,allow_other,nonempty 0 0
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
2021-06-18T16:21:37.574Z [CRT] s3fs_logger.cpp:LowSetLogLevel(219): change debug level from [CRT] to [INF] 
2021-06-18T16:21:37.574Z [INF]     s3fs.cpp:set_mountpoint_attribute(4020): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
2021-06-18T16:21:37.576Z [INF] curl.cpp:InitMimeType(436): Loaded mime information from /etc/mime.types
2021-06-18T16:21:37.577Z [INF] fdcache_stat.cpp:CheckCacheFileStatTopDir(79): The path to cache top dir is empty, thus not need to check permission.
fuse: device not found, try 'modprobe fuse' first
```

Thanks for your support!

**Comment by CarstenGrohmann** [comment]
Please check if the fuse kernel module is loaded. 

I use a similar OS and there the check and the result looks like this:
```
# lsmod | grep fuse
fuse                   91926  2

# ls -l /dev/fus*
crw-rw-rw- 1 root root 10, 229 Jun 15 08:20 /dev/fuse
```

If `lsmod `doesn't return anything, try:
```
# modprobe fuse
```

**Comment by fabianober** [comment]
Yes, it seems like the fuse kernel is not installed correctly but I used every command I can found in order to install fuse?


`lsmod | grep fuse` doesn't return anything...

`ls -l /dev/fus*` returns `crw-rw-rw- 1 root root 10, 229 18. Jun 16:01 /dev/fuse`

And `modprobe fuse` returns nothing as well...


Only `lsmod` returns the following list in which I can't find fuse:

`Module                  Size  Used by
xt_time                 4242  -2 
raw_diag                4242  -2 
netlink_diag            4242  -2 
af_packet_diag          4242  -2 
unix_diag               4242  -2 
nf_conntrack_ftp        4242  -2 
xt_CT                   4242  -2 
nft_counter             4242  -2 
nf_tables_bridge        4242  -2 
nf_tables               4242  -2 nf_tables_bridge,nft_counter
sch_sfq                 4242  -2 
cls_u32                 4242  -2 
sch_htb                 4242  -2 
ip_set_hash_ip          4242  -2 
xt_NFLOG                4242  -2 
xt_u32                  4242  -2 
xt_length               4242  -2 
xt_connbytes            4242  -2 
xt_set                  4242  -2 
xt_mark                 4242  -2 
xt_recent               4242  -2 
xt_state                4242  -2 
xt_REDIRECT             4242  -2 
nf_nat_redirect         4242  -2 xt_REDIRECT
xt_owner                4242  -2 
ip6t_rpfilter           4242  -2 
ebtable_nat             4242  -2 
ebtable_broute          4242  -2 
ip6table_nat            4242  -2 
nf_nat_ipv6             4242  -2 ip6table_nat
ip6table_mangle         4242  -2 
ip6table_security       4242  -2 
ip6table_raw            4242  -2 
iptable_raw             4242  -2 
iptable_security        4242  -2 
iptable_mangle          4242  -2 
nf_conntrack_netlink     4242  -2 
xt_nat                  4242  -2 
ipt_MASQUERADE          4242  -2 
nf_nat_masquerade_ipv4     4242  -2 ipt_MASQUERADE
iptable_nat             4242  -2 
nf_nat_ipv4             4242  -2 iptable_nat
ip6t_REJECT             4242  -2 
nf_reject_ipv6          4242  -2 ip6t_REJECT
nf_log_ipv6             4242  -2 
xt_hl                   4242  -2 
ip6t_rt                 4242  -2 
nf_conntrack_ipv6       4242  -2 
nf_defrag_ipv6          4242  -2 nf_conntrack_ipv6
ipt_REJECT              4242  -2 
nf_reject_ipv4          4242  -2 ipt_REJECT
xt_comment              4242  -2 
nf_log_ipv4             4242  -2 
nf_log_common           4242  -2 nf_log_ipv4,nf_log_ipv6
xt_LOG                  4242  -2 
xt_multiport            4242  -2 
xt_limit                4242  -2 
xt_addrtype             4242  -2 
xt_conntrack            4242  -2 
binfmt_misc             4242  -2 
tcp_diag                4242  -2 
udp_diag                4242  -2 
inet_diag               4242  -2 tcp_diag,raw_diag,udp_diag
ip_set_hash_net         4242  -2 
ip_set                  4242  -2 ip_set_hash_net,ip_set_hash_ip,xt_set
8021q                   4242  -2 
garp                    4242  -2 8021q
mrp                     4242  -2 8021q
devlink                 4242  -2 
ip6table_filter         4242  -2 
ip6_tables              4242  -2 ip6table_filter,ip6table_mangle,ip6table_security,ip6table_nat,ip6table_raw
iptable_filter          4242  -2 
nfnetlink_log           4242  -2 xt_NFLOG
nfnetlink               4242  -2 nf_tables,nfnetlink_log,ip_set,nf_conntrack_netlink
rpcsec_gss_krb5         4242  -2 
nfsv4                   4242  -2 
dns_resolver            4242  -2 nfsv4
nfs                     4242  -2 nfsv4
fscache                 4242  -2 nfs,nfsv4
iTCO_wdt                4242  -2 
iTCO_vendor_support     4242  -2 iTCO_wdt
ebtable_filter          4242  -2 
ebt_among               4242  -2 
ebtables                4242  -2 ebtable_broute,ebtable_nat,ebtable_filter
vfat                    4242  -2 
fat                     4242  -2 vfat
skx_edac                4242  -2 
intel_powerclamp        4242  -2 
coretemp                4242  -2 
intel_rapl              4242  -2 
iosf_mbi                4242  -2 intel_rapl
kvm_intel               4242  -2 
kvm                     4242  -2 kvm_intel
ast                     4242  -2 
i2c_algo_bit            4242  -2 ast
ttm                     4242  -2 ast
irqbypass               4242  -2 kvm
drm_kms_helper          4242  -2 ast
crc32_pclmul            4242  -2 
ghash_clmulni_intel     4242  -2 
aesni_intel             4242  -2 
syscopyarea             4242  -2 drm_kms_helper
sysfillrect             4242  -2 drm_kms_helper
lrw                     4242  -2 aesni_intel
sysimgblt               4242  -2 drm_kms_helper
gf128mul                4242  -2 lrw
fb_sys_fops             4242  -2 drm_kms_helper
glue_helper             4242  -2 aesni_intel
ablk_helper             4242  -2 aesni_intel
cryptd                  4242  -2 ghash_clmulni_intel,aesni_intel,ablk_helper
drm                     4242  -2 ast,ttm,drm_kms_helper
pcspkr                  4242  -2 
sg                      4242  -2 
joydev                  4242  -2 
drm_panel_orientation_quirks     4242  -2 drm
mei_me                  4242  -2 
mei                     4242  -2 mei_me
lpc_ich                 4242  -2 
i2c_i801                4242  -2 
wmi                     4242  -2 
ipmi_si                 4242  -2 
ipmi_devintf            4242  -2 
ipmi_msghandler         4242  -2 ipmi_devintf,ipmi_si
acpi_power_meter        4242  -2 
acpi_pad                4242  -2 
tun                     4242  -2 
nfsd                    4242  -2 
auth_rpcgss             4242  -2 nfsd,rpcsec_gss_krb5
nfs_acl                 4242  -2 nfsd
lockd                   4242  -2 nfs,nfsd
grace                   4242  -2 nfsd,lockd
sunrpc                  4242  -2 nfs,nfsd,rpcsec_gss_krb5,auth_rpcgss,lockd,nfsv4,nfs_acl
br_netfilter            4242  -2 
veth                    4242  -2 
ip_vs_ftp               4242  -2 
overlay                 4242  -2 
ip_vs                   4242  -2 ip_vs_ftp
ip6_vzprivnet           4242  -2 
ip6_vznetstat           4242  -2 
nf_nat                  4242  -2 ip_vs_ftp,nf_nat_redirect,nf_nat_ipv4,nf_nat_ipv6,xt_nat,nf_nat_masquerade_ipv4
ip_vznetstat            4242  -2 
ip_vzprivnet            4242  -2 ip6_vzprivnet
vziolimit               4242  -2 
nf_conntrack_ipv4       4242  -2 
vzevent                 4242  -2 
nf_defrag_ipv4          4242  -2 nf_conntrack_ipv4
vzlist                  4242  -2 
vzstat                  4242  -2 
vznetstat               4242  -2 tun,ip_vznetstat,ip6_vznetstat
vznetdev                4242  -2 
vzmon                   4242  -2 vznetdev
nf_conntrack            4242  -2 ip_vs,xt_CT,nf_nat,xt_connbytes,xt_state,nf_nat_ipv4,nf_nat_ipv6,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_netlink,nf_conntrack_ftp,nf_conntrack_ipv4,nf_conntrack_ipv6
vzdev                   4242  -2 vzmon,vziolimit,vznetdev,vzlist,vznetstat
bridge                  4242  -2 br_netfilter,ebtable_broute
stp                     4242  -2 garp,bridge
libcrc32c               4242  -2 ip_vs,nf_nat,nf_conntrack
llc                     4242  -2 stp,garp,bridge
ip_tables               4242  -2 iptable_security,iptable_filter,iptable_mangle,iptable_nat,iptable_raw
ext4                    4242  -2 
mbcache                 4242  -2 ext4
jbd2                    4242  -2 ext4
sd_mod                  4242  -2 
crc_t10dif              4242  -2 sd_mod
crct10dif_generic       4242  -2 
ixgbe                   4242  -2 
crct10dif_pclmul        4242  -2 
ahci                    4242  -2 
crct10dif_common        4242  -2 crct10dif_pclmul,crct10dif_generic,crc_t10dif
crc32c_intel            4242  -2 
libahci                 4242  -2 ahci
megaraid_sas            4242  -2 
libata                  4242  -2 ahci,libahci
mdio                    4242  -2 ixgbe
ptp                     4242  -2 ixgbe
pps_core                4242  -2 ptp
dca                     4242  -2 ixgbe
nfit                    4242  -2 skx_edac
libnvdimm               4242  -2 nfit
pio_kaio                4242  -2 
pio_nfs                 4242  -2 
pio_direct              4242  -2 
pfmt_raw                4242  -2 
pfmt_ploop1             4242  -2 
ploop                   4242  -2 pfmt_raw,pfmt_ploop1,pio_kaio,pio_direct`

**Comment by CarstenGrohmann** [comment]
Maybe it is a customised (self-compiled) kernel with fuse built-in instead of a custom kernel module.

One way or another fuse should be listed in `/proc/filesystems` and in `/sys

```
# grep fuse /proc/filesystems
        fuseblk
nodev   fuse
nodev   fusectl
```

```
# find /sys/ 2>/dev/null | grep fuse
/sys/fs/fuse
/sys/fs/fuse/connections
/sys/devices/virtual/misc/fuse
[...]
/sys/module/fuse
/sys/module/fuse/srcversion
/sys/module/fuse/notes
[...]
```

Please check additionally:
```
# dmesg | grep -i fuse
[380963.906837] fuse init (API version 7.22)

# grep -i fuse /var/log/messages

 # systemctl | grep -i fuse
sys-module-fuse.device                                                                           loaded active plugged   /sys/module/fuse

# systemctl status sys-module-fuse.device
â sys-module-fuse.device - /sys/module/fuse
   Loaded: loaded
   Active: active (plugged) since Tue 2021-06-15 08:20:44 CEST; 4 days ago
   Device: /sys/module/fuse
```

**Comment by fabianober** [comment]
`# grep fuse /proc/filesystems` returns nothing...

Also `find /sys/ 2>/dev/null | grep fuse` returns nothing.

`dmesg | grep -i fuse` returns nothing as well...

 `grep -i fuse /var/log/messages` returns the following log messages:

```
Jun 18 09:48:07 fabian-ober yum[1724]: Installed: fuse-libs-2.9.2-11.el7.x86_64
Jun 18 09:48:07 fabian-ober yum[1724]: Installed: fuse-devel-2.9.2-11.el7.x86_64
Jun 18 09:48:07 fabian-ober yum[1724]: Installed: fuse-2.9.2-11.el7.x86_64
Jun 18 09:54:18 fabian-ober yum[4012]: Erased: fuse-2.9.2-11.el7.x86_64
Jun 18 10:02:23 fabian-ober mount: mount: unknown filesystem type 'fuse'

```

`systemctl | grep -i fuse` returns nothing.

And `systemctl status sys-module-fuse.device` returns the following message:

```
● sys-module-fuse.device
   Loaded: loaded
   Active: inactive (dead)

```

Could it bee, that fuse is loaded but not activated or dead cause in the `systemctl status` we see "loaded" but "inactive"?

**Comment by CarstenGrohmann** [comment]
> ```
> ● sys-module-fuse.device
>    Loaded: loaded
>    Active: inactive (dead)
> ```
> 
> Could it bee, that fuse is loaded but not activated or dead cause in the `systemctl status` we see "loaded" but "inactive"?

I am not sure about `Loaded: loaded` - it probably just says that systemd has loaded the unit definition.


Fuse is inactive on your system. Otherwise it would be listed in `/proc/filesystems`.

A final try: mount the control filesystem manually and check if this helps:
```
# mount -t fusectl none /sys/fs/fuse/connections
```
If this step fails, then you can only ask your hosting provider again for support and share the output of `grep fuse /proc/filesystems` and `dmesg | grep -i fuse` with it.

**Comment by fabianober** [comment]
`# mount -t fusectl none /sys/fs/fuse/connections` returns `mount: mount point /sys/fs/fuse/connections does not exist`

Is `/sys/fs/fuse/connections` the correct path on centos?

Otherwise I really have to go back to hostinger and ask for support there...

**Comment by CarstenGrohmann** [comment]
I don't see this mount on my system, but the current fuse documentation at kernel.org contains it.

May you ask hostinger and share the outcome here, please.

**Comment by fabianober** [comment]
I'll do so...

**Comment by fabianober** [comment]
So I asked my hostinger and it really seems, that their servers don't support fuse.

So the solution would be changing the hosting provider...

**Comment by cryponder** [comment]
i am facing same problem. someone have solution for it ?

**Comment by amamrenko** [comment]
the same here

**Comment by glad2os** [comment]
still appears

```
Writing manifest to image destination

Error: mounting new container: mounting build container "4eeae3ce21065d2aced4170a0a3bc460b2c5c70c5077a69285a8aaa48fb686ba": creating overlay mount to /var/lib/containers/storage/overlay/8eb3ced6a3a24445a6a07d4c51415ed3e64cb6632ad52896f84a8e2212265d44/merged, mount_data="lowerdir=/var/lib/containers/storage/overlay/l/ATJZ4DKGWULAGQR6JUQFLLREBG:/var/lib/containers/storage/overlay/l/JJL4A6XJTUBUQ3G4UNIJ4XJE2M:/var/lib/containers/storage/overlay/l/G5L47OZSMRZH4EYX5IM5X67WCN:/var/lib/containers/storage/overlay/l/4PUEB4JXF4F4OULP2J5NT5TXVW,upperdir=/var/lib/containers/storage/overlay/8eb3ced6a3a24445a6a07d4c51415ed3e64cb6632ad52896f84a8e2212265d44/diff,workdir=/var/lib/containers/storage/overlay/8eb3ced6a3a24445a6a07d4c51415ed3e64cb6632ad52896f84a8e2212265d44/work,nodev,fsync=0,volatile": using mount program /usr/bin/fuse-overlayfs: unknown argument ignored: lazytime

fuse: device not found, try 'modprobe fuse' first

fuse-overlayfs: cannot mount: No such file or directory

: exit status 1
```
