### ISSUE TITLE
Crash, transport not connected

### ISSUE THREAD

**Issue by davidvoisonics** [s3fs-fuse/s3fs-fuse#1706]
We experienced a crash with s3fs. Version information is:
s3fs: 1.82-1
fuse: 2.9.7-1ubuntu1
kernel: 4.15.0-142-generic
Ubuntu: 18.04.5

From apport.log:
ERROR: apport (pid 10303) Mon Jun 28 06:06:39 2021: executable: /usr/bin/s3fs (command line "s3fs mcloud-4 /mnt/amazons3/mcloud-4 -o rw,noatime,allow_other,uid=115,gid=118,use_cache=/tmp,default_acl=public-read,dev,suid")
ERROR: apport (pid 10303) Mon Jun 28 06:09:02 2021: wrote report /var/crash/_usr_bin_s3fs.0.crash

There were no related messages in /var/log/syslog. I will attach the apport report. Thanks.

**Comment by davidvoisonics** [comment]
The crash file can be downloaded from here:

https://download.voisonics.com/s3fs/usr_bin_s3fs.0.crash.gz

If any further information is needed please let me know.

**Comment by gaul** [comment]
1.82 is several years old -- please retest with the latest 1.89.

**Comment by davidvoisonics** [comment]
Thanks, we'll have to compile from source or give Ubuntu a kick to update their package.

**Comment by gaul** [comment]
Compiling from source is your fastest path.  Ubuntu regularly updates s3fs in new releases but does not upgrade them in the LTS releases:

https://bugs.launchpad.net/ubuntu/+source/s3fs-fuse/+bug/1828849

You might ask the Ubuntu maintainers to include s3fs in the backports mechanism:

https://help.ubuntu.com/community/UbuntuBackports

**Comment by gaul** [comment]
Please reopen if symptoms persist with 1.89.
