### ISSUE TITLE
AWSACCESSKEYID vs AWS_ACCESS_KEY_ID

### ISSUE THREAD

**Issue by CarstenGrohmann** [s3fs-fuse/s3fs-fuse#1708]
The environment variables for an access key, secret key, and session token differ between s3fs and aws cli. 
In s3fs, these variables are in uppercase but without underscore, and aws cli uses the same naming but with underscore. Is this intentional?

https://github.com/s3fs-fuse/s3fs-fuse/blob/487df2700842c0a74e6314b898d726ff57a55589/src/s3fs.cpp#L3992-L3994
AWS reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-set

If this is not intended, then I can contribute a PR.

**Comment by gaul** [comment]
s3fs (2007) predates the AWS CLI (2012) so it was not our intention but their choice (although I prefer their choice).  AWS CLI is likely more popular and thus s3fs should align with their choices to reduce user friction.  s3fs should accept both variants so it retains backwards compatibility for our users.  We can change the s3fs documentation to only mention the AWS style though.

**Comment by CarstenGrohmann** [comment]
ok, I'll create a PR
