### ISSUE TITLE
s3fs not using credential_process in ~/.aws/config

### ISSUE THREAD

**Issue by akrish2011** [s3fs-fuse/s3fs-fuse#1724]
s3fs is not able to use credential_process in ~/.aws/config, I am not finding any option to force use S3FS to use ~/.aws/config like aws cli to generate STS tokens using credential_process defined in the config file. This will help to solve token expiry problem in S3FS as well as solve the problem of remounting each time after token expiry

**Comment by gaul** [comment]
Duplicate of #1122.
