### ISSUE TITLE
Get this working on OSX

### ISSUE THREAD

**Issue by mooredan** [s3fs-fuse/s3fs-fuse#174]
Hi Dan Moore here. I've been away for a while and I'm happy to see that the project is still under development.   This was an issue from way back and wasn't ever resolved.  I don't have a Linux-based desktop/laptops any more and always had a mind to get this working under OSX.

With MacPorts and two small code changes, s3fs is working on my Yosemite system.  Who/what is the gatekeeper these days?  I would like to submit the changes.

**Comment by andrewgaul** [comment]
@mooredan Please submit pull requests for any changes.  If you have expertise with Travis and Mac OS X it would be good to add that to our test matrix.

**Comment by ggtakec** [comment]
@mooredan Please send pull request.
And if I not mistaken, you are the original owner of s3fs(on gc).
Thanks in advance for your assistance.

**Comment by mooredan** [comment]
I am that person. 

I have been playing with s3fs on my macbookpro, it appears to be working for what I want it to do: backups to S3. rsync worked fine. I'll put in a pull request shortly and contribute to the HOWTO.

make check doesn't work due to differences in OSX's netstat ~ I'll investigate that further

**Comment by andrewgaul** [comment]
Travis offers Mac OS X support:

http://docs.travis-ci.com/user/osx-ci-environment/

But they are currently not accepting multi-os build requests:

http://docs.travis-ci.com/user/multi-os/

This is likely due to capacity problems:

http://blog.travis-ci.com/2015-04-20-state-of-the-mac-infrastructure-on-travis-ci/

We could still test this in a one-off fashion by creating a `macosx` branch.  @mooredan Could you look into this?

**Comment by ggtakec** [comment]
We can branch maxos, and I think it is probably not differ from master branch.
@mooredan could you help us?

**Comment by andrewgaul** [comment]
@ggtakec To be clear, I would like the source code to remain the same between `master` and `macosx` branches.  The latter would just have a different Travis configuration until they can accommodate multi-os builds again.  This would allow people like me to run Mac OS tests without access to Apple software.

**Comment by ggtakec** [comment]
@andrewgaul I created new branch  macosx from master. :-)
