### ISSUE TITLE
Problem mounting s3 using /etc/fstab

### ISSUE THREAD

**Issue by korulis** [s3fs-fuse/s3fs-fuse#1744]
### Additional Information
I am trying to mount using this content in my `/etc/fstab`

#### Version of s3fs being used (s3fs --version)
```
Amazon Simple Storage Service File System V1.82(commit:unknown) with GnuTLS(gcrypt)
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
```
Package: fuse
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 104
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.9.7-1ubuntu1
Depends: libc6 (>= 2.14), libfuse2 (= 2.9.7-1ubuntu1), adduser, mount (>= 2.19.1), sed (>= 4)
Conffiles:
 /etc/fuse.conf 298587592c8444196833f317def414f2
Description: Filesystem in Userspace
 Filesystem in Userspace (FUSE) is a simple interface for userspace programs to
 export a virtual filesystem to the Linux kernel. It also aims to provide a
 secure method for non privileged users to create and mount their own filesystem
 implementations.
Homepage: https://github.com/libfuse/libfuse/wiki
Original-Maintainer: Laszlo Boszormenyi (GCS) <gcs@debian.org>
```

#### Kernel information (uname -r)
```
5.4.0-1055-aws
```

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
```
LABEL=cloudimg-rootfs   /        ext4   defaults,discard        0 1
s3fs#my-bucket /home/karolis/test-s3-folder fuse _netdev,allow_other,url=https://s3-eu-west-1.amazonaws.com 0 0
```

#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
sudo grep s3fs /var/log/syslog:
```
Aug 18 17:58:46 ip-172-31-45-12 s3fs[842]: s3fs.cpp:s3fs_init(3378): init v1.82(commit:unknown) with GnuTLS(gcrypt)
Aug 18 17:58:46 ip-172-31-45-12 s3fs[842]: Libgcrypt warning: missing initialization - please fix the application
```

journalctl | grep s3fs - no recent messages.

### Details about issue

I am aware of this ticket. https://github.com/s3fs-fuse/s3fs-fuse/issues/1018
but when I 
`sudo apt update`
and
`sudo apt upgrade`
or just 
`sudo apt install s3fs --reinstall`
, the s3fs package just stays at the same version `s3fs (1.82-1)`
Indeed if I can read this correctly 1.82-1 is the latest version for s3fs for ubuntu 18.04 https://packages.ubuntu.com/bionic/s3fs.
So how do I install a higher version, like 1.85 or 1.89?

**Comment by gaul** [comment]
Sorry we cannot support old versions.  You can try [compiling s3fs from source](https://github.com/s3fs-fuse/s3fs-fuse/blob/master/COMPILATION.md) or upgrading your Ubuntu version.

Unfortunately Ubuntu does not backport s3fs versions to older LTS distributions.  You can try filing a bug on [Launchpad](https://bugs.launchpad.net/) and ask for an [SRU](https://wiki.ubuntu.com/StableReleaseUpdates).

**Comment by korulis** [comment]
Hi @gaul, 
thank you for your prompt answer.
What other info could I provide you?
Do I understand correctly, your suggested solution for me is to upgrade my ubuntu VM from 18.04 to 20.04?
Are there any other paths I can take in order to facilitate consistent continuous sync of files between my VM folder and my S3 bucket?

**Comment by korulis** [comment]
I think I am going to install docker,
use my Ubuntu 18 as volume for an Ubuntu 20 container 
and setup fstab inside that Ubuntu 20 container.

**Comment by korulis** [comment]
Apparently the issue was that s3 bucket was somehow misconfigured. I created a new s3 bucket and the sync with fstab config worked like a charm.

BTW. The idea with docker did not work. All the ubuntu docker images I could find were missing valid fstab configuration.. something about virtual devices, I guess?
