### ISSUE TITLE
live video stream recording not working with s3fs-fuse

### ISSUE THREAD

**Issue by dhanababum** [s3fs-fuse/s3fs-fuse#175]
we are working on live video stream recording with kurento. kurento is a media server for recording videos, but unfortunatly kurento only supports file system.So we moved to s3fs. we are successfully mounting s3 buckets into my local system. I have copied some video files to mounting folder and it is succefully uploading. But whenever I am going with live recording I am getting Permission Denied from  kurento server and I didn't find s3fs-fuse log, where it is located ?. Can you tell me what is the problem. I did most google search nothing found. 

I am using Ubuntu-14.04 LTS.

Regards,
Dhana

**Comment by andrewgaul** [comment]
@dhanababum Can you try running s3fs with `-d -f` options?

**Comment by dhanababum** [comment]
Thanks for reply I have solved my problem using "allow_other" option.
