### ISSUE TITLE
s3fs crashes with segfault

### ISSUE THREAD

**Issue by AGirin** [s3fs-fuse/s3fs-fuse#18]
Version: 1.76

We have a script that parses some files and writes output to s3. s3fs-fuse constantly crash and we get Transport is not connected error. 

The only log message in the messages log is:
kernel: s3fs[28576]: segfault at 0 ip 0000000000423679 sp 00007f3d87569870 error 4 in s3fs[400000+51000]

We tried running with s3fs -f and... it does not crash at all. So we cannot get the real output beside that message in the messages log file. 

Not sure how to go about it. I think we can get dump file if this will help.

Thanks!

Andrew

**Comment by jiazhiguang** [comment]
I occurred this problem too, and I used the master version.
