### ISSUE TITLE
s3fs-fuse for machine learning training

### ISSUE THREAD

**Issue by Stevenyu1982** [s3fs-fuse/s3fs-fuse#1805]
How does s3fs-fuse handle loading the big files. about 300GB file. If we only need part of the data from the 300GB file, does any one know how does s3fs-fuse handle it. 

Let's say I have a 300Gb file , but I only need 2Gb content from this big file. Will s3fs download the whole file in order to get that 2Gb content. if not, how does it work?

**Comment by gaul** [comment]
s3fs does not download the entire object to read part of the file.  Instead it issues (5) 10 MB parallel HTTP GET range requests at a given offset.  It caches this data to satisfy future read requests.  For your example, if the 2 GB is contiguous it will only download 2 GB.  But if the 2 GB are scattered in small chunks throughout the object then s3fs will request a lot more data.

**Comment by Stevenyu1982** [comment]
@gaul Thanks so much for the explanation
