### ISSUE TITLE
Not work --no-verify-ssl option for aws cli on some Runner

### ISSUE THREAD

**Issue by ggtakec** [s3fs-fuse/s3fs-fuse#1812]
### Additional Information
In some GithubActions Runners(`ubuntu 18.04`, `debian buster`, `opensuse/leap 15`), the aws command call is in error.

The error is:
```
SSL validation failed for https://127.0.0.1:8080/s3fs-integration-test/testrun-30317/test-s3fs-ALT.txt [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
```

The aws command is called with `--no-verify-ssl` but receives `CERTIFICATE_VERIFY_FAILED`.

I've tried some workarounds, but I still can't solve them, so I'll report them as Issue.
- Specify `--ca-bundle` option
- Specify `AWS_CA_BUNDLE` environment
- Upgrade `certifi` pip pacakge
- Reinstall `ca-certificates` and execute `update-ca-certificates`
- etc

I've tried the above, but it still doesn't work.
I hope someone knew something ...

**Comment by gaul** [comment]
Note that this only happens with the AWS CLI on older distros.
