### ISSUE TITLE
Question - Is it possible to use s3fs with DreamHost?

### ISSUE THREAD

**Issue by yuriw** [s3fs-fuse/s3fs-fuse#1814]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
_example: 1.00_
s3fs --version
Amazon Simple Storage Service File System V1.86 (commit:unknown) with GnuTLS(gcrypt)
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_example: 2.9.4_
dpkg -s fuse
Package: fuse
Status: install ok installed
Priority: standard
Section: utils
Installed-Size: 113
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.9.9-3
Depends: libc6 (>= 2.28), libfuse2 (= 2.9.9-3), adduser, mount (>= 2.19.1), sed (>= 4)
Conffiles:
 /etc/fuse.conf 298587592c8444196833f317def414f2
Description: Filesystem in Userspace
 Filesystem in Userspace (FUSE) is a simple interface for userspace programs to
 export a virtual filesystem to the Linux kernel. It also aims to provide a
 secure method for non privileged users to create and mount their own filesystem
 implementations.
Original-Maintainer: Laszlo Boszormenyi (GCS) <gcs@debian.org>
Homepage: https://github.com/libfuse/libfuse/wiki

#### Kernel information (uname -r)
_command result: uname -r_
uname -r 
5.13.19-1-pve

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_command result: cat /etc/os-release_

#### s3fs command line used, if applicable
```
s3fs delete1 /media/dreamhost/ -o passwd_file=${HOME}/.passwd-s3fs
fuse: device not found, try 'modprobe fuse' first
```
#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
sudo grep s3fs /var/log/syslog
Dec  3 11:35:34 emby-vm s3fs[1285]: s3fs: MOUNTPOINT: /media/dreamhost/ permission denied.
Dec  4 08:38:25 emby-vm s3fs[17347]: s3fs: missing BUCKET argument.
```
### Details about issue

Is it possible to use s3fs with DreamHost?  Where the endpoint URL is defined?

**Comment by gaul** [comment]
See https://github.com/s3fs-fuse/s3fs-fuse/wiki/Non-Amazon-S3#dreamobjects .
