### ISSUE TITLE
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

### ISSUE THREAD

**Issue by jekatarina** [s3fs-fuse/s3fs-fuse#1815]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
_Amazon Simple Storage Service File System V1.86 (commit:unknown) with GnuTLS(gcrypt)
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law._

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_Package: fuse
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 113
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.9.9-3
Depends: libc6 (>= 2.28), libfuse2 (= 2.9.9-3), adduser, mount (>= 2.19.1), sed (>= 4)
Conffiles:
 /etc/fuse.conf 298587592c8444196833f317def414f2
Description: Filesystem in Userspace
 Filesystem in Userspace (FUSE) is a simple interface for userspace programs to
 export a virtual filesystem to the Linux kernel. It also aims to provide a
 secure method for non privileged users to create and mount their own filesystem
 implementations.
Original-Maintainer: Laszlo Boszormenyi (GCS) <gcs@debian.org>
Homepage: https://github.com/libfuse/libfuse/wiki_

#### Kernel information (uname -r)
_.4.72-microsoft-standard-WSL2_

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal_

#### s3fs command line used, if applicable
```
s3fs backup-database-bucket-test /var/lib/mysql/ -o nonempty -o passwd_file=/etc/passwd-s3fs -o endpoint=eu-central-1 -f -d
```
#### /etc/fstab entry, if applicable
```
# UNCONFIGURED FSTAB FOR BASE SYSTEM
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
[CRT] s3fs.cpp:set_s3fs_log_level(297): change debug level from [CRT] to [INF]
[INF]     s3fs.cpp:set_mountpoint_attribute(4400): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40700)
[INF] s3fs.cpp:s3fs_init(3493): init v1.86(commit:unknown) with GnuTLS(gcrypt)
[INF] s3fs.cpp:s3fs_check_service(3828): check services.
[INF]       curl.cpp:CheckBucket(3413): check a bucket.
[INF]       curl.cpp:prepare_url(4703): URL is https://s3.amazonaws.com/backup-database-bucket-test/
[INF]       curl.cpp:prepare_url(4736): URL changed is https://backup-database-bucket-test.s3.amazonaws.com/
[INF]       curl.cpp:insertV4Headers(2753): computing signature [GET] [/] [] []
[INF]       curl.cpp:url_to_host(99): url is https://s3.amazonaws.com
[ERR] curl.cpp:RequestPerform(2436): HTTP response code 403, returning EPERM. Body Text: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>1HJTCAHD1ZNAWJWY</RequestId><HostId>TjeqWeV/WgkIOOC68XM7cxoNqokf3/O/1qS8V/89+1qsl4kjSEa2KtTEP9CutVLmBxarsTYkCVM=</HostId></Error>
[ERR] curl.cpp:CheckBucket(3439): Check bucket failed, S3 response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>1HJTCAHD1ZNAWJWY</RequestId><HostId>TjeqWeV/WgkIOOC68XM7cxoNqokf3/O/1qS8V/89+1qsl4kjSEa2KtTEP9CutVLmBxarsTYkCVM=</HostId></Error>
[CRT] s3fs.cpp:s3fs_check_service(3883): Failed to connect by sigv4, so retry to connect by signature version 2.
[INF] curl.cpp:ReturnHandler(318): Pool full: destroy the oldest handler
[INF]       curl.cpp:CheckBucket(3413): check a bucket.
[INF]       curl.cpp:prepare_url(4703): URL is https://s3.amazonaws.com/backup-database-bucket-test/
[INF]       curl.cpp:prepare_url(4736): URL changed is https://backup-database-bucket-test.s3.amazonaws.com/
[ERR] curl.cpp:RequestPerform(2431): HTTP response code 400, returning EIO. Body Text: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>1HJTYTZNGWVCRCEX</RequestId><HostId>V93Ft4vonc7khZxKAlsgJr+ZST5QovNdNuhVii2jTNzlBL4xmRoXX5uYHIw8vplUKyy6ulJslpg=</HostId></Error>
[ERR] curl.cpp:CheckBucket(3439): Check bucket failed, S3 response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>1HJTYTZNGWVCRCEX</RequestId><HostId>V93Ft4vonc7khZxKAlsgJr+ZST5QovNdNuhVii2jTNzlBL4xmRoXX5uYHIw8vplUKyy6ulJslpg=</HostId></Error>
[CRT] s3fs.cpp:s3fs_check_service(3895): Bad Request(host=https://s3.amazonaws.com) - result of checking service.
[ERR] s3fs.cpp:s3fs_exit_fuseloop(3483): Exiting FUSE event loop due to errors

[INF] s3fs.cpp:s3fs_destroy(3546): destroy
```
### Details about issue
Unable to mount file directory to S3

**Comment by gaul** [comment]
It looks like your credentials are incorrect.  The confusing error message is due to sigv2 fallback.  You can disable this with `-o sigv4`.

**Comment by jekatarina** [comment]
Thanks for your answer. I've controlled my credentials again and the credentials are written in the form
AccessKeyId:SecretAccessKey
in the file and the values are correct. 
When i am adding the -o sigv4 option, i get following error:
...
[CRT] s3fs.cpp:set_s3fs_log_level(297): change debug level from [CRT] to [INF]
[INF]     s3fs.cpp:set_mountpoint_attribute(4400): PROC(uid=0, gid=0) - MountPoint(uid=999, gid=0, mode=40777)
fuse: unknown option `sigv4'
...

**Comment by iamhritik** [comment]
I think you are using secret key first and then access key in passwd-s3fs file. Please use it correctly

**Comment by ggtakec** [comment]
@jekatarina 
You are using v1.86, but this version does not have the `sigv4` option built in.(The `sigv4` option is supported since v1.88.)
Please try again with the latest version.
Thanks in advance for your assistance.

**Comment by gaul** [comment]
Please test with 1.93 and reopen if your symptoms persist.
