### ISSUE TITLE
I am looking for s3fs_1.87-1_arm64.deb

### ISSUE THREAD

**Issue by Waffleuncle** [s3fs-fuse/s3fs-fuse#1824]
Hi , 
for project i am looking for the s3fs_1.87-1_arm64.deb
if some one have it please tell me the link

**Comment by gaul** [comment]
This project does not create packages; you will need to follow up with Debian or Ubuntu or whatever distro you run.  I cannot correlate 1.87 with any known major release so this looks niche or home-grown.
