### ISSUE TITLE
s3fs Filesystem Size is 16E with df -h

### ISSUE THREAD

**Issue by indychou** [s3fs-fuse/s3fs-fuse#1870]
s3fs is working very well for my vm. 

It is likely that the bucket size is too large causing an error in some applications.
it show bucket size (16E) with df -h command.

Have any way to get a correct bucket size value with df command? 

The following information from my vm:
s3fs version: 1.90
fuse Version : 2.9.2
uname -a: 3.10.0-1160.45.1.el7.x86_64
cat /etc/os-release: centos 7.9

/etc/fstab: 
mybucket /data fuse.s3fs _netdev,dbglevel=debug,enable_noobj_cache,allow_other,mp_umask=002,use_path_request_style,use_cache=/dev/shm,del_cache,big_writes,multipart_size=100,max_write=131072,max_stat_cache_size=1000000,parallel_count=100,url=https://s3.twcc.ai,nonempty  0 0

**Comment by gaul** [comment]
s3fs is working as intended.  AWS S3 has "infinite" space so it reports the largest possible value.  The S3 API does not expose either a current or maximum size, either in number of object or their sizes.

Which application cannot handle this value?  Have you reported issues against these projects?

**Comment by NoAccident** [comment]
@indychou I have encountered the same problem, how did you solve it please?

**Comment by gaul** [comment]
What is the same problem?
