### ISSUE TITLE
Attempts to access non-existent files may result in bogus EPERM instead of ENOENT

### ISSUE THREAD

**Issue by UnitedMarsupials** [s3fs-fuse/s3fs-fuse#188]
If the attempted name contains asterisk, the error-code will be `EPERM`, which is incorrect. Otherwise, the failure is `ENOENT`. Here, for example, we have an S3-bucket mounted under `/data/ftp`. Trying to list three non-existent names, one gets different results:
```
% ls -l '/data/ftp/*ogus' '/data/ftp/?ogus' '/data/ftp/bogus'
ls: cannot access /data/ftp/*ogus: Operation not permitted
ls: cannot access /data/ftp/?ogus: No such file or directory
ls: cannot access /data/ftp/bogus: No such file or directory
```
Note, how using ?-template still works properly, but asterisk must have some special meaning, which causes erroneous behavior.

**Comment by UnitedMarsupials** [comment]
This is, probably, due to the fact, that `*` is copied verbatim instead of being escaped in `urlEncode()`.

BTW, this function seems to have another problem -- it relies on `isalnum()`, which can have a different result depending on locale. It should instead check for the characters being one of the three ranges instead: `'a'`-`'z'`, `'A'`-`'Z'`, `'0'`-`'9'`.

Oh, and the special case for space is gratuitous for it is indistinguishable for the general case implemented after it.

**Comment by UnitedMarsupials** [comment]
The fixes the problem for me -- and picks the above-mentioned nits from `urlEncode()`:

```diff
--- src/string_util.cpp 2015-03-25 14:00:46 -0400
+++ src/string_util.cpp 2015-05-12 18:39:19 -0400
@@ -124,14 +124,12 @@
   string result;
   for (unsigned i = 0; i < s.length(); ++i) {
-    if (s[i] == '/') { // Note- special case for fuse paths...
+    if (s[i] == '/' // Note- special case for fuse paths...
+      || (s[i] <= 'z' && s[i] >= 'a')
+      || (s[i] <= 'Z' && s[i] >= 'A')
+      || (s[i] <= '9' && s[i] >= '0')
+      || s[i] == '.'
+      || s[i] == '-'
+      || s[i] == '_') { // Should more characters -- like ^ -- be added here?
       result += s[i];
-    } else if (isalnum(s[i])) {
-      result += s[i];
-    } else if (s[i] == '.' || s[i] == '-' || s[i] == '*' || s[i] == '_') {
-      result += s[i];
-    } else if (s[i] == ' ') {
-      result += '%';
-      result += '2';
-      result += '0';
     } else {
       result += "%";
```

**Comment by andrewgaul** [comment]
I have not looked into this yet, but we should add tests for special characters to `integration-test-main.sh`.

**Comment by andrewgaul** [comment]
Some percent-encoding references:

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
