### ISSUE TITLE
s3fs: unexpected error from stat().

### ISSUE THREAD

**Issue by freetec1** [s3fs-fuse/s3fs-fuse#1889]
#### Version of s3fs being used (s3fs --version)
1.90
#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.7

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

#### s3fs command line used, if applicable
```
sudo s3fs bucketname /mnt/raw_storage/
```

### Details about issue

Hello,

if i try to mount the s3 bucket with the given line i just get the error "s3fs: unexpected error from stat()". The mountpoint does exist and if i check the connection to s3 via

```
aws s3 ls s3://bucketname
```
i can see every file from the bucket.

Can somebody help me figure out the problem? Do you need any additional information.

Kind regards

**Comment by joetex** [comment]
We are seeing this issue as well.  
```
error s3fs: unexpected error from stat().
```
Was there a new release recently?  We automate the setup in Docker, and this occurred after pushing a code update.

**Comment by mcaidans** [comment]
Bumping, same issue, no change to code or our automatic deployment. Our last successful deploy was 16 days ago, and failed yesterday, so some change between those two times on the master branch caused the issue.

Solution for now is switching to 1.9.0 as already stated.

**Comment by ggtakec** [comment]
@joetex @mcaidans Thanks for your bug reports.
I think this error is a bug fixed in # 1896.
(After this fix, I have another fix now)
Please try again with the latest master code.

**Comment by bhoov** [comment]
I'm getting this same error after a fresh `brew install gromgit/fuse/s3fs-mac` (which downloads `s3fs` version 1.9.1). The command:

```
s3fs BUCKET /PATH/TO/MOUNT -o url=ENDPOINT -o passwd_file=~/.passwd-s3fs
```

results in

```
s3fs: unexpected error from stat(~/.passwd-s3fs)
```

I am using M1 MacBook Ventura 13.0.1.

**Comment by ggtakec** [comment]
I think this bug has been fixed in master, so I will close this issue.
If you still have problems with the master code, please reopen it.

**Comment by Yaski** [comment]
Still has this error
s3fs version 1.91

**Comment by papanito** [comment]
You can also use `$HOME` instead of `~`
