### ISSUE TITLE
Permissons of mounted bucket don't allow reading

### ISSUE THREAD

**Issue by gbell12** [s3fs-fuse/s3fs-fuse#191]
Using Ubuntu 14.04 LTS, I can mount but see this:
```
$ ll mountpnt
total 512
d--------- 1 root 0 Oct 30  2014 wordpress_backups
```

I'm afraid to chmod that... is there a good reason nobody can read that dir?

**Comment by kahing** [comment]
Was it a directory that was written through s3fs or through some other applications? s3fs relies on its own metadata to store the permissions, without those metadata it's expected to show what you see here

**Comment by gbell12** [comment]
It's an existing bucket, so it was created/written via the web interface.

What do I do in that use case?

**Comment by gbell12** [comment]
Put another way, can I initialise the metadata from an existing bucket?

**Comment by kahing** [comment]
Could you try chmod'ing the files manually?

**Comment by ertrzyiks** [comment]
Thats happens when you upload files from website. S3 bucket store permissions in metadata field called `x-amz-meta-mode` and default value is 0000. Once you set chmod manually on mounted folder, s3fs will update that field and your chmod will be remembered for next time you mount your bucket.

**Comment by gbell12** [comment]
Ah, beauty.  Thanks ertrzyiks.
