### ISSUE TITLE
Connecting to S3 for Thousand genomes data

### ISSUE THREAD

**Issue by Phillip-a-richmond** [s3fs-fuse/s3fs-fuse#1928]
Hello,

I'm trying to mount the public S3 bucket (s3:/1000genomes) to visualize these large files as a mounted filesystem using Integrative Genomics Viewer (IGV). 

I installed s3fs through brew on my Mac (Mac Pro 2019, OS v10.15.7) and it seems to work fine. But when I run the mount command I get a "Device not configured" error after it hangs for a few moments. Perhaps it's the syntax of my command?

The s3 cli equivalent of viewing the data:

```
aws s3 ls s3://1000genomes/data/NA21143/alignment/ --no-sign-request
```

The command I'm running which fails:

```
s3fs -o public_bucket=1 s3:/1000genomes/data/NA21143/alignment/  ~/S3_Mount/
```

Where ~/S3_Mount/ is just an empty directory on my local machine.

Any help would be appreciated!

Thanks,
Phil

**Comment by gaul** [comment]
s3fs does not use the `s3://` syntax.  Please try:

```
s3fs -o public_bucket=1 1000genomes:/data/NA21143/alignment/ ~/S3_Mount/
```

Note colon after bucket name).

**Comment by gaul** [comment]
Please reopen if your symptoms persist.
