### ISSUE TITLE
docker run "ls: /opt/s3fs/bucket: Permission denied"

### ISSUE THREAD

**Issue by pljplj** [s3fs-fuse/s3fs-fuse#1930]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
/opt/s3fs # s3fs --version
Amazon Simple Storage Service File System V1.86 (commit:bb20fc3) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_/opt/s3fs # pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse
/bin/sh: pkg-config: not found

#### Kernel information (uname -r)
5.13.0-1021-aws

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.0
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
dev/cdrom      /media/cdrom    iso9660 noauto,ro 0 0
/dev/usbdisk    /media/usb      vfat    noauto,ro 0 0

#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
There is no file /var/log/syslog in the container

### Details about issue
On an ec2 instance I did:
$ docker pull efrecon/s3fs

Then I did:
$ docker run -it --rm \
    --device /dev/fuse \
    --cap-add SYS_ADMIN \
    --security-opt "apparmor=unconfined" \
    --env "AWS_S3_BUCKET=picard-prov" \
    --env "AWS_S3_ACCESS_KEY_ID=obscured" \
    --env "AWS_S3_SECRET_ACCESS_KEY=obscured" \
    --env UID=$(id -u) \
    --env GID=$(id -g) \
    -v /mnt/tmp:/opt/s3fs/bucket:rshared \
    efrecon/s3fs

The result was:
ls: /opt/s3fs/bucket: Permission denied
Mounted bucket picard-prov onto /opt/s3fs/bucket

When I sh into the container /opt/s3fs/bucket is empty despite the s3 bucket not being empty

**Comment by rcfox** [comment]
Try using `efrecon/s3fs:1.91`. The base name is a fairly old version.

**Comment by gaul** [comment]
Please reopen if symptoms persist with 1.91.

**Comment by TDenisM** [comment]
Hi! It's still here
`/opt/s3fs # ls
ls: ./bucket: Permission denied
passwd-s3fs`

**Comment by pacsui** [comment]
@TDenisM can you specify how it was your issue, I have the same error and wasn't able to figure out yet.
