### ISSUE TITLE
Add AWS SSO Authentifcation 

### ISSUE THREAD

**Issue by VivienMoretto87** [s3fs-fuse/s3fs-fuse#1931]
Hi, 

I need to integrate the AWS SSO authentifcation in s3fs. I have just checked the opensource project aws-cli (SSOCredentialFetcher in credentials.py in the project https://github.com/aws/aws-cli/tree/v2/awscli ) and the s3fs seems not to be compatible with this kind of authentication. 

I have modified the code : 
- get the cache json file with SSO credentials (it is the result sha1 of a json file { 'startUrl': self._start_url, 'roleName': self._role_name, 'accountId': self._account_id }) 
- get credentials for the cache json file (parse the json with nlohmann library )

It seems to work. 

Can you tell if it is possible to contribute the community by pushing my code and give some advises to have a clearer implementation ? 

Regards,

**Comment by ggtakec** [comment]
@VivienMoretto87 Thanks for your kindness.
s3fs-fuse doesn't currently support SSO authentication, so we'd appreciate it if you could make a PullRequest.
After that, @gaul and I will be able to review it.

As a solution to this problem, I am now submitting another PR (# 1927).
This PR is the code to delegate the authentication process to an external DSO.
I think that combining this PR code with the DSO( https://github.com/ggtakec/s3fs-fuse-awscred-lib) should enable AWS SSO authentication.
This DSO just calls aws-sdk-cpp and it does the same authentication process as awscli and can get the tokens it needs.

If you are interested, I would be grateful if you could try # 1927 as well.

**Comment by VivienMoretto87** [comment]
Thank you for the answer, I will push my code. I tested it Friday and it seems to work (other authentication too). 

Regards, 
Vivien

**Comment by Emru1** [comment]
Hey, can we expect this feature any time soon?
Looking forward to it

**Comment by ggtakec** [comment]
#1927 adds `credlib` and `credlib_ops` options.
Authentication not currently supported by s3fs can be supported by specifying a dedicated DSO for these options.
Please try to create your own DSO or use a trusted one.
I provide https://github.com/ggtakec/s3fs-fuse-awscred-lib which can cover all AWS authentication.

We will continue to add support for AWS and other cloud-based authentication, but for now please try to use the above DSO for AWS authentication which are not supported by s3fs.
