### ISSUE TITLE
Tilda in a file-name breaks things (EPERM)

### ISSUE THREAD

**Issue by UnitedMarsupials** [s3fs-fuse/s3fs-fuse#194]
Trying to `touch` a file `test~` or `mkdir` a directory with the same name results in `EPERM`:

    test~: Operation not permitted

Seems like Issue #188, but the tilda-symbol does _not_ have a special handling in the `urlEncode`-function (whereas asterisk used to). Maybe, unlike `'*'`, the `'~'` _does_ need to be passed-through unescaped?

**Comment by andrewgaul** [comment]
@UnitedMarsupials I updated #192 to correctly handle tilde.  This reference helped me:

http://en.wikipedia.org/wiki/Percent-encoding
