### ISSUE TITLE
Mounting Folder Using Instance Role

### ISSUE THREAD

**Issue by qscacheri** [s3fs-fuse/s3fs-fuse#1942]
Is possible to use s3fs using an instance role for access without having to give the role access to the root of the bucket? I'd like to mount a folder without having to give the role access to anything else in the bucket. Is this possible?

Thanks!

**Comment by shmuelzon** [comment]
Hey, I'd like to know as well. The user has access only to one directory in a bucket, but not the root directory. `s3cmd` works when specifying the directory but it seems s3fs is trying to log-in to the root of the bucket.

@qscacheri, where you able to get this working? I tried tricking it with the `servicepath` option to add the specific directory to the URL `s3fs` uses but that didn't seem to work.

Thanks in advance!

**Comment by ggtakec** [comment]
@qscacheri @shmuelzon Sorry for my late reply.
I believe this is fixed due to #2087.
If you can, please try it(master branch).
This issue will be closed, but please reopen it if you still have problems.
