### ISSUE TITLE
Can't install via pip3 python  3.9 ALONG WITH aws CLI

### ISSUE THREAD

**Issue by AaronRohrbacher** [s3fs-fuse/s3fs-fuse#1952]
### Additional Information
Sounds like a common issue, but any support for Python anymore?

pip3 install awscli
pip3 install s3fs

**Comment by AaronRohrbacher** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.3.2 requires botocore<1.24.22,>=1.24.21, but you have botocore 1.26.9 which is incompatible.

**Comment by gaul** [comment]
s3fs-fuse is not the same as boto3 s3fs despite the similar name.
