### ISSUE TITLE
NFS client does not notice file updates via s3fs mount

### ISSUE THREAD

**Issue by ggtakec** [s3fs-fuse/s3fs-fuse#1961]
### Details about issue
When the directory mounted by s3fs is mounted by NFS, the file object created in S3 bucket by s3fs is not reflected.
_It is unknown whether this is a problem with the NFS specifications._

#### Reproduction procedure
- mount any bucket `/mnt/s3` with s3fs
- mount `/mnt/s3` on `/mnt/nfs` with NFS
- create a file in directly to `/mnt/s3` (ex. `touch /mnt/s3/test`)
- the test file does not exist when `/mnt/nfs` is displayed by `ls`.  
However, you can display `ls /mnt/nfs/test`.

A quick check shows that `GETATTR(/)` is called from FUSE, but it seems that subsequent `GETATTR(/test)` has not been called.

**Comment by ggtakec** [comment]
It is uncertain, but it is suspected that the cause is that s3fs has not changed the stat(`mtime` / `atime`) of the parent directory of the manipulated file.
I continue to work this and test.

**Comment by giulianoc** [comment]
Thank you, let me know if I can help you testing in my scenario.

**Comment by ggtakec** [comment]
@giulianoc 
Added `update_parent_dir_stat` option to update parent directory stat information when file operations are performed.
With this, I think that you can catch file and directory updates when used with NFS.
See #2016 for details.
Try using master's code with the `update_parent_dir_stat` option.
