### ISSUE TITLE
umask and mp_umask are mutually exclusive in that using umask causes mp_umask to be overridden

### ISSUE THREAD

**Issue by michaelsmoody** [s3fs-fuse/s3fs-fuse#2032]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
s3fs 1.91

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
FUSE 2.9.2

#### Kernel information (uname -r)
5.10.135-122.509.amzn2.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
Amazon Linux 2

#### s3fs command line used, if applicable
```
s3fs -o url=https://s3-us-gov-west-1.amazonaws.com -o endpoint=us-gov-west-1 -o allow_other -o umask=007 -o mp_umask=022 -o dev -o suid -o use_xattr cust-s3-transfer-storage:/FOLDER /mnt/folder
```
#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
2022-09-16T18:46:15.410Z [INF]     s3fs.cpp:set_mountpoint_attribute(3628): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
```
### Details about issue

Despite this line in the logs, despite this setting, it appears that `umask` and `mp_umask` are mutually exclusive, and that when both are set, my mountpoint gets set to the setting of `umask` **NO MATTER WHAT**, which prevents what I need to work from actually working.

`drwxrwx---.  1 root root    0 Jan  1  1970 /mnt/folder`

This is an unfortunate consequence (combined of course with the sticky bit problem, and several other blocking issues as well) that prevents production usage of S3FS at this time.

I've attempted a combination of removing and adding options for this and other reasons, such as the reason this is being worked on in the first place, CHROOT (`suid`, `dev`, `uid`/`gid`, etc), and while `uid`/`gid` are properly obeyed, they do have another unfortunate consequence that I'll bring up elsewhere.

Any help of course that you can provide would be greatly appreciated!

**Comment by ggtakec** [comment]
I believe this issue will be resolved once #1964 is merged.
With the above PR, you will be able to set permissions for mount points.
I believe that mp_umask will be deprecated accordingly.
Please wait until it is merged.

**Comment by michaelsmoody** [comment]
@ggtakec I've seen #1964 merged, however would you mind confirming that mp_umask is indeed being deprecated and that I should now chaos/chown the mountpount directly? Do you happen do know when a release might be made with this commit/merge? (No push, just curious what the release cycle looks like)

**Comment by ggtakec** [comment]
We'd like to release it sooner, but we don't have a firm date yet. (#2102)
This issue will be closed, but please reopen it if you still have problems.
