### ISSUE TITLE
can't open folder with S3Fs

### ISSUE THREAD

**Issue by mbensaid23** [s3fs-fuse/s3fs-fuse#2034]
Hello, 

I installed S3fs and I mounted my bucket in a directory /ojs , but when I copy folders I can't access these folders I can't see it I don't have the rights to the folder

root@root ojs# ls -l 
??????????? ? ?    ?         ?            ? testOJS 

can you help me plz

**Comment by ggtakec** [comment]
Please share s3fs version, boot command line, or fstab line for s3fs.
After that, if you have a little more detailed information(what to do), it would be helpful.
Also, the `compat_dir` option may be useful if you are copying with the S3 console or similar.

**Comment by DarthGandalf** [comment]
I have the same issue.

V1.91

```
$ s3fs <bucketname> mountpoint -o passwd_file=/tmp/passwd-s3fs -o noatime (but doesn't work without noatime either)

$ cd mountpoint

$ mkdir testtest
mkdir: cannot create directory 'testtest': No such file or directory

$ ls -ld testtest
ls: cannot access 'testtest': No such file or directory

$ ls -l | grep test
ls: cannot access 'testtest': No such file or directory
?????????? ? ?        ?        ?            ? testtest
```
Non-folder files show correctly.  The folder created using `mkdir` is visible in S3 AWS web console; folders created via that console are also visible this way - with question marks.

**Comment by DarthGandalf** [comment]
>  Also, the compat_dir option may be useful if you are copying with the S3 console or similar.

Can you clarify?

```
fuse: unknown option `compat_dir'
```

**Comment by DarthGandalf** [comment]
If you mean `notsup_compat_dir`, that changes the error, but doesn't work either:

```
$ mkdir test
mkdir: cannot create directory 'test': Input/output error

$ ls -l test
-rwxr-x--- 1 user user 0 Jan  1  1970 test

$ cd test
cd: not a directory: test
```

In AWS console it looks like a folder

**Comment by DarthGandalf** [comment]
nvm, PEBKAC

My IAM policy was too restrictive

**Comment by ggtakec** [comment]
@DarthGandalf Thank you for your comment.
I understood that the inability to create the directory was the effect of an `IAM policy`.
I'm going to close this issue.

And I apologize for the inaccurate description of the `compat_dir` option I gave you.
The correct explanation is:
Up to v1.91, the compatibility directory information is displayed by default.(Use `notsup_compat_dir` option if you don't want it to be displayed)
In the current master branch, it will not be displayed by default, so if you want to display it, you will have to specify `compat_dir`.

**Comment by DarthGandalf** [comment]
>  I understood that the inability to create the directory was the effect of an IAM policy.

Not exactly. The directory was created just fine. But immediately after creation, it couldn't be read, because there was no "s3:GetObject" permission, and this inability to read the newly created directory caused the issue described above.

I thought "s3:ListBucket" and "s3:PutObject" would be enough, since I was never going to read *files* using this user, but only write them.

> And I apologize for the inaccurate description of the compat_dir option I gave you.

That was actually @mbensaid23, not me. I just looked through open issues before creating a new one, therefore commented here. But since he never replied with any more details, I'm fine with you closing this issue :) Hopefully he fixed his issue too.

> In the current master branch, it will not be displayed by default

Any ETA when new release happens? I'm fine not displaying it, but I also would like to keep options passed explicitly to minimum.

**Comment by ggtakec** [comment]
We plan to prepare the next release once the known bugs have been fixed.(It will take a little longer)
I think we should reduce the number of options that must be specified as much as possible. So I would like to continue to consider the default value of each option.
