### ISSUE TITLE
Uploading large files with multipart enabled / disabled is failing 

### ISSUE THREAD

**Issue by krishna8189** [s3fs-fuse/s3fs-fuse#2044]
#### Version of s3fs being used (s3fs --version)
V1.91 (commit:3e242d0)

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Version: 2.9.7-1ubuntu1

#### Kernel information (uname -r)
5.4.0-1084-aws

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
Ubuntu 18.04.6 LTS

#### /etc/fstab entry, if applicable
s3fs#<bucket_name> /mnt/s3/<bucket_name> fuse _netdev,allow_other,use_sse=1,endpoint=us-east-1,uid=1000,gid=1000,iam_role=auto 0 0

### Details about issue
Hello Team,
We are facing issues when copying / downloading large files via the s3fs, with or with out multipart enabled

When the fstab entry is as below
s3fs#<bucket_name> /mnt/s3/<bucket_name> fuse _netdev,allow_other,use_sse=1,endpoint=us-east-1,uid=1000,gid=1000,iam_role=auto 0 0
we are getting "operation not permitted" error with a file size of 50 mb

as a workaround, we have updated the fstab entry as below
s3fs#<bucket_name> /mnt/s3/<bucket_name> fuse _netdev,allow_other,use_sse=1,endpoint=us-east-1,uid=1000,gid=1000,iam_role=auto,nomultipart 0 0
which resolved the issue with 50 mb files, however, when trying to download files with are 600mb / close to 1GB we are getting a file too large error. 

Also, we have tried bunch of other options like multipart_size, multipart_copy_size etc.. but none of them worked in our case, can you please suggest a solution for this issue and also why this issue is happening .
Also, can you please let me know what is the file size that I can copy / download without the multipart enabled.

Thanks,
krishna

**Comment by krishna8189** [comment]
Can someone pls look into this issue ?
Thanks..

**Comment by ggtakec** [comment]
@krishna8189 Sorry for my late reply.
This issue may have the same cause as the issue fixed in #2091.
Could you try it with the current master branch code?
Thanks in advance for your assistance.

**Comment by gaul** [comment]
Please reopen if symptoms persist with the latest 1.93.
