### ISSUE TITLE
some directory  not shown

### ISSUE THREAD

**Issue by mbensaid23** [s3fs-fuse/s3fs-fuse#2045]
Hello

I installed s3fs on VM1 RED Hat 8.6 and mounted the s3bucket. but when i synchronize my local folder and my files i can't see all the folders, the folder is there but I don't see them it's as if the folders are hidden.

Cammand tha i used:

s3fs $SCW-BUCKET-NAME $FOLDER-TO-MOUNT -o allow_other -o passwd_file=$HOME/.passwd-s3fs -o use_path_request_style -o endpoint=fr-par -o url=https://s3.fr-par.scw.cloud

also i add uid= and gid, umask , but nothing has changed.

can you help me plz

**Comment by ggtakec** [comment]
@mbensaid23 
The default of the object(file/directory) compatibility option has been changed since V1.91.
You may need to give the compat_dir and complement_stat options.

**Comment by 880831ian** [comment]
@ggtakec Hello, I also have the same problem and would like to ask how to add compat_dir and complement_stat options

**Comment by ggtakec** [comment]
@880831ian 
You just specify `compat_dir` and `complement_stat` in the options  when starting sfs or in fstab.
Please see below for the necessity of each option.

#### `compat_dir`
Here's an excerpt from the man page on the current master branch:

> s3fs supports two different naming schemas "dir/" and "dir" to map directory names to S3 objects and vice versa by default.
> As a third variant, directories can be determined indirectly if there is a file object with a path (e.g. "/dir/file") but without the parent directory. 
> This option enables a fourth variant, "dir_$folder$", created by older applications.
> S3fs uses only the first schema "dir/" to create S3 objects for directories.
> The support for these different naming schemas causes an increased communication effort.

s3fs recognizes an object `dir/` as a directory. (This is an object for directory stat information)
However, if you create a directory or object with a client other than s3fs, this object will not exist.
Therefore, in such cases, specify the `compat_dir` option.

#### `complement_stat`
Here's an excerpt from the man page on the current master branch:

> s3fs uses the "x-amz-meta-mode header" to determine if an object is a file or a directory.
> For this reason, objects that do not have the "x-amz-meta-mode header" may not produce the expected results(The directory cannot be displayed, etc.).
> By specifying the "complement_stat" option, s3fs can automatically complete this missing attribute information, and you can get the expected results.

Specify this option if the objects in your S3 bucket do not have `x-amz-meta***` headers.

#### NOTE
From v1.91, you have to grant this option if you have a above case.
(Before that, the behavior of these options was the default, but the communication cost was too high, so the default behavior has been changed.)

I'll close this issue, if you have a problem, please reopen this.
