### ISSUE TITLE
df -h does not show how much space used about s3fs

### ISSUE THREAD

**Issue by huntersman** [s3fs-fuse/s3fs-fuse#2047]
#### Version of s3fs being used (s3fs --version)
V1.91

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.2

#### Kernel information (uname -r)
5.4.213-1.el7.elrepo.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
CentOS7

#### s3fs command line used, if applicable
```
s3fs myBucket /mount/s3fs -o passwd_file=${HOME}/.passwd-s3fs -o url=http://myIp -o use_path_request_style -o noxmlns -o dbglevel=error -o default_acl=public-read -o logfile=/var/log/s3fs.log -o allow_other
```
### Details about issue
I want to use `df -h` to see how much space I used about s3fs, but find it always be 0.

**Comment by gaul** [comment]
s3fs cannot store this information.  You can calculate it yourself via `du -s /mount/s3fs`.

**Comment by huntersman** [comment]
> s3fs cannot store this information. You can calculate it yourself via `du -s /mount/s3fs`.

I got it, thank you
