### ISSUE TITLE
Any way to do recursive operations faster?

### ISSUE THREAD

**Issue by Jafo232** [s3fs-fuse/s3fs-fuse#205]
When doing a recursive operation like CHMOD or CHOWN, it takes FOREVER.  Is there anyway to speed this up?

**Comment by andrewgaul** [comment]
This is a problem for single-threaded commands running against any network file system but particularly acute for s3fs.  Could you introduce parallelism via:

```
find | xargs --max-args=1 --max-procs=50 chmod
```

**Comment by Jafo232** [comment]
Thanks, that helps a bit.  Still slow, but not as much.

**Comment by andrewgaul** [comment]
Also you can mount your S3 bucket with an EC2 instance in the same region to decrease per-operation latency.
