### ISSUE TITLE
Cannot set `http_proxy` environment variable in fstab

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#2069]
s3fs may need to add a flag to directly support mounting via fstab while setting a proxy.  Context:

https://serverfault.com/questions/1019109/mount-aws-s3-on-boot-while-behind-proxy-using-s3fs

**Comment by ggtakec** [comment]
The same issue was also pointed out in #1861. I'm sorry for not start to work for it yet.

**Comment by ggtakec** [comment]
Now that we have completed the implementation of proxy options, I will close this issue.
