### ISSUE TITLE
Feauture server-side encryption details

### ISSUE THREAD

**Issue by allahshukur-ahmadzada** [s3fs-fuse/s3fs-fuse#2070]
Hi, I see in README there is feature "optional server-side encryption" but cant find detailed information about it. Can you please help me to understand how it works? how is it different compared to MiniO/KES/KMS setup.

**Comment by ggtakec** [comment]
@allahshukur-ahmadzada I'm sorry for my late reply.
For SSE, please try running `s3fs --help` or `man s3fs`.
Optionally, it provides `use_sse` and supports SSE-C, SSE-S3 and SSE-KMS depending on the parameters.
_[Note] V1.91 has a problem with SSE-C, and it will be released with a fix in the next version._

I will close this issue, but if you have a problem yet, please reopen this issue.
