### ISSUE TITLE
df command shows wrong values (Used=0)

### ISSUE THREAD

**Issue by Framsfex** [s3fs-fuse/s3fs-fuse#2071]
#### Version of s3fs being used (`s3fs --version`)
V1.86 (commit:unknown)

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`)
2.9.9-3

#### Kernel information (`uname -r`)
5.4.0-132-generic

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)
Ubuntu 20.04.5

#### How to run s3fs, if applicable
s3fs s3fs-test /S3 -o passwd_file=/root/.passwd-s3fs -o url=https://s3.tik.uni-stuttgart.de  -o use_path_request_style

### Details about issue
root@obertux:/S3# mount | grep S3
s3fs on /S3 type fuse.s3fs (rw,nosuid,nodev,relatime,user_id=0,group_id=0)

root@obertux:/S3# df -TH .
Filesystem     Type       Size  Used Avail Use% Mounted on
s3fs           fuse.s3fs  282T     0  282T   0% /S3

root@obertux:/S3# du -sh
41G     .

root@obertux:/S3# find . | wc -l
108

==> df shows Used=0 but there IS at least 41 GB of file data!

**Comment by gaul** [comment]
s3fs cannot support this feature since it does not/cannot store the number of bytes used.  You need to use `df` instead.

**Comment by Framsfex** [comment]
Please look at my report: I have used df! THIS IS the problem! df reports wrong numbers!

**Comment by gaul** [comment]
I corrected my comment.  Again, this is not something s3fs will ever support since S3 does not provide this information and it is expensive to calculate.
