### ISSUE TITLE
s3fs command not found 

### ISSUE THREAD

**Issue by cinek2000** [s3fs-fuse/s3fs-fuse#208]
after installing this on centos 7 and amazon linux 03.2015 I keep getting the following error
s3fs command not found 
is centos7 and amazon linux 03.2015 supported or do I have to use an earlier version?

**Comment by kahing** [comment]
How did you install s3fs? 
On Jul 14, 2015 03:05, cinek2000 <notifications@github.com> wrote:after installing this on centos 7 and amazon linux 03.2015 I keep getting the following error
s3fs command not found 
is centos7 and amazon linux 03.2015 supported or do I have to use an earlier version?

**Comment by bhargav-nunna** [comment]
Hi I am trying to install s3fs on Amazon Linux 01.2018 and I am getting the same error. Is there any solution for this one?
