### ISSUE TITLE
Unable to read or copy some of the files from mounted S3 but works fine with others

### ISSUE THREAD

**Issue by tongliang11** [s3fs-fuse/s3fs-fuse#2082]
#### Version of s3fs being used (`s3fs --version`)
V1.91

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`)
fuse Version: 2.9.2

#### Kernel information (`uname -r`)
5.10.130-118.517.amzn2.x86_64

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

### Details about issue
I mounted a S3 bucket to a local directory with the following command:
```
sudo s3fs bucket ~/s3/ -o passwd_file=$HOME/.aws_pass,nonempty,rw,allow_other,mp_umask=002,uid=$UID,gid=$UID -o url=http://s3.us-east-2.amazonaws.com,endpoint=us-east-2,use_path_request_style
```
then I'm able to ls files in the directory `~/s3/` and I can read **some** of the files but not others. For the files that I cannot read, I cannot either copy the file to directories on the machine with the command:
```
cp ~/s3/some_dir/filename ~
```
The error I got is:
```
cp: error reading ‘filename’: Input/output error
cp: failed to extend ‘/home/ec2-user/filename’: Input/output error
```
I'm also able to create new files on that directory, just not able to read or copy files. Any idea of why this is happening? thanks!

**Comment by skight-shen** [comment]
I encountered the same issue. How did you fix it?
