### ISSUE TITLE
URL Changes causing Transport Endpoint Disconnected Error.

### ISSUE THREAD

**Issue by DicklePick** [s3fs-fuse/s3fs-fuse#2092]
#### Version of s3fs being used (`s3fs --version`)
V1.89 (commit:unknown)

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`)
2.9.9

#### Kernel information (`uname -r`)
5.10.0-20-amd64

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)
Debian GNU/Linux 11 (bullseye)

#### How to run s3fs, if applicable

[] command line  
[X] /etc/fstab  

s3fs#ci-live-mountedfiles /ci-live-mountedfiles/ fuse _netdev,allow_other,passwd_file=/etc/.passwd-s3fs,umask=000,uid=33,gid=33,use_cache=/root/cache,dbglevel=debug,logfile=/var/log/s3fs.log 0 0

#### s3fs syslog messages (`grep s3fs /var/log/syslog`, `journalctl | grep s3fs`, or `s3fs outputs`)

[s3fs.log](https://github.com/s3fs-fuse/s3fs-fuse/files/10389716/s3fs.log)

### Details about issue
On a weekly basis, sometimes twice a week my file system gets unmounted and i receive an error that the transport endpoint is not connected. a server reboot resolves the issue until it happens again. For the most part it all works well for a decent amount of time.
I notice this alot in the logfile:
curl_util.cpp:url_to_host(327): url is https://s3-eu-central-1.amazonaws.com
curl.cpp:RequestPerform(2329): HTTP response code 404 was returned, returning ENOENT
AND
URL is https://s3-eu-central-1.amazonaws.com/ci-live-mountedfiles/documents/e3516443-f73d-43e5-9c58-bb20f10cdcd6/applications/4b29bbbe-4379-4458-83cb-29b369d415c5/CV_2022-12-05-095108_pdf.pdf_%24folder%24
curl_util.cpp:prepare_url(283): URL changed is https://ci-live-mountedfiles.s3-eu-central-1.amazonaws.com/documents/e3516443-f73d-43e5-9c58-bb20f10cdcd6/applications/4b29bbbe-4379-4458-83cb-29b369d415c5/CV_2022-12-05-095108_pdf.pdf_%24folder%24

**Comment by ggtakec** [comment]
@DicklePick 
Do you know what you are doing when this error occurs?
_That information may be needed to solve the problem._
And since v1.89 used by you is old, could you try to use latest version?
_We would love to know if the latest version would cause the same problem, because some bugs have been fixed up to it._
Thanks in advance for your help.

**Comment by DicklePick** [comment]
Thank i will look into updating the application. I was not aware there was an update as i am using the debian OS repo for the application which states that there is no update.
