### ISSUE TITLE
[Feature] Limit the size of maximum storage space.

### ISSUE THREAD

**Issue by fxzxmic** [s3fs-fuse/s3fs-fuse#2094]
To avoid high bills due to errors or mistakes, request to add a new feature to set and limit the size of maximum storage space.

**Comment by ggtakec** [comment]
@fxzxmic Thanks for the feature request.

As you said, it would be nice if there was a function to set the number of requests and the upper limit of storage capacity.
However, I think it is difficult to control them on the s3fs side.
For example, in the case of AWS, I think it would be easier to monitor the maximum number of requests and storage capacity in the settings on the AWS S3 side.
Currently, I think it is difficult to check the server side capacity (measure the size of all objects) on the client(s3fs) side.

Could you set the restrictions that you want to enforce be restricted on the server side?

**Comment by fxzxmic** [comment]
> @fxzxmic Thanks for the feature request.
> 
> As you said, it would be nice if there was a function to set the number of requests and the upper limit of storage capacity. However, I think it is difficult to control them on the s3fs side. For example, in the case of AWS, I think it would be easier to monitor the maximum number of requests and storage capacity in the settings on the AWS S3 side. Currently, I think it is difficult to check the server side capacity (measure the size of all objects) on the client(s3fs) side.
> 
> Could you set the restrictions that you want to enforce be restricted on the server side?

No, that's why I want to set restrictions on the client side.

**Comment by ggtakec** [comment]
As per the previous answer, I think it will be difficult to support this feature.

Example)
- If you put a limit on the total amount of objects in the bucket, when s3fs(client) starts, we have to get the size of all files(objects) in the bucket.  
Even if this were provided, it would still take a long time to process, depending on the objects in the bucket.
- If you want to limit the communication capacity and number of times after starting s3fs, you have to accumulate the communication capacity and number of times from the start of s3fs to the end.  
This might be possible to implement, but the behavior of s3fs when the limit is reached is difficult.(forced termination? / make all errors? etc.)

In above case, I'm sorry I think it is realistically difficult to impose restrictions from the client side at this time.

But, if your desire is to set a file size limit for a single uploaded file, you can consider implementing it or not.

**Comment by fxzxmic** [comment]
I understand. If the server cannot directly return the used storage capacity, the implementation on the client will sacrifice a lot of performance.
Let me close this issue.
