### ISSUE TITLE
latest version for aarch64 is s3fs-fuse-1.85-1.el7.aarch64

### ISSUE THREAD

**Issue by barabo** [s3fs-fuse/s3fs-fuse#2100]
#### Version of s3fs being used (`s3fs --version`)

```
s3fs --version
Amazon Simple Storage Service File System V1.85(commit:unknown) with OpenSSL
```

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`)

`fuse-2.9.2-11.amzn2.aarch64`

#### Kernel information (`uname -r`)

`5.10.162-141.675.amzn2.aarch64`

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)

```
cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

#### How to run s3fs, if applicable
```
# /etc/fstab
repo /www fuse.s3fs _netdev,allow_other,use_path_request_style,url=https://REDACTED.r2.cloudflarestorage.com,dbglevel=warn,nomixupload,use_cache=/cache,notsup_compat_dir,max_stat_cache_size=1000000,stat_cache_expire=3600,ensure_diskfree=500 0 0
```

#### s3fs syslog messages (`grep s3fs /var/log/syslog`, `journalctl | grep s3fs`, or `s3fs outputs`)

```
Jan 29 04:17:05 ip-172-31-15-38 s3fs[31517]: init v1.85(commit:unknown) with OpenSSL
Jan 29 04:17:06 ip-172-31-15-38 s3fs[31534]: s3fs.cpp:set_s3fs_log_level(296): change debug level from [CRT] to [WAN]
```

### Details about issue
I would like to use the `nomixupload` option on a graviton instance, but I can't seem to upgrade the s3fs-fuse package to the latest `1.91`.

**Comment by gaul** [comment]
Which distribution is this?  If it is Amazon Linux you should ask them to update their package.  Otherwise you have to compile your own.

**Comment by barabo** [comment]
I was able to compile and install the latest version from source like this:
```
yum install -y git automake gcc-c++ {fuse,curl,libxml2,openssl}-devel
git clone --depth 1 --branch v1.91 https://github.com/s3fs-fuse/s3fs-fuse.git
cd s3fs-fuse
./autogen.sh
./configure
make
make install
```
