### ISSUE TITLE
Request to add ALPINE to supported OS(Build/Test)

### ISSUE THREAD

**Issue by ggtakec** [s3fs-fuse/s3fs-fuse#2110]
### Correspond to ALPINE.
Support ALPINE(v3.17) in GithubActions(CI).
_I don't think there is much to fix._

The packages required for building and the contents that need to be modified are as follows:
- Requires OpenSSL 3.0 support  
already supported by master
- Dependent packages required for building  
automake, autoconf, util-linux-misc, fuse, fuse-dev, libxml2-dev, curl-dev
- autoconf  
autoconf is newer version, so we need to run autoupdate before running autogen.sh
- curl version  
Requires support for CURLOPTDEPRECATED warning
- etc

**Comment by adamqqqplay** [comment]
This is a great question, hopefully the support on ALPINE will improve. Thanks!

**Comment by ggtakec** [comment]
@adamqqqplay 
I have posted a PR code to build and test ALPINE with Github Actions.
That code and CI environment has been confirmed to work on ALPINE as well.

**Comment by adamqqqplay** [comment]
> @adamqqqplay I have posted a PR code to build and test ALPINE with Github Actions. That code and CI environment has been confirmed to work on ALPINE as well.

Thanks, I will test it soon.

**Comment by ggtakec** [comment]
This will be closed. If you still have problems, please reopen or post a new issue.
