### ISSUE TITLE
S3FS excepion  Input/output error 

### ISSUE THREAD

**Issue by fazalmf** [s3fs-fuse/s3fs-fuse#2121]
Getting exceptions while writing a new file using s3fs  when  **S3 Object lock & Governance enabled**
 
root@VMNAME test]# touch test1.txt
touch: failed to close 'test1.txt': Input/output error
[root@VMNAME test]# cd 
[root@VMNAME ~]# ls -l *.txt
-rw-r----- 1 root root 19 Feb 23 17:15 file.txt
[root@VMNAME ~]# cp file.txt  /backup/full_backup1/
cp: failed to close '/backup/full_backup1/file.txt': Input/output error

**however AWS S3 copy works good** 
root@VMNAME ~]# aws s3 cp file.txt s3://test/full_backup
upload: ./file.txt to test/full_backup

![image](https://user-images.githubusercontent.com/17859524/221240347-0636bd88-0f65-4699-a545-de40278fddea.png)

**Comment by fazalmf** [comment]
root@VMNAME~]# s3fs  --version
Amazon Simple Storage Service File System V1.91 (commit:unknown) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by fazalmf** [comment]
[root@VMNAME~]# cat /etc/os-release
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"

**Comment by fazalmf** [comment]
hello anyone working on this issue?

**Comment by fazalmf** [comment]
root@VMNAMEbackup]# s3fs  test2:/test1  /backup/full_backup1 -o umask=0007,uid=$(id -u xxxxx) -o allow_other -o x-amz-bypass-governance-retention:true
**fuse: unknown option `x-amz-bypass-governance-retention:true'**

**Comment by ggtakec** [comment]
@fazalmf 
We are not currently working on "Bypass Governance Retention".
In the future, I think that we will prepare a corresponding dedicated option, but I think it will be a little longer.

I haven't tried it yet, but maybe you can add the `x-amz-bypass-governance-retention: true` header by preparing the `ahbe_conf` option and a file to specify it, and it might work.

**Comment by knorr3** [comment]
Try enabling `enable_content_md5`. This solved the error for me.

From  https://manpages.ubuntu.com/manpages/bionic/man1/s3fs.1.html:

>    -o enable_content_md5 ( default is disable )
>              verifying uploaded data without multipart by content-md5 header.   Enable  to  send
>              "Content-MD5"  header  when  uploading a object without multipart posting.  If this
>              option is enabled, it has some influences on a performance of s3fs  when  uploading
>              small  object.   Because  s3fs  always checks MD5 when uploading large object, this
>              option does not affect on large object.

**Comment by fazalmf** [comment]
thanks @knorr3  your solution worked for me.. 

s3fs -f test:/test1  /backup/test1 -o umask=0007,uid=$(id -u fazal) -o allow_other  -o enable_content_md5

**Comment by fazalmf** [comment]
Thanks @ggtakec  & @knorr3   ,  appreciate your help.
