### ISSUE TITLE
Does this support flock?

### ISSUE THREAD

**Issue by hackersean** [s3fs-fuse/s3fs-fuse#2137]
### Additional Information
I would like to know if s3fs supports flock, which is used to select the master during multi-party mounting.

#### How to run s3fs, if applicable

[] command line  
[] /etc/fstab  

```
```

#### s3fs syslog messages (`grep s3fs /var/log/syslog`, `journalctl | grep s3fs`, or `s3fs outputs`)

```
```

**Comment by ggtakec** [comment]
@hackersean 
s3fs doesn't handle `flock`, but it is handled the default behavior of FUSE library.
Perhaps it can be used as an advisory lock for files on the same host.
(Note that the usual notice is that it is not available as a lock to other hosts.)
