### ISSUE TITLE
Chown results input/output error

### ISSUE THREAD

**Issue by hasnainhakim** [s3fs-fuse/s3fs-fuse#2138]
Hi All I have mounted a bucket to ubuntu 20.04 and I mount the my s3 bucket using the below command 

s3fs BucketName pathtobucketfolder  -o passwd_file=$HOME/.passwd-s3fs,nonempty,rw,allow_other,mp_umask=002,uid=1000,gid=1000 -o url=http://s3.us-east-1.amazonaws.com,endpoint=us-east-1,use_path_request_style

Now I am trying to change the permission on that folder but getting input error 

chown: changing ownership of '/home/test-user/bucket/': Input/output error,.

**Comment by ggtakec** [comment]
@hasnainhakim 
Please try specifying the logging options when starting s3fs.
For example, you can add `dbglevel=info`(and `curldbg`).
You may want to start s3fs in the foreground with `-f` as well.
Those logs will help to solve this problem.
Thanks in advance for your assistance.

**Comment by hasnainhakim** [comment]
> @hasnainhakim Please try specifying the logging options when starting s3fs. For example, you can add `dbglevel=info`(and `curldbg`). You may want to start s3fs in the foreground with `-f` as well. Those logs will help to solve this problem. Thanks in advance for your assistance.

Thankyou for your reply do I need to mount again ?

**Comment by ggtakec** [comment]
@hasnainhakim Thank you for your report.
If you are using code from the `master` branch, you may have been affected by the bug.
I posted a PR #2147 for fixing a bug which I detect about this Issue.
_(If you can, please retry new code after merging that PR.)_

I will close this issue, but if you still have a problem, please reopen this issue.
