### ISSUE TITLE
CURLE_COULDNT_RESOLVE_HOST error when using url option

### ISSUE THREAD

**Issue by ogg1e** [s3fs-fuse/s3fs-fuse#216]
I have nginx set up as a reverse proxy.  I'm able to use s3cmd to connect through the reverse proxy as well as via chrome browser. So I know it works.

If I try to use the url startup option:
./s3fs mybucket /tmp/bucket -o url=http://localhost:8080 -f

I always get :
```code
./s3fs mybucket ./bucket/ -o url=http://localhost:8080 -f
    set_moutpoint_attribute(4052): PROC(uid=501, gid=20) - MountPoint(uid=501, gid=20, mode=40755)
s3fs_init(3236): init
s3fs_check_service(3595): check services.
    CheckBucket(2537): check a bucket.
    insertV4Headers(1973): computing signature [GET] [/] [] []
    url_to_host(99): url is http://localhost:8080
RequestPerform(1692): ### CURLE_COULDNT_RESOLVE_HOST
    RequestPerform(1790): ### retrying...
    RemakeHandle(1453): Retry request. [type=5][url=http://mybucket.localhost:8080/][path=/]
RequestPerform(1692): ### CURLE_COULDNT_RESOLVE_HOST
    RequestPerform(1790): ### retrying...
    RemakeHandle(1453): Retry request. [type=5][url=http://mybucket.localhost:8080/][path=/]
RequestPerform(1692): ### CURLE_COULDNT_RESOLVE_HOST
    RequestPerform(1790): ### retrying...
    RemakeHandle(1453): Retry request. [type=5][url=http://mybucket.localhost:8080/][path=/]
RequestPerform(1797): ### giving up
CheckBucket(2575): Check bucket failed, S3 response: 
```

If I don't use the reverse proxy and leave out the url option, it connects to aws no problem. So why does it not like the url option?

I have:

127.0.0.1	localhost 

in my /etc/hosts file.

**Comment by kahing** [comment]
s3fs by default uses hostname based bucket request, which is why it tried to resolve mybucket.localhost and failed. Either put that in your /etc/hosts or use the use_path_request_style option to change to path based requests.

**Comment by kahing** [comment]
s3fs by default uses hostname based bucket request, which is why it tried to resolve mybucket.localhost and failed. Either put that in your /etc/hosts or use the use_path_request_style option to change to path based requests.

**Comment by ogg1e** [comment]
Ahh. I missed that. Thanks!
