### ISSUE TITLE
All files in S3 are zero bytes when seen in RHEL

### ISSUE THREAD

**Issue by bbyrd74** [s3fs-fuse/s3fs-fuse#2167]
#### Version of s3fs being used (`s3fs --version`)
Amazon Simple Storage Service File System V1.91 (commit:unknown) with OpenSSL

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`
2.9.7

#### Kernel information (`uname -r`)
4.18.0-425.19.2.el8_7.x86_64
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"

#### How to run s3fs, if applicable

FSTAB entry:
<BUCKET> /home/oracle/sftp fuse.s3fs rw,allow_other,nonempty,umask=0007,uid=1002,gid=1002,passwd_file=/etc/passwd-s3fs
where 1002 is the oracle user.  oracle also owns /home/oracle/sftp

#### s3fs syslog messages (`grep s3fs /var/log/syslog`, `journalctl | grep s3fs`, or `s3fs outputs`)
May 23 23:50:55 DTVTOT-LINUX-A s3fs[739872]: s3fs version 1.91(unknown) : s3fs -o rw,allow_other,nonempty,umask=0007,uid=1002,gid=1002,passwd_file=/etc/passwd-s3fs,dev,suid dcs33082nprd /home/oracle/sftp
May 23 23:50:55 DTVTOT-LINUX-A s3fs[739872]: Loaded mime information from /etc/mime.types
May 23 23:50:55 DTVTOT-LINUX-A s3fs[739873]: init v1.91(commit:unknown) with OpenSSL
May 23 23:50:55 DTVTOT-LINUX-A s3fs[739873]: s3fs.cpp:s3fs_check_service(3547): Failed to connect region 'us-east-1'(default), so retry to connect region 'us-west-2'.

### Details about issue
when CD'ing and LS'ing in the s3 buckets all the s3 folders seem to have usable permissions, owners, and groups.  but just files themselves always show as zero bytes with 0000 as permissions

**Comment by bbyrd74** [comment]
moar detailed logs:

May 24 00:05:34 DTVTOT-LINUX-A s3fs[740168]: [path=/]
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]: [path=/<REDACTED>2]
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2]
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2][bpath=][save=][sseckeypos=18446744073709551615]
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2] [] []
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      HTTP response code 404 was returned, returning ENOENT
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/]
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/][bpath=][save=][sseckeypos=18446744073709551615]
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/] [] []
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2_$folder$]
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2_$folder$][bpath=][save=][sseckeypos=18446744073709551615]
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2_%24folder%24
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2_%24folder%24
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2_$folder$] [] []
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      HTTP response code 404 was returned, returning ENOENT
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:  [path=/<REDACTED>2]
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2]
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>?delimiter=/&max-keys=2&prefix=<REDACTED>2/
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com?delimiter=/&max-keys=2&prefix=<REDACTED>2/
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      computing signature [GET] [/] [delimiter=/&max-keys=2&prefix=<REDACTED>2/] []
May 24 00:05:37 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      HTTP response code 200
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: s3fs_xml.cpp:get_base_exp(110): marker_xp->nodesetval is empty.
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      add stat cache entry[path=/<REDACTED>2/]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: [path=/<REDACTED>2][flags=0x18800]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: [path=/<REDACTED>2]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:  [path=/<REDACTED>2]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>?delimiter=/&max-keys=1000&prefix=<REDACTED>2/
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com?delimiter=/&max-keys=1000&prefix=<REDACTED>2/
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [GET] [/] [delimiter=/&max-keys=1000&prefix=<REDACTED>2/] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      HTTP response code 200
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:  [path=/<REDACTED>2/][list=0]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/crystalreports.txt][bpath=crystalreports.txt][save=/<REDACTED>2/crystalreports.txt][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/do-NOT-delete.txt][bpath=do-NOT-delete.txt][save=/<REDACTED>2/do-NOT-delete.txt][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [count=2]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/do-NOT-delete.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/crystalreports.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiPerform(172): thread terminated with non-zero return code: -1
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiPerform(172): thread terminated with non-zero return code: -1
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiRead(221): failed a request(403: https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt)
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/crystalreports.txt][bpath=crystalreports.txt][save=/<REDACTED>2/crystalreports.txt][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiRead(221): failed a request(403: https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt)
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/do-NOT-delete.txt][bpath=do-NOT-delete.txt][save=/<REDACTED>2/do-NOT-delete.txt][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/do-NOT-delete.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/crystalreports.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiPerform(172): thread terminated with non-zero return code: -1
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiPerform(172): thread terminated with non-zero return code: -1
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiRead(221): failed a request(403: https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt)
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/crystalreports.txt][bpath=crystalreports.txt][save=/<REDACTED>2/crystalreports.txt][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiRead(221): failed a request(403: https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt)
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/do-NOT-delete.txt][bpath=do-NOT-delete.txt][save=/<REDACTED>2/do-NOT-delete.txt][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/do-NOT-delete.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/crystalreports.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiPerform(172): thread terminated with non-zero return code: -1
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiPerform(172): thread terminated with non-zero return code: -1
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiRead(221): failed a request(403: https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt)
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/crystalreports.txt][bpath=crystalreports.txt][save=/<REDACTED>2/crystalreports.txt][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiRead(221): failed a request(403: https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt)
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/do-NOT-delete.txt][bpath=do-NOT-delete.txt][save=/<REDACTED>2/do-NOT-delete.txt][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/do-NOT-delete.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/crystalreports.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiPerform(172): thread terminated with non-zero return code: -1
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiPerform(172): thread terminated with non-zero return code: -1
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiRead(221): failed a request(403: https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt)
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/crystalreports.txt][bpath=crystalreports.txt][save=/<REDACTED>2/crystalreports.txt][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiRead(221): failed a request(403: https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt)
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/do-NOT-delete.txt][bpath=do-NOT-delete.txt][save=/<REDACTED>2/do-NOT-delete.txt][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/do-NOT-delete.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/crystalreports.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiPerform(172): thread terminated with non-zero return code: -1
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiPerform(172): thread terminated with non-zero return code: -1
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiRead(221): failed a request(403: https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt)
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/crystalreports.txt][bpath=crystalreports.txt][save=/<REDACTED>2/crystalreports.txt][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiRead(221): failed a request(403: https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt)
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/do-NOT-delete.txt][bpath=do-NOT-delete.txt][save=/<REDACTED>2/do-NOT-delete.txt][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/crystalreports.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/do-NOT-delete.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiPerform(172): thread terminated with non-zero return code: -1
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiPerform(172): thread terminated with non-zero return code: -1
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiRead(221): failed a request(403: https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt)
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: s3fs.cpp:multi_head_retry_callback(2550): Over retry count(5) limit(/<REDACTED>2/crystalreports.txt).
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl_multi.cpp:MultiRead(221): failed a request(403: https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt)
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: s3fs.cpp:readdir_multi_head(2628): error occurred in multi request(errno=-5), but continue...
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:    Could not find /<REDACTED>2/crystalreports.txt file in stat cache.
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:    Could not find /<REDACTED>2/do-NOT-delete.txt file in stat cache.
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: [path=/]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: [path=/<REDACTED>2/crystalreports.txt]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/crystalreports.txt]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/crystalreports.txt][bpath=][save=][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/crystalreports.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/crystalreports.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      add stat cache entry[path=/<REDACTED>2/crystalreports.txt]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: [path=/<REDACTED>2/do-NOT-delete.txt]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/do-NOT-delete.txt]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      [tpath=/<REDACTED>2/do-NOT-delete.txt][bpath=][save=][sseckeypos=18446744073709551615]
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL is https://s3-us-west-2.amazonaws.com/<REDACTED>/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      URL changed is https://<REDACTED>.s3-us-west-2.amazonaws.com/<REDACTED>2/do-NOT-delete.txt
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      computing signature [HEAD] [/<REDACTED>2/do-NOT-delete.txt] [] []
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      url is https://s3-us-west-2.amazonaws.com
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]: curl.cpp:RequestPerform(2371): HTTP response code 403, returning EPERM. Body Text:
May 24 00:05:38 DTVTOT-LINUX-A s3fs[740168]:      add stat cache entry[path=/<REDACTED>2/do-NOT-delete.txt]

**Comment by ggtakec** [comment]
@bbyrd74 
Was the file in question and the directory containing that file created via s3fs?
(Or is it something you created with some other s3 client (AWS console, aws command, etc?)

s3fs expects an object to have file stat information in its header.
If they don't exist, you'll see file permissions as `0000`, timestamps as `Jan 1 1970`(unixtime=0), and so on.

To avoid these, s3fs provides `compat_dir` and `complement_stat` options.
If possible, please give these options and try again.

But in your description it looks like the file size is `zero`, so maybe that's not all.
Do you have permission to access those objects in S3?

**Comment by bbyrd74** [comment]
ok it was a googy permission issue - but how can I implement those 2 options you specified?  I tried to add them in the fstab entry and they errored out.

**Comment by ggtakec** [comment]
Please check the version of your s3fs.
To see if your version supports these options, check the man page or run with the -help option.
As a sample, write the fstab entry as follows:
```
s3fs#<bucket> <mount point path> fuse allow_other,...<s3fs options>,compat_dir,complement_stat 0 0
```
This issue will be closed, but please reopen it if the problem persists.
Thanks in advance for your assitance.
