### ISSUE TITLE
[Question] Can /etc/passwd-s3fs have more then one credential?

### ISSUE THREAD

**Issue by yuriw** [s3fs-fuse/s3fs-fuse#2171]
#### Version of s3fs being used (`s3fs --version`)

s3fs --version
Amazon Simple Storage Service File System V1.86 (commit:unknown) with GnuTLS(gcrypt)

#### Kernel information (`uname -r`)

5.15.0-72-generic

#### How to run s3fs, if applicable

[] command line  
[] /etc/fstab  

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```
#s3fs mount
s3fs#delete1 /media/dreamhost/ fuse _netdev,allow_other,passwd_file=/etc/passwd-s3fs,url=https://objects-us-east-1.dream.io/,umask=000 0 0
```

#### s3fs syslog messages (`grep s3fs /var/log/syslog`, `journalctl | grep s3fs`, or `s3fs outputs`)

```
```

### Details about issue

I'd like to mount three more buckets and am unclear what the best way to handle credentials
I have one line in /etc/passwd-s3fs

TIA

**Comment by gaul** [comment]
Can you just add three more lines, each with a different bucket, mountpoint, and `passwd_file`?  Another approach is to use the profile option.

**Comment by yuriw** [comment]
@gaul Sure I can and in fact, that's what I did :)

I was wondering what's the most recommended way.
Can you elaborate on `profile option` pls?

**Comment by ggtakec** [comment]
@yuriw 
s3fs can use the credential file(${HOME}/.aws/credentials) used by `aws cli` as credentials.
This file can contain multiple profile information, and the profile(user) can be specified with the `profile` option(`profile=<profile name>`) of s3fs.
Any profile can be created with `aws configure --profile <profile name>`. (This is a text file, so edit it however you like)
s3fs only uses the `AWS Access Key ID(aws_access_key_id)` and `AWS Secret Access Key(aws_secret_access_key)` fields.

Please try it.
_This issue will be closed, but please reopen it if you still have problems._
