### ISSUE TITLE
v1.92 mount issue , folder path appending with additional / 

### ISSUE THREAD

**Issue by sathishstorm** [s3fs-fuse/s3fs-fuse#2186]
#### Version of s3fs being used (`s3fs --version`)

1.92

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`)

Version     : 2.9.2

#### Kernel information (`uname -r`)

5.4.241-150.347.amzn2.x86_64

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

#### How to run s3fs, if applicable

[] command line  
[] /etc/fstab  

 s3fs bucketname:/folderpath /mountpath -o allow_other,use_cache=/tmp,connect_timeout=10,nonempty,umask=0022 

#### s3fs syslog messages (`grep s3fs /var/log/syslog`, `journalctl | grep s3fs`, or `s3fs outputs`)

```
```

2023-06-07T15:35:54.258Z [ERR] curl.cpp:CheckBucket(3741): Check bucket failed, S3 response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>folderpath/</Key><RequestId>********</RequestId><HostId>**************************************</HostId></Error>
2023-06-07T15:35:54.258Z [CRT] s3fs.cpp:s3fs_check_service(4443): Failed to check bucket and directory for mount point : Bucket or directory(/folderpath) not found(host=https://s3.amazonaws.com) - You may need to specify the compat_dir option.
2023-06-07T15:35:54.258Z [ERR] s3fs.cpp:s3fs_exit_fuseloop(4200): Exiting FUSE event loop due to errors

### Details about issue

additional / is added to the folder path so mount failing with error key not found. 
after upgrading to v1.92 this error comes. when i downgraded to v1.91 it is working fine.

**Comment by sathishstorm** [comment]
after checking the difference between the versions 1.91 and 1.92 looks like we need to use **compat_dir** parameter to resolve this issue which is added newly in 1.92

s3fs bucketname:/folderpath /mountpath -o allow_other,use_cache=/tmp,connect_timeout=10,nonempty,umask=0022,**compat_dir**

**Comment by gaul** [comment]
Could you be more specific about what the directory layout looks like, e.g., AWS CLI --recursive output?  You should not need this flag for most buckets.

**Comment by ggtakec** [comment]
@sathishstorm Sorry to make you spend time to confirm.
As you've noticed, from v1.92 there are times when you should give `compat_dir` in `bucket/folder` checks.
It is required for folders created by clients other than s3fs.

For reference, when this error occurs, v1.92 will output the following to the log:
```
Failed to check bucket and directory for mount point : Bucket or directory(/xxxxxxx) not found(host=https://xxxx.amazonaws.com) - You may need to specify the compat_dir option.
```
Thanks for your kindness.
