### ISSUE TITLE
Unmounting segfault

### ISSUE THREAD

**Issue by arbrebinaire** [s3fs-fuse/s3fs-fuse#2188]
#### Version of s3fs being used (`s3fs --version`)

V1.92 (commit:unknown) with OpenSSL

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`)

Version     : 2.9.7
Packager    : infrastructure@rockylinux.org
Vendor      : Rocky

#### Kernel information (`uname -r`)

4.18.0-425.19.2.el8_7.x86_64

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)

NAME="Rocky Linux"
VERSION="8.8 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.8 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"

#### How to run s3fs, if applicable

```
umount  "/mnt/some_mountpoint"
```

#### s3fs syslog messages (`grep s3fs /var/log/syslog`, `journalctl | grep s3fs`, or `s3fs outputs`)

```
[Wed Jun 14 21:24:40 2023] s3fs[375044]: segfault at 7f3aa13c89d0 ip 00007f3aa4fd5550 sp 00007fff47292b90 error 4 in libpthread-2.28.so[7f3aa4fcc000+1b000]
[Wed Jun 14 21:24:40 2023] Code: 48 89 7c 24 f8 64 48 8b 04 25 10 00 00 00 f0 48 0f b1 54 24 f8 c3 0f 1f 40 00 f3 0f 1e fa 41 56 41 55 41 54 55 53 48 83 ec 40 <44> 8b 87 d0 02 00 00 64 48 8b 04 25 28 00 00 00 48 89 44 24 38 31

```

### Details about issue

The segfault happens whenever a mointpoint is unmounted.  The mountpoint is properly unmounted.

**Comment by ryanmichaelsmith** [comment]
I'm not positive it's related, but I'm having a similar issue with v1.92. Listing the contents of the root of the mount point fails and logs a segfault in syslog. I reran under gdb looking at the curl debug messages and AWS returns a 404 which seems to result in s3fs signaling a crash.

Issue started with v1.92, didn't occur with v1.91.

**Comment by VVoidV** [comment]
@arbrebinaire  what is your commandline para for s3fs?  I found that using the "streamupload" option can cause a segfault when unmounting.

**Comment by arbrebinaire** [comment]
> @arbrebinaire what is your commandline para for s3fs? I found that using the "streamupload" option can cause a segfault when unmounting.

Here is the line in fstab:
`s3fs#leaf-03       /mnt/leaf-03       fuse    _netdev,allow_other,use_path_request_style,url=https://node1.mys3provider.com 0 0`

**Comment by ggtakec** [comment]
@VVoidV Thanks foryour kindness.

@arbrebinaire @ryanmichaelsmith 
I merged the #2204 PR, then could you try latest code(current master branch)?

**Comment by arbrebinaire** [comment]
Thanks!  I'll have to wait until your fix is available through RockyOS which could take a little while I suppose. I'll be happy to report when this happens.

**Comment by gaul** [comment]
Please reopen if symptoms persist.
