### ISSUE TITLE
Delay in updating file's modified timestamp on EBS

### ISSUE THREAD

**Issue by nitishtw** [s3fs-fuse/s3fs-fuse#2189]
We have mounted an s3 bucket through `s3fs` onto an EC2 machine which is being used for an SFTP use-case. We have lately observed that if the same file is re-uploaded to s3 bucket then it takes around 5-10 mins time to reflect the updated modification time inside EC2 box.

Ex - If a file `cost.csv` is re-uploaded at 3:40 PM in s3 bucket then if I run `ls -lah` inside EC2 box; the mtime of file will not be modified for the first 5-10 mins; and it will not reflect 3:40 PM as mtime of the file.

Initially we had a hunch that it was happening due to s3 eventual consistency model; but we also have one AWS managed transfer family setup which also use s3 as backend; and we haven't seen any use-case or behaviour like this.

AWS support also confirmed that this might be an issue with s3fs and not with s3! Have we seen such issues in past or is it a known issue? and is there any suggested fix for this?

**Comment by gaul** [comment]
s3fs caches stat entries for 900 seconds (15 minutes) by default.  You can control this via `-o stat_cache_expire`
