### ISSUE TITLE
S3 version enabled receives two versions for new objects. First 0 bytes, second the actual data

### ISSUE THREAD

**Issue by james-crocker** [s3fs-fuse/s3fs-fuse#2210]
#### Version of s3fs being used (`s3fs --version`)
V1.86 (commit:unknown)

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`)
2.9.9-3

#### Kernel information (`uname -r`)
5.15.0-1039-aws

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

#### How to run s3fs, if applicable

[] command line  
[x] /etc/fstab  
hank-ai-clients:/abc.com     /sftp-client-push/abs-kc.com/aws-s3     fuse.s3fs       _netdev,allow_other,use_cache=/tmp,passwd_file=/etc/s3fs-passwd/client-abc.com,umask=002,uid=1004,gid=1001   0 0

#### s3fs syslog messages (`grep s3fs /var/log/syslog`, `journalctl | grep s3fs`, or `s3fs outputs`)
Not in debug mode. journalctl --since today | grep s3fs returned null result.

### Details about issue
The s3fs mounted S3 bucket is a versioned bucket. When copying a new, non zero byte, non-existent object (file) to the mount point an object is successfully created in the bucket. However, unexpectedly, two versions are created. The first version is a 0 byte object and the second (most recent) is the non-zero byte version of the file.

Our expectation was that a single, non-zero byte version of the file(object) would be created for an object which had no previous existence in the versioned S3 bucket.

**Comment by gaul** [comment]
Fixed in the latest version.
