### ISSUE TITLE
test_cache_file_stat fails with `-o use_cache`

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#2216]
test_cache_file_stat:

```
first line(cache file stat) is different: "52025:0" != "52025:26214400"
test_cache_file_stat failed
```

test_list:

```
Expected 2 file but got 3
test_list failed
```

I assume the latter is related to the recent `nocompat_dir` fix but I checked these more carefully in #2215.  Found via `ALL_TESTS=1 make -C test/ check`.

**Comment by gaul** [comment]
This still fails even with d0a944fcaaaef4ed20238b02fd37d9ca9346997e.

**Comment by ggtakec** [comment]
@gaul I have not been able to reproduce this. 
_(ThreadSanitizer errors are summarized in #2220.)_
Are there any special steps or environment to reproduce?

**Comment by gaul** [comment]
I see this symptom:

```
first line(cache file stat) is different: "55518:0" != "55518:26214400"
test_cache_file_stat failed
FAIL: test_cache_file_stat
```

I think `test_list` only fails because the other test does not clean up.

**Comment by ggtakec** [comment]
@gaul Thanks, but I haven't been able to reproduce it yet.
Please let me know which OS (used for CI test) this error occurs.
_Maybe there are conditions different from mine and Github Actions environment._

**Comment by ggtakec** [comment]
I tested it with the `use_cache` option, but I couldn't reproduce it.
Using Github Actions(only some test cases), I tried it on all OSs targeted by CI, and it also passed.
_(The branch will be deleted soon, but here's the log of the GithubActions I just ran: https://github.com/ggtakec/s3fs-fuse/actions/runs/5588207318)_

**Comment by gaul** [comment]
Sorry I think this is a few symptoms but the primary one is something specific about my SELinux config on Fedora 38.  Closing this.
