### ISSUE TITLE
[Question] Determining if s3fs has completed syncing files to S3

### ISSUE THREAD

**Issue by ju2wheels** [s3fs-fuse/s3fs-fuse#2233]
Hi, im trying to find more technical information on how to figure out if s3fs is done syncing any file changes to S3.

For my usage, im mounting a bucket to a folder, making some changes to the contents of that folder and then i want to unmount the s3fs mount and shutdown my instance once im sure s3fs is done syncing.

The only two methods i can think of coming up with for doing this is a combination of the following:

1. Check the cache directory (which I have configured to be /tmp/s3fs) for what appear to be temporary files for tracking the sync (they may be actual duplicates or sharded chunks of the files being uploaded but i am not sure) and assume its safe to unmount if none exist. I saw files of the format `/tmp/s3fs/.<bucket-name>.mirror/<random file name>.tmp` .
2. Attempt fusermount -u in a loop until it succeeds after doing the above check and waiting for all temp files to be gone (since this should fail to unmount with device/resource busy if theres any open file handles left).

This seems to be the best way i could come up with given that i cany find documentation on how to check the sync status unless i missed it somewhere, but i still feel like this potentially a sync/unmount race condition waiting to happen even if i combine the two approaches above.

Are there any other options here?

**Comment by gaul** [comment]
s3fs does not asynchronously sync files.  During a call to `fsync` or `close`, the object is synchronously uploaded to S3.  Thus if the calls succeed then the file exists in S3.
