### ISSUE TITLE
Only when refreshing the directory, the meta information(timestamp) of files in that directory will be updated

### ISSUE THREAD

**Issue by jestiny0** [s3fs-fuse/s3fs-fuse#2264]
#### Version of s3fs being used (`s3fs --version`)

V1.86

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`)

2.9.9-3

#### Kernel information (`uname -r`)

5.15.0-1040-aws

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)

NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

#### How to run s3fs, if applicable
`mkdir /models-s3 && echo xxx > /passwd-s3fs && chmod 600 /passwd-s3fs && 
            s3fs model /models-s3 -o passwd_file=/passwd-s3fs`

### Details about issue

<img width="1110" alt="image" src="https://github.com/s3fs-fuse/s3fs-fuse/assets/105039245/130ed2bd-3248-4bfe-9ba6-6eba3893c192">

I have a Java program that checks the timestamp and size of a certain file to determine whether to reload the file. The core code is as follows:
```
File f = new File("vocab");
        long lastModify = f.lastModified();
        long size = f.length();
        System.out.println(lastModify);
        System.out.println(size);
```

Problem Reproduction:
1.  Run the Java program and find that the file's timestamp is 1.
2. Use the "ls" command on the file in the directory and find that the timestamp is 1 (it should actually be 2).
3. Use the "ls" command on the directory and find that the timestamp becomes 2.
4. Use the "ls" command on the file and find that the timestamp also becomes 2.
5. Run the Java program again, and the timestamp is successfully changed to 2

**Comment by gaul** [comment]
1.86 has no default time limit for caching metadata.  If you set `-o stat_cache_expire=900` then it will only be cached for 15 minutes.  1.89 and later set this value by default.

**Comment by jestiny0** [comment]
Fixed! Thanks for your reply
