### ISSUE TITLE
Does s3fuse copies uid, gid and file permission of object from s3bucket in mounted directory

### ISSUE THREAD

**Issue by Tulsishah** [s3fs-fuse/s3fs-fuse#2266]
Hi,

I have created a file in the local system and assigned some file permission(e.g., 644). I have uploaded this file on s3bucket. Now if I mount the s3bucket with s3fuse, will it copy this file permission and, moreover uid, gid ?

Thanks,
Tulsi Shah

**Comment by gaul** [comment]
Yes.  Please reopen this issue if your testing reveals otherwise.
