### ISSUE TITLE
s3fs should include git commit hash in --version

### ISSUE THREAD

**Issue by andrewgaul** [s3fs-fuse/s3fs-fuse#228]
This would help debug issues when people have older pre-release versions of s3fs.

**Comment by ggtakec** [comment]
It is possible to add commit hash string as debugging message during initializing.
And in print version.
I will add it, please wait for a while.
Regards,

**Comment by ggtakec** [comment]
s3fs can print version with commit short hash.
(and debug message, in /var/log/messages)
