### ISSUE TITLE
Use s3fs version 1.92 to generate a large number of hidden ".fs-detect" files in the mount root directory. What does this do?

### ISSUE THREAD

**Issue by huihuikj** [s3fs-fuse/s3fs-fuse#2290]
### Use s3fs version 1.92 to generate a large number of hidden ".fs-detect" files in the mount root directory. What does this do?
Additional Information
Version of s3fs being used
V1.92

Version of fuse being used
2.9.2

Kernel information
3.10.0-862.el7.x86_64

How to run s3fs, if applicable
```shell
$ /usr/bin/s3fs bucketname /mnt/mys3fs -o compat_dir -o use_wtf8 -o listobjectsv2 -o dbglevel=info -f -o curldbg  -o passwd_file=/home/huihui/.password-s3fs -o url=https://xxx.xxx.com:443 -o use_path_request_style -o allow_other -o nonempty  
```
```
$ ls -a
.fs-detect.xxxxx      .....

$ cat .fs-detect.xxxxx
FS-RW2023-08-22 15:55:33

$ cat s3log
[CURL DBG] > PUT /bucketname/.fs-detect.xxxxx HTTP/1.1
[INF] curl.cpp:insertV4headers(2891):computing signature [PUT]
```

**Comment by gaul** [comment]
s3fs does not generate these files -- some other process on your system is doing this.  If you compile from master then ee49ca4abfce5dc711b02a2c0b71658c9fc996d2 should tell you which pid is responsible.  Can you try this and tell us what is creating these?

**Comment by huihuikj** [comment]
Sorry, after our investigation, we found that it was caused by the monitoring written by the business side.
