### ISSUE TITLE
I can't mount an s3 bucket (token session)

### ISSUE THREAD

**Issue by Titouanwallahi** [s3fs-fuse/s3fs-fuse#2338]
#### Version of s3fs being used
Amazon Simple Storage Service File System V1.90 (commit:unknown) with GnuTLS(gcrypt)

### Details about issue
I'm on ubuntu and i'm trying to mount an s3 bucket with this command:
`sudo s3fs <bucket> /home/<name>/buckets3/ -o passwd_file=aws -o url=https://s3.amazonaws.com -o use_session_token -o endpoint=eu-west-1 -f`
With the keys specified in the aws file, and the session token + keys in /.aws/credentials
But I get these error messages 
`2023-10-04T14:07:30.632Z [INF] curl.cpp:InitMimeType(434): Loaded mime information from /etc/mime.types`
`2023-10-04T14:07:30.633Z [INF] s3fs.cpp:s3fs_init(3382): init v1.90(commit:unknown) with GnuTLS(gcrypt)`
`2023-10-04T14:07:30.737Z [CRT] s3fs.cpp:s3fs_check_service(3575): Failed to connect by sigv4, so retry to connect by signature version 2.`
`2023-10-04T14:07:30.760Z [CRT] s3fs.cpp:s3fs_check_service(3590): invalid credentials(host=https://s3.amazonaws.com) - result of checking service`.`
Any ideas why ?

**Comment by rohitsanj** [comment]
Hey, we're seeing a similar error. Were you able to figure out what the fix was?

**Comment by braxtoon-hash** [comment]
> Hey @braxtoon-hash, we're seeing a similar error. Were you able to figure out what the fix was?

Hey, sorry to reply so late and no I haven't found a viable solution, only sometimes it works sometimes it doesn't, I have no way of knowing why, I've tried lots of things. What seems to work best is to use IAM profiles with -o profile=name, with the keys in .aws/credentials.
If you've found a solution I'd be glad to know it.
Here is the command I use : 
`sudo s3fs bucket /home/XXX -o profile=YYY -o url="https://s3-eu-west-1.amazonaws.com" -o endpoint=eu-west-1 -o use_sse`
