### ISSUE TITLE
can s3fs show the real capacity of bucket

### ISSUE THREAD

**Issue by JayjieL** [s3fs-fuse/s3fs-fuse#2359]
hi,
in my case, df -h show that the mounted bucket has 64P capacity, it's abnormal.
i wonder whether s3fs can show the real capacity of bucket.
hope for your reply, thanks.

![image](https://github.com/s3fs-fuse/s3fs-fuse/assets/39478235/d7f8eac1-8996-48ca-8584-43e9d32dccc4)

**Comment by JayjieL** [comment]
What is the meaning of 64P?

**Comment by gaul** [comment]
No s3fs cannot do this since this S3 does not provide an API for capacity.  The alternative would require listing every object in the bucket, potentially an expensive operation.  64P refers to 64 petabytes which is the largest possible value.

**Comment by OttaviaB** [comment]
Hello,
`s3fs` cannot compute the size for you, but if you already know the size by some other means you can set it by hand when mounting the bucket with the option `bucket_size`, available in version 1.92 and above.
This will then show up correctly in `df -h`.
