### ISSUE TITLE
Update Google Code page to point to GitHub

### ISSUE THREAD

**Issue by andrewgaul** [s3fs-fuse/s3fs-fuse#236]
https://code.google.com/p/s3fs/ should include a pointer to https://github.com/s3fs-fuse/s3fs-fuse/ before Google Code goes read-only on 25 August.

**Comment by rrizun** [comment]
I updated the google code page to point to https://github.com/s3fs-fuse/s3fs-fuse

**Comment by andrewgaul** [comment]
Thanks @rrizun!

**Comment by ggtakec** [comment]
Thanks all.
