### ISSUE TITLE
Building on MacOs

### ISSUE THREAD

**Issue by kevindiffily** [s3fs-fuse/s3fs-fuse#2403]
The instructions to manually build refer to a non-existent file ./configure

#### How to run s3fs, if applicable

[] command line  
[] /etc/fstab  

```
```
#### s3fs syslog messages (`grep s3fs /var/log/syslog`, `journalctl | grep s3fs`, or `s3fs outputs`)

```
```

**Comment by ggtakec** [comment]
Please run `autogen.sh` first, it will create a configure file.
These steps can be found by browsing `.github/workflows/ci.yml`.

This issue will be closed, but if you still have problems, please reopen this issue or create a new one.
