### ISSUE TITLE
permission denied whatever ownership is set while mounting

### ISSUE THREAD

**Issue by stupidloud** [s3fs-fuse/s3fs-fuse#2414]
The OS is debian 11
PHP is installed from APT with the version 7.4, running as www-data
s3fs mount command under root is
`s3fs gallery e2s3 -o passwd_file=${HOME}/.passwd-s3fs -o url=https://uvw.xyz.idrivee2-4.com/ -o use_path_request_style,gid=33,uid=33`
the number 33 is both gid and uid of www-data
I also have the mount point moved into a place where maked sure by php-fpm has access with its function is_readable()
everthing looks fine
`drwx------  1 www-data www-data    0 Jan  1  1970 e2s3`
but access premission is always denied.

**Comment by adamqqqplay** [comment]
Maybe you can try `-o allow_other` or `-o umask=0000` to solve your problem.

**Comment by stupidloud** [comment]
> Maybe you can try `-o allow_other` or `-o umask=0000` to solve your problem.

It works. Thank you.
