### ISSUE TITLE
Can not read S3 public_bucket

### ISSUE THREAD

**Issue by akizou** [s3fs-fuse/s3fs-fuse#242]
Hello

I want to mount S3 public_bucket "landsat-pds"

See. Landsat on AWS
https://aws.amazon.com/jp/public-data-sets/landsat/

mount sucess, but can not read.

# /usr/local/bin/s3fs landsat-pds /s3 -o public_bucket=1,ro,allow_other 

$ ls -l /s3
d---------. 1 root root       0 Jan  1  1970 L8
----------. 1 root root 4309685 Jul 29 20:28 L8.reprocessed.2015.txt
----------. 1 root root   23764 Jan 28  2015 index.html
----------. 1 root root    7640 Aug 18 08:54 landsat-pds_stats
----------. 1 root root      25 Apr 14 17:43 robots.txt
----------. 1 root root      38 Aug 18 07:39 run_info.json
d---------. 1 root root       0 Jan  8  2015 runs
----------. 1 root root 9104504 Aug 18 07:39 scene_list.gz
d---------. 1 root root       0 Jan 13  2015 tarq
d---------. 1 root root       0 Jan  1  1970 tarq_corrupt
d---------. 1 root root       0 Jan  6  2015 test

$ cat  /s3/index.html
cat: /s3/index.html: Permission denied

$ ls -l /s3/L8
ls: cannot open directory /s3/L8: Operation not permitted

Can you mount and read  "landsat-pds" on your EC2 instance?

**Comment by kahing** [comment]
can you try to pass -oumask=0022 to s3fs?

**Comment by akizou** [comment]
# s3fs landsat-pds /s3 -o public_bucket=1,ro,allow_other,umask=0022 

$ time ls -lF /s3
-rwxr-xr-x. 1 root root   23764 Jan 28  2015 index.html*
drwxr-xr-x. 1 root root       0 Jan  1  1970 L8/

real        0m2.044s
user        0m0.001s
sys         0m0.001s

work fine. thank you.

**Comment by kahing** [comment]
Could you close this ticket then? I do agree there should be a better default umask for the cases when the files were not written through s3fs, could you file another ticket for that?
