### ISSUE TITLE
Providing more details in docs

### ISSUE THREAD

**Issue by tuxpeople** [s3fs-fuse/s3fs-fuse#2421]
Hi

I'm stumbled upon this:
https://github.com/s3fs-fuse/s3fs-fuse/blob/70a30d6e26a5dfd07a00cf79ce1196079e5ab11a/COMPILATION.md?plain=1#L9-L23

Would it be possible to differentiate between build dependencies and runtime dependencies?

Thanks!

**Comment by ggtakec** [comment]
@tuxpeople I'm sorry for my late replying.
Could you tell me specifically what you stumbled on?

**Comment by gaul** [comment]
I believe he wants to separate build dependencies:

* automake
* gcc-c++
* make
* pkg-config (or your OS equivalent)

From runtime dependencies:

* fuse >= 2.8.4
* libcurl
* libxml2
* openssl
* mime.types (the package providing depends on the OS)
	* s3fs tries to detect `/etc/mime.types` as default regardless of the OS
	* Else s3fs tries to detect `/etc/apache2/mime.types` if OS is macOS
	* s3fs exits with an error if these files are not exist
	* Alternatively, you can set mime.types file path with `mime` option without detecting these default files

Agree that this would be a slight improvement.  It would also be good to clarify that OpenSSL is not required and that either GnuTLS or NSS can be used.

**Comment by tuxpeople** [comment]
> @tuxpeople I'm sorry for my late replying. 

No worries, I've got the same problem with issues people open in my repos ;-)

> I believe he wants to separate build dependencies:

Yes. Unfortunately, I'm unable to remember why exactly I asked for this. I think I've tried to create a container image with it, and my goal was to have a small footprint using a multi-stage build.

Anyway, the PR looks good to me, thanks a lot!

**Comment by ggtakec** [comment]
@tuxpeople Thank you for the reply.
I merged PR#2445.
If there are any parts that are still unclear, please let us know.
(This PR will be closed.)
