### ISSUE TITLE
 when i use https,Which version of libcurl should be used?

### ISSUE THREAD

**Issue by loongyiyao** [s3fs-fuse/s3fs-fuse#2440]
Additional Information
Version of s3fs being used (s3fs --version)
V1.89

Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse or dpkg -s fuse)
Kernel information (uname -r)
5.10.134-13.1.zncgsl6.x86_64

GNU/Linux Distribution, if applicable (cat /etc/os-release)
How to run s3fs, if applicable
/usr/bin/s3fs sttest /dev/mount1 -o url=https://xx.xx.xx.xx:xx -o endpoint=cn-east-1 -o sigv2 -o passwd_file=/home/.passwd-s3fs -o use_path_request_style -o allow_other -o umask=0 -o use_cache=/dev/cache1 -o del_cache -o ensure_diskfree=-4096 -o enable_noobj_cache -o parallel_count=20 -o multipart_size=52 -o dbglevel=warn

**Comment by gaul** [comment]
Please test with the latest version 1.94 and reopen if your symptoms persist.
