### ISSUE TITLE
Passwd-s3fs files for different mounts if /etc/fstab

### ISSUE THREAD

**Issue by alexeyantropov** [s3fs-fuse/s3fs-fuse#2453]
Hello, there's a feature request. 

It would be useful to have a mount option to choose a passwd-s3fs file instead of the only one /etc/passwd-s3fs for different mounts in /etc/fstab.

Smth like the line below:

```
mybucket /path/to/mountpoint fuse.s3fs <...>,url=https://url.to.s3/,PASSWDFILE=/SOME/PATH 0 0
```

#### Version of s3fs being used (`s3fs --version`)
```
# s3fs --version
Amazon Simple Storage Service File System V1.94 (commit:unknown) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by icassassin** [comment]
I've been using the 'passwd_file' option and as far as I can tell it does exactly what you're looking for.

One of my fstab entries:
```
[MOUNT_NAME] /mnt/[MOUNT_NAME] fuse.s3fs _netdev,allow_other,umask=0077,url=https://[S3_SERVER],passwd_file=[PASSWDFILE_S3FS],use_sse=custom:[S3FS_KEY],bucket_size=1TiB,nocopyapi 0 0
```

**Comment by alexeyantropov** [comment]
> I've been using the 'passwd_file' option and as far as I can tell it does exactly what you're looking for.
> 
> One of my fstab entries:
> 
> ```
> [MOUNT_NAME] /mnt/[MOUNT_NAME] fuse.s3fs _netdev,allow_other,umask=0077,url=https://[S3_SERVER],passwd_file=[PASSWDFILE_S3FS],use_sse=custom:[S3FS_KEY],bucket_size=1TiB,nocopyapi 0 0
> ```

The option isn't documented for fstab cases (only for mounts thought cli). Thx you, I'll try it.
