### ISSUE TITLE
running git commit in a s3fs mount error

### ISSUE THREAD

**Issue by zhujintao** [s3fs-fuse/s3fs-fuse#2512]
`git commit -a -m "update"`
error: non-monotonic index .git/objects/pack/._pack-50f486edacd086d8cc2259d1aa811a006d8549d0.idx
error: non-monotonic index .git/objects/pack/._pack-50f486edacd086d8cc2259d1aa811a006d8549d0.idx
error: non-monotonic index .git/objects/pack/._pack-50f486edacd086d8cc2259d1aa811a006d8549d0.idx
error: non-monotonic index .git/objects/pack/._pack-50f486edacd086d8cc2259d1aa811a006d8549d0.idx
error: non-monotonic index .git/objects/pack/._pack-50f486edacd086d8cc2259d1aa811a006d8549d0.idx
fatal: sha1 file '/s3disk/zkitx/.git/index.lock' write error: Device not configured

**Comment by gaul** [comment]
Are you running `git commit` in a s3fs mount?  Does this reproduce using any specific git repo that I can access?

**Comment by zhujintao** [comment]
git clone repository in s3fs mount, modify files and git commit error

**Comment by ggtakec** [comment]
@zhujintao 
I have tried clone/change sources/add files/commit/push of the git repository using my own environment.
However, it works fine and I cannot reproduce this problem.

Please tell us your s3fs startup command line(or fstab).
Also, could you collect logs by specifying `dbglevel(=info)`(and `curldbg` if necessary) options?
I think you can find logs when an error occurs, so please share that information.

**Comment by zhujintao** [comment]
@ggtakec 
tks! I remount it using command script it will work normally.

use `launchd` mount problem, for macOS

 `launchctl load ~/Library/LaunchAgents/mydisk-sync.s3fs.plist`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Keepalive</key>
		<true/>
		<key>Label</key>
		<string>mydisk-sync.s3fs</string>
		<key>Program</key>
		<string>/usr/local/bin/s3fs</string>
		<key>ProgramArguments</key>
		<array>
			<string>/usr/local/bin/s3fs</string>
			<string>mydisk-sync</string>
			<string>/Users/xxxx/mydisk-sync</string>
			<string>-o</string>
			<string>kernel_cache</string>
			<string>-o</string>
			<string>endpoint=xxxxxxxxx</string>
			<string>-o</string>
			<string>passwd_file=/Users/xxxx/.passwd-s3fs</string>
			<string>-o</string>
			<string>url=https://xxxxxxxxxxx</string>
			<string>-f</string>
			<string>-o</string>
			<string>allow_other</string>
			<string>-o</string>
			<string>compat_dir</string>
			<string>-o</string>
			<string>dbglevel=debug</string>
			<string>-o</string>
			<string>curldbg</string>
			<string>-o</string>
			<string>volname=MyDisk-S3</string>
		</array>
		<key>RunAtLoad</key>
		<true/>
		<key>StandardErrorPath</key>
		<string>/tmp/mydisk-sync.s3fs-err.log</string>
		<key>StandardOutPath</key>
		<string>/tmp/mydisk-sync.s3fs-out.log</string>
	</dict>
</plist>
```

**Comment by ggtakec** [comment]
@zhujintao Thanks for your reply.
Does this issue occur only with s3fs launched via launchd on macOS?
You say that the error occurs with the `git commit` command, but do other operations such as reading and writing to files and directory listings work normally?
In any case, I think we will need to check the logs output by dbglevel and curldbg to identify the cause.

**Comment by zhujintao** [comment]
Now, s3fs launched normal,  only upgrade macOS  15 Beta 7.  Thank!
