### ISSUE TITLE
-bash: s3fs: command not found

### ISSUE THREAD

**Issue by alebeta90** [s3fs-fuse/s3fs-fuse#255]
Hello friends! i already have a fresh installation of CentOS7 and i install s3fs browser in the way that you explain. When i use my user to run de s3fs command its ok. But when i try to run like root i have this message

-bash: s3fs: command not found

Thanks for the support!
All the best.

**Comment by andrewgaul** [comment]
`make install` puts the binary in `/usr/local/bin` by default.  Try running the full path, e.g., `/usr/local/bin/s3fs`.

**Comment by okram999** [comment]
@alebeta90 : pls close if the issue is resolved

**Comment by alebeta** [comment]
Yes the problem was solved... only restart the server and works.

Thanks a lot!

**Comment by okram999** [comment]
@alebeta90 @alebeta - go ahead with the final ritual to close the issue. Too many open issues which have been 'actually' closed gives a negative feel on the project.

**Comment by alebeta** [comment]
@okram999 where is the option to submit the ticket like a closed??

**Comment by okram999** [comment]
@alebeta scroll down. you should see a "close" or "comment & close" button.

**Comment by alebeta** [comment]
Only appear Comment, the green one @okram999

**Comment by kahing** [comment]
You need to use the same account that you filled the ticket from

**Comment by RobbKistler** [comment]
@ggtakec can close it when he sees these comments.

**Comment by alebeta90** [comment]
@kahing interesting kahing hahahaha is true i was in a different account! thanks! and thanks to everyone!
