### ISSUE TITLE
Strange Bug: Creating folder "showshow" results in unwriteable folder.

### ISSUE THREAD

**Issue by Cat5TV** [s3fs-fuse/s3fs-fuse#259]
Encountered a very strange bug (I'm assuming it's a bug) in creating a folder specifically named "showshow". No matter what, if I make a folder with that name under s3fs, I get a folder where NO FILE can be written. All files placed in this folder simply end up being 0 bytes (glad I caught this!)

It is not a Linux permissions issue.

Check it out:
user@server:~/s3fs-mountpoint$ mkdir showshow
user@server:~/s3fs-mountpoint$ cd showshow
user@server:~/s3fs-mountpoint/showshow$ touch test
touch: closing `test': Bad file descriptor
user@server:~/s3fs-mountpoint/showshow$ cd ..
user@server:~/s3fs-mountpoint$ mkdir show
user@server:~/s3fs-mountpoint$ cd show
user@server:~/s3fs-mountpoint/show$ touch test
user@server:~/s3fs-mountpoint/show$ ls
test
user@server:~/s3fs-mountpoint/show$ 

Weird eh? Why would this be?

Thanks!!

**Comment by andrewgaul** [comment]
@Cat5TV This works for me.  Can you retest this running s3fs with the `-d -d -f -o f2 -o curldbg` flags?

**Comment by Cat5TV** [comment]
Thanks @andrewgaul - I'm using fstab. What would you like me to try?

**Comment by andrewgaul** [comment]
@Cat5TV You want mount without fstab for this -- we use the flags to dump debug output so we can further troubleshoot.

**Comment by Cat5TV** [comment]
Gives me "fuse: unknown option `f2' "

S3FS version 1.67

Yes, yes... I'll upgrade when I can replace the server, but it's operating on a live server.

:)

Thanks!

**Comment by andrewgaul** [comment]
Sorry, 1.67 precedes my involvement in the project and later versions likely address your issue.  I recommend upgrading to 1.79.

**Comment by ggtakec** [comment]
"f2" option was added after 1.67 because raw level debugging message on foreground mode.

The problem that the file size is zero, has occurred mainly such as communication timeout as a cause.
(Of course, it is not only it)
Please use the latest version that fixes a lot of problems.
We hope that it is the bes way to solve this issue.

Best Regards,

**Comment by Cat5TV** [comment]
Thanks. Yes, I'll have to update the OS in order to do that. It was just a strange thing. I just went with a different folder name for now.  :)
