### ISSUE TITLE
What's the minimum REST API requirement for the backend object storage?

### ISSUE THREAD

**Issue by akiradeveloper** [s3fs-fuse/s3fs-fuse#262]
This project is quite interesting to me. So I will ask you a question:

It doesn't seem like s3fs use all the s3 APIs. For example, the bucket is given so the "PUT Bucket" API isn't required.

My guess is it only uses restricted version of

* PUT Object
* DELETE Object
* GET Object
* LIST Bucket

restricted means subset of parameters and headers are required within the APIs.

**Comment by andrewgaul** [comment]
@akiradeveloper s3fs calls a few more APIs:

* POST multi-part upload
* POST multi-part copy
* PUT single-part copy
* HEAD Object
* GET Bucket (used for checking credentials)

You can grep through the source for `CalcSignatureV2` to see creation of RPCs.  We should collect the full list so that users can create restricted IAM roles.

**Comment by akiradeveloper** [comment]
Oh, multipart upload is required. I guess this is required because file can be larger than threshold (5MB?) but it's not easy to implement as normal PUT.

Ideally, the requirement should be as small as possible so only simple GET/HEAD/PUT/LIST are required because they are simpler.

Do you have a plan to add a special mode that s3fs assumes the files are smaller than threshold and never use multipart uploads?

**Comment by andrewgaul** [comment]
@akiradeveloper You can control multipart behavior via `-o multipart_size` or disable it via `-o nomultipart`.  You can also emulate copy via `-o nocopyapi`.  Which object store are you using that does not support these operations?

**Comment by akiradeveloper** [comment]
Thanks. But not particularly yet. It was just of my curiosity from technical aspect. This project is nice.

**Comment by ggtakec** [comment]
Hi, 
Additional information, you are going to using object strage like S3 but it does not support all of S3 API, you can see man page about "nocopyapi", "norenameapi" and "nomultipart".
These helps to connect S3 compatible object storage.

**Comment by akiradeveloper** [comment]
Thank you for the information.
