### ISSUE TITLE
s3fs swift on top of radosgw

### ISSUE THREAD

**Issue by xasima** [s3fs-fuse/s3fs-fuse#27]
I have set up ceph 0.72.2 with radosgw (S3 / Swift - compatible  API) for local S3 storage cluster. 

The python-swiftclient (S3 compatible) client connects to the local node `http://hmetrics002` and works well, allowing to perform upload / download / list commands for  bucket 'backup'.  
```
> export ST_AUTH=http://hmetrics002/auth
> export ST_USER=metrics-backup:swift
> export ST_KEY=XXUv90NDQtzaTn5ogda8wj1it66hwC67IAaE7XW
> swift -V 1.0 upload backup test.txt
 
> swift -V 1.0 list backup
test.txt
```

Here is the  log of try  mounting this  S3-compatible bucket using latest compiled s3fs-fuse. Please notice that we need to use exported variables due to having already comma symbol in the name of KEY (`metrics-backup:swift`), that has been provided  by ceph. So neither `/etc/passwd-s3fs`, nor  `~/passwd-s3fs` file can be used due to this reason of separator overlapping.

Anyway, the mount of this local S3-compatible  storage  fails and I can't figure out what to change to overcome this
```
export AWSACCESSKEYID=metrics-backup:swift
export AWSSECRETACCESSKEY=XXUv90NDQtzaTn5ogda8wj1it66hwC67IAaE7XW
sudo src/s3fs backup /mnt/s3fs-fuse -o use_cache=/tmp,url=http://hmetrics002 -f --debug
    set_moutpoint_attribute(3293): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
s3fs: could not determine how to establish security credentials
```

Here is the details on versions 
```
 > sudo pkg-config --modversion fuse
2.8.6

> sudo src/s3fs --version
Amazon Simple Storage Service File System 1.76
 
> grep s3fs /var/log/syslog
Mar 31 16:50:12 metrics s3fs: init $Rev: 497 $

>uname -a 
uname -a
Linux hmetrics001 3.2.0-31-generic #50-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux

```

Need to mention, that nothing interesting appears in syslog

**Comment by ggtakec** [comment]
I'm sorry about this Issue had been left at a long period of time.

If you have this problem yet, please try to use latest code.
("-f", "dbglevel" and "curldbg" options help to solve your problem.)
And if you found a problem, please post new issue.

Thanks in advance for your help.

**Comment by vlada-dudr** [comment]
Sorry, to comment on so old issue. Just in case someone bumps into it, when having similar problem.

It looks like the above problem is caused by using sudo, which resets the environment variables. One can use sudo -E to preserve them... Cheers!
