### ISSUE TITLE
how to connect to OVH OBJECT STORAGE (Openstack)

### ISSUE THREAD

**Issue by Dexus** [s3fs-fuse/s3fs-fuse#277]
Hi, i try to connect to ovh's object storage, but allways i get `s3fs: invalid credentials`.

can some one give me a hint how i can connect to the service?

**Comment by Amethi** [comment]
Did you ever connect? I'm just trying to connect via curl (http://developer.openstack.org/api-guide/quick-start/api-quick-start.html#authenticate) and can't. I get 401 unauthorised responses. OVH are as helpful as a chocolate teapot too.

**Comment by patrickdamery** [comment]
Best description I've ever read for OVH's support! I've managed to connect to my Object Storage by using Swift.
Here's a link explaining how to install Swift: http://stackoverflow.com/questions/10976317/can-i-install-swift-openstack-storage-infrastructure-of-openstack-without-inst.
After installing it, go to OVH's control panel and go to Project Management and Consolidation, once in there go to the OpenStack option and create a user. After the user is created, click on the little wrench and select the option that reads: Generate an OpenStack Token. Keep a copy of all the data id's passwords, etc.
After you've done this you can go use Swift like this: swift --os-auth-token 0bc3de*****************96e5c --os-storage-url https://storage.gra1.cloud.ovh.net/v1/AUTH000000/OBJECT_NAME list
Hope this is helpful for some people!

**Comment by soualid** [comment]
Also looking for a way to use s3fs with ovh object storage, did you finally succeed ?

**Comment by andrewgaul** [comment]
@soualid You can use s3fs with S3Proxy using the Swift backend.

**Comment by soualid** [comment]
Amazing, thank you.

**Comment by gaul** [comment]
@Dexus were you able to connect to OVH using S3Proxy?  If so please close this issue.

**Comment by Dexus** [comment]
I never got it to work.
But its form 2016 so let us close it.

Now I'm use a other OS Hosting
