### ISSUE TITLE
s3fs on CentOS 6.x - finally OK

### ISSUE THREAD

**Issue by fdutheil** [s3fs-fuse/s3fs-fuse#279]
Hi,

Getting s3fs command to work was pretty straightforward:
- get fuse 2.9.2 SRPM from CentOS 7 and rebuild it on a CentOS 6: fuse now meets s3fs minimum version requirement (sadly CentOS 6's fuse doesn't)
- follow s3fs-fuse documentation to compile s3fs
- use s3fs command to mount - success

Now, the tricky and dirty part: fstab
- Try to mount the very same bucket from fstab: FAIL
- Use basic mount command (not mount.fuse): FAIL
- Use mount.fuse command: success. Yeah, tricky, indeed.

In short: I tried several syntax in fstab with no luck. The "deprecated" "s3fs#mybucket" with a "fuse" type, or the "actual" (I presume) syntax with "mybucket" and "fuse.s3fs" type where not working either. 

Analysing strace gave me some clue:

```
stat("/sbin/mount.fuse.s3fs", 0x7ffc83e991c0) = -1 ENOENT (No such file or directory)
stat("/sbin/mount.fuse", 0x7ffc83e991c0) = -1 ENOENT (No such file or directory)
rt_sigprocmask(SIG_BLOCK, ~[TRAP SEGV RTMIN RT_1], NULL, 8) = 0
stat("/sbin/mount.fuse.s3fs", 0x7ffc83e99190) = -1 ENOENT (No such file or directory)
stat("/sbin/mount.fuse", 0x7ffc83e99190) = -1 ENOENT (No such file or directory)
mount("s3fs#mybucket", "/srv/mymountpoint", "fuse.s3fs", MS_MGC_VAL|MS_NOATIME, "max_stat_cache_size=100001,stat_"...) = -1 EINVAL (Invalid argument)
```

Now, the dirty part: `ln -s /usr/sbin/mount.fuse /sbin/mount.fuse` solves the fstab problem... 
That's ugly, I know... If you have any suggestion, feel free to share :)

**Comment by andrewgaul** [comment]
I wonder why FUSE 2.8.4 is the minimum required.  147dd86215f58593748095f70af8dd66d44bc1f3 changed this but I cannot see the requirement from its diff.

@mooredan any ideas?

**Comment by fdutheil** [comment]
@andrewgaul : I've been wondering myself and found a solid reason here: issue #42

**Comment by juliogonzalez** [comment]
Just for reference, I updated #42: even if the instability mentioned was not related to 2.8.3, tests are not passing anymore with 2.8.3 for some basic things such as truncating files or removing non empty directories.

**Comment by juliogonzalez** [comment]
@gaul, I just updated the Wiki with all the details, so I think we can close this issue.

**Comment by gaul** [comment]
@fdutheil Could you close this issue?

**Comment by fdutheil** [comment]
Oh yes, and the procedures in the wiki seems much cleaner. Nice.
