### ISSUE TITLE
Consider changing default transport to HTTPS

### ISSUE THREAD

**Issue by andrewgaul** [s3fs-fuse/s3fs-fuse#282]
This would protect private data when used over the public Internet.  Users can opt-in to unencrypted HTTP if they need additional performance on a local network.

**Comment by driskell** [comment]
This also becomes a requirement when using SSE_KMS, or things just don't work at all.

**Comment by ggtakec** [comment]
@andrewgaul @driskell 
I would like to change default protocol HTTP to HTTPS at next version 1.81(#586)
If you need to post issue about this, please post here.

**Comment by ggtakec** [comment]
@andrewgaul Thanks for PR
