### ISSUE TITLE
chmod removes SSE

### ISSUE THREAD

**Issue by jdh237** [s3fs-fuse/s3fs-fuse#286]
I have a bucket with an object encrypted with SSE. It seems that any metadata changes through s3fs remove the SSE setting. An example is shown below.

This seems to be an extreme problem for another bucket where SSE is required. In that case, it seems not to be possible to use s3fs at all.

Perhaps I have a setting wrong somewhere?

-Jason

$ s3fs -o rw,allow_other,uid=500,gid=500,**use_sse** my-bucket /home/ec2-user/temp
$ ls -l temp/std1.out 
---------- 1 ec2-user ec2-user 12071 Oct 28 20:03 temp/std1.out
$ aws s3api head-object --bucket my-bucket --key std1.out
{
    "AcceptRanges": "bytes", 
    "ContentType": "binary/octet-stream", 
    "LastModified": "Wed, 28 Oct 2015 20:03:58 GMT", 
    "ContentLength": 12071, 
    "ETag": "\"bff9fb24e76685ae149bfca973bd24b1\"", 
    "ServerSideEncryption": "**AES256**",
    "Metadata": {}
}
$ chmod +r temp/std1.out 
$ ls -l temp/std1.out 
-r--r--r-- 1 ec2-user ec2-user 12071 Oct 28 20:05 temp/std1.out
$ aws s3api head-object --bucket my-bucket --key std1.out
{
    "AcceptRanges": "bytes", 
    "ContentType": "binary/octet-stream", 
    "LastModified": "Wed, 28 Oct 2015 20:05:19 GMT", 
    "ContentLength": 12071, 
    "ETag": "\"bff9fb24e76685ae149bfca973bd24b1\"", 
    "Metadata": {
        "mode": "33060"
    }
}

**Comment by ggtakec** [comment]
@jdh237 
Thanks fore reporting this problem.
This was a bug, and I fixed this problem.
Please try to use latest codes.

I closed this issue, if you found a bug about this, please reopen this or post new issue.
Regards,
