### ISSUE TITLE
unsuccessful "make"

### ISSUE THREAD

**Issue by Chasego** [s3fs-fuse/s3fs-fuse#287]
Hi all,
I'm new to s3fs-fuse. After I follow the "Installation" section (on README.md) to do "make", it showed the results as follows, which seems to do nothing because of the message "Nothing to be done for 'all' ".

I'm not sure it is successful or not? If not, what the problems may be?

The system setting are:
Host: Win 8.1 64-bit
Guest: Ubuntu 14.04 on VirtualBox 4.3.30

![image](https://cloud.githubusercontent.com/assets/1727284/10851081/8b3b950c-7eff-11e5-9afc-b8eaa6424108.png)

**Comment by RobbKistler** [comment]
@chasego make does "incremental builds" -- it won't re-run steps if they aren't necesary.  What you pasted looks like the results of running make again after a successful build has already occured.  You can verify this by checking for the existence of `src/s3fs`, which is the executable created by make. You can also ask make to install the s3fs exectuable for you:

```
sudo make install
```

**Comment by Chasego** [comment]
I verified the existence of ```src/s3fs```

![image](https://cloud.githubusercontent.com/assets/1727284/10861104/d424e498-7f4b-11e5-9401-c1fd0751b1f9.png)

Then I typed ```sudo make install```. It seems that there's no problem. But I'd like to make sure because of ```Nothing to be done```. However, based on your explanation, it should be OK.

![image](https://cloud.githubusercontent.com/assets/1727284/10861135/2ab38e1c-7f4d-11e5-9098-669b4c1ec6e2.png)

**Comment by RobbKistler** [comment]
You can force a build
```
make clean
make
```

**Comment by Chasego** [comment]
@RobbKistler Thank your patience for telling me the basics
