### ISSUE TITLE
Possible to create Debian/Ubuntu packages?

### ISSUE THREAD

**Issue by jaddison** [s3fs-fuse/s3fs-fuse#29]
I'm not sure how to go about it, but this seems like a really useful addition to standard package repositories. RedHat, etc. too.

Here's some info on Ubuntu/Debian: https://wiki.ubuntu.com/UbuntuDevelopment/NewPackages

**Comment by michalmedvecky** [comment]
Quick hack for building from source to debian package:

mkdir /tmp/installdir
make install DESTDIR=/tmp/installdir
apt-get install ruby ruby-dev
gem install fpm
fpm -s dir -t deb -n s3fs-fuse -v <MYOWNVERSIONNUMBER> -C /tmp/installdir -p s3fs-fuse_VERSION_ARCH.deb

Replace MYOWNVERSIONNUMBER with the version number you love. Do not touch VERSION and ARCH as they are FPM params.

**Comment by jollyroger** [comment]
Hi, @ggtakec . Glad to tell you a sponsor to upload the package into Debian archive was found (at last!). It seems the last tagged release was 1.79, but there was some important bufixing afterwards. May I ask you to make another tagged release so we could start with it?

Thank you.

**Comment by jollyroger** [comment]
Hi @ggtakec and everyone. I've created a snapshot tag in my own repo and thanks to Mattia Rizzolo and our sponsor Gianfranco Costamagna we were able to push the package into Debian's NEW queue(https://ftp-master.debian.org/new/s3fs-fuse_1.79+git90-g8f11507-1.html) . Awaiting for the package to appear in the Debian archive. 

Thank you everyone for your work and for your interest in Debian!

**Comment by ggtakec** [comment]
@jollyroger 
I appreciate your kindness and Mattia Rizzolo, Gianfranco Costamagna.
I'm glad s3fs-fuse is distributed as a debian package.

Now I'm modifying s3fs-fuse for fixing a issue.
After the change has been completed, I will to make a new tag.

I couldn't have done it without you.
Thank you very much!!!

**Comment by jollyroger** [comment]
Today s3fs was accepted into Debian Archive. From now on it will be available for all Debian users. Waiting for the new release from you :+1: 

Meanwhile we moved to Debian git hosting to work on packaging ( https://anonscm.debian.org/cgit/collab-maint/s3fs-fuse.git) Feel free to contact if any action is required from our side.

**Comment by ggtakec** [comment]
I'm so excited about accepting debian archive!
Your help was much appreciated.
We could not have done it without you.

I'll work so as to be useful tool s3fs in the future.

Thank you very much for your great help.
