### ISSUE TITLE
File opened with O_TRUNC is not flushed

### ISSUE THREAD

**Issue by RobbKistler** [s3fs-fuse/s3fs-fuse#290]
s3fs-fuse @ ad2a4062058db3ebed85dd4d350221e177ab31fe

*Scenerio:*
Open an existing file, non-empty file O_TRUNC and close it (no writes), 

*Expected results:*
File with zero length. (Verified on local ext4 filesystem)

*Actual results:*
The file still contains original content.

**Comment by RobbKistler** [comment]
Created PR with repro test and potential fix.

**Comment by ggtakec** [comment]
@RobbKistler Thanks for your fixed codes.

I made a few changes to your correction.
Only when the file size is needed to change, s3fs calls RowFlush function.

When the open function is called with O_TRUNC, the file size is set Zero as soon as possible.
So it means that s3fs calls REST api(upload zero size object) when calling open with O_TRUNC.
Then you are correct about calls flush, but it does not need evey time.
My changes after your cahnages, If the file size is zero, s3fs does not call flush.

Please check it.
Thanks in advance for your help.

**Comment by RobbKistler** [comment]
Look great!  Thank you.
