### ISSUE TITLE
Ubuntu Packages

### ISSUE THREAD

**Issue by stevedh** [s3fs-fuse/s3fs-fuse#292]
Hey -- I don't know how if this is the right place to put this but we created some ubuntu packages for your last release here.  The packaging scripts are pretty trivial since your build scripts seem to work well but let me know if it his is something you're interested in supporting.

https://launchpad.net/~stevedh/+archive/ubuntu/bacnet-tools

**Comment by ggtakec** [comment]
@stevedh thanks, and please see closed issue #29 
And if you have a problem or question, please post new issue.
Regards,
