### ISSUE TITLE
Ok to use mount as a shared file directory across a cluster of servers?

### ISSUE THREAD

**Issue by curiosity26** [s3fs-fuse/s3fs-fuse#30]
What I'd like to do is use a S3 bucket as a mountpoint for a cluster of compute instances. The configuration would do more reading than writing, so I figure that would be ok. I thought of this solution when I was looking at auto-scaling and a Hadoop configuration and thought it would be better for scaling and management to automount an S3 Bucket via S3fs and boom. I feel the support for write-locking would prevent corruption, even though the system I use doesn't overwrite files, just renames by appending _N. Any pros/cons to this solution?

**Comment by tspicer** [comment]
Just for clarification in case any stumbles upon this (like me). The proper syntax is iam_role="role name" and not aim_role="role name". 

Example: -o iam_role="s3access-role"

**Comment by rcsavage** [comment]
This works well - confirmed.

s3fs bucketName /target/mount/point -o iam_role="role name"

**Comment by ggtakec** [comment]
@tspicer Thanks for help my fault.
It is correct the option name is **iam_role**.
Regards,

**Comment by gl-lamhnguyen** [comment]
If I want to mount on boot by editing /etc/fstab file, where should I store iam_role?

**Comment by lvandeyar** [comment]
I can't see to setup /etc/fstab with an IAM role. Is there official documentation anywhere?

**Comment by yuanzhou** [comment]
@ggtakec I read through this thread but still didn't get how to mount s3 bucket on a AWS cluster. I'm building a EC2 cluster using `cfncluster` and it appeared that I could mount s3 with s3fs to the master node, but I couldn't figure out how to also mount this s3 bucket to all other compute nodes so when I run a job scheduler, it knows where to get the input files and where to put the result data files. Can you please shed some light?

**Comment by ggtakec** [comment]
@lvandeyar I updated iam_role option by #411.
This change added "auto" value for iam_role option, it gets iam_role name from meta data on your EC2.
Then if you can get the meta data at booting, I think it works good.
Please try it.
Thanks in advance for your help.
