### ISSUE TITLE
Integration with Cloudfront

### ISSUE THREAD

**Issue by ajaygarga** [s3fs-fuse/s3fs-fuse#318]
Does S3FS has support for Cloudfront integration. What I mean is S3FS configure as a file system to write to S3 bucket directly but to read it from configured Cloudfront. This will help in quicker access to the file as Cloudfront are available in distributed locations.

**Comment by ggtakec** [comment]
s3fs does not support the request through cloudfront.
I probably understand that your are saying the benefits, but it will be difficult because of request type/authentication/object size(multi part)/etc.
I close this issue, but if you have more quiesion or etc, please reopen this.
Regards,
