### ISSUE TITLE
S3FS sometimes claims files are corrupted (images) when opening them directly

### ISSUE THREAD

**Issue by AlmirKadric** [s3fs-fuse/s3fs-fuse#322]
On OSX I can preview a file (press space), download (copy & paste) a file locally. However when I try to open it directly from the drive (e.g. double click on an image file and thus opening in `Preview` application) if the filename has spaces it fails with the following error `“File Name With Space.png” is damaged and can’t be opened. You should eject the disk.`

**Comment by AlmirKadric** [comment]
after further investigation, it doesn't seem that the spaces in the file name are the issue. I found files with spaces which work and file without not working. Also seems to be isolated so far to images. Also copy & pasting them locally seems to solve the problem. Not sure why s3fs is claiming they are corrupted.

**Comment by ollietreend** [comment]
@AlmirKadric Have you tried opening the image files in an application other than Preview? For example, what happens if you open it directly in Photoshop, or another image editor? I wonder whether Preview is doing something weird with the file which is causing that error message.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
