### ISSUE TITLE
s3fs: BUCKET bucket.name.with.dots, name not compatible with virtual-hosted style.

### ISSUE THREAD

**Issue by martyychang** [s3fs-fuse/s3fs-fuse#332]
When I try to mount a bucket where the bucket name has periods in it (e.g., "bucket.name.with.dots"), the attempt to mount fails with the following error:

```
$ s3fs bucket.name.with.dots local/mount/point/
s3fs: BUCKET bucket.name.with.dots, name not compatible with virtual-hosted style.
```

I am able to successfully mount other buckets that have simple alphanumeric names (e.g., "bucket1").

**Comment by RobbKistler** [comment]
The alternative to virtual-hosted style requests is path style requests:
```
s3fs -o use_path_request_style -o url=http://s3.amazonaws.com bucket.name local/mount/point
```

**Comment by martyychang** [comment]
Thank you for the quick tip, @RobbKistler ! That worked like a charm.

**Comment by adavanisanti** [comment]
I am running into a problem with buckets with dots in their names.

```
s3fs -o url=http://s3.amazonaws.com -o use_path_request_style -o endpoint=us-west-2 -o bucket=a.b.cd.ef  <mount_dir>
```
I can see <mount_dir> in `df -h`. 
```
ubuntu@ip-172-31-45-177:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
s3fs            XT     0  XT   0% <mount_dir>

```

But, I don't see anything in `mount_dir` when I `ls <mount_dir>`. When I `cd <mount_dir>` and `ls`, I see the following error message:
```
ls: error while loading shared libraries: libselinux.so.1: file too short
```

s3fs version is 1.83
```
Amazon Simple Storage Service File System V1.83(commit:0f503ce) with OpenSSL
```

**Comment by trajano** [comment]
Can we have an equivalent in /etc/fstab form?

**Comment by ckujau** [comment]
Apparently [s3fs.cpp:4915](https://github.com/s3fs-fuse/s3fs-fuse/blob/d1c638ab7ac7e2dcdcee03097da0ca18e6ea0b0f/src/s3fs.cpp#L4915) only checks that `bucket names cannot contain upper case characters in virtual-hosted style`. I.e renaming buckets (if [possible](https://help.backblaze.com/hc/en-us/articles/217666908-What-you-need-to-know-about-B2-Bucket-names "What you need to know about B2 Bucket names
")) or creating a bucket with a valid name will help here too.

**Comment by ctrlcctrlv** [comment]
That "solution" of using the path req style is everywhere but is worse and slower. This should have remained open.
