### ISSUE TITLE
Files appear empty after reboot, issue between del_cache and stat cache

### ISSUE THREAD

**Issue by diasjorge** [s3fs-fuse/s3fs-fuse#337]
We were having issues with s3fs after rebooting the servers. The files would appear mounted but when checked with cat for instance they'd appear empty.

To start s3 we use:

 /usr/bin/s3fs -o use_cache=/var/cache/s3fs -o del_cache -o ensure_diskfree=1024 -o allow_other -o nonempty -o iam_role=ROLE BUCKET FOLDER

After some debugging we noticed that If we kill s3fs and start it again then the problem always happens, which explains the issue happening on reboot.

Then if we delete the folder /var/cache/s3fs/.FOLDER.stat and start s3fs again the problem is gone.

It appears to me that when del_cache is used and s3fs is restarted then it presents the metainformation about the files stored in .stat but they files are not present in the cache and so they are empty since they're not fetched again.

It'd seem to me that when using del_cache the stat cache should be deleted as well.

**Comment by ggtakec** [comment]
@diasjorge 
I fixed this problem by #352.
#352 added removing stat cache directory at starting/exiting s3fs if del_cache option is specified.
Please try to use and check it.
I close this issue, but if you find a problem please reopen this issue.
Thanks in advance for your help.
