### ISSUE TITLE
Add option to use "path style" requests

### ISSUE THREAD

**Issue by Andrew-Dunn** [s3fs-fuse/s3fs-fuse#34]
At the moment s3fs-fuse only supports virtual host style requests with the path prepended to the Host, i.e:

```
DELETE /puppy.jpg HTTP/1.1
User-Agent: dotnet
Host: mybucket.s3.amazonaws.com
Date: Tue, 15 Jan 2008 21:20:27 +0000
x-amz-date: Tue, 15 Jan 2008 21:20:27 +0000
Authorization: signatureValue
```

However some S3 compatible APIs do not support this style of request, and instead need the bucket name to be in the path, i.e.

```
DELETE /mybucket/puppy.jpg HTTP/1.1
User-Agent: dotnet
Host: s3.amazonaws.com
Date: Tue, 15 Jan 2008 21:20:27 +0000
x-amz-date: Tue, 15 Jan 2008 21:20:27 +0000
Authorization: signatureValue
```

I'm currently working on a patch which would allow this style of request to be used, which would be enabled with a configuration option such as `use_path_style_request`.

**Comment by alebeta90** [comment]
Hello, is still possible use the path style? im trying:
s3fs -o use_path_style_request -o host=http://ecs.domain.com bucketname s3/
and i get this error

fuse: unknown option `use_path_style_request'

Thanks for your time!
Alejandro B.

**Comment by andrewgaul** [comment]
@alebeta90 Which version of s3fs do you use?  1.78 and later should include `use_path_request_style`.

**Comment by Andrew-Dunn** [comment]
Hey @alebeta90, the option name is `use_path_request_style`, not `use_path_style_request`.
