### ISSUE TITLE
Defining HTTP Header Info per Directory in a Bucket 

### ISSUE THREAD

**Issue by degging** [s3fs-fuse/s3fs-fuse#343]
In the ahbe.conf, can you define header info per embedded directory in a bucket? E.g.

/var/www/files/*.png Cache-Control 300
/var/www/files/*.xml Cache-Control 600
/var/www/assets/*.png Cache-Control 600
/var/www/assets/*.xml Cache-Control 300

Thank you

**Comment by ggtakec** [comment]
@degging 
s3fs does not allow path for ahbe.conf entry, it must be file(object) suffix only.
Time is undecided, but I think that I can support regular expressions to ahbe.conf.
Please wait a while.
Regards,

**Comment by ggtakec** [comment]
@degging 
"Additional Header" was a feature that was created by the rush.
From that time, but I should add a regular expression matching, it has not been able to achieve.

# 354, I was able to support regular expressions.

Probabely I think that I can work with you to specify as follows.
 `` `
 reg: (. *) [.] ^ / var / www / files / png $ Cache-Control 300
 `` `
Please try to use latest codes in master branch, and check it.
I close this issue, if you have a problem, please reopen this issue.
Regards,
