### ISSUE TITLE
Can rmdir a non-empty directory running against AWS S3

### ISSUE THREAD

**Issue by RobbKistler** [s3fs-fuse/s3fs-fuse#345]
The integration test `test_remove_nonempty_directory` fails if s3fs-fuse is running against Amazon AWS.  It passes against S3Proxy 1.4.0.  See https://github.com/andrewgaul/s3proxy/issues/119

**Comment by andrewgaul** [comment]
@RobbKistler great catch!  I was testing S3Proxy 1.5.0-SNAPSHOT and could not figure out why it regressed vs. 1.4.0.  Turns out some of the prefix and delimiter fixes in 1.5.0 made S3Proxy more correct and thus fail like real S3.

**Comment by RobbKistler** [comment]
Thanks :)  Check out #346, hopefully fixes the issue without breaking anything else.

**Comment by ggtakec** [comment]
@RobbKistler and @andrewgaul I merged #346, sorry for replying late.
