### ISSUE TITLE
Travis-CI tests not working?

### ISSUE THREAD

**Issue by RobbKistler** [s3fs-fuse/s3fs-fuse#349]
I don't see the output from the small-integration-test.sh tests in any Travis builds from the last 3 months.  Does Travis hide the output?   The raw log shows:

```
[32;1mThe command "modprobe fuse" exited with 0.[0m
travis_time:start:07c1046a
[0K$ make check -C test
make: Entering directory `/home/travis/build/s3fs-fuse/s3fs-fuse/test'
make  check-TESTS
make[1]: Entering directory `/home/travis/build/s3fs-fuse/s3fs-fuse/test'
make[2]: Entering directory `/home/travis/build/s3fs-fuse/s3fs-fuse/test'
[0;32mPASS[m: small-integration-test.sh
make[3]: Entering directory `/home/travis/build/s3fs-fuse/s3fs-fuse/test'
make[3]: Nothing to be done for `all'.
```
Except for the one build that failed:
https://travis-ci.org/s3fs-fuse/s3fs-fuse/builds/94634872

That has full output from the small-integration-test.sh

**Comment by RobbKistler** [comment]
Ah -- it looks like Travis just squelches the output when it passes.  I expected a "raw" log to contain everything.

@ggtakec or @andrewgaul can you confirm just for my peace of mind?

**Comment by ggtakec** [comment]
@RobbKistler 
https://github.com/s3fs-fuse/s3fs-fuse/commit/7bfaa24d252e99a59a7ec06004ab7eb38b52ea21
It seems that changes about this is after this commit.

I think if you need to display detail, I will allow to add -x option in test script.
(It will be removed after test.)

@andrewgaul Do you think about this?

Regards,

**Comment by RobbKistler** [comment]
Even before 7bfaa24 there is no output unless the "make check" fails.  

I now understand that Travis does not display stdio from the test unless there is a failure.  I verified by opening a PR with a failing test.  I can see all the stdio from "make check".

I will close this issue, everything seems to be working.

**Comment by ggtakec** [comment]
Ok, I appreciate your help.
