### ISSUE TITLE
S3FS with NFS

### ISSUE THREAD

**Issue by zubryan** [s3fs-fuse/s3fs-fuse#362]
I just installed S3FS and want to run it with ganesha NFS.
When I mount with NFS client, I can read but cannot write things in mount point.
Any suggestion?

Thanks
Bryan

**Comment by ggtakec** [comment]
@zubryan Since we first must know the symptoms, could you run s3fs with dbglevel option?
(If you need more debug information, you can use curldbg, -f option.)
And please let us know about your s3fs options.

Thanks in advance for your help.

**Comment by zubryan** [comment]
@ggtakec I ran with option "-o allow_other -o uid=1000 -o gid=1000 -o rw", everything is working except for NFS. I want to mount it as NFS.

Thanks,
Bryan

**Comment by ggtakec** [comment]
@zubryan Can you copy a file into mount point manualy without problem?
(Only failed through NFS?)
I want to know why s3fs failed to write file, thus please specify dbglevel option.
It makes s3fs put debug messages, we can know whether the cause is s3fs and what the cause is.

Thanks in advance for your assistance.

**Comment by zubryan** [comment]
@Takeshi Thanks for your reply, I don't think it's the problem with s3fs
because when I tried locally without NFS, it works.
So maybe I have something to do with ganesha nfs.

2016-02-11 22:16 GMT+08:00 Takeshi Nakatani <notifications@github.com>:

**Comment by ggtakec** [comment]
@zubryan The reason for this is I feel like setting of ganesha NFS side.
I'm not familiar with NFS, but it seems that exports setting(Access_type) in ganesha.nfsd.conf is related.
I am sorry if it is already confirmed.

If you found about s3fs problem about this, please post here.

Regards,
