### ISSUE TITLE
s3fs 1.79 on server with selinux enabled

### ISSUE THREAD

**Issue by ngbranitsky** [s3fs-fuse/s3fs-fuse#365]
What do I have to add to selinux configuration (RHEL 7.2) to allow s3fs v1.79 to start?
The program name?
The mount point?

**Comment by ggtakec** [comment]
I'm not ready how to set the terms of SELinux now.
I think that we will reference it if someone set s3fs for SELinux.
Regards

**Comment by loganstellway** [comment]
You can try running [`audit2allow`](https://linux.die.net/man/1/audit2allow) to see if there are any rules you need to enable:
```
audit2allow -a
```

**Comment by gaul** [comment]
Please reopen if the suggested workaround does not address your symptoms.
