### ISSUE TITLE
Multiple SFTP clients

### ISSUE THREAD

**Issue by willembressers** [s3fs-fuse/s3fs-fuse#369]
I've managed to setup the SFTP upload for me (ec2-user). 

If I want to upload files, I connect to the instance (with filezilla), navigate to the `/mnt/bucket` and upload a file to the `uploads` folder.

This is fine (for me) but I want to give access to a third party to the specific (`/mnt/bucket/uploads`) folder only, preferably without navigation and an *.ppk key, but with (username: password) credentials.

Is this feasible? and if so how?
* Do I need to create an AWS user with access to the EC2 (S3)?
* Do I need to add an user on the instance and add it to an appropriate group?

I'm quite new to FTP (regarding setting up the server).

Cheers
Willem

**Comment by RobbKistler** [comment]
Hi Willem.  It's feasible but this is more of a general Unix and EC2/S3 question.   S3fs-fuse provides normal Unix user/group access control as long as you start it with the -oallow_other flag.  You can create a Unix user in the instance with a password login, add the group to the user, and then give that group access.  s3fs-fuse will always authenticate access to the bucket with the S3 access key you configure it with.  It doesn't try to map Unix users to S3 IAM users, AFAIK.

**Comment by willembressers** [comment]
Thanks Robb
