### ISSUE TITLE
s3fs with bacula backups - transport end not connected 

### ISSUE THREAD

**Issue by ghost** [s3fs-fuse/s3fs-fuse#373]
I'm using s3fs 1.7.3 with fuse 2.9.5 to store backup tapes for the backup system bacula.

What I find is that when bacula finishes backing up one server, I'll get an S3FS error on the directory where I have bacula's virtual backup tapes mounted before it can move onto backing up the next server:

```
[root@ops:/etc/bacula] #df -h /backup/tapes
df: ‘/backup/tapes’: Transport endpoint is not connected
I mounted the S3FS share using this line in my /etc/fstab and using the 'mount -a' cmmand:

s3fs#jf-backup /backup/tapes fuse defaults,noatime,allow_other,uid=133,gid=133,connect_timeout=60,readwrite_timeout=120,use_cache=/cache,default_acl=public-read,multireq_max=5 0 0
```

I'm able to unmount the '/backup/tapes' directory using the 'umount -l /backup/tapes' command, and then remount it through the fstab file with the 'mount -a' command. And when I go into the bacula CLI and mount the directory again I can move onto the next host and back that one up. However, by the time it gets to the host after that, the 'transport connect' error will reoccur.

I really don't want to keep doing this for all 30 hosts that I need to back up ! How can I get s3fs to stay connected so that the nightly backups will happen without intervention?

Thanks

**Comment by RobbKistler** [comment]
I don't see any releases versioned 1.7.3.  

"Transport endpoint is not connected" can happen when the fuse daemon has crashed.

**Comment by ggtakec** [comment]
@bluethundr Probably the version of s3fs which you uses is 1.73.
If you can, please use latest version or latest codes in master branch.
And latest version fixed bugs about "Transport endpoint is not connected", this cause is as said of @RobbKistler.

Regards,

**Comment by gaul** [comment]
@ghost I suspect that s3fs has exited due to an internal error.  Could you try again with the latest version which includes fixes for symptoms similar to your and report back your results?  Also please run with `-f -d` to get debug logs.

**Comment by gaul** [comment]
Please test with the latest version 1.85 and reopen if symptoms persist.
