### ISSUE TITLE
input/output error on chgrp / chown

### ISSUE THREAD

**Issue by maltorfer** [s3fs-fuse/s3fs-fuse#374]
I have input/output errors for chown/chgrp commands. We're using the lastet s3fs-fuse on amazon beanstalk. We can read/write to the directory, but we can't deploy over AWS beanstalk since amazon does some magic with chown/chgrp during deploy and this fails on the S3 mounted directory.

mount command:
s3fs <bucket> /var/app/content -o nonempty -o uid=498 -o gid=496 -o use_cache=/tmp -o allow_other -o passwd_file=/etc/passwd-s3fs -o mp_umask=002 -d -f

[ec2-user@xx app]$ id -u webapp
498
[ec2-user@xx app]$ id -g webapp
496

[ec2-user@ip-172-31-1-121 app]$ ll /var/app/
total 13
drwxrwxr-x  1 webapp webapp    0 Jan  1  1970 content

[ec2-user@xx app]$ sudo chgrp webapp content
chgrp: changing group of ‘content’: Input/output error

Debug log:
[INF] s3fs.cpp:s3fs_getattr(807): [path=/]
[INF] s3fs.cpp:s3fs_chown(1633): [path=/][uid=4294967295][gid=496]
[ERR] s3fs.cpp:s3fs_chown(1636): Could not change owner for maount point.

I find the the uid pretty strange?

**Comment by ggtakec** [comment]
@maltorfer Could not change owner/group for mount point.
If you need to do it, please change those before mounting by s3fs.
(But you can change permission(mode) by mp_umask option.)

Regards,
