### ISSUE TITLE
Problem sharing encrypted s3-bucket across nodes (nodes can only read their own data)

### ISSUE THREAD

**Issue by mhandeland** [s3fs-fuse/s3fs-fuse#381]
Hi,

I'm having a problem sharing an encrypted s3-bucket across 2 nodes. Each node is started with exactly the same parameters, but can only read data created by themselves. Data created by other nodes is unreadable.

I have successfully mounted using commandline and fstab with without sse, with sse-keys in a file or with keymanagement through aws/kms.  

Example command:

> sudo s3fs -f backup-cassandra-node1 -o allow_other,use_cache=/tmp,use_sse=kmsid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx,url=https://s3.amazonaws.com,endpoint=eu-west-1 /mnt/s3/backup-cassandra-node1

Magnus

**Comment by gl-lamhnguyen** [comment]
So this is a thing now ... https://github.com/s3fs-fuse/s3fs-fuse/issues/15

**Comment by ggtakec** [comment]
@mhandeland I'm sorry for late reply.
As @gl-lamhnguyen pointed out, this problem might be a bug has been modified by the #395.
Currently, the bug has been fixed.
Please try to use latest codes on master branch.
If this reason is not #395, please let me know.

Thanks in advance for your help.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
