### ISSUE TITLE
Usage of stat_cache_expire=<expiration seconds> turns off stat cache for all values of <expiration seconds>

### ISSUE THREAD

**Issue by adupon** [s3fs-fuse/s3fs-fuse#382]
When I include stat_cache_expire option, s3fs does not use the stat cache at all...

/usr/bin/s3fs mybucket /mnt/mybucket -ostat_cache_expire=10000,passwd_file=/etc/passwd-s3fs

I tested this using 

ls /mnt/mybucket ; ls /mnt/mybucket

When stat_cache_expire is included as an option... both ls commands take about 10 seconds each..  When I remove the stat_cache_expire option... the first command takes 10 seconds, the second command is instant...

s3fs --version
Amazon Simple Storage Service File System V1.79(commit:cf56b35) with OpenSSL

**Comment by grutherford** [comment]
I get the same issue also using v1.79 I enabled stat_cache_expire as the server memory was all getting used, since implementing this nothing is cached, do we need to set another option at the same time?

**Comment by ggtakec** [comment]
@adupon  and @grutherford, I'm very sorry for my late reply.

I can reproduce your report issue content, and it is a fatal bug.
So I fixed it by #415

Please use latest master branch code.
Regards,
