### ISSUE TITLE
All files mounted from S3 are corrupted

### ISSUE THREAD

**Issue by gl-lamhnguyen** [s3fs-fuse/s3fs-fuse#384]
It worked before, I don't know what update from s3fs broke it. Now all files are corrupted from local machine (but not files from S3 bucket)

**Comment by Morc001** [comment]
Is it not #15 by any chance? I found that turning ensure_diskfree off with caching enabled "fixes" the problem. So at the moment master branch produces all-zero content files with caching and ensure_diskfree enabled.

  Morc

**Comment by ggtakec** [comment]
@gl-lamhnguyen I'm sorry for late reply.
This problem might be a bug has been modified by the #395.
Currently, the bug has been fixed.
Please try to use latest codes on master branch.

Thanks in advance for your help.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
