### ISSUE TITLE
Multiple headers ahbe_conf

### ISSUE THREAD

**Issue by mohakevin** [s3fs-fuse/s3fs-fuse#386]
It would be interesting add multiple values to a same extension in ahbe_conf
Maybe with a separator.

i.e.

.js Content-Encoding    gzip |  Cache-Control public, max-age=31536000

**Comment by ggtakec** [comment]
@mohakevin I'm sorry for my late reply.
I have modified the codes.
By new code, you can write multiple entries with the same extension in the ahbe_conf file.
As a result, you will be able to define multiple HTTP header for one extension.

- example
```
.js	Content-Encoding	gzip
.js	Cache-Control	public, max-age=31536000
```
- example's result
```
Content-Encoding: gzip
Cache-Control: public, max-age=31536000
```

I closed this issue, if you found bugs about this, please reopen.
Regrads,
