### ISSUE TITLE
Why do you need to specify IAM role name?

### ISSUE THREAD

**Issue by wimnat** [s3fs-fuse/s3fs-fuse#387]
I would like to know why you need to specify IAM role name?  When would IAM role specified be different than what can be found out from http://169.254.169.254/latest/meta-data/iam/info?

To maintain backward compatibility, I propose that you should be able to specify an option that reads the IAM role from http://169.254.169.254/latest/meta-data/iam/info and then uses this to authenticate.

My reasoning for this request - I want to add an s3fs mount to my fstab before creating an AMI.  The AMI may be started with different iam roles so i don't want to hard code to a particular iam role name.

**Comment by ggtakec** [comment]
@wimnat I'm sorry for my late reply.

I mered new codes which is changed about iam_role option.

New iam_role option requires the IAM role name or "auto".
If you specify "auto", s3fs will automatically use the IAM role names that are set to an instance.(loading IAM role name from http://169.254.169.254/latest/meta-data/iam/info)
If you specify this option without any argument, it is the same as that you have specified the "auto".

As a result of this change, I think it is what you want.

I closed this issue, but if you found bugs or have requests, please reopen this issue.
Thanks.

**Comment by vbarba** [comment]
Hi,

I think that this is not working propperly:

# s3fs bucket-tomount /mnt -o iam_role
s3fs: could not determine how to establish security credentials.

and:

s3fs: could not determine how to establish security credentials.

Thanks.

**Comment by nturner** [comment]
I'm seeing the same problem as @vbarba. I filed https://github.com/s3fs-fuse/s3fs-fuse/issues/419 to track this.

**Comment by ggtakec** [comment]
@vbarba I merged @nturner 's patch, please see  #421 and use latest codes in master branch.
Regards,
