### ISSUE TITLE
Files uploaded through awscli or s3cmd can't be read by s3fs

### ISSUE THREAD

**Issue by mohakevin** [s3fs-fuse/s3fs-fuse#392]
It appears impossible to read data through s3fs when the files are uploaded through s3cmd or aws cli 
The files uploaded contains binary data or something like that.

Is that behaviour normal?

If i copy (cp) the data, everything works like expected. But, if i try to use one of those tools, the data isn't readable.
However, if i access the files through the bucket endoint, i can see everything ok (http://bucket/file)

Thanks!

**Comment by jazzl0ver** [comment]
s3fs uses special meta data to keep an owner and permissions compatible with general file systems, while s3cmd doesn't do that.

**Comment by ggtakec** [comment]
@mohakevin please check #333 
The files which are uploaded by s3cmd/awscli/aws console/etc do not have any attibutes for file system.
uid/gid/umask/etc options sets attributes for those files, you can see man pages.

Regards,
