### ISSUE TITLE
s3fs www-data permissions

### ISSUE THREAD

**Issue by gophee** [s3fs-fuse/s3fs-fuse#398]
I have installed s3fs on Ubuntu 14.04.4 LTS, all seems ok, the only thing is that my web application can't create folders or files. my drive mount line is:
s3fs -o allow_other,nonempty,default_acl=public-read -o use_cache=~/tmp moodleS3 ./moodledataS3

Any idea ?

Thank you 
Ziv

**Comment by ggtakec** [comment]
@gophee I'm sorry for my late reply.
If you need to write to your bucket, you should not specify "public-read".
default_acl value is allowed following values.
https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html
please check your access control mode, and specify it.

I closed this issue, but if you need to open this, please reopen.
Thanks in advance for your assistance.
