### ISSUE TITLE
Using s3fs behind a proxy 

### ISSUE THREAD

**Issue by gnwlyonme** [s3fs-fuse/s3fs-fuse#400]
s3fs does not use http_proxy, all_proxy, etc... env vars when used behind a proxy.

I had to add the following in curl.cpp in function S3fsCurl::ResetHandle in order to mount S3
     curl_easy_setopt(hCurl, CURLOPT_PROXY, "http://corp-proxy:8080");

Is this the only option currently, or is there a way it can be set? If not, an -o proxy option would be a nice feature to have.

Thanks,
Mike

**Comment by andrewgaul** [comment]
@gnwlyonme Run `export http_proxy=127.0.0.1:1080` before invoking `s3fs`.

**Comment by yren** [comment]
I use s3fs in a docker container and behind a proxy, 
I tried this 
Run export http_proxy=127.0.0.1:1080 , then invoking s3fs . But it's not work.
The error message "fuse: failed to exec fusermount: No such file or directory"

Any suggestion on this. Thanks.
BTW, this can work on docker host machine.

**Comment by gnwlyonme** [comment]
yren,
Have you tried adding --privileged to docker run?
That fixed my problem.

**Comment by yren** [comment]
Cool, it works for me. Thanks @gnwlyonme

**Comment by ggtakec** [comment]
@andrewgaul thank you.
@gnwlyonme and @yren I'm sorry for my late reply.

So the issue has been resolved, I closed this issue.
If there is a problem to continue, please reopen this issue or post new issue.

Thanks all.
