### ISSUE TITLE
mount disappears

### ISSUE THREAD

**Issue by vadirajks** [s3fs-fuse/s3fs-fuse#405]
Hi,
we have application to do image resizing on fly on the mount drive.  parallely may be around 20 to 30 below mentioned commands we run and i am not sure after few minutes mount will get disappear.

all are small files:

convert /img02/6671/f/2/c/6671_sku_ATOM_SIZE_MACRO_f2c78cd885139bc3ac7d0e5a9c0c9761.jpg -resize 1200x627 -gravity center -extent 1200x627 /img02/6671/f/2/c/6671_sku_1200x627Padded_f2c78cd885139bc3ac7d0e5a9c0c9761.jpg
convert /img02/6671/4/9/4/6671_sku_ATOM_SIZE_MACRO_494534379b6ae77fe3dd192a3618b25f.jpg -resize 1200x800 -gravity center -extent 1200x800 /img02/6671/4/9/4/6671_sku_1200x800Padded_494534379b6ae77fe3dd192a3618b25f.jpg
convert /img02/6671/2/f/9/6671_sku_ATOM_SIZE_MACRO_2f9244d56d8414edafab3ec6189021c9.jpg -resize 100x100 /img02/6671/2/f/9/6671_sku_100x100_2f9244d56d8414edafab3ec6189021c9.jpg
convert /img02/6671/9/0/6/6671_sku_ATOM_SIZE_MACRO_906d3a992f889479dc96ec38cc3954dd.jpg -resize 460x460 -gravity center -extent 460x460 /img02/6671/9/0/6/6671_sku_460x460Padded_906d3a992f889479dc96ec38cc3954dd.jpg
convert /img02/6671/6/d/2/6671_sku_ATOM_SIZE_MACRO_6d22a64e1f461bdd7de9a0c84776db2a.jpg -resize 1280x720 -gravity center -extent 1280x720 /img02/6671/6/d/2/6671_sku_1280x720Padded_6d22a64e1f461bdd7de9a0c84776db2a.jpg
convert /img02/6671/5/5/4/6671_sku_ATOM_SIZE_MACRO_554c696df4bac84047311afa874e8107.jpg -resize 1280x720 -gravity center -extent 1280x720 /img02/6671/5/5/4/6671_sku_1280x720Padded_554c696df4bac84047311afa874e8107.jpg
convert /img02/6671/e/3/a/6671_sku_ATOM_SIZE_MACRO_e3acddf6b42ecfc946b39bfddc5cd8b8.jpg -resize 1200x800 -gravity center -extent 1200x800 /img02/6671/e/3/a/6671_sku_1200x800Padded_e3acddf6b42ecfc946b39bfddc5cd8b8.jpg
convert /img02/6671/4/e/0/6671_sku_ATOM_SIZE_MACRO_4e0cf8628bc88f7f2f2da88d8dcac055.jpg -resize 460x460 -gravity center -extent 460x460 /img02/6671/4/e/0/6671_sku_460x460Padded_4e0cf8628bc88f7f2f2da88d8dcac055.jpg
convert /img02/6671/0/6/d/6671_sku_ATOM_SIZE_MACRO_06d3ff5d67cba40e991a65951dc8842a.jpg -resize 1200x800 -gravity center -extent 1200x800 /img02/6671/0/6/d/6671_sku_1200x800Padded_06d3ff5d67cba40e991a65951dc8842a.jpg

 fuse ver 
fuse-2.9.4-1.17.amzn1.x86_64
fuse-python-0.2.1-1.el6.x86_64
fuse-python-debuginfo-0.2.1-1.el6.x86_64
fuse-dislocker-0.5.1-2.el6.x86_64
fuse-devel-2.9.4-1.17.amzn1.x86_64
fuse-sshfs-debuginfo-2.4-1.el6.x86_64
fuse-libs-2.9.4-1.17.amzn1.x86_64
fuse-afp-0.8.1-6.el6.x86_64
fuse-sshfs-2.4-1.el6.x86_64
/etc/fstab
s3fs#img02 /img02 fuse storage_class=reduced_redundancy,auto,defaults,noatime,allow_other,uid=48,gid=48,del_cache,retries=20,connect_timeout=5000,readwrite_timeout=3000,nodnscache,parallel_count=100,multireq_max=100,default_acl=public-read,dbglevel=info,endpoint=ap-southeast-1 0 0

log file 
[s3fs.log.gz](https://github.com/s3fs-fuse/s3fs-fuse/files/234673/s3fs.log.gz)

Please let me know if anything i am doing wrong.

Thanks,
Vadiraj

**Comment by ggtakec** [comment]
@vadirajks 
I checked your log file, but I could not find anything wrong.
The log is terminated after uploading 6671_sku_460x460Padded_4e0cf8628bc88f7f2f2da88d8dcac055.jpg file.
Then I do not know the reason about s3fs disapear.

Did s3fs process run on server when mount got disappear?
If you can run s3fs with -f option for fourground and with dbglevel option for logging, please try to do it.
The logs will help us to solve this problem when mount will get disappear.

Thanks in advance for your assistance.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
