### ISSUE TITLE
Root user not able to access the s3fs mount directory

### ISSUE THREAD

**Issue by jeevarathinam-dhanapal** [s3fs-fuse/s3fs-fuse#413]
Objects inside the buckets are visible in the mounted directory but couldn't create/upload a file in the directory. 
I'm using s3fs inside docker/kubernetes container.  

Mount dir shows it has root permission.
When tried to change permission it throws "i/o error"

 The bucket content was initially uploaded with EC2 role. Now I have mounted the s3fs with IAM user role. Not sure if this could cause an issue.

I have tried mounting uid,gid=0,allow-others. Nothing worked.

**Comment by ggtakec** [comment]
@jeevarathinam-dhanapal 
Could you set log level of s3fs by dbglevel option?
And check it.
If you need to change mount point permission after running s3fs, you can specify mp_umask option.
We maybe need to know more your enviroment(s3fs command line or fstab, etc).

Regards,

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
