### ISSUE TITLE
chown -R www-data:www-data  /var/www/website/rootfolder/

### ISSUE THREAD

**Issue by MourIdri** [s3fs-fuse/s3fs-fuse#414]
Hi,
Could not do chown. I tired to remove all security stuff : 

s3fs bucket /var/www/website/rootfolder/ -o passwd_file=/etc/passwd-s3fs -o nonempty -o url=https://my.s3.objectstore.corp:8082  -o sigv2  -o no_check_certificate -o use_path_request_style -d -d -f -o f2 -o curldbg -o retries=1 -o use_cache=/tmp -o allow_other -o uid=1000 -o gid=1000 -o default_acl=public-write-read

I got this : 

[INF]       curl.cpp:RequestPerform(1940): HTTP response code 200
[DBG] curl.cpp:ReturnHandler(295): Return handler to pool: 31
[INF]       cache.cpp:AddStat(344): add stat cache entry[path=/uploads/]
[DBG] cache.cpp:GetStat(267): stat cache hit [path=/uploads/][time=4886.908116375][hit count=0]
[DBG] fdcache.cpp:ExistOpen(1927): [path=/uploads][fd=-1][ignore_existfd=false]
[DBG] fdcache.cpp:Open(1876): [path=/uploads][size=-1][time=-1]
[DBG] s3fs.cpp:s3fs_getattr(832): [path=/uploads] uid=33, gid=33, mode=40775
   unique: 4506, success, outsize: 120
unique: 4507, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
   unique: 4507, success, outsize: 16
unique: 4508, opcode: SETATTR (4), nodeid: 1, insize: 128, pid: 1417
chown / 33 33
[INF] s3fs.cpp:s3fs_chown(1634): [path=/][uid=33][gid=33]
[ERR] s3fs.cpp:s3fs_chown(1637): Could not change owner for maount point.
   unique: 4508, error: -5 (Input/output error), outsize: 16

Not sure to understand, since I can do a chown for each sub dir separatly

**Comment by ggtakec** [comment]
@MourIdri 
It seems that you run s3fs with uid=1000/gid=1000 but you try to change mount point owner uid=33/gid=33.
s3fs could not change mount point owner and permission after it running.
You can use the uid/gid/mp_umask option instead.
Please try to set those.

Thanks in advance for your assistance.

**Comment by MourIdri** [comment]
Hi ggtakec-san :)

Your are right ! I did a wrong chmod/chown command. It is working now.

**Comment by ggtakec** [comment]
@MourIdri I'm glad about your result.
I'm closing this issue.
Regards,
