### ISSUE TITLE
Debug level messages do not print/log

### ISSUE THREAD

**Issue by fstuff** [s3fs-fuse/s3fs-fuse#416]
Hello,

It seems to me that debug level messages are not being printed/logged even when the debug log level is set to "debug".

Steps to view/reproduce:

- Using version 1.79
>s3fs --version
Amazon Simple Storage Service File System V1.79(commit:d16d616) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

- Start s3fs

`sudo /usr/local/bin/s3fs $mybucket $mypath \
`
`-o use_cache="/tmp/" \
`
`-o storage_class="standard_ia" \
`
`-o url="https://s3.amazonaws.com" \
`
`-o endpoint="us-west-2" \
`
`-o ensure_diskfree="1000" \
`
`-o allow_other \
`
`-o dbglevel="debug"`

-  The following log is displayed:

> May 13 23:02:30 ip-10-0-0-215 s3fs[11950]: s3fs.cpp:set_s3fs_log_level(253): **change debug level from [CRT] to [DBG]** 
May 13 23:02:30 ip-10-0-0-215 s3fs[11950]:     PROC(uid=0, gid=0) - MountPoint(uid=497, gid=497, mode=40755)
[ec2-user@ip-10-0-0-215 gallery]$ May 13 23:02:30 ip-10-0-0-215 s3fs[11951]: s3fs.cpp:s3fs_init(3334): init v1.79(commit:d16d616) with OpenSSL
May 13 23:02:30 ip-10-0-0-215 s3fs[11951]: check services.
May 13 23:02:30 ip-10-0-0-215 s3fs[11951]:       check a bucket.
May 13 23:02:30 ip-10-0-0-215 s3fs[11951]:       URL is https://s3.amazonaws.com/$mybucket/
May 13 23:02:30 ip-10-0-0-215 s3fs[11951]:       URL changed is https://$mybucket.s3.amazonaws.com/
May 13 23:02:30 ip-10-0-0-215 s3fs[11951]:       computing signature [GET] [/] [] []
May 13 23:02:30 ip-10-0-0-215 s3fs[11951]:       url is https://s3.amazonaws.com
May 13 23:02:30 ip-10-0-0-215 s3fs[11951]:       HTTP response code 200

-   Attempt to create file in $mypath

`cp robots.txt $mypath`

- The following is the end portion of the log:

>May 13 23:02:42 ip-10-0-0-215 s3fs[11951]:     [path=/robots.txt][mode=100644]
May 13 23:02:42 ip-10-0-0-215 s3fs[11951]:       [tpath=/robots.txt]
May 13 23:02:42 ip-10-0-0-215 s3fs[11951]:       create zero byte file object.
May 13 23:02:42 ip-10-0-0-215 s3fs[11951]:       URL is https://s3.amazonaws.com/$mybucket/robots.txt
May 13 23:02:42 ip-10-0-0-215 s3fs[11951]:       URL changed is https://$mybucket.s3.amazonaws.com/robots.txt
May 13 23:02:42 ip-10-0-0-215 s3fs[11951]:       computing signature [PUT] [/robots.txt] [] []
May 13 23:02:42 ip-10-0-0-215 s3fs[11951]:       url is https://s3.amazonaws.com
May 13 23:02:42 ip-10-0-0-215 s3fs[11951]:       uploading... [path=/robots.txt][fd=-1][size=0]
May 13 23:02:42 ip-10-0-0-215 s3fs[11951]:       **HTTP response code 403 was returned, returning EPERM**
May 13 23:02:42 ip-10-0-0-215 s3fs[11951]:       delete stat cache entry[path=/robots.txt]

- The bolded log line from the prior snippet appears to come from a call to S3fsCurl::RequestPerform(),  [curl.cpp, lines 1956-1959](https://github.com/s3fs-fuse/s3fs-fuse/blob/master/src/curl.cpp#L1956):

`         case 403:
`
`            S3FS_PRN_INFO3("HTTP response code 403 was returned, returning EPERM");
`
`            S3FS_PRN_DBG("Body Text: %s", (bodydata ? bodydata->str() : ""));
`
`            return -EPERM;`

As shown in the log printout above, however, the debug line is not logged.  As far as I can tell, no debug printouts are displaying at all.

**Comment by ggtakec** [comment]
@fstuff 
You are running s3fs as background process, then s3fs's message puts syslog(/var/messages etc) now.
S3FS_PRN_DBG function(macro) puts messages as LOG_DEBUG level of syslog messages.
Then you can change syslog.conf for putting LOG_DEBUG level log, or run s3fs as forground process.
If you run s3fs foreground, you can catch LOG_DEBUG message on stdout.

Thanks in advance for your assistance.

**Comment by fstuff** [comment]
Ok thank you for your helpful response.  I ran s3fs in the foreground and confirmed that debug messages are printed to the console.  Looks like there is some issue with my syslog configuration.  Closing this issue, thanks again.

**Comment by SachitNayak** [comment]
to run s3fs as foreground process use -f, example: s3fs -f .......

**Comment by vijayscsa** [comment]
Hi Team, which is the log file or folders to be checked for debug as my s3fs mounted fs in Redhat linux 8 disconnects frequently..  Also how shall i find out how many minutes the file system was mounted/up and running.. Thanks
