### ISSUE TITLE
s3fs should try using IAM role automatically if there are no configured credentials

### ISSUE THREAD

**Issue by nturner** [s3fs-fuse/s3fs-fuse#418]
If s3fs cannot find credentials for a bucket in a password file, instead of giving up, it would be cool if it checked for an IAM role (like when iam_role=auto has been specified). 

This would allow the same mount options to work for systems that are using Roles and those that are using static credentials files, and would be consistent with how the upstream AWS tools work.

**Comment by ggtakec** [comment]
@nturner Thanks for you help, we were able to implement it.
Regards,

**Comment by lou-k** [comment]
@ggtakec, is this truely supported in https://github.com/s3fs-fuse/s3fs-fuse/releases/tag/v1.80 ? It seems s3fs still requires a password file even if the roles are specified.
