### ISSUE TITLE
syntax error near unexpected token `common_lib_checking,'

### ISSUE THREAD

**Issue by david-rahrer** [s3fs-fuse/s3fs-fuse#438]
I'm attempting to build 1.80 on Ubuntu 14.04 and get this error on configure:

```
./configure: line 4285: syntax error near unexpected token `common_lib_checking,'
./configure: line 4285: `PKG_CHECK_MODULES(common_lib_checking, fuse >= ${min_fuse_version} libcurl >= 7.0 libxml-2.0 >= 2.6)'
```
I've verified that those package versions are above that but it is a syntax error anyway. And min_fuse_version is defined on line # 4140.

```
case "$target" in
   *-darwin* )
      # Do something specific for mac
      min_fuse_version=2.7.3
      ;;
   *)
      # Default Case
      # assume other supported linux system
      min_fuse_version=2.8.4
      ;;
esac
```
I've tried replacing the variable directly with 2.8.4 but get the same error. Have I missed something?

**Comment by david-rahrer** [comment]
I'm going to close this as I started all over and cloned the git instead of using the release and also reinstalled all the necessary packages and it worked fine after. I don't know what it was, but it likely isn't an issue. Thanks.

**Comment by hierony94** [comment]
What is the necessary packages @david-rahrer 
Because after I change my Dockerfile to provision PHP7, it screw it.
(When my Dockerfile provision PHP5 it run smoothly).

Thanks.

**Comment by gsaslis** [comment]
fwiw, i'm also having this issue...

**Comment by AstroTom** [comment]
Also having the issue in Ubuntu 14.04

**Comment by johnh530** [comment]
For Ubuntu 20.04 doing:
`sudo apt-get install build-essential libcurl4-openssl-dev libxml2-dev pkg-config libssl-dev libfuse-dev ./autogen.sh `
fixed it as well
johnh...
