### ISSUE TITLE
(vsftpd) mounting to a directory to be used as ftp user home dir

### ISSUE THREAD

**Issue by ramotswa** [s3fs-fuse/s3fs-fuse#439]
Hello all,

I am following [this](http://resources.intenseschool.com/amazon-aws-howto-configure-a-ftp-server-using-amazon-s3/) / [this](http://cloudacademy.com/blog/s3-ftp-server/) (and others) - and I am getting stuck at the same point every time. 
I create the folder to mount to. I mount to it and then that's all fine. I can browse my s3 data via command line. 
I do this as root.

Then I create a new user and set the home directory as the mount folder. 

However when I connect I always get the silly 'OOPS: cannot change directory:' message. 

I have a feeling it has to do with permissions - and when I look at the permissions of the mounted folder as root it's drwx------, but when looking at them just as the ubuntu user, they are; d????????? 

Is that to be expected?

Thanks for any tips.

**Comment by ggtakec** [comment]
@ramotswa 
You can use mp_umask option which is specified permission mode for mount point directory.
Please try to specify it.
Thanks in advance for your help.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
Is this problem continuing?
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
