### ISSUE TITLE
Extremely expensive on LIST actions

### ISSUE THREAD

**Issue by drtweety** [s3fs-fuse/s3fs-fuse#442]
I realise this isn't the best place to ask, but if I constantly go in and out of the mounted directory won't it make too many LIST requests, ending up in costing quite a bit on S3 because they charge per request?

**Comment by andrewgaul** [comment]
Amazon charges 0.5 cents per 1000 LIST requests so this should not add up to much.  s3fs has a metadata cache if you worry about this cost.
