### ISSUE TITLE
Use case suitabilty

### ISSUE THREAD

**Issue by codecowboy** [s3fs-fuse/s3fs-fuse#450]
I have some legacy code on a website which looks for video files to serve for download at an absolute path on file system. The disk is filling up and there is no money to rewrite the website code or buy expensive diskspace. Could I mount an s3 bucket using s3fs-fuse as a crude workaround to this problem? Could it handle concurrent file requests from apache?

**Comment by ggtakec** [comment]
@codecowboy 
Probabry you can set a directory path for apache using to mountpoint by s3fs.

I think that there is no problem without performance.
But you only are care for that s3fs does not exclusive control for the file.

Please try to use s3fs for your apache working directories.
Regards,

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
I will close this, but if the problem persists, please reopen or post a new issue.
