### ISSUE TITLE
IAM user with S3 policy for access into specific folder - won't work....

### ISSUE THREAD

**Issue by SysEngDan** [s3fs-fuse/s3fs-fuse#452]
Example:

Bucket name: **dans_test_bucket**
Folders within bucket: **/folder1/folder2/**
IAM User: **dans_test_user**
Policy: allow dans_test_user access only into dans_test_bucket/folder1/folder2/*

Policy:

```
{
  "Statement": [
    {
      "Sid": "Test Policy",
      "Action": "s3:*",
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::dans_test_bucket/folder1/folder2/*",
      "Principal": {
        "AWS": [
          "arn:aws:iam::1234567890:user/dans_test_user"
        ]
      }
    }
  ]
```

}

How do I configure the local mount and CLI to access files in dans_test_bucket/folder1/folder2/ ?

**Comment by bengoodwyn** [comment]
s3:ListBucket on arn:aws:s3:::dans_test_bucket must also be granted to the user. This applies to the entire bucket so that the IAM user would be able to list ALL objects in the entire bucket (seeing the object names of ALL objects), but would only be able to access the objects with the folder1/folder2/ prefix.

**Comment by rodrigosrangel** [comment]
I have the same problem reading files from a bucket, not owed by me.
The "owner" defined one folder for each of his clients (I'm one of them) and won't grant me the s3:ListBucket arguing that I can't identify all his other clients.
So I got stuck ,Created an account on AWS for testing this behavior and have no idea about how to solve it. Any ideas?

**Comment by anmolnagpal** [comment]
https://www.cloudberrylab.com/blog/how-to-give-user-access-to-an-s3-folder-with-cloudberry-explorer/

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
I will close this, but if the problem persists, please reopen or post a new issue.
