### ISSUE TITLE
FreeBSD: failed to open fuse device: No such file or directory

### ISSUE THREAD

**Issue by landaire** [s3fs-fuse/s3fs-fuse#457]
Followed all of the instructions, the FUSE kernel module is loaded:

```
# kldstat
Id Refs Address            Size     Name
 1    9 0xffffffff80200000 17bc6a8  kernel
 2    1 0xffffffff819bd000 1a2b8    fuse.ko
 3    1 0xffffffff81c11000 32d6a    pf.ko
 4    1 0xffffffff81c44000 6469     nullfs.ko
 5    1 0xffffffff81c4b000 56c6     fdescfs.ko
```

Trying to mount my s3 bucket and:

```
# s3fs MYBUCKET /usr/home/ftp/s3/ -o /etc/passwd-s3fs
fuse: failed to open fuse device: No such file or directory
```

Any ideas? I can successfully access the bucket with Transmit using these credentials.

**edit**: I just noticed that the latest version available in `pkg` is 1.78, which is very old. I'll see if I can build from source.

**Comment by jhgorse** [comment]
Did you ever resolve this?

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
Is this problem continuing?
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
