### ISSUE TITLE
FreeNAS :  mount_fusefs: /dev/fuse on /mnt/test: Operation not permitted 

### ISSUE THREAD

**Issue by sachinkarale** [s3fs-fuse/s3fs-fuse#458]
I am trying to mount s3 bucket by s3fs-fuse on FreeNAS machine from jail but facing some errors 
root@amazon:/ # s3fs freenas-bucket /mnt/test/  
mount_fusefs: /dev/fuse on /mnt/test: Operation not permitted  
fuse: failed to mount file system: Invalid argument 
I am able to do this thing with same commands in ubuntu 14 ,

**Comment by ggtakec** [comment]
We kept this issue open for a long time.

Is this problem continuing?
You should check /etc/fuse.conf and user_allow_other value in it.

We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
