### ISSUE TITLE
chmod does not work

### ISSUE THREAD

**Issue by ju4npabl0** [s3fs-fuse/s3fs-fuse#459]
Hello!

I was trying to chmod the folders inside the mount point but it doesn't work.

My goals are:
1. /mnt/mys3bucket/ should have 755 permissions (for chroot)
2. parent_folder and child_folder should both have 775 permissions

Is this possible to achieve?

**Mount Command:**

`s3fs mys3bucket /mnt/mys3bucket -o use_cache=/tmp -o allow_other -o umask=022 -o iam_role=S3FullAccess -o endpoint=us-east-1`

**/etc/fstab**

`s3fs#mys3bucket /mnt/mys3bucket fuse _netdev,use_cache=/tmp,allow_other,umask=022,iam_role=S3FullAccess,endpoint=us-east-1 0 0`

**Tests:**

```
[root@ec2 ~]# mkdir -pv /mnt/mys3bucket/parent_folder/child_folder
mkdir: created directory ‘/mnt/mys3bucket/parent_folder’
mkdir: created directory ‘/mnt/mys3bucket/parent_folder/child_folder’
[root@ec2 ~]#
```

```
[root@ec2 ~]# chmod -Rc 775 /mnt/mys3bucket/parent_folder
mode of ‘/mnt/mys3bucket/parent_folder’ changed from 0755 (rwxr-xr-x) to 0775 (rwxrwxr-x)
mode of ‘/mnt/mys3bucket/parent_folder/child_folder’ changed from 0755 (rwxr-xr-x) to 0775 (rwxrwxr-x)
[root@ec2 ~]#
```

```
[root@ec2 ~]# ls -ld /mnt/mys3bucket/ /mnt/mys3bucket/parent_folder /mnt/mys3bucket/parent_folder/child_folder
drwxr-xr-x 1 root root 0 Jan  1  1970 /mnt/mys3bucket/
drwxr-xr-x 1 root root 0 Aug  7 07:48 /mnt/mys3bucket/parent_folder
drwxr-xr-x 1 root root 0 Aug  7 07:48 /mnt/mys3bucket/parent_folder/child_folder
[root@ec2 ~]#   
```

Thank you!

**Comment by ju4npabl0** [comment]
Hello!

Gentle follow up on this.

Thank you!

**Comment by ggtakec** [comment]
Hi, @ju4npabl0 
You run s3fs with umask=022 option, it means umask 022 for all files/directories.
Thus you could not work chmod 0775 to files, if you need to access as 0775 files, you should change umask option value.
Regards,

**Comment by gsaslis** [comment]
@ju4npabl0 are you sure you meant `-o umask=022` and not `-o mp_umask=022` ?

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
Is this problem continuing?
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
