### ISSUE TITLE
Operation not permitted using ahbe_conf

### ISSUE THREAD

**Issue by luizrojo** [s3fs-fuse/s3fs-fuse#46]
I'm trying to use ahbe_conf to set specific headers, but when enabled I'm getting a "Operation not permitted" error while copying files to my bucket.

My ahbe_conf only line ".js     Content-Type    charset=utf-8"

I tried to use the example file to test, but I get the same errors.

Version of s3fs being used (s3fs --version): 1.74

Version of fuse being used (pkg-config --modversion fuse): 2.9.3

System information (uname -a): Linux "hostname" 3.4.66-55.43.amzn1.x86_64 #1 SMP Wed Oct 16 06:26:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Distro (cat /etc/issue): Amazon Linux AMI release 2013.09

/etc/fstab entry (if applicable): s3fs#"bucket_name" /export/s3/lib fuse _netdev,use_cache=/tmp,use_rrs=1,default_acl=public-read,ahbe_conf=/etc/s3fs/ahbe.conf,allow_other,uid=222,gid=500 0 0

**Comment by ggtakec** [comment]
I'm sorry about this Issue had been left at a long period of time.

If you have this problem yet, please try to use latest code.
("-f", "dbglevel" and "curldbg" options help to solve your problem.)
And if you found a problem, please post new issue.

Thanks in advance for your help.
