### ISSUE TITLE
How to use umask and cp all local file to bucket with same local 

### ISSUE THREAD

**Issue by internalG** [s3fs-fuse/s3fs-fuse#460]
1. The default  allow_other option gives the folder 777 permissions but I only want it at 2775, can umask help this?
2. When I use cp -rp to copy my local files to bucket, the copied files in bucked don't have the same owner as local files. Is it a special issue for s3fs?

TIA

**Comment by ggtakec** [comment]
@internalG I'm sorry for late reply.

1. You can use mp_umask option, please see man page.
2. It was a problem due to two reasons
   Latest s3fs supports xattr, but thereby s3fs can not set permissions by the behavior of FUSE(1).
   And if s3fs does not support it, s3fs has a bug by itself(2).

I already fixed and tested for case (2) and it worked good, but case(1) is not solved yet.
I try to check FUSE and s3fs now, please wait a while.

Thanks in advance for your help.

**Comment by ggtakec** [comment]
I fixed case (2) by #466.
And duplicated this issue to #467.
Please wait a while.
Regards,

**Comment by internalG** [comment]
Thanks a lot! I'm a little confused by current situation. The xattr and cp -p are mutex. The official decision is to use use_xattr option to enable xattr explicitly, and -p option is enabled by default, right?

**Comment by ggtakec** [comment]
Hi @internalG 
I think that s3fs must operate the cp command with preserve mode as default operation.
If there is no mistake in my s3fs check, cp command does not work as a preserve(file mode only is affected) when s3fs handles the xattrs for FUSE operation.
(If there is my mistake, I have to understand it and made a duplicated Issue(#467) for that.)
Thus I will change xattr handling by option, it will like "use_xattr" option.

I believe that most users are not affected by this change.
And s3fs will can also suppress the extra request without this option.

Regards,

**Comment by internalG** [comment]
Nice! Keep forward.

**Comment by ggtakec** [comment]
@internalG 
I merged #471 for this second problem.
Then s3fs works without the extended attribute as deafult, so you can copy a file with preserve file mode.
Please try to use latest master branch codes.
Regards,

**Comment by internalG** [comment]
Roger! 👍

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
I will close this, but if the problem persists, please reopen or post a new issue.
