### ISSUE TITLE
OSXFUSE: force ejecting (no response from user space 5)

### ISSUE THREAD

**Issue by dcow** [s3fs-fuse/s3fs-fuse#463]
I'm using `s3fs` to try and list a rather large directory (many entries). The bucket mounts successfully but, when trying to list, `ls` hangs for a bit then reports that the volume is no longer mounted. That's the only error message I receive.

**Comment by ggtakec** [comment]
@dcow 
How many files in directory do you have?
Does s3fs keep to try to list files after you seems like s3fs hangup?

s3fs sends many requests to S3 for reading each file's attribute, probably it includes this problem.
If you can, please try to run s3fs with dbglevel option.
It reports many information about this issue.

Thanks in advance for your help.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
