### ISSUE TITLE
Fails to build on FreeBSD & MidnightBSD

### ISSUE THREAD

**Issue by laffer1** [s3fs-fuse/s3fs-fuse#476]
It appears 1.79 and 1.80 include a file that does not exist on FreeBSD or MidnightBSD. This header is a linux interface (that NetBSD appears to have a compatibility shim for).  

```
s3fs.cpp:37:10: fatal error: 'sys/xattr.h' file not found
#include <sys/xattr.h>
```

**Comment by ggtakec** [comment]
@laffer1 
Thanks for your report.
I merged #477 to master branch, please try to build latest code.
I'm closing this issue, but if you found problem, please reopen this issue.

Thanks in advance for your help.
