### ISSUE TITLE
storing syslog into s3 bucket.

### ISSUE THREAD

**Issue by yuvarajanlga** [s3fs-fuse/s3fs-fuse#478]
Hi ,

I use s3 bucket to store the syslog . Its working fine. But the logs are updating in bucket after restarting the rsyslog service. 

I configured s3 with IAM policy.  And i mounted with the following command

s3fs netsafelogs /var/log/netsafe/  -o iam_role="auto"

Please let me know, how to frequently update the logs in s3bucket.

**Comment by brianabrams** [comment]
Check out Logstash or AWS Cloudwatch Logs Agent. It may be a better option for your use case.

**Comment by ggtakec** [comment]
@yuvarajanlga I'm sorry for my late reply.
In s3fs, the trigger to upload a file is to flush(or close) the file.
I think that syslog files mounting by s3fs is not good for performance.

Then you should use AWS Cloudwatch as @brianabrams said.

Thanks in advance for your help.
(I'm closing this issue, but if you have more problem please reopen this issue.)
