### ISSUE TITLE
Content-Length is searched for in case sensitive manner

### ISSUE THREAD

**Issue by jdanders** [s3fs-fuse/s3fs-fuse#480]
RFC 7230 states: "Each header field consists of a **case-insensitive** field name followed by a colon (":")"

If the HTTP header coming back from the S3 server has 'content-length:' in it instead of 'Content-Length:' then s3fs fails to find the size and reports the file has 0 length.

I believe the problem code is src/s3fs_util.cpp line [721](https://github.com/s3fs-fuse/s3fs-fuse/blob/1a93897e8510a618686510dd25bb8bf033fbfd69/src/s3fs_util.cpp#L721), where a case-sensitive find is performed.

**Comment by ggtakec** [comment]
@jdanders Thanks for your help.
I fixed this issue by #488(#489), please try to check latest codes.
Regards,
