### ISSUE TITLE
Content-Type set to application/octet-stream during recursive copy

### ISSUE THREAD

**Issue by cowmix88** [s3fs-fuse/s3fs-fuse#481]
I'm moving some javascript files from some nested folders onto an s3fs mount. If I don't use the recursive flag "-r" then the files have the Content-Type marked correctly was "text/javascript" but as soon as I use recursive flag to also copy over the nested folders and their files all files get marked as application/octet-stream.

**Comment by cowmix88** [comment]
Ah I found the issue it looks like its because these files are actually links instead of the actual file. S3Fs looks up the content-type of the link itself instead of the target file resulting in the wrong Content-Type. Is there a way to make S3FS use the content type of the link target?

**Comment by ggtakec** [comment]
@cowmix88 I'm very sorry for late my reply.
The content type of the symbolic link is application/octet-stream.
If you want to change the content-type for this symbolic link, specifying the ahbe_conf option is the only way to do it.
Please refer to the test/sample_ahbe.conf file and describe the following contents and specify it in the ahbe_conf option.
```
.js     Content-Type   text/javascript
```
Thus, even if the *.js is a symbolic link, the content-type will be text/javascript.

I'm closing this issue, but if you have more question, please reopen this issue.
Regards,
