### ISSUE TITLE
Erroneous error message from script "configure"

### ISSUE THREAD

**Issue by MgFrobozz** [s3fs-fuse/s3fs-fuse#484]
Using f38aaa3d0e as HEAD, if libfuse-dev, libcurl4-gnutls-dev, and libxml2-dev are installed but libssl-dev is not installed, ./configure issues this error ...

> configure: error: Package requirements (fuse >= 2.8.4 libcurl >= 7.0 libxml-2.0 >= 2.6 libcrypto >= 0.9) were not met:

Installing libssl-dev will then eliminate the error.

**Comment by ggtakec** [comment]
@MgFrobozz 
If you use gnutls, you need to specify "--with-gnutls" for configure option.

You can see help configure option by "configure -h".
```
Optional Packages:
  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
  --with-nettle           s3fs build with nettle in GnuTLS(default no)
  --with-openssl          s3fs build with OpenSSL(default is no)
  --with-gnutls           s3fs build with GnuTLS(default is no)
  --with-nss              s3fs build with NSS(default is no)
```
If the SSL library option is not specified, configure will try to use openssl.

Please try to run configure with "--with-gnutls".
Thanks in advance for your assistance.
