### ISSUE TITLE
Support ACD

### ISSUE THREAD

**Issue by xelra** [s3fs-fuse/s3fs-fuse#490]
Is it possible, with only minor changes, to support Amazon Cloud Drive? Maybe the API is the same.

**Comment by andrewgaul** [comment]
Totally different API and outside the scope of s3fs.  Perhaps someone could write an Amazon Cloud Drive integration for [S3Proxy](https://github.com/andrewgaul/s3proxy)/[Apache jclouds](https://jclouds.apache.org/) which s3fs could use.

**Comment by ggtakec** [comment]
I am sorry, s3fs does not have a means, now.(This Issue is similar to #496)
@andrewgaul Thanks for your help.
