### ISSUE TITLE
URGENT QUESTION: Operation not permitted

### ISSUE THREAD

**Issue by victropolis** [s3fs-fuse/s3fs-fuse#492]
Another app that uses the AWS S3 Java SDK to upload content to an s3 bucket.  When I look at the bucket using s3fs, I get "Operation not permitted" on the directories.

The FAQ talks about setting the following headers properly, but it doesn't go into a lot of detail.

- x-amz-meta-mtime 
- x-amz-meta-mode 
- x-amz-meta-uid 
- x-amz-meta-gid

Can you please give me some examples?  Or, point me at some sample code somewhere?  Thanks in advance!

**Comment by ggtakec** [comment]
@victropolis I'm sorry for my late reply.
You can do ls command under mount point, then you can see permission made by those header about files(objects).
```
$ ls -la
total 32798
drwxrwxrwx 1 root  root         0 Jan  1  1970 .
drwxr-xr-x 8 root  root      4096 Jun  2  2014 ..
drwxrwxrwx 1 users users        0 Oct 30 07:53 dir1
drwxr-xr-x 1 users users        0 Sep  2  2013 dir2
-rw-r--r-- 1 users users        0 Nov 28 10:08 file1
-rwxr-xr-x 1 users users      186 Nov 18  2013 exefile1
```
Those headers means and sets following: 
x-amz-meta-mtime is modified time by decimal unixtime
x-amz-meta-mode  is file mode by decimal
x-amz-meta-uid   is uid by decimal
x-amz-meta-gid   is gid by decimal

You can see man page for mount command.

To solve this issue problem, you should use umask and mp_umask option for s3fs.
You can see man page for s3fs about these options.

Thanks in advance for your assistance.
(I'm closing this issue, but if you have more question, please reopsn this issue.)
