### ISSUE TITLE
Java process crashed while trying to Copy File - (urgent help needed)

### ISSUE THREAD

**Issue by nilasissen** [s3fs-fuse/s3fs-fuse#493]
Hello
when i am trying to run  FileUtils.copyFile(srcFilePath, destFilePath); this code at that time java process crashed. The destFilePath is the mounted path of Amazon s3 which is using s3fs. we can not find any server log after this crash.
 error- "Transport endpoint is not connected"

**Comment by andrewgaul** [comment]
Please re-run s3fs with `-d -d -f -o f2 -o curldbg` flags and attach relevent logs to this issue.

**Comment by gaul** [comment]
@nilasissen Please reopen if you can reproduce these symptoms with the latest version which includes several crash fixes.
