### ISSUE TITLE
does s3fs supports active directory authentication on namespace?

### ISSUE THREAD

**Issue by vgadhadaran** [s3fs-fuse/s3fs-fuse#496]

**Comment by andrewgaul** [comment]
No, s3fs supports only AWS v2 and v4 signatures.  You could add support for Active Directory to something like [S3Proxy](https://github.com/andrewgaul/s3proxy) which would proxy S3 requests, but this is a significant undertaking.

**Comment by ggtakec** [comment]
I am sorry, s3fs does not have a means, now.
@andrewgaul Thanks
