### ISSUE TITLE
diskspace issue

### ISSUE THREAD

**Issue by vgadhadaran** [s3fs-fuse/s3fs-fuse#497]
[CRT] s3fs.cpp:set_s3fs_log_level(253): change debug level from [CRT] to [INF]
[INF]     s3fs.cpp:set_moutpoint_attribute(4151): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
s3fs: There is no enough disk space for used as cache(or temporary) directory by s3fs.
 
I am getting the error although I have enough disk space. S3testdemo1 has around 300gb free space and my /tmp/nav folder has 50g of free space.. what should be the work around?

**Comment by andrewgaul** [comment]
Can you add some logging to `FdManager::IsSafeDiskSpace` so we can diagnose this further?

**Comment by ggtakec** [comment]
@vgadhadaran I'm sorry for my late reply,
And Thanks @andrewgaul 

s3fs checks free disk space at starting by using statvfs function.
So you do not specify use_cache option, s3fs checks free disk space by "/tmp/" path.
It seems that this result is false, thus statvfs result is under 10MB.

Could you add the debugging codes in FdManager::GetFreeDiskSpace() in fdcache.cpp?
(or in FdManager::IsSafeDiskSpace() function, andrewgaul said.)

Thanks in advance for your help.

**Comment by vgadhadaran** [comment]
[root@k0001279 rediff]# s3fs phase1 /tmp/aws -o nocopyapi -o use_path_request_style -o nomultipart -o sigv2 -o url=https://awspoc.hcpdevn1.travt.net/ -o allow_other -o passwd_file=/etc/passwd-s3fs -o no_check_certificate -o nonempty
s3fs: There is no enough disk space for used as cache(or temporary) directory by s3fs.

1. Even though I didnt set use_cache option, where does it points to the temp directory , as it prompts there is no enough disk space?

2. Adding this line in fdcache.cpp will be sufficient

FdManager::InitEnsureFreeDiskSpace();
  if(!FdManager::IsSafeDiskSpace(NULL, S3fsCurl::GetMultipartSize())){
    S3FS_PRN_EXIT("There is no enough disk space for used as cache(or temporary) directory by s3fs.");
    exit(EXIT_FAILURE);
  }

3. Is there any command parameters that I can pass on with s3fs command for diskspace?

**Comment by ggtakec** [comment]
@vgadhadaran I'm sorry fore my late reply.

1. when does not specify use_cache option, default path is /tmp
2. we changed codes about checking free disk space recently, #557.
   so please try to use latest version on mster branch.
3. ensure_diskfree option.

I am sorry to have trouble, if you can please retry to use latest codes.
Thanks in advance for your assistance.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
Is this problem continuing?
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
