### ISSUE TITLE
HTTP response code 409 error

### ISSUE THREAD

**Issue by vgadhadaran** [s3fs-fuse/s3fs-fuse#500]
I am trying to move the file however getting the below error

```
[root@k8002180 abc]# mv 500m1 /tmp/s3demo
mv: preserving times for `/tmp/s3demo/500m1': Input/output error
mv: closing `/tmp/s3demo/500m1': Input/output error
```

Digging at the log file I am seeing the response code return i 409 . how to fix this?

[

**Comment by andrewgaul** [comment]
Do you use Hitachi S3 storage?  You may have encountered an issue where HCP does not support overwriting existing objects.  #436 tracks a similar issue.

**Comment by vgadhadaran** [comment]
yes, its hitachi. however  I am getting this error when trying to move the data for first time and not overwriting it.

**Comment by ggtakec** [comment]
@vgadhadaran @andrewgaul 
Please see my #436 comment, I think HCP can not over write any object when the versioning is not enabled.

**Comment by ggtakec** [comment]
#436 was closed, solve this issue by enable versioning on HCP.

**Comment by vgadhadaran** [comment]
versioning enabled but still the same issue

May  8 12:10:01 k0001808 s3fs[2212]:       delete stat cache entry[path=/fs_ro_test]
May  8 12:10:01 k0001808 s3fs[2212]:       [tpath=/fs_ro_test]
May  8 12:10:01 k0001808 s3fs[2212]:       [tpath=/fs_ro_test][bpath=][save=][sseckeypos=-1]
May  8 12:10:01 k0001808 s3fs[2212]:       URL is https://awspoc.hcpdevn1.travt.net/phase1/fs_ro_test
May  8 12:10:01 k0001808 s3fs[2212]:       URL changed is https://phase1.awspoc.hcpdevn1.travt.net/fs_ro_test
May  8 12:10:01 k0001808 s3fs[2212]:       computing signature [HEAD] [/fs_ro_test] [] []
May  8 12:10:01 k0001808 s3fs[2212]:       url is https://awspoc.hcpdevn1.travt.net
May  8 12:10:01 k0001808 s3fs[2212]:       HTTP response code 200
May  8 12:10:01 k0001808 s3fs[2212]:       add stat cache entry[path=/fs_ro_test]
May  8 12:10:01 k0001808 s3fs[2212]:       [path=/fs_ro_test][fd=8][time=1494259801]
May  8 12:10:01 k0001808 s3fs[2212]: [path=/fs_ro_test][fd=8]
May  8 12:10:01 k0001808 s3fs[2212]:       [tpath=][path=/fs_ro_test][fd=8]
May  8 12:10:01 k0001808 s3fs[2212]: [path=/fs_ro_test][mtime=1494259801]
May  8 12:10:01 k0001808 s3fs[2212]:     [path=/fs_ro_test]
May  8 12:10:01 k0001808 s3fs[2212]:       [tpath=/fs_ro_test]
May  8 12:10:01 k0001808 s3fs[2212]:       URL is https://awspoc.hcpdevn1.travt.net/phase1/fs_ro_test
May  8 12:10:01 k0001808 s3fs[2212]:       URL changed is https://phase1.awspoc.hcpdevn1.travt.net/fs_ro_test
May  8 12:10:01 k0001808 s3fs[2212]:       computing signature [PUT] [/fs_ro_test] [] []
May  8 12:10:01 k0001808 s3fs[2212]:       url is https://awspoc.hcpdevn1.travt.net
May  8 12:10:01 k0001808 s3fs[2212]:       copying... [path=/fs_ro_test]
May  8 12:10:01 k0001808 s3fs[2212]:       HTTP response code 200
May  8 12:10:01 k0001808 s3fs[2212]:       [path=/fs_ro_test][fd=8][time=1494259801]
May  8 12:10:01 k0001808 s3fs[2212]:       delete stat cache entry[path=/fs_ro_test]
May  8 12:10:01 k0001808 s3fs[2212]: [path=/fs_ro_test]
May  8 12:10:01 k0001808 s3fs[2212]:       [tpath=/fs_ro_test]
May  8 12:10:01 k0001808 s3fs[2212]:       [tpath=/fs_ro_test][bpath=][save=][sseckeypos=-1]
May  8 12:10:01 k0001808 s3fs[2212]:       URL is https://awspoc.hcpdevn1.travt.net/phase1/fs_ro_test
May  8 12:10:01 k0001808 s3fs[2212]:       URL changed is https://phase1.awspoc.hcpdevn1.travt.net/fs_ro_test
May  8 12:10:01 k0001808 s3fs[2212]:       computing signature [HEAD] [/fs_ro_test] [] []
May  8 12:10:01 k0001808 s3fs[2212]:       url is https://awspoc.hcpdevn1.travt.net
May  8 12:10:01 k0001808 s3fs[2212]:       HTTP response code 200
May  8 12:10:01 k0001808 s3fs[2212]:       add stat cache entry[path=/fs_ro_test]
May  8 12:10:01 k0001808 s3fs[2212]: [path=/fs_ro_test][fd=8]
May  8 12:10:01 k0001808 s3fs[2212]:       [tpath=][path=/fs_ro_test][fd=8]
May  8 12:10:01 k0001808 s3fs[2212]: [path=/fs_ro_test][fd=8]
May  8 12:10:01 k0001808 s3fs[2212]:       delete stat cache entry[path=/fs_ro_test]
May  8 12:10:01 k0001808 s3fs[2212]:       [path=/fs_ro_test][fd=8]
May  8 12:10:01 k0001808 s3fs[2212]:       [path=/fs_ro_test][fd=8]
May  8 12:25:01 k0001808 s3fs[2212]: [path=/fs_ro_test]
May  8 12:25:01 k0001808 s3fs[2212]:       [tpath=/fs_ro_test]
May  8 12:25:01 k0001808 s3fs[2212]:       [tpath=/fs_ro_test][bpath=][save=][sseckeypos=-1]
May  8 12:25:01 k0001808 s3fs[2212]:       URL is https://awspoc.hcpdevn1.travt.net/phase1/fs_ro_test
May  8 12:25:01 k0001808 s3fs[2212]:       URL changed is https://phase1.awspoc.hcpdevn1.travt.net/fs_ro_test
May  8 12:25:01 k0001808 s3fs[2212]:       computing signature [HEAD] [/fs_ro_test] [] []
May  8 12:25:01 k0001808 s3fs[2212]:       url is https://awspoc.hcpdevn1.travt.net
May  8 12:25:02 k0001808 s3fs[2212]:       HTTP response code 200
May  8 12:25:02 k0001808 s3fs[2212]:       add stat cache entry[path=/fs_ro_test]
May  8 12:25:02 k0001808 s3fs[2212]: [path=/fs_ro_test][flags=34817]
May  8 12:25:02 k0001808 s3fs[2212]:       delete stat cache entry[path=/fs_ro_test]
May  8 12:25:02 k0001808 s3fs[2212]:       [tpath=/fs_ro_test]
May  8 12:25:02 k0001808 s3fs[2212]:       [tpath=/fs_ro_test][bpath=][save=][sseckeypos=-1]
May  8 12:25:02 k0001808 s3fs[2212]:       URL is https://awspoc.hcpdevn1.travt.net/phase1/fs_ro_test
May  8 12:25:02 k0001808 s3fs[2212]:       URL changed is https://phase1.awspoc.hcpdevn1.travt.net/fs_ro_test
May  8 12:25:02 k0001808 s3fs[2212]:       computing signature [HEAD] [/fs_ro_test] [] []
May  8 12:25:02 k0001808 s3fs[2212]:       url is https://awspoc.hcpdevn1.travt.net
May  8 12:25:02 k0001808 s3fs[2212]:       HTTP response code 200
May  8 12:25:02 k0001808 s3fs[2212]:       add stat cache entry[path=/fs_ro_test]
May  8 12:25:02 k0001808 s3fs[2212]:       [path=/fs_ro_test][fd=8][time=1494259802]
May  8 12:25:02 k0001808 s3fs[2212]: [path=/fs_ro_test][fd=8]
May  8 12:25:02 k0001808 s3fs[2212]:       [tpath=][path=/fs_ro_test][fd=8]
May  8 12:25:02 k0001808 s3fs[2212]: [path=/fs_ro_test][mtime=1494260702]
May  8 12:25:02 k0001808 s3fs[2212]:     [path=/fs_ro_test]
May  8 12:25:02 k0001808 s3fs[2212]:       [tpath=/fs_ro_test]
May  8 12:25:02 k0001808 s3fs[2212]:       URL is https://awspoc.hcpdevn1.travt.net/phase1/fs_ro_test
May  8 12:25:02 k0001808 s3fs[2212]:       URL changed is https://phase1.awspoc.hcpdevn1.travt.net/fs_ro_test
May  8 12:25:02 k0001808 s3fs[2212]:       computing signature [PUT] [/fs_ro_test] [] []
May  8 12:25:02 k0001808 s3fs[2212]:       url is https://awspoc.hcpdevn1.travt.net
May  8 12:25:02 k0001808 s3fs[2212]:       copying... [path=/fs_ro_test]
May  8 12:25:02 k0001808 s3fs[2212]:       HTTP response code = 409, returning EIO

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
Is this problem continuing?
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
