### ISSUE TITLE
s3fs mount to CentOS 6.5

### ISSUE THREAD

**Issue by ZerozhengCN** [s3fs-fuse/s3fs-fuse#510]
Hi, All
The mount was success before, but when I restart the VM want to mount again. Here is very strange situation. 

```
[root@localhost ~]# s3fs mount mnts3fs ~/mntpoint/ -o nocopyapi -o use_path_request_style -o nomultipart -o sigv2 -o url=http://172.16.165.162 -d -f -o curldbg -of2 -o allow_other -o passwd_file=/etc/pwd
[CRT] s3fs.cpp:set_s3fs_log_level(254): change debug level from [CRT] to [INF] 
[CRT] s3fs.cpp:set_s3fs_log_level(254): change debug level from [INF] to [DBG] 
s3fs: unable to access MOUNTPOINT mnts3fs: No such file or directory
[root@localhost ~]# s3fs mnts3fs ~/mntpoint/ -o nocopyapi -o use_path_request_style -o nomultipart -o sigv2 -o url=http://172.16.165.162 -d -f -o curldbg -of2 -o allow_other -o passwd_file=/etc/pwd
[CRT] s3fs.cpp:set_s3fs_log_level(254): change debug level from [CRT] to [INF] 
[CRT] s3fs.cpp:set_s3fs_log_level(254): change debug level from [INF] to [DBG] 
[INF]     s3fs.cpp:set_mountpoint_attribute(4196): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
[CRT] s3fs.cpp:s3fs_init(3375): init v1.80(commit:8a11d7b) with OpenSSL
[WAN] curl.cpp:InitShareCurl(483): curl_share_setopt(SSL SESSION) returns 1(Unknown share option), but continue without shared ssl session data.
[INF] s3fs.cpp:s3fs_check_service(3753): check services.
[INF]       curl.cpp:CheckBucket(2883): check a bucket.
[DBG] curl.cpp:GetHandler(272): Get handler from pool: 31
[INF]       curl.cpp:prepare_url(4199): URL is http://172.16.165.162/mnts3fs/
[INF]       curl.cpp:prepare_url(4231): URL changed is http://172.16.165.162/mnts3fs/
[DBG] curl.cpp:RequestPerform(1916): connecting to URL http://172.16.165.162/mnts3fs/
* About to connect() to 172.16.165.162 port 80 (#0)
*   Trying 172.16.165.162... * connected
* Connected to 172.16.165.162 (172.16.165.162) port 80 (#0)
> GET /mnts3fs/ HTTP/1.1
User-Agent: s3fs/1.80 (commit hash 8a11d7b; OpenSSL)
Host: 172.16.165.162
Accept: */*
Authorization: AWS kqlBnSEzCrKqsoRTnO40:eCB1Cu9slnTR+n1MAJjTQryBDvA=
Date: Tue, 29 Nov 2016 00:17:00 GMT

< HTTP/1.1 200 OK
< Date: Tue, 29 Nov 2016 00:15:38 GMT
< X-Clv-Request-Id: 4e1fec91-8008-4f3c-8390-128a2e775870
< Accept-Ranges: bytes
< Server: Cleversafe/3.8.2.19
< X-Clv-S3-Version: 2.5
< x-amz-request-id: 4e1fec91-8008-4f3c-8390-128a2e775870
< Content-Type: application/xml
< Content-Length: 857
< 
* Connection #0 to host 172.16.165.162 left intact
[INF]       curl.cpp:RequestPerform(1933): HTTP response code 200
[DBG] curl.cpp:ReturnHandler(295): Return handler to pool: 31
```

It is just stuck here, no error message, and whatever how long I wait, no any other message come out. I have to press ctrl+C jump out. Any one could help on this? Many Thanks

**Comment by ZerozhengCN** [comment]
Any one can help?

**Comment by liuyuhong66** [comment]
this is Success，you should copy some objects in  ~/mntpoint/  ,then it can give you some logs

**Comment by robert-breekie** [comment]
It mounted suucesfully. But when you mount with the s3fs command like this, it won't give you back your shell prompt. You can put an '&' at the end. Then it will be put to the background. But because you have debugging options set, i asume you'd like to see the debug output. So kickoff the command and if it mounts ok, then open another shell and see if you can access the vault.

**Comment by Aleksandaar** [comment]
Nice explanation @robert-breekie . Even-though it might seem like an error, the log actually shows it is connected.

**Comment by ggtakec** [comment]
@ZerozhengCN 
After run s3fs(with "-f" option), you connect to this server by another terminal.
And you run some command which accesses a file(or directory) in your mount point.
(ex. "ls ~/mntpoint/")
Thus you will get some log messages at first terminal if s3fs will run normally.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
Is this problem continuing?
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.

If you encounter problems with s3fs as well, try using the `dbglevel`` -d` `curldbg` or similar option to print out the log.
It contains information for the solution.
