### ISSUE TITLE
File Permission

### ISSUE THREAD

**Issue by vgadhadaran** [s3fs-fuse/s3fs-fuse#514]
An data with certain level of permission and ownership moved to an HCP /AWS S3 bucket, Can retain the same level while we are retrieving the data? If so, What conditions needs to be set on the bucket or s3fs level?

**Comment by ggtakec** [comment]
@vgadhadaran 
Please point out if I misunderstood the meaning of your question.
And about the setting of bucket of HCP I have little premise.

If HCP is compatible with S3, I think that you can read the object uploaded with s3fs without problems.

The reason for this is that s3fs gives the object an attribute in the HTTP header.
If HCP is able to grant HTTP headers to objects, I think that there is no problem.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
I will close this, but if the problem persists, please reopen or post a new issue.
