### ISSUE TITLE
S3 eventual consistency

### ISSUE THREAD

**Issue by dangmocrang** [s3fs-fuse/s3fs-fuse#515]
Hello,

As I know amazon s3 now free from eventual consistency. All regions now support read-after-write. This issue is mentioned in S3 FAQ https://aws.amazon.com/s3/faqs/

So maybe document section "Eventual consistency" is no need.

Regards,
Dung

**Comment by andrewgaul** [comment]
This is a bit subtle, although the us-standard region has strengthened its consistency guarantees, but Amazon still exhibits eventual behavior in read-after-overwrite and read-after-write-after-read scenarios:

https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel

I document these guarantees but my data are out of date:

https://github.com/andrewgaul/are-we-consistent-yet

**Comment by ggtakec** [comment]
I added URL link(FAQ) in README.md
Thanks @andrewgaul
