### ISSUE TITLE
Cache not expiring

### ISSUE THREAD

**Issue by shardebeck** [s3fs-fuse/s3fs-fuse#523]
#### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

- Version of s3fs being used (s3fs --version)
 - _example: 1.0_

Amazon Simple Storage Service File System V1.79 with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

- Version of fuse being used (pkg-config --modversion fuse)
 - _example: 2.9.4_

2.9.3

- System information (uname -a)
 - _command result: uname -a_

Linux ip-10-179-61-141 4.4.30-32.54.amzn1.x86_64 #1 SMP Thu Nov 10 15:52:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Distro (cat /etc/issue)
 - _command result: result_

- s3fs command line used (if applicable)
```
```
- /etc/fstab entry (if applicable): 
```
```s3fs#abms-static-dev /opt/ABMS fuse rw,noatime,nosuid,_netdev,allow_other,nonempty,uid=91,gid=48,umask=133,stat_cache_expire=600,enable_content_md5,del_cache,use_cache=/var/cache/s3fs 0 0

- s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
#### Details about issue

We are having an issue with the cache not expiring on the local system and any new files published to S3 are not showing up. The file shows the current date on the server and in the cache, but, when looking at the contents, it shows the old content.

Have tried updating s3fs to the latest version and am still not having any luck with the cache receiving the updated files after a designated amount of time, set in the expire parameter.

Also, tried the dbglevel=dbg parameter and it says unknown option.

Sonya

**Comment by ggtakec** [comment]
@shardebeck I'm sorry for late reply.

Now by stat_cache_expire option, s3fs updated the cached time of stat information to the time when it was accessed to that cache.
This effectively reduces the number of requests for continuous cache access.
However, this specification will cause problems like your case.
This means that you are using multiple boxes(multiple s3fs processes), accessing the target file object within the effective time, the cache will not be updated.

I have disabled the function to automatically extend this expiration time.
This will solve your problem, the codes in master branch is it.

If you want to extend the expiration date automatically as before, we added the stat_cache_interval_expire option so you can use this new option.(This option is made for compatibility.)

I'm closing this issue, but if you have any problem about this issue, please reopen this.

Regards,
