### ISSUE TITLE
Readonly / FSTAB Question

### ISSUE THREAD

**Issue by bjay1404** [s3fs-fuse/s3fs-fuse#525]
Hi, this is not an issue.

The software works great!

I'm trying to figure out how to mount a bucket as read only. I've noticed that the permissions change when I mount the folder - so chmod is obviously out. How can I mount a bucket as read only without modifying IAM credentials? Also, how can I specify an iam role / read only in fstab?

Thanks!

**Comment by hayd** [comment]
Surprising where the write is required even for ls.

Are there some specific objects that could be writable which would allow "mostly readonly"?

**Comment by ggtakec** [comment]
@bjay1404 
To restrict writing to a file, you can use umask (mp_umask).
And to restrict the change of file permissions, the execution status flag(x) must not be set the current directory.
These are the same as the file system.
If you want to adapt the restrictions to all files under the bucket, you can use the umask(mp_umask) option.
If you want to use iam role, you can use iam_role option.

(if you need more information or my fault, please reopen this issue.)
Regards,

**Comment by hayd** [comment]
@ggtakec The question is should s3fs be able to mount and read files if (either the role or api keys - I don't think that aspect is relevant) have readonly permissions to the s3 bucket?

When I tried (with readonly bucket permission) I was unable to mount. Is that expected?

**Comment by ggtakec** [comment]
@hayd 
I tried to access read only bucket which is mounted by s3fs(normal options).
It works(read the object under bucket, and could not write it, could not change permission) good for me.
example my s3fs line)
   s3fs <my read only bucket> /mnt/s3 -o allow_other,url=https://s3.amazonaws.com

Regards,
