### ISSUE TITLE
use_sse=kmsid causes HTTP response code 404 was returned, returning ENOENT

### ISSUE THREAD

**Issue by adespain** [s3fs-fuse/s3fs-fuse#526]
#### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

- Version of s3fs being used (s3fs --version)
 - _example: 1.0_
s3fs --version
Amazon Simple Storage Service File System V1.79(commit:unknown) with GnuTLS(gcrypt)

- Version of fuse being used (pkg-config --modversion fuse)
 - _example: 2.9.4_
I used apt-get install s3fs

- System information (uname -a)
 - _command result: uname -a_
uname -a
Linux ip-172-31-35-65 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Distro (cat /etc/issue)
 - _command result: result_
Ubuntu 16.04.1 LTS \n \l

- s3fs command line used (if applicable)
```
```

- /etc/fstab entry (if applicable): 
```
```
s3bucket /home/logs fuse.s3fs _netdev,-d,use_cache=/tmp,uid=deploy,gid=deploy,multireq_max=5,endpoint=us-west-2,allow_other,mp_umask=0077,use_sse=kmsid:arn:aws:kms:us-west-2:xxxxxxxxxxxx:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx,retries=3 0 0
- s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
#### Details about issue

I would like to use server side encryption with my kms key that I created.  However when I mount he bucket and then try to touch a file I get this:
touch: cannot touch 'hithere3': Input/output error

in the logs I see this:
Jan 24 23:27:12 ip-172-31-35-65 s3fs[10585]:       [tpath=/hithere3_$folder$]
Jan 24 23:27:12 ip-172-31-35-65 s3fs[10585]:       [tpath=/hithere3_$folder$][bp
ath=][save=][sseckeypos=-1]
Jan 24 23:27:12 ip-172-31-35-65 s3fs[10585]:       URL is http://s3.amazonaws.co
m/s3bucket/hithere3_%24folder%24
Jan 24 23:27:12 ip-172-31-35-65 s3fs[10585]:       URL changed is http://s3bucket.s3.amazonaws.com/hithere3_%24folder%24
Jan 24 23:27:12 ip-172-31-35-65 s3fs[10585]:       computing signature [HEAD] [/
hithere3_$folder$] [] []
Jan 24 23:27:12 ip-172-31-35-65 s3fs[10585]:       url is http://s3.amazonaws.com
Jan 24 23:27:12 ip-172-31-35-65 s3fs[10585]:       HTTP response code 404 was returned, returning ENOENT

My /etc/fstab is probably wrong but I can't figure it out, any help would be greatly appreciated, thanks!

**Comment by adespain** [comment]
I finally got it to work, and it appears you have to specify url=https:s3.amazonaws.com in order for sse_kms to work.  Hopefully that helps someone else.

**Comment by pritambarhate** [comment]
Just stumbled on this through a google Search. I think docs [here](https://github.com/s3fs-fuse/s3fs-fuse/wiki/Fuse-Over-Amazon) should updated to reflect that "https" url is required if sse_kms is used.

**Comment by aamyrrkhan** [comment]
@adespain - you are a life saver. Been digging around for days. This should be highlighted in documentation. Setting up https worked for me. Thanks

**Comment by ggtakec** [comment]
@pritambarhate @aamyrrkhan 
Thanks to you guys, I was able to submit the PR.
I hope this PR will be merged and it will be useful to you.
(The wiki page will be updated before being merged)
