### ISSUE TITLE
Do we need to install latest version of fuse?

### ISSUE THREAD

**Issue by braincert** [s3fs-fuse/s3fs-fuse#527]
S3FS automatically installs older version of fuse file system. Can we manually install latest version from https://github.com/libfuse/libfuse? Is there any drawbacks doing so?

**Comment by ggtakec** [comment]
@braincert 
s3fs requires libfuse as 2.8.4 later, it does not force an old version.
You can use libfuse 2.X.X, but not 3.x.x
if you need to use latest libfuse, you can use it in github(2.x.x).

Regards,
