### ISSUE TITLE
automount at boot *and* using IAM role

### ISSUE THREAD

**Issue by ezeeetm** [s3fs-fuse/s3fs-fuse#529]
I know we can do 

    s3fs mybucket /path/to/mountpoint -o iam_role="auto"

to use the IAM instance profile role associated with the instance.  We can also create an FSTAB entry to automount on boot.  But there is no way to pass -o iam_role="auto" to FSTAB entry. 

Is there a way to use FSTAB (or perhaps an s3fs config file) to get the iam_role="auto" to persist so the FSTAB entry can use it?

**Comment by bjay1404** [comment]
This is what the FSTAB entry should look like

s3fs#bucketname /PATHtoLocalMount fuse _netdev,iam_role=nameofiamrolenoquotes

**Comment by ggtakec** [comment]
@ezeeetm 
You can use fstab entry like @bjay1404 
(@bjay1404 thanks)
