### ISSUE TITLE
s3fs on mac

### ISSUE THREAD

**Issue by zijwang** [s3fs-fuse/s3fs-fuse#530]
- Version of s3fs being used (s3fs --version)
 - _example: 1.80

- Version of fuse being used (pkg-config --modversion fuse)
 - _example: 2.7.3

- System information (uname -a)
 - _command result: 16.4.0 Darwin Kernel Version 16.4.0 Macbook Pro

#### Details about issue

I've a s3 bucket and I'm used to use it on ec2. Now I want to mount this bucket onto my mac. The mounting process is good and I can read all the files. However, it looks like I do not have the permissions to write existed files. Any thoughts to fix that?

**Comment by lorainekv** [comment]
Does the user policy for the AWS credentials you used during s3fs setup include the PutObject action? You can check by visiting IAM in AWS console, then looking at the policies on your user account. https://aws.amazon.com/blogs/security/writing-iam-policies-how-to-grant-access-to-an-amazon-s3-bucket/

**Comment by ggtakec** [comment]
@zijwang 
If your objects do not have any meta header(x-amz-meta-*), you can see the object like following.
```
---------- 1 root root 1225 Mar 19 18:59 test_file
d--------- 1 root root    0 Mar 19 19:00 test_dir
```

s3fs needs meta header for all object, but if there is no meta information for the obejct, it looks like no permission.
To solve this, you can set meta header to all object.
Or you can use umask/mp_umask/uid/gid option for s3fs.

Regards,

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
I will close this, but if the problem persists, please reopen or post a new issue.
