### ISSUE TITLE
S3 Sync implemented?

### ISSUE THREAD

**Issue by ylluminate** [s3fs-fuse/s3fs-fuse#534]
Is Sync functionality implemented in `s3fs-fuse` as per [this](http://s3tools.org/s3cmd-sync) wherein synchronization is handled as it is explained there, namely:

> only files that don’t exist at the destination in the same version are transferred by the s3cmd sync command. By default a md5 checksum and file size is compared. This is similar to a unix rsync command, with some exceptions outlined below.

**Comment by andrewgaul** [comment]
No; s3cmd syncs files while s3fs writes files in real-time.  With the former you work locally for reading and writing then initiate a sync while with the latter you work remotely and reads and writes propagate immediately.

**Comment by ylluminate** [comment]
So [`s3backer`](https://github.com/archiecobbs/s3backer) would be a union of both of these wherein operations are performed locally and then committed to S3, right?

What I'm ultimately stabbing at here is a solution for a service like Linode that doesn't offer a block storage option (yet) and need to immediately store large amounts of data in an efficient manner.  I guess `s3fs-fuse` would match up to the need of a realtime block storage, but I worry about efficiency quite a bit on a disparate network like this where it has to go back and forth so much off (V)LAN for data...

**Comment by andrewgaul** [comment]
s3backer works well if you want a block device which asynchronously writes to S3.  s3fs works at the file level and synchronizes writes when closing a file.  This is a long shot but maybe you want to use something like [jSCSI](http://jscsi.org/)?

**Comment by ylluminate** [comment]
That is a very interesting suggestion @andrewgaul. It may be even more interesting in light of this:
http://kops.uni-konstanz.de/handle/123456789/26506
