### ISSUE TITLE
Configuration failure on CentOS 7: No package 'fuse' found

### ISSUE THREAD

**Issue by ylluminate** [s3fs-fuse/s3fs-fuse#536]
After successfully compiling libfuse via:
```
mkdir src
cd src
# Most recent version: https://github.com/libfuse/libfuse/releases
wget https://github.com/libfuse/libfuse/releases/download/fuse-3.0.0/fuse-3.0.0.tar.gz
tar xvf fuse-3.0.0.tar.gz
cd fuse-3.0.0
./configure --prefix=/usr/local
make & make install
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
ldconfig
modprobe fuse
```

I ended up hitting an error whilst configure'ing `s3fs`:
```
cd ~/src
git clone https://github.com/s3fs-fuse/s3fs-fuse.git
cd s3fs-fuse
./autogen.sh
./configure # and even with --prefix=/usr/local
```
Output with error:
```
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/xattr.h usability... yes
checking sys/xattr.h presence... yes
checking for sys/xattr.h... yes
checking attr/xattr.h usability... no
checking attr/xattr.h presence... no
checking for attr/xattr.h... no
checking sys/extattr.h usability... no
checking sys/extattr.h presence... no
checking for sys/extattr.h... no
checking s3fs build with nettle(GnuTLS)... no
checking s3fs build with OpenSSL... no
checking s3fs build with GnuTLS... no
checking s3fs build with NSS... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for common_lib_checking... no
configure: error: Package requirements (fuse >= 2.8.4 libcurl >= 7.0 libxml-2.0 >= 2.6) were not met:

No package 'fuse' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables common_lib_checking_CFLAGS
and common_lib_checking_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by ManjotS** [comment]
same here

**Comment by ggtakec** [comment]
Please check the version of fuse in your environment.
@ylluminate @ManjotS 
If yum installable version is lower than 2.8.4, please install fuse after 2.8.4.
There is explanation in [s3fs-wiki](https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes).
Alternatively, you can compile and install fuse from the source code.
(you can download it from https://github.com/libfuse/libfuse/releases, but you can not use 3.x.x.)

I'm going to close this isse, but you need more information and problem, please post new issue about it.
Regards,

**Comment by ylluminate** [comment]
This issues is resolving compilation from scratch / source code. Not using the actual package via yum and so there are no versions already installed.  This is an attempt to run 3.x instead of 2.x on CentOS.

**Comment by ylluminate** [comment]
An example tutorial that reproduces the same results:
https://www.interserver.net/tips/kb/mount-s3-bucket-centos-ubuntu-using-s3fs/

Note the specific first step regarding CentOS:
`yum remove fuse fuse-s3fs`

**Comment by ylluminate** [comment]
I've updated the results with using the most recent `libfuse` release (3.0.1) and `libfuse` still builds properly:
```
mkdir src
cd src
# Most recent version: https://github.com/libfuse/libfuse/releases
wget wget https://github.com/libfuse/libfuse/archive/fuse-3.0.1.tar.gz
tar xvf fuse-3.0.1.tar.gz
cd fuse-3.0.1
./makeconf.sh
./configure --prefix=/usr/local
make & make install
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
ldconfig
modprobe fuse
```

Same error whilst configure'ing `s3fs`:
```
cd ~/src
git clone https://github.com/s3fs-fuse/s3fs-fuse.git
cd s3fs-fuse
./autogen.sh
./configure # and even with --prefix=/usr/local
```

```
configure: error: Package requirements (fuse >= 2.8.4 libcurl >= 7.0 libxml-2.0 >= 2.6) were not met:

No package 'fuse' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables common_lib_checking_CFLAGS
and common_lib_checking_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

As noted, there are NO previous `libfuse` support libraries other than 3.0.1 as noted above.  Something crazy is happening with regards to the detection of the 3.0.x libfuse library not being detected.

**Comment by ggtakec** [comment]
@ylluminate
Maybe, you can find /usr/local/lib/pkgconfig/fuse3.pc and make symbolic link it to /usr/local/lib/pkgconfig/fuse.pc .
Thus you will get no error from configure.

As expected, fuse 3.0 is not supported in s3fs now.
You will receive build errors.

Please try to make symbolic link.
Regards,

**Comment by azavrin** [comment]
I am facing exact same issue.

**Comment by azavrin** [comment]
After createing symlink as suggested above, i get this:
# make
make  all-recursive
make[1]: Entering directory `/usr/src/s3fs-fuse'
Making all in src
make[2]: Entering directory `/usr/src/s3fs-fuse/src'
g++ -DHAVE_CONFIG_H -I. -I..  -I/usr/local/include/fuse3 -I/usr/include/libxml2      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT s3fs.o -MD -MP -MF .deps/s3fs.Tpo -                                                                             c -o s3fs.o s3fs.cpp
In file included from /usr/local/include/fuse3/fuse.h:19,
                 from s3fs.h:26,
                 from s3fs.cpp:47:
/usr/local/include/fuse3/fuse_common.h:726:4: error: #error only API version 30 or greater is supported
s3fs.cpp: In function âint readdir_multi_head(const char*, S3ObjList&, void*, int (*)(void*, const char*, const stat*, off_t, fuse_fill_dir_flags))â:
s3fs.cpp:2403: error: too few arguments to function
s3fs.cpp:2406: error: too few arguments to function
s3fs.cpp: In function âint s3fs_readdir(const char*, void*, int (*)(void*, const char*, const stat*, off_t, fuse_fill_dir_flags), off_t, fuse_file_info*)â:
s3fs.cpp:2434: error: too few arguments to function
s3fs.cpp:2435: error: too few arguments to function
s3fs.cpp: In function âint main(int, char**)â:
s3fs.cpp:4975: error: invalid conversion from âint (*)(const char*, stat*)â to âint (*)(const char*, stat*, fuse_file_info*)â
s3fs.cpp:4982: error: invalid conversion from âint (*)(const char*, const char*)â to âint (*)(const char*, const char*, unsigned int)â
s3fs.cpp:4985: error: invalid conversion from âint (*)(const char*, mode_t)â to âint (*)(const char*, mode_t, fuse_file_info*)â
s3fs.cpp:4986: error: invalid conversion from âint (*)(const char*, uid_t, gid_t)â to âint (*)(const char*, uid_t, gid_t, fuse_file_info*)â
s3fs.cpp:4987: error: invalid conversion from âint (*)(const char*, const timespec*)â to âint (*)(const char*, const timespec*, fuse_file_info*)â
s3fs.cpp:4989: error: invalid conversion from âint (*)(const char*, mode_t)â to âint (*)(const char*, mode_t, fuse_file_info*)â
s3fs.cpp:4990: error: invalid conversion from âint (*)(const char*, uid_t, gid_t)â to âint (*)(const char*, uid_t, gid_t, fuse_file_info*)â
s3fs.cpp:4991: error: invalid conversion from âint (*)(const char*, const timespec*)â to âint (*)(const char*, const timespec*, fuse_file_info*)â
s3fs.cpp:4993: error: invalid conversion from âint (*)(const char*, off_t)â to âint (*)(const char*, off_t, fuse_file_info*)â
s3fs.cpp:5002: error: invalid conversion from âint (*)(const char*, void*, int (*)(void*, const char*, const stat*, off_t, fuse_fill_dir_flags), off_t, fuse_fil                                                                             e_info*)â to âint (*)(const char*, void*, int (*)(void*, const char*, const stat*, off_t, fuse_fill_dir_flags), off_t, fuse_file_info*, fuse_readdir_flags)â
s3fs.cpp:5003: error: invalid conversion from âvoid* (*)(fuse_conn_info*)â to âvoid* (*)(fuse_conn_info*, fuse_config*)â
make[2]: *** [s3fs.o] Error 1
make[2]: Leaving directory `/usr/src/s3fs-fuse/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/src/s3fs-fuse'
make: *** [all] Error 2

**Comment by myGod0rz** [comment]
I got the same error.

> ...
checking for common_lib_checking... no
configure: error: Package requirements (fuse >= 2.8.4 libcurl >= 7.0 libxml-2.0 >= 2.6) were not met:

No package 'fuse' found



CentOS 7.4.1708 x64

try this:
yum install fuse-devel

fuse-devel-2.9.2-10.el7.x86_64

IT WORKS FOR ME 。

**Comment by KES777** [comment]
On Ubuntu:

    sudo apt install libfuse-dev

**Comment by jerry123je** [comment]
on AmazonLinux2, yum install fuse-devel save the day!

**Comment by harunsah** [comment]
sudo apt-get install libssl-dev
sudo apt install libfuse-dev

these two package resolved for ubuntu 18.04.

**Comment by raqueldias** [comment]
In CentOS 6, this worked for me:
`yum install fuse-devel.i686 fuse-devel.x86_64 fuse-libs.x86_64 fuse-libs.i686`

Then configure step passed:
```
./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for library containing dlsym... -ldl
checking OpenSSH version... 5.3 >= 4.4, disabling NODELAY workaround
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SSHFS... yes
checking for fuse_opt_parse... yes
checking for fusermount... fusermount -u
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing depfiles commands

```

**Comment by ml-and-ml** [comment]
> I got the same error.
> 
> > ...
> > checking for common_lib_checking... no
> > configure: error: Package requirements (fuse >= 2.8.4 libcurl >= 7.0 libxml-2.0 >= 2.6) were not met:
> 
> No package 'fuse' found
> 
> CentOS 7.4.1708 x64
> 
> try this: yum install fuse-devel
> 
> fuse-devel-2.9.2-10.el7.x86_64
> 
> IT WORKS FOR ME 。

true king. works

**Comment by kparmar-winfo** [comment]
I got the same issue while configuring s3fs latest version. (OS Release: Oracle Linux 7.9)

```
checking for fuse_library_checking... no
configure: error: Package requirements (fuse >= 2.8.4) were not met:

No package 'fuse' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables fuse_library_checking_CFLAGS
and fuse_library_checking_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

Just tried executing `yum` install fuse-dev libxml2-devel libcurl-devel` and it worked for me.

Thanks,
Karan Parmar.
