### ISSUE TITLE
#351 breaks automount on boot

### ISSUE THREAD

**Issue by root360-AndreasUlm** [s3fs-fuse/s3fs-fuse#538]
- Version of s3fs being used (s3fs --version)
 - 1.80

- Version of fuse being used (pkg-config --modversion fuse)
 - 2.9.2-4ubuntu4.14.04.1

- System information (uname -a)
 - Linux hostname 3.13.0-110-generic #157-Ubuntu SMP Mon Feb 20 11:54:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Distro (cat /etc/issue)
 - Distributor ID: Ubuntu
 - Description:    Ubuntu 14.04.5 LTS
 - Release:        14.04
 - Codename:       trusty

- /etc/fstab entry (if applicable): 
```
s3fs#bucket                /mnt/s3     fuse    noauto,_netdev,allow_other,use_cache=/tmp/s3/,uid=0,gid=33,retries=5,connect_timeout=300,readwrite_timeout=60,endpoint=eu-central-1,url=http://s3.eu-central-1.amazonaws.com
```
- s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
```
$ mount /mnt/s3/
s3fs: cache directory(/tmp/s3/) is specified, but it does not exist or is not directory.
```
#### Details about issue

This issue was introduced by #351 and is IMO severe.

S3FS can't be mounted at boot anymore because the cache directory is missing.
There is no (easy) way to create the cache direcotry before the system mounts all mountpoints defined in the fstab.

I can understand the issue described in 347 but the default behaviour definitly should not be changed just because of one use-case.

IMO there are 3 options to fix this issue:
- create cache directory & provide an option to disable cache directory creation
- don't create cache directory & provide an option to enable cache directory creation
- if cache directory does not exists: if it can be created: create directory; else exit with error message

We are running ~300 servers with s3fs and due to this change of behaviour we can't upgrade.

Best regards,
Andreas

**Comment by ggtakec** [comment]
@root360-AndreasUlm I'm sorry for my late replying.

I added a new check_cache_dir_exist option and disabled #351 fix.
Only when the check_cache_dir_exist option is given, checks the cache directory at s3fs startup.
By this #557 fix, if only use_cache option is specified, the operation will be as before.

If you can, please try to test latest codes.
And I'm going to close this issue, but if you found problem about this, please reopen this issue.

Thanks in advance for your help.

**Comment by root360-AndreasUlm** [comment]
@ggtakec No problem. Thank you for reviewing my issue.

My tests concerning this issue show that your fix works.
By running s3fs manually and on boot by fstab entry the cache directory is created successfully when missing.
