### ISSUE TITLE
Can't unmount

### ISSUE THREAD

**Issue by Sklein88** [s3fs-fuse/s3fs-fuse#562]
#### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

- Version of s3fs being used (s3fs --version)
 - 1.80

- Version of fuse being used (pkg-config --modversion fuse)
 - 2.9.2

- System information (uname -a)
 - Linux ip-172-31-53-236 3.13.0-86-generic #130-Ubuntu SMP Mon Apr 18 18:27:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Distro (cat /etc/issue)
 - Ubuntu 14.04.4 LTS \n \l
```
- s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  

#### Details about issue

I can't find how to unmount , the command unmount is not installed, there is like an option to unmount like  s3fs -o unmount latinostockphoto.com /var/www/prestashop/imgR

I tried rm -r  but says "device busy" ...

Regards!

**Comment by RobbKistler** [comment]
Try `umount` instead of `unmount`.

**Comment by Sklein88** [comment]
Oh my, sorry I'm still so noob on Linux, thanks!
