### ISSUE TITLE
s3fs only works properly with -f option?

### ISSUE THREAD

**Issue by timbostop** [s3fs-fuse/s3fs-fuse#57]
Hi

I've successfully setup s3fs working on an EC2 instance and connecting to S3 via an IAM role (using the iam_role option).

Everything works fine when I invoke s3fs using the -f option - and I see the log of what's going on in the terminal window.

However if I try to run this without the -f option or to add it to /etc/fstab so that it runs at boot and mounts automatically it doesn't work.
The command returns fine, but when I try to access the local directory containing the mount, I get:

s3fs: unable to access MOUNTPOINT /mnt/batches: Transport endpoint is not connected

I can get it working again by running umount and then s3fs with -f option again.

Any clues as to what I'm doing wrong?

**Comment by caztial** [comment]
mount (shows)
s3fs on /var/www/html/skwirk/uploadFiles type fuse.s3fs (rw,allow_other)
s3fs on /var/www/html/media/system/images/avatar/user_images type fuse.s3fs (rw,allow_other)

df -h (shows)
df: `/var/www/html/media/system/images/avatar/user_images': Transport endpoint is not connected
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvde1       99G  3.6G   90G   4% /
tmpfs           3.7G     0  3.7G   0% /dev/shm
s3fs            256T     0  256T   0% /var/www/html/skwirk/uploadFiles

uploadfiles connecting but user images not connecting

**Comment by caztial** [comment]
looks like you cant go too deep in a bucket folders 
 s3fs -f skwirks3au:/media/system/images -o nonempty -o allow_other -o default_acl=public-read  /var/www/html/media/system/images/avatar/userimg
    set_moutpoint_attribute(3291): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
s3fs_init(2595): init
s3fs_check_service(2894): check services.
    CheckBucket(2228): check a bucket.
RequestPerform(1595): ### CURLE_HTTP_RETURNED_ERROR
RequestPerform(1600): HTTP response code =404
s3fs: Failed to access bucket.

 s3fs -f skwirks3au:/media/system -o nonempty -o allow_other -o default_acl=public-read  /var/www/html/media/system/images/avatar/userimg
    set_moutpoint_attribute(3291): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
s3fs_init(2595): init
s3fs_check_service(2894): check services.
    CheckBucket(2228): check a bucket.
    RequestPerform(1483): HTTP response code 200

**Comment by ggtakec** [comment]
@caztial Thanks about your report.
I found some bugs about setting deep folder for mount point.
It will need to check all of codes about signature( signature v4 too), so please wait a while.

Regards,

**Comment by nickstinger** [comment]
Having the same problem here on Ubuntu 15.04.
I'm trying to mount  the root of a bucket, and getting the same error.

```
s3fs: ### retrying...
s3fs: Retry request. [type=5][url=http://xxx.s3.amazonaws.com/][path=/]
s3fs: ### CURLE_COULDNT_RESOLVE_HOST
```

The url is correct (although obfuscated).
I wonder if the mount is occurring before the network is up.
Mounting from shell after login works fine.

**Comment by RobbKistler** [comment]
You could could try adding _netdev to the mount options but I'm not sure that works for later version of Ubuntu.  s3fs-fuse retries a few times but if its a wi-fi network that doesn't come up until you log in....

**Comment by nickstinger** [comment]
I am sorry, I did not know about the _netdev option.  I tried it after considering jriehl and RobbKistler's replies, and the bucket started mounting properly.  My post is now off topic, but so as not to be a waste of mental effort, I will see if I can submit this information to the Wiki.

**Comment by ggtakec** [comment]
@nickstinger I'm sorry for replying late, and I added FAQ about _netdev.
Sorry for taking your time about this issue.

**Comment by anskrish** [comment]
these are the updates steps to mount the S3 bucket on redhat 7
yum update -y
sudo sudo yum install automake fuse fuse-devel gcc-c++ git libcurl-devel libxml2-devel make openssl-devel
git clone https://github.com/s3fs-fuse/s3fs-fuse.git
cd s3fs-fuse
./autogen.sh
./configure
make
sudo make install
echo AJOUROBLEA:Yp9KTMHWrroh3 > ~/.passwd-s3fs
chmod 600 ~/.passwd-s3fs
mkdir /test
vim ~/.bash_profile
##update below line
PATH=$PATH:$HOME/bin:/usr/local/bin
source ~/.bash_profile 
s3fs test1bber /test -o passwd_file=~/.passwd-s3fs 
df -h
