### ISSUE TITLE
mount s3 without credentials

### ISSUE THREAD

**Issue by AbubakrSamsodien** [s3fs-fuse/s3fs-fuse#573]
Hey guys

How do i mount s3 bucket without secret access keys? Ive attached a role on my ec2 that grants me full access to the specific s3 bucket.

if i run the mount command without password it gives this: 
    _s3fs: could not determine how to establish security credentials._

I dont intend to leave my credentials inside of the ec2

**Comment by ggtakec** [comment]
@AbubakrSamsodien 
You can do with iam_role option, please see man s3fs.
Regrads,
