### ISSUE TITLE
s3fs cache

### ISSUE THREAD

**Issue by vgadhadaran** [s3fs-fuse/s3fs-fuse#577]
If I dont specify use_cache location , s3fs writes to a local cache in the root directory. How can I locate the s3cache directory? This is giving problem when I intend to transfer much larger file size and dont have much space on my server . I dont see anything meaningfully created in my /tmp created as well.

**Comment by ggtakec** [comment]
@vgadhadaran 
If you do not specify use_cache option, s3fs uses tmpfile() function for updalo/download object.
I think the directory used by tmpfile is system dependent.
Do you have any reason why the use_cache option can not be specified?
If possible, it seems good to use this option.

Regards,

**Comment by vgadhadaran** [comment]
During the PUT operations, it writes 0 KB to HCP from the use_cache location.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
Is this problem continuing?
We launch new version 1.86, which fixed some problem(bugs).
Please use the latest version.
I will close this, but if the problem persists, please reopen or post a new issue.
