### ISSUE TITLE
Dummy files being created in folder

### ISSUE THREAD

**Issue by MOPineyro** [s3fs-fuse/s3fs-fuse#589]
#### Additional Information
```
- Version of s3fs being used (s3fs --version)
 - 1.80

- Version of fuse being used (pkg-config --modversion fuse)
 - 2.9.4

- System information (uname -a)
 - Linux ip-172-31-31-184 4.9.20-11.31.amzn1.x86_64 #1 SMP Thu Apr 13 01:53:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Distro (cat /etc/issue)
 - Amazon Linux AMI release 2017.03
```
#### Details about issue

Tons of empty files being created. Seems like s3fs is the culprit. File names all follow a similar structure: 
- undefined2017-05-09-05-36-29-61C90F3F199B695D

And contain something like:
00d22f9083afee55a3f4deb2c09e9a46547e9c69f56c888e33cb5f4394d03444 nba-ftp-feed [09/May/2017:04:22:50 +0000] 10.176.134.44 3272ee65a908a7677109fedda345db8d9554ba26398b2ca10581de88777e2b61 2E50C3AE3E26B525 REST.PUT.OBJECT undefined2017-05-09-04-22-50-7C905FA2F925FE5D "PUT /nba-ftp-feed/undefined2017-05-09-04-22-50-7C905FA2F925FE5D HTTP/1.1" 200 - - 381 48 12 "-" "aws-internal/3" -

Any help?

**Comment by andrewgaul** [comment]
@MOPineyro s3fs does not create these files.  Please check your environment to see which process creates them.

**Comment by ggtakec** [comment]
@andrewgaul Thanks,
@MOPineyro please check your environemnt,
I'm closing this issuse, but you need to keep this issue, please reopen this.
