### ISSUE TITLE
modify permissions and change ownership to Files/Folder in s3fs directory

### ISSUE THREAD

**Issue by vgadhadaran** [s3fs-fuse/s3fs-fuse#592]
It works for files but not for folders. The folders has sub folders and files.

s3fs#phase1 /tmp/abc fuse__netdev,allow_other,url=https://awspoc.xxx.xxx.xxx,no_check_certificate,nomultipart,nonempty,dbglevel=info 0 0

[root@k0001809 abc]# ls -la |grep "OAIsys"
d---------  1 root   root             0 May  9 14:08 OAIsys

[root@k0001809 abc]# chown -R -v n5f356:zabbix OAIsys
changed ownership of `OAIsys/BENCHMARK/OUTPUT' to n5f356:zabbix
changed ownership of `OAIsys/BENCHMARK/WORK' to n5f356:zabbix
changed ownership of `OAIsys/BENCHMARK' to n5f356:zabbix
changed ownership of `OAIsys' to n5f356:zabbix

[root@k0001809 abc]# chmod 775 OAIsys
[root@k0001809 abc]# ls -la |grep "OAIsys"
d---------  1 root   root             0 May  9 14:08 OAIsys

I am trying to change the ownership and permission for the  s3fs mount folder OAIsys but couldn't. Is that not feasible?

Same implies for Files too

[root@k0001809 abc]# chown -R -v n5f356:zabbix tar1
chown: changing ownership of `tar1': Input/output error
failed to change ownership of `tar1' to n5f356:zabbix

**Comment by ggtakec** [comment]
@vgadhadaran 
Probably I think the OAIsys directory is an object created with tools other than s3fs.
This object does not have x-amz-meta-* header information.
Therefore, although it can be recognized as a directory, it is in a state where permission can not be acquired.

You can grant permissions below the mount point using options such as uid/gid/umask.
Alternatively, you can try the complement_stat option using the latest code from the master branch.

I'm closing this issue, but you need to keep this, please reopen this.
Regards,
