### ISSUE TITLE
New version of s3fs

### ISSUE THREAD

**Issue by vgadhadaran** [s3fs-fuse/s3fs-fuse#599]
when is the new version of S3fS 1.81 expected?Will it work with fuse.x86_64-2.9.2-7.el7  version or it needs an higher version of Fuse component?

**Comment by andrewgaul** [comment]
1.82 released today:

https://github.com/s3fs-fuse/s3fs-fuse/releases

Supports FUSE 2.x but not FUSE 3.x

**Comment by ggtakec** [comment]
@vgadhadaran Please try to use latest codes, thanks.
