### ISSUE TITLE
Difference in Filename copying

### ISSUE THREAD

**Issue by vgadhadaran** [s3fs-fuse/s3fs-fuse#610]
Why there is a
Scenario A: created a file name "oneg" of a gb in size and everything was successful.

May 26 12:56:03 k8005227 s3fs[1345]:      uploading... [path=/oneg][fd=29][size=1073741824]
May 26 12:57:13 k8005227 s3fs[1345]:      HTTP response code 200
May 26 12:57:13 k8005227 s3fs[1345]: [path=/oneg][fd=29]
May 26 12:57:13 k8005227 s3fs[1345]:      delete stat cache entry[path=/oneg]
May 26 12:57:13 k8005227 s3fs[1345]:      [path=/oneg][fd=29]
May 26 12:57:13 k8005227 s3fs[1345]:      [path=/oneg][fd=29]

scenario 2: created a file name "hundtengb" with a filesize of 110gb. But only 0MB is shown on the namespace and not nothing copied. Also I see the file name as "fs_ro_test" instead of "hundtengb".

May 26 12:40:02 k0002170 s3fs[7374]:       add stat cache entry[path=/fs_ro_test]
May 26 12:40:02 k0002170 s3fs[7374]: [path=/fs_ro_test][fd=10]
May 26 12:40:02 k0002170 s3fs[7374]:       [tpath=][path=/fs_ro_test][fd=10]
May 26 12:40:02 k0002170 s3fs[7374]: [path=/fs_ro_test][fd=10]
May 26 12:40:02 k0002170 s3fs[7374]:       delete stat cache entry[path=/fs_ro_test]
May 26 12:40:02 k0002170 s3fs[7374]:       [path=/fs_ro_test][fd=10]
May 26 12:40:02 k0002170 s3fs[7374]:       [path=/fs_ro_test][fd=10]

**Comment by gaul** [comment]
s3fs creates a zero-byte file with metadata before uploading the real file.  In this case, the second upload failed due to too many parts.  You can work around this by specifying `-o multipart_size=500` which will allow the maximum 5 TB object size.

**Comment by ggtakec** [comment]
It now displays an error in #948 by @gaul (Thanks). 
I'm closing this issue.
