### ISSUE TITLE
SSE not working when executing s3fs command

### ISSUE THREAD

**Issue by calum-mcelhone** [s3fs-fuse/s3fs-fuse#619]
- Version of s3fs - 1.80

#### Details about issue

Hi Guys, 

I am currently using s3fs to fuse a docker container directory to an S3 Bucket.

Files are syncing fine.  The only issue i am running into is getting my files encrypted in my S3Bucket.

The command i am currently using to fuse is as follows:

sudo /usr/bin/s3fs lmb-enrollment-cust-bucket-${DEPLOY_REGION} /s3-share -o use_sse -o gid=$sftpGroupId,mp_umask=0002,allow_other -o umask=0002 -o iam_role=auto -o default_acl=private,retries=1

I am not getting any errors in my logs specifying encryption failed or the like.  Its simply a case that the files sync without getting encrypted in the related S3Bucket.

As you can see i am passing the -o use_sse parameter so i would have expected the appropriate metadata to have been included in the PUT request to the S3Bucket.

If anyone has run into the same issue or can see clearly what the issue might be i would be interested to hear back from you.

**Comment by gaul** [comment]
Could you test with master?  It includes a fix for #696 which may resolve your issue as well.

**Comment by gaul** [comment]
Please reopen if you can reproduce these symptoms.
