### ISSUE TITLE
Unable to install latest version 2017-07-18 on centos 7

### ISSUE THREAD

**Issue by quadgnim** [s3fs-fuse/s3fs-fuse#622]
#### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

- Version of s3fs being used (s3fs --version)
 - _example: 1.0_

- Version of fuse being used (pkg-config --modversion fuse)
 - _example: 2.9.4_
2.9.2 (of fuse)

-- s3fs version
tags = v1.82
pulled down s3fs-fuse-master.zip on 2017-07-17

- System information (uname -a)
 - _command result: uname -a_
Linux ip-10-154-177-139 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

CentOS Linux release 7.3.1611 (Core)

- Distro (cat /etc/issue)
 - _command result: result_
\S
Kernel \r on an \m

- s3fs command line used (if applicable)

================================

during install: running ./configure

checking sys/extattr.h presence... no
checking for sys/extattr.h... no
checking s3fs build with nettle(GnuTLS)... no
checking s3fs build with OpenSSL... no
checking s3fs build with GnuTLS... no
checking s3fs build with NSS... no
checking for pkg-config... /bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for common_lib_checking... yes
checking compile s3fs with... OpenSSL
checking for DEPS... no
configure: error: Package requirements (fuse >= 2.8.4 libcurl >= 7.0 libxml-2.0 >= 2.6 libcrypto >= 0.9) were not met:

No package 'libcrypto' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DEPS_CFLAGS
and DEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

================================

NOTE: Ran the yum install as directed, everything installed fine

see troubleshooting:

># yum list | grep fuse
fuse.x86_64                                2.9.2-7.el7                 @base    
fuse-devel.i686                            2.9.2-7.el7                 @base    
fuse-devel.x86_64                          2.9.2-7.el7                 @base    
fuse-libs.i686                             2.9.2-7.el7                 @base    
fuse-libs.x86_64                           2.9.2-7.el7                 @base    
fuseiso.x86_64                             20070708-15.el7             base     
fusesource-pom.noarch                      1.9-7.el7                   base     
glusterfs-fuse.x86_64                      3.7.9-12.el7.centos         base     
gvfs-fuse.x86_64                           1.22.4-8.el7                base     
ostree-fuse.x86_64                         2017.5-3.el7                extras 

># yum list | grep libcurl
libcurl.x86_64                             7.29.0-35.el7.centos        installed
libcurl-devel.x86_64                       7.29.0-35.el7.centos        @base    
libcurl.i686                               7.29.0-35.el7.centos        base     
libcurl-devel.i686                         7.29.0-35.el7.centos        base 

># yum list | grep libxml 
libxml2.x86_64                             2.9.1-6.el7_2.3             installed
libxml2-devel.x86_64                       2.9.1-6.el7_2.3             @base    
libxml2-python.x86_64                      2.9.1-6.el7_2.3             installed
libxml2.i686                               2.9.1-6.el7_2.3             base     
libxml2-devel.i686                         2.9.1-6.el7_2.3             base     
libxml2-static.i686                        2.9.1-6.el7_2.3             base     
libxml2-static.x86_64                      2.9.1-6.el7_2.3             base     
pentaho-libxml.noarch                      1.1.3-10.el7                base     
pentaho-libxml-javadoc.noarch              1.1.3-10.el7                base     
perl-libxml-perl.noarch                    0.08-19.el7                 base  

libcrypto not found, but when installing it using yum install -y libcrypto, it reports openssl, so tried ./configure with 

./configure --prefix=/usr --with-openssl

still get the same errors

Any suggestions of guidance would be most appreciated

Thanks

**Comment by quadgnim** [comment]
I think I got it working.  Added the following to yum install

    gcc libstdc++-devel mailcap curl-devel

and then running ./autogen.sh and ./configure worked without errors

**Comment by ujjwalpl** [comment]
Solution is..
# yum install -y openssl-devel libcurl-devel
# ./configure --prefix=/usr --with-openssl

**Comment by gaul** [comment]
@quadgnim If this issue is resolved can you please close it?  Also note that EPEL now hosts a `s3fs-fuse` package.

**Comment by juliogonzalez** [comment]
@quadgnim can this be closed?
