### ISSUE TITLE
Mount hanging on macOS 10 (Sierra)

### ISSUE THREAD

**Issue by crudmucosa** [s3fs-fuse/s3fs-fuse#624]
#### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

- Version of s3fs being used (s3fs --version)
```
 - Amazon Simple Storage Service File System V1.82(commit:unknown) with GnuTLS(gcrypt)
```
- Version of fuse being used (pkg-config --modversion fuse)
```
 - osxfuse 3.6.3
```
- System information (uname -a)
```
 - _command result: Darwin cad-bane.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:13:31 PDT 2017; root:xnu-3789.60.24~4/RELEASE_X86_64 x86_64
cad-bane:picturesofusS3buckets fenris$ 
```
- Distro (cat /etc/issue)
```
 - _command result: (result from sw_vers) sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F2073
```
- s3fs command line used (if applicable)
```
s3fs picturesofus.net picturesofus -d -d -f -o f2 -o curldbg
```
- /etc/fstab entry (if applicable): 
```
```
- s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
[CRT] s3fs.cpp:set_s3fs_log_level(257): change debug level from [CRT] to [INF] 
[CRT] s3fs.cpp:set_s3fs_log_level(257): change debug level from [INF] to [DBG] 
[INF]     s3fs.cpp:set_mountpoint_attribute(4193): PROC(uid=501, gid=20) - MountPoint(uid=501, gid=20, mode=40755)
FUSE library version: 2.9.7
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 1304
INIT: 7.19
flags=0xf8000008
max_readahead=0x00100000
[CRT] s3fs.cpp:s3fs_init(3378): init v1.82(commit:unknown) with GnuTLS(gcrypt)
[INF] s3fs.cpp:s3fs_check_service(3754): check services.
[INF]       curl.cpp:CheckBucket(2914): check a bucket.
[DBG] curl.cpp:GetHandler(283): Get handler from pool: 31
[INF]       curl.cpp:prepare_url(4205): URL is https://s3.amazonaws.com/picturesofus.net/
[INF]       curl.cpp:prepare_url(4237): URL changed is https://picturesofus.net.s3.amazonaws.com/
[INF]       curl.cpp:insertV4Headers(2267): computing signature [GET] [/] [] []
[INF]       curl.cpp:url_to_host(100): url is https://s3.amazonaws.com
[DBG] curl.cpp:RequestPerform(1923): connecting to URL https://picturesofus.net.s3.amazonaws.com/
*   Trying 52.216.226.136...
* TCP_NODELAY set
* Connected to picturesofus.net.s3.amazonaws.com (52.216.226.136) port 443 (#0)
* SSL certificate problem: Invalid certificate chain
* Curl_http_done: called premature == 1
* Closing connection 0
[ERR] curl.cpp:RequestPerform(2025): ### CURLE_SSL_CACERT
[ERR] curl.cpp:LocateBundle(718): s3fs: /etc/pki/tls/certs/ca-bundle.crt is not readable
[ERR] curl.cpp:RequestPerform(2031): could not get CURL_CA_BUNDLE.
[ERR] curl.cpp:CheckBucket(2953): Check bucket failed, S3 response: 
[CRT] s3fs.cpp:s3fs_check_service(3820): unable to connect(host=https://s3.amazonaws.com) - result of checking service.
[DBG] curl.cpp:ReturnHandler(306): Return handler to pool: 31
[ERR] s3fs.cpp:s3fs_exit_fuseloop(3368): Exiting FUSE event loop due to errors

   INIT: 7.19
   flags=0x00000010
   max_readahead=0x00100000
   max_write=0x02000000
   max_background=0
   congestion_threshold=0
   unique: 2, success, outsize: 40

[INF] s3fs.cpp:s3fs_destroy(3441): destroy
[WAN] s3fs.cpp:s3fs_destroy(3445): Could not release curl library.
```
#### Details about issue

After mounting a bucket, any directory command (cd, ls, etc) run inside of the mount directory hangs the terminal for a good minute or more. Eventually, the terminal returns but the mount is gone. Any help is appreciated!

**Comment by crudmucosa** [comment]
Well I think I found out what my issue was (thanks to finding the right documentation and then RTFM'ing it) I had to mount it using the "use_path_request_style" option. Right now I run: 
'''
s3fs texas.picturesofus.net texas -o allow_other,rw,umask=022,use_path_request_style
'''
which almost does everything I need! For some reason, files I upload are not set with the correct content-type (I host websites from most of my buckets and html files (well...all the files) are being marked as binary/octet-stream instead of their proper mime type. 

I added a mime.types file to /etc (copied from an ubuntu box I've got running on virtualbox) to see if s3fs would pick it up/use it. Still no joy on getting the mime-type set appropriately (both from ubuntu and macOS).

**Comment by crudmucosa** [comment]
After still more messing about, it seems I can write successfully and have content-type set correctly when mounting a bucket that has no dots in its name. I use:

`s3fs grandtwotest texas -o allow_other,rw,umask=022,url=http://s3.amazonaws.com`

(I am also able to successfully mount that grandtwotest bucket without the url option. Not so with the bucket with dots in the name).

Upload wesbsite files to it and it displays just fine, content-types are set just fine.

http://grandtwotest.s3-website-us-east-1.amazonaws.com/

Whereas if I try to mount the real site:

`s3fs texas.picturesofus.net texas -o allow_other,rw,umask=022,url=http://s3.amazonaws.com`

Uploaded files do not receive the correct content-type:

http://texas.picturesofus.net/

Any ideas? I suppose I could make a workaround by creating buckets without the dots and redirect calls to urls to them?

**Comment by ggtakec** [comment]
@crudmucosa Can you solve your problem with the ahbe_conf option?
You can add an HTTP header corresponding to file extension etc.
The sample file is in test / sample_ahbe.conf.
Regards,

**Comment by digitalrinaldo** [comment]
I am having the same issue. I have tried the above options with no success.

Darwin I1.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

I1:~ rinaldo$ s3fs --version
Amazon Simple Storage Service File System V1.82(commit:unknown) with GnuTLS(gcrypt)
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

installed via homebrew

**Comment by jkoepcke** [comment]
Can see this issue as well in 1.84

**Comment by gaul** [comment]
Please test with the latest release 1.87 or master.

**Comment by gaul** [comment]
Please reopen if symptoms persist.

**Comment by masbaehr** [comment]
I'm having the same symptom with MacOS Big Sur. Followed the guide at https://github.com/s3fs-fuse/s3fs-fuse  -> Everything went fine until s3fs mybucket /path/to/mountpoint -o passwd_file=${HOME}/.passwd-s3fs
hanging immediately after issueing the command no error whatsoever
