### ISSUE TITLE
Cannot resolve IP address in URL option

### ISSUE THREAD

**Issue by kunallillaney** [s3fs-fuse/s3fs-fuse#629]
#### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

- Version of s3fs being used (s3fs --version)
 - 1.82

- Version of fuse being used (pkg-config --modversion fuse)
 - 2.9.2

- System information (uname -a)
 - 3.10.0-514.26.2.el7.x86_64

- s3fs command line used (if applicable)
```
s3fs testfs /data/testfs -d -o url=http://10.0.0.7:4567
```

- s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
CURLE_COULDNT_RESOLVE_HOST
```
#### Details about issue
Hey I am trying to mount s3fuse over s3proxy or fakes3. I have them running over a remote node (10.0.0.7). The error log shows couldn't resolve host. The same issue occurs even when I run it at localhost with url=127.0.0.1:4567. But it works correctly when I explicitly mention localhost instead of 127.0.0.1.
I think there might be an issue that it does not resolve IP addresses and requires host names. Or maybe I am missing something/doing something stupid.

**Comment by kunallillaney** [comment]
Okay. This is resolved. I used the use_path_request_style option. How can I add this to the documentation?

**Comment by andrewgaul** [comment]
Where do you think it should be documented?

**Comment by kunallillaney** [comment]
@andrewgaul Maybe in the README.md in s3fs-fuse under a different section. There seems to be very little documentation (or maybe I haven't looked enough) on how to use s3fuse with s3proxy. A sample command with the corresponding s3proxy.conf (example: aws-v4 for s3proxy.authorization) might be helpful here. Alternately, you can mention this in s3proxy.

**Comment by andrewgaul** [comment]
@kunallillaney Thanks for the suggestion and I opened #637 to document this.  Documenting S3Proxy falls outside the scope of s3fs but the S3Proxy wiki has client compatibility instructions:

https://github.com/andrewgaul/s3proxy/wiki/Client-compatibility-list#s3fs-fuse
