### ISSUE TITLE
fuse: device not found, try 'modprobe fuse' first

### ISSUE THREAD

**Issue by yellowmamba** [s3fs-fuse/s3fs-fuse#647]
#### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

- Version of s3fs being used (s3fs --version)
```
Amazon Simple Storage Service File System V1.82(commit:c5c1101) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

- Version of fuse being used (pkg-config --modversion fuse)
`2.9.4`

- System information (uname -a)
`Linux fae8d21da480 4.9.43-17.38.amzn1.x86_64 #1 SMP Thu Aug 17 00:20:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

- Distro (cat /etc/issue)
`Ubuntu 16.04 LTS \n \l`

- s3fs command line used (if applicable)
**N/A**

- /etc/fstab entry (if applicable): 
```
# UNCONFIGURED FSTAB FOR BASE SYSTEM
my-bucket-name /mnt/s3-bucket fuse.s3fs _netdev,allow_other,umask=000,default_acl=public-read,use_cache=/tmp 0 0
```
- s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
fuse: device not found, try 'modprobe fuse' first
```
#### Details about issue

I am not sure why, it used to work for my other projects. When I am prompt with this error message, I tried `modprobe fuse` and got `bash: modprobe: command not found`. Really out of ideas of what went wrong. Can anyone assist?

Thanks

**Comment by yellowmamba** [comment]
hmm, I am pretty sure now it's because of this line in `/etc/fstab`

```
# UNCONFIGURED FSTAB FOR BASE SYSTEM
```
But I have no idea why it's not configured.

**Comment by yellowmamba** [comment]
OK, it was due to docker run permission issue, need a `--privileged` flag. Unrelated to s3fs itself. Sorry.

**Comment by audiofeature** [comment]
@yellowmamba Can you explain in more detail how this is solved? I don't know where to use that --privileged flag.

**Comment by yellowmamba** [comment]
Hi @audiofeature , it's a flag you can attach to docker, i.e. `docker run --privileged`.

**Comment by gigioSouza** [comment]
@yellowmamba not every hero wears a cape...
How did you figured this out?

**Comment by braco** [comment]
There has to be some way to fix this with a pure Dockerfile

**Comment by rustyx** [comment]
`--privileged` gives too many permissions to the container.

FUSE functionality needs in fact only the following permissions:

```
--cap-add SYS_ADMIN --device /dev/fuse
```

 SYS_ADMIN is needed for mount/umount functionality, and `/dev/fuse` exposes the FUSE device to the container.

**Comment by diman82** [comment]
Have this change already been integrated in a release version?
Also, how do I use it inside docker-compose?

**Comment by gnosisgithub** [comment]
So 'docker --privileged run ...'?

**Comment by Dr-Steve** [comment]
This does not work in the context of AWS and Fargate, where you are not allowed to run with --privileged or --device (see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html)

Is there any way to get around this?

**Comment by ChrisPappalardo** [comment]
I have the same issue as @Dr-Steve.  I tried following [this answer](https://stackoverflow.com/a/60556131/5451813) and ran into the device not found here discussed here.  If I set privileged mode in development, it works, but that is not supported by AWS Fargate.  Is there a recommended way to use s3fs with AWS Fargate that is also compatible with ecs-cli?

**Comment by nminhquang** [comment]
Try to run docker container with these options:
--cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined

**Comment by R70YNS** [comment]
> This does not work in the context of AWS and Fargate, where you are not allowed to run with --privileged or --device (see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html)
> 
> Is there any way to get around this?

Any update on this?

**Comment by dnz-bdeboer** [comment]
In case people come back here and think the last solution applies to Fargate: it does not. Fargate does not support SYS_ADMIN capability. You probably need to run your container in ECS. No big deal.

**Comment by ChrisPappalardo** [comment]
Following up on this, I abandoned using s3fs in ECS with Fargate, it's much cleaner and easier using EFS which can be mounted via the task definition.  If you really need to use S3, I suggest using it at the app level via an SDK (such as boto3 in python).  S3 just isn't great for block-level storage in my opinion and I've had multiple issues trying to implement it that way.

**Comment by ayush5112** [comment]
I am getting the problem of permission denied on my system when I try to access a database mounted directory :
**ls: cannot access '/home/ayushk/dla/scratch.dla': Permission denied**
So, I tried to mount the directory from the docker itself but the error says :
**fuse: device not found, try 'modprobe fuse' first**
If we give --privileged option in the command to run the docker then error when is :
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: failed to write "a *:* rwm": write /sys/fs/cgroup/devices/docker/39b947e020815aae5bbdb0ad03dff2b6d662b96e8ed3dc898a92237e26bbd5f9/devices.allow: operation not permitted: unknown.

So how can we mount a directory  on docker?

**Comment by Abdelrahman-Abbas** [comment]
Did anyone solve such an issue when working with google cloud build to build the docker? I think it doesn't have the `--privileged` option. Any help?

**Comment by BloodyIron** [comment]
@ChrisPappalardo your note on using EFS vs s3fs is interesting, thanks! I'll have to look into that...

**Comment by sinnrrr** [comment]
to add this permission to docker-compose add the following to the config file:
```yaml
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
```

**Comment by lebyanelm** [comment]
How do you apply these fixes on a docker container running under **kubectl**?

**Comment by KMint1819** [comment]
I've tried `--cap-add SYS_ADMIN --device /dev/fuse` but then it shows 
```bash
fuse: mount failed: Permission denied

Cannot mount AppImage, please check your FUSE setup.
```

**Comment by kjxbyz** [comment]
@KMint1819 it works for me.

```
--cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined
```
