### ISSUE TITLE
Cannot mount a bucket that has a dot(.) in its name even though I use "use_path_request_style"

### ISSUE THREAD

**Issue by MariusStanciu95** [s3fs-fuse/s3fs-fuse#653]
I'm using 1.82 or newer and I keep getting unknown option "use_path_request_style" or "endpoint".

I've read that if my bucket has a dot(.) inside its name , I should use the "use_path_request_style" option.

My call when I try mounting:

 s3fs bucket.name /mnt/s3 -o passwd_file=/etc/passwd-s3fs -endpoint=eu-west-2 -o use_path_request_style

Did anyone encounter this problem? Any suggestions (besides renaming the bucket, because I'm not allowed to do that) ?

**Comment by gaul** [comment]
Please post the logs from the failed command.

**Comment by djdevin** [comment]
I posted logs in #626

**Comment by Vacilando** [comment]
Same problem here. If the bucket name contains a dot, s3fs mount fails (no error message).

**Comment by stevesuh** [comment]
Same here.  This worked back in August.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
Please try again with the latest version and you can see https://github.com/s3fs-fuse/s3fs-fuse/wiki/FAQ#q-https-connecting-failed-if-bucket-name-includes-dot- .

I will close this, but if the problem persists, please reopen or post a new issue.
