### ISSUE TITLE
S3FS IAM roles

### ISSUE THREAD

**Issue by aktarali** [s3fs-fuse/s3fs-fuse#66]
Hi;

Is there an example of how to use s3fs with IAM roles please. If my server has an IAM role attached to it, how will I define that in the s3fs configs? How do I do this?

Thanks
Ali.

**Comment by marcanthony** [comment]
is there a way to specify a IAM Role from another AWS account using the FULL ARN?

**Comment by ggtakec** [comment]
This issue takes over to #241 , and then close.

**Comment by marcanthony** [comment]
The full ARN would permit the IAM ROLE in another AWS Account and Permit
Cross Region Bucket replication Ownership to work.



marcanthony barrette
marcanthony.barrette@gmail.com
415.350.1143
