### ISSUE TITLE
Issue with jsoncpp package not being found.

### ISSUE THREAD

**Issue by jashaffe** [s3fs-fuse/s3fs-fuse#682]
#### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

- Version of s3fs being used (s3fs --version)
 - Latest from Github

- Version of fuse being used (pkg-config --modversion fuse)
 - _example: 2.9.4_

- System information (uname -a)
 - Linux 4.9.58-18.55.amzn1.x86_64 #1 SMP Thu Nov 2 04:38:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Distro (cat /etc/issue)
 - Amazon Linux AMI release 2017.09

- s3fs command line used (if applicable)
```
```
- /etc/fstab entry (if applicable): 
```
```
- s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
#### Details about issue
Installing using AMI linux instructions:

sudo yum install -y gcc git libstdc++-devel gcc-c++ fuse fuse-devel curl-devel libxml2-devel mailcap automake openssl-devel jsoncpp-devel git
git clone https://github.com/s3fs-fuse/s3fs-fuse
cd s3fs-fuse/
./autogen.sh
./configure --prefix=/usr --with-openssl
make
sudo make install

Has been installing fine and just stop working today.  I've installed it on over 100 machines doing testing and this error comes up each time:

Cloning into 's3fs-fuse'...
remote: Counting objects: 3781, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 3781 (delta 20), reused 24 (delta 13), pack-reused 3738
Receiving objects: 100% (3781/3781), 1.98 MiB | 12.94 MiB/s, done.
Resolving deltas: 100% (2586/2586), done.
--- Make commit hash file -------
--- Finished commit hash file ---
--- Start autotools -------------
configure.ac:26: installing './config.guess'
configure.ac:26: installing './config.sub'
configure.ac:27: installing './install-sh'
configure.ac:27: installing './missing'
src/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
--- Finished autotools ----------
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/xattr.h usability... yes
checking sys/xattr.h presence... yes
checking for sys/xattr.h... yes
checking attr/xattr.h usability... no
checking attr/xattr.h presence... no
checking for attr/xattr.h... no
checking sys/extattr.h usability... no
checking sys/extattr.h presence... no
checking for sys/extattr.h... no
checking s3fs build with nettle(GnuTLS)... no
checking s3fs build with OpenSSL... yes
checking s3fs build with GnuTLS... no
checking s3fs build with NSS... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for common_lib_checking... no
configure: error: Package requirements (fuse >= 2.8.4 libcurl >= 7.0 libxml-2.0 >= 2.6 jsoncpp >= 0.6 ) were not met:

No package 'jsoncpp' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables common_lib_checking_CFLAGS
and common_lib_checking_LIBS to avoid the need to call pkg-config. 

Any thoughts?

Thanks!

**Comment by gaul** [comment]
Can you try the instructions in #683?

**Comment by jashaffe** [comment]
Thanks Gaul.  Interesting that I've not had need those packages over that last few weeks.  It was just today it started.  Seems AWS' repo doesnt have them and have to be installed manually.

**Comment by gaul** [comment]
#671 recently merged which added a dependency on jsoncpp.  It looks like you are running the Amazon AMI so it would be great to add any instructions for it to https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes#installing-on-amazon-linux-ami .

**Comment by mchesler** [comment]
This caused a problem for me starting this morning as well (running on Amazon AMI for EMR).  Enabling EPEL and installing the `jsoncpp-devel` package (`sudo sed -i 's/enabled=0/enabled=1/' /etc/yum.repos.d/epel.repo && sudo yum install -i jsoncpp-devel`) resolved the issue for me.

**Comment by jashaffe** [comment]
Hey Matt, I think your solution is more appropriate.  If you don't mind, I'm going to update the instructions:

sudo sed -i 's/enabled=0/enabled=1/' /etc/yum.repos.d/epel.repo
yum install -y gcc libstdc++-devel gcc-c++ fuse fuse-devel curl-devel libxml2-devel mailcap  automake openssl-devel jsoncpp-devel
git clone https://github.com/s3fs-fuse/s3fs-fuse
cd s3fs-fuse/
./autogen.sh
./configure --prefix=/usr --with-openssl
make
sudo make install

Was kinda lazy and did:
wget ftp://mirror.switch.ch/pool/4/mirror/epel/6/x86_64/Packages/j/jsoncpp-devel-0.10.5-2.el6.x86_64.rpm
wget ftp://mirror.switch.ch/pool/4/mirror/epel/6/x86_64/Packages/j/jsoncpp-0.10.5-2.el6.x86_64.rpm
sudo rpm -ivh *.rpm

**Comment by ggtakec** [comment]
@jashaffe @mchesler I wonder about this, then I post new issue #685.
Please watch over the issue.
Thanks for all.

**Comment by ggtakec** [comment]
@jashaffe @mchesler I removed jsoncpp from s3fs dependency.
For reasons, please see #685.

Please use the code of the latest master branch, I think you can build s3fs as before.
I apologize for letting me do some extra work.
Thanks in advance for your assistance.
