### ISSUE TITLE
Unnecessary items in Installation Notes(wiki)

### ISSUE THREAD

**Issue by ggtakec** [s3fs-fuse/s3fs-fuse#687]
#### Additional Information
- Version of s3fs being used (s3fs --version) - n/a
- Version of fuse being used (pkg-config --modversion fuse) - n/a
- System information (uname -a) - n/a
- Distro (cat /etc/issue) - n/a
- s3fs command line used (if applicable) - n/a
- /etc/fstab entry (if applicable):  n/a
- s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  - n/a

#### Details about issue
Section(item) **Installing on centOS 6 (s3fs version 1.74)** in https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes, do we need this?
I think this is old explanation when s3fs codes were on google codes.
Now we explain same item in it(ex. "Fedora / CentOS"), then I think we can remove it.

**Comment by gaul** [comment]
Related to #1354.

**Comment by juliogonzalez** [comment]
> https://github.com/s3fs-fuse/s3fs-fuse/issues/1354#issuecomment-671508068

Is anything else missing?
