### ISSUE TITLE
Readme or FAQ should answer: How and where do I get my S3 identity?

### ISSUE THREAD

**Issue by ADTC** [s3fs-fuse/s3fs-fuse#691]
How and where do I get my S3 identity?

I'm having trouble finding any documentation explaining how and where I can get my S3 identity. A helpful tip will be useful.

**Comment by ADTC** [comment]
For anyone here with the same question:

1. Log in to **Amazon AWS** management console website.
1. Click on Services and search for _IAM_. Open **IAM**.
1. Click on **Users** on the left side. (You may try [this link](https://console.aws.amazon.com/iam/home#/users) to skip through the first 3 steps.)
1. Click on _your own username_.
1. Click on **Security Credentials** tab.
1. In the **Access Keys** section:
   - If you can find the existing access key's secret, you may use that. _(You may have saved it somewhere. AWS will not show the secret for any key a second time.)_

   - Otherwise click on **Create access key** and copy the ID and secret. _(You may download the CSV for future reference.)_

   - If **Create access key** button is disabled, you may need to delete an existing access key.
1. Now you may `echo` this to your password file:

        echo MYIDENTITY:MYCREDENTIAL > /path/to/passwd
   where `MYIDENTITY` is the access key ID and `MYCREDENTIAL` is the secret access key.

Hope this helps!

**Comment by ggtakec** [comment]
@ADTC Thanks for your reporting.
I'm adding this FAQ to wiki.

**Comment by soulprovidr** [comment]
Sorry to comment on an old issue, but I just ran into this confusion. I feel like adding this information to the readme would be beneficial:

> "MYIDENTITY is the access key ID and MYCREDENTIAL is the secret access key."

(I can create a PR if you're open to the idea).

**Comment by gaul** [comment]
> Sorry to comment on an old issue, but I just ran into this confusion. I feel like adding this information to the readme would be beneficial:
> 
> >    "MYIDENTITY is the access key ID and MYCREDENTIAL is the secret access key."
> 
> (I can create a PR if you're open to the idea).

Please do. But instead could you write the more self-explanatory:

```
echo MY_ACCESS_KEY_ID:MY_SECRET_ACCESS_KEY > /etc/passwd-s3fs
```

**Comment by soulprovidr** [comment]
Cool, will do.
