### ISSUE TITLE
invalid option -- 'b'

### ISSUE THREAD

**Issue by Seungwoo321** [s3fs-fuse/s3fs-fuse#694]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

#### Version of s3fs being used (s3fs --version)
_example: 1.00_

Amazon Simple Storage Service File System V1.82(commit:566961c) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

#### Version of fuse being used (pkg-config --modversion fuse)
_example: 2.9.4_

2.9.4

#### System information (uname -r)
_command result: uname -r_

4.9.62-21.56.amzn1.x86_64

#### Distro (cat /etc/issue)
_command result: cat /etc/issue_
Amazon Linux AMI release 2017.09
Kernel \r on an \m

#### s3fs command line used (if applicable)
```
s3fs swlee.dev /s3fs -o endpoint=ap-northeast-1 -o use_path_request_style -dbglevel=info -f -o curldbg
```
#### /etc/fstab entry (if applicable): 
```
Not entry
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
output :
[root@ip-172-31-26-250 s3fs]# s3fs swlee.dev /s3fs -o endpoint=ap-northeast-1 -o use_path_request_style -dbglevel=info -f -o curldbg
s3fs: invalid option -- 'b'

```

**Comment by gaul** [comment]
Specify `-o dbglevel=info` instead of `-dbglevel=info`.

**Comment by ggtakec** [comment]
I'm closing this issue, but if you have a problem yet, please reopen this.
And @gaul Thanks.
Regards,
