### ISSUE TITLE
Using SSE-C results in "Input/output error"

### ISSUE THREAD

**Issue by alindt** [s3fs-fuse/s3fs-fuse#696]
#### Version of s3fs being used (s3fs --version)
$ s3fs --version
Amazon Simple Storage Service File System V1.82(commit:unknown) with GnuTLS(gcrypt)

#### Version of fuse being used (pkg-config --modversion fuse)
Package: fuse
Version: 2.9.4-1ubuntu3.1

#### System information (uname -r)
$ uname -r
4.10.0-40-generic

#### Distro (cat /etc/issue)
$  cat /etc/issue
Linux Mint 18.3 Sylvia \n \l

### Details about issue
Using SSE-C as described in the man page results in "Input/output error" when uploading.
Works fine without SSE-C.

#### s3fs command line used (if applicable)
```
$ AWSSSECKEYS="test" s3fs -f XXXXX ~/Amazon.S3/ -o use_sse=custom,dbglevel=info,url="https://s3.eu-central-1.amazonaws.com",endpoint="eu-central-1"
```

#### s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
[debug.log](https://github.com/s3fs-fuse/s3fs-fuse/files/1545226/debug.log)

**Comment by ggtakec** [comment]
@alindt I'm sorry for my late reply.
In your log, it is recorded that the upload failed as EIO.
Please try s3fs with "- o curldbg" as it is necessary to know more detailed log if possible.
Thanks in advance for your assistance.

**Comment by alindt** [comment]
```
$ AWSSSECKEYS="test" s3fs -f XXXXX ~/Amazon.S3/ -o curldbg,use_sse=custom,dbglevel=info,url="https://s3.eu-central-1.amazonaws.com",endpoint="eu-central-1" 2>&1 | tee /dev/shm/curldbg_sse-c.log
$ echo "cici" > ~/Amazon.S3/cici.txt
```
[curldbg_sse-c.log](https://github.com/s3fs-fuse/s3fs-fuse/files/1629573/curldbg_sse-c.log)

```
$ s3fs -f XXXXX ~/Amazon.S3/ -o curldbg,dbglevel=info,url="https://s3.eu-central-1.amazonaws.com",endpoint="eu-central-1" 2>&1 | tee /dev/shm/curldbg_no_sse-c.log
$ echo "cici" > ~/Amazon.S3/cici.txt
```
[curldbg_no_sse-c.log](https://github.com/s3fs-fuse/s3fs-fuse/files/1629578/curldbg_no_sse-c.log)

**Comment by ggtakec** [comment]
@alindt Thanks for sending your log.
There is certainly an error 400 in your log processing in your log.
I will try to confirm a little time.
Regards,

**Comment by ggtakec** [comment]
@alindt 
This problem is caused by the small number of characters of AWSSSECKEYS you specified.
Please specify at least 32 characters in AWSSSECKEYS. Otherwise, in S3fs, an error "The secret key was invalid for the specified algorithm" is received from S3 API and an EIO error occurs.
Please retry with at least 32 characters for AWSSSECKEYS environemnt.

**Comment by alindt** [comment]
@ggtakec thank you for the explanation - it makes sense.
It would be useful to make this error (and others) more visible for the end user when using s3fs.

**Comment by xuemingcoffeehuang** [comment]
i have a similar problem that i get the input/output error:
[root@weixin-static-u53mq storage]# chown apps:apps @vmr
chown: changing ownership of `@vmr': Input/output error

i dont know if is because of the character '@'
'@vmr' is a directory in /my/mount/point
