### ISSUE TITLE
Support for file ACL (setfacl, getfacl) setfacl: filename: Operation not supported

### ISSUE THREAD

**Issue by melaraj2** [s3fs-fuse/s3fs-fuse#698]
Is there any planned support for file ACLs?  Currently I get this error when I try to setfacl on files in the mounted folder:

setfacl: filenam: Operation not supported

**Comment by ggtakec** [comment]
@melaraj2 You can specify use_xattr option at start s3fs.
Please try it.
Thanks in advance for your assistance.

**Comment by gaul** [comment]
@melaraj2 Did you try testing with a newer version of s3fs and `-o use_xattr`?

**Comment by gaul** [comment]
Please reopen if the latest version 1.85 does not resolve your symptoms.

**Comment by AgrawalAmey** [comment]
@ggtakec @gaul I was trying to use the ACLs with s3fs, after enabling use_xattr, setfacl and getfacl are working fine, but looks like these values are not getting used in actually resolving the permissions. For example, if Alice has a file foo with permissions 700, if we give rwx access to Bob using setfacl, the correct acl string would show up in getfacl. But if I try to cat the file as user Bob, it fails with "Operation not permitted" error.

**Comment by abhilashck72** [comment]
Any solution for this. I am also facing same issue,,without giving 777 it wont work. use_xattr is able to set permission, but it never works in actual operation.
