### ISSUE TITLE
s3fs is taking more cpu in ubuntu 16.0.4

### ISSUE THREAD

**Issue by chand8** [s3fs-fuse/s3fs-fuse#700]
Recently I have migrated my website from ubuntu 12 to 16. From that time, s3fs is taking more cpu.

My mount options are
/usr/local/bin/s3fs my-data-01 /var/www/application/public/data -opasswd_file=/etc/passwd-s3fs -ouse_cache=/tmp -oallow_other -ourl=https://s3.amazonaws.com -ouid=48 -ogid=48 -oumask=022

![image](https://user-images.githubusercontent.com/20638334/34046861-7bb9590e-e1d4-11e7-955d-ade4866829a8.png)

s3fs --version
Amazon Simple Storage Service File System 1.70

Lots of s3fs processes are running

![error-s3fs](https://user-images.githubusercontent.com/20638334/34047983-095cc78e-e1d8-11e7-96bc-4def31903f2e.png)

**Comment by ggtakec** [comment]
@chand8 I'm sorry for my late reply.
It seems that s3fs is old version, probably we hard to support that version.
If you could update s3fs(latest version is v.1.83), please try to use latest one.
Thanks in advance for your assistance.

**Comment by gaul** [comment]
@chand8 Sorry this is too broad of an issue for us to act upon.  Try profiling with `perf` and see where the bottleneck lies.

**Comment by gaul** [comment]
I wonder if you have `updatedb` running on this machine?  This is a common symptom:

https://stackoverflow.com/questions/52372095/tracking-down-s3-costs-s3fs

**Comment by gaul** [comment]
Please reopen if the suggested workaround does not address your symptoms.
