### ISSUE TITLE
linux ls is pending while one of the file in the directory is opened for writing.

### ISSUE THREAD

**Issue by winglq** [s3fs-fuse/s3fs-fuse#707]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

#### Version of s3fs being used (s3fs --version)
Amazon Simple Storage Service File System V1.83(commit:e1dafe7) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

#### Version of fuse being used (pkg-config --modversion fuse)
fuse-2.9.2-8.el7.x86_64

### Details about issue
I think ls is a read operation, why it could not happen concurrently with a write operation. Obviously, ext3/4 support this.
Thanks.

**Comment by gaul** [comment]
Fixed by 50d13255e4a732a620e7dad294204090d7e37655.
