### ISSUE TITLE
s3fs-fuse-NFS problems

### ISSUE THREAD

**Issue by DHB-liuhong** [s3fs-fuse/s3fs-fuse#709]
Hello,I use s3fs-fuse to mount object-storage bucket，and want to share the mounted directory for others by NFS，The configure file of NFS /etc/exports is 
/onest/t01 10.139.6.0/24(rw,no_root_squash,fsid=2)
/onest/t02 10.139.6.0/24(rw,root_squash,fsid=3)
I find some problem.  
## **1.** 
  when I  operate(cp,mkdir,touch) the directory t01 with root user, It is ok
   But I  operate(eg:vi ) the directory t01 with a general user,eg：onest
  

> 
 [onest@test03 t01]$ ls -al
drwxrwxrwx  1 root      root          0 Jan  1  1970 .
drwxr-xr-x 10 root      root       4096 Jan 29 14:22 ..
-rw-rw-r--  1 onest     onest        15 Jan 29  2018 lhobject2
----------  1 onest     onest         0 Aug  4  1974 .lhobject2.swp
  You will find a swp file.
## **2** 
  If I want to copy a file to t01 with onest user
> 
 [onest@test03 test]$ cp /home/onest/testfile t01
cp: cannot create regular file ‘t01/testfile’: Permission denied
   Although you can see this file in the directory, but nothing in it ,its permissions is 000
> 
[onest@test03 t01]$ ll
---------- 1 nfsnobody nfsnobody     0 Jul 19  2034 lhobject1
-rw-rw-r-- 1 onest     onest        15 Jan 29 14:37 lhobject2
---------- 1 onest     onest         0 Aug 17  1974 testfile
## **3**  
when I  operate(cp,mkdir,touch) the directory t02 with root user or a general user,I will have the same question as above

**Comment by DHB-liuhong** [comment]
@rrizun could you help me take a look? thanks:-)

**Comment by DHB-liuhong** [comment]
i have solved it

**Comment by henres** [comment]
Hello @DHB-liuhong Can you describe your final nfs configuration ? And how you solved it ?

Thanks

**Comment by zulaysalas** [comment]
Hi @DHB-liuhong, can you please describe the nfs setup and how you solved it. I am using s3fs-fuse on Ubuntu 22 to mount an object storage bucket and am having problems with the commands (cp, mkdir, touch, rsync, mv). 

Thanks!
