### ISSUE TITLE
S3fs-fuse support samba?

### ISSUE THREAD

**Issue by DHB-liuhong** [s3fs-fuse/s3fs-fuse#716]
I use s3fs-fuse to mount storage bucket, use samba to share the shared directory to windows user。
I found that the doc file has messy code in it when I open it again after modifying a doc file and save it.
The md5 value of the doc file in storage bucket and storage bucket isn't the same.

**Comment by gaul** [comment]
Please reopen if the latest version 1.85 does not address your symptoms.
