### ISSUE TITLE
S3FS Getting A Performance Boost From Elastic Network Adapter (ENA) ?

### ISSUE THREAD

**Issue by tspicer** [s3fs-fuse/s3fs-fuse#717]
Looks like if setup correctly, the pipe between EC2 and S3 just got a big upgrade. I was curious how this impacts S3FS. My assumption is that it would realize the benefits of this upgrade, but maybe it is not so simple :)

"Traffic to and from Amazon Simple Storage Service (S3) can now take advantage of up to 25 Gbps of bandwidth. Previously, traffic of this type had access to 5 Gbps of bandwidth. This will be of benefit to applications that access large amounts of data in S3 or that make use of S3 for backup and restore."

https://aws.amazon.com/blogs/aws/the-floodgates-are-open-increased-network-bandwidth-for-ec2-instances/

**Comment by gaul** [comment]
That is a lot of bandwidth!  I suspect that s3fs needs some tuning to take advantage of this.  @orozery added some performance improvements a few months ago so I encourage you to test with the latst version and report back.  It would also be interesting to compare with [goofys](https://github.com/kahing/goofys).

**Comment by tspicer** [comment]
Was not familiar with goofys so thanks for the tip. In terms of testing i will look at what would be involved and report back once I have some time to undertake it.

**Comment by MaartenW** [comment]
Sounds very interesting. Were you able to allocate some time to investigate?

**Comment by tspicer** [comment]
I have not. We have prioritized stability vs speed at the moment so I have not looked at this

**Comment by gaul** [comment]
You should test with master which has some performance improvements.  Also see #743 which suggests tuning `-o multipart_size`.

**Comment by gaul** [comment]
Newer versions of s3fs improve write speed.  #941 tracks automatically tuning the part sizes.  We do expect AWS ENA to improve performance.
