### ISSUE TITLE
Environment Variables for Creds

### ISSUE THREAD

**Issue by jashaffe** [s3fs-fuse/s3fs-fuse#720]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

#### Version of s3fs being used (s3fs --version)
_example: 1.83

#### Version of fuse being used (pkg-config --modversion fuse)
_example: 2.9.4

#### System information (uname -r)
_command result: 4.9.76-3.78.amzn1.x86_64

#### Distro (cat /etc/issue)
_command result: Amazon Linux AMI release 2017.09

#### s3fs command line used (if applicable)
```
```
#### /etc/fstab entry (if applicable): 
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
### Details about issue
The instructions state that: setting the AWSACCESSKEYID and AWSSECRETACCESSKEY environment variables is an acceptable way of passing creds.  When I do a man s3fs this doesnt show possible.  I've noticed that older versions accept creds in arguments.  Is the only way to write the API keys to file?  I'd rather not write them disk for security.

Thanks!

**Comment by spacesuitdiver** [comment]
@jashaffe a quick look at the .cpp it seems like it's still a thing? https://github.com/s3fs-fuse/s3fs-fuse/blob/master/src/s3fs.cpp#L4136

**Comment by gaul** [comment]
Works for me.
