### ISSUE TITLE
AWSChina Supports

### ISSUE THREAD

**Issue by 15921050052** [s3fs-fuse/s3fs-fuse#722]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

#### Version of s3fs being used (s3fs --version)
latest

#### Version of fuse being used (pkg-config --modversion fuse)
2.9.7

#### System information (uname -r)
3.10.0-327.el7.x86_64

#### Distro (cat /etc/issue)
\S
Kernel \r on an \m

#### s3fs command line used (if applicable)
```
```
#### /etc/fstab entry (if applicable): 
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
### Details about issue
s3fs endpoint not support AWS China, because AWSChina used a different url
s3.cn-north-1.amazonaws.com.cn
while the code in line s3fs.cpp [3771](https://github.com/s3fs-fuse/s3fs-fuse/blob/master/src/s3fs.cpp#L3771) is
```
http://s3.amazonaws.com 
```
I just modified source code in my server environment
May some will commit a patch.

**Comment by lizepeng** [comment]
The following command usage works in my environment. :)

```bash
s3fs $BUCKET_NAME $PATH_TO_LOCAL -o passwd_file=$PATH_TO_PASSWORD -o url=https://s3.cn-north-1.amazonaws.com.cn/ -o use_path_request_style -o endpoint=cn-north-1 -o complement_stat -o allow_other -o dbglevel=info -f -o curldbg
```

**Comment by gaul** [comment]
@15921050052 Did @lizepeng suggestion work?  If so please close this issue.

**Comment by gaul** [comment]
Please reopen if the suggested workaround does not address your symptoms.

**Comment by socrateslee** [comment]
just note that the above workaround with ```-o url=https://s3.cn-north-1.amazonaws.com.cn/``` also works with ``` -o iam_role=auto```
