### ISSUE TITLE
How to make the performance turning for the big data files?

### ISSUE THREAD

**Issue by wangf8406** [s3fs-fuse/s3fs-fuse#743]
#### Version of s3fs being used (s3fs --version)
_example: 1.87

### Details about issue
Hi there, we now working on backup the big files (usually 200G to 400G), how to configure the options to make the S3FS have best performance ? currently the connection bandwidth is enough to get the best transport performance? the main scenario is to transfer the big files .

**Comment by gaul** [comment]
You should try tuning the `-o multipart_size` flag since its default 10 MB is low for large files.  This should influence both read and write speeds.  Please share the results of your test which other users will value!

**Comment by lsde** [comment]
I can confirm a huge increase in read performance after increasing the part size.
In our case, 300% increase on large files (hundreds of GBs) with `-o multipart_size=100` using MINIO as a backend.

**Comment by gaul** [comment]
#941 tracks automatically tuning the part size.
