### ISSUE TITLE
Does s3fs support AWS Batch job role?

### ISSUE THREAD

**Issue by monitoringit** [s3fs-fuse/s3fs-fuse#746]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

#### Version of s3fs being used (s3fs --version)
_example: 1.00_

#### Version of fuse being used (pkg-config --modversion fuse)
_example: 2.9.4_

#### System information (uname -r)
_command result: uname -r_

#### Distro (cat /etc/issue)
_command result: cat /etc/issue_

#### s3fs command line used (if applicable)
```
```
#### /etc/fstab entry (if applicable): 
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, or s3fs outputs)  
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
### Details about issue
If i am trying to mount s3fs within a container (executed by AWS Batch) running on an ec2 machine, will -o iam_role option while mounting s3fs, honor container's job role or will it only use underlying ec2 host iam role?

**Comment by monitoringit** [comment]
I can confirm that the AWS Batch job roles are not honoured but underlying ec2 instance profile role is what s3fs honors when using -o iam_role option [curl -s http://169.254.169.254/latest/meta-data/iam/info]. It will really be nice to make s3fs use job roles over ec2 instance role as then access to s3 folders can be granted at job level rather than ec2 instance level.

**Comment by monitoringit** [comment]
will using job role over ec2 iam role be a priority in future?

**Comment by gaul** [comment]
Can someone clarify what needs to be fixed here?  s3fs has both the `-o ecs` and `o iam_role` flags -- do these allow use of the batch role?

**Comment by gaul** [comment]
Please reopen if symptoms persist.
