### ISSUE TITLE
How to use it on windows machine?

### ISSUE THREAD

**Issue by GajananMore** [s3fs-fuse/s3fs-fuse#752]
### Additional Information
_I am new s3fs. I was looking how can I use it on windows machine._

### Details about issue
can you please guide me how to make this work on my windows machine.

**Comment by gaul** [comment]
See #728 and #712.  I do not believe this works presently but needs some more WinFSP work.

**Comment by ggtakec** [comment]
@GajananMore Please watch #728.
@gaul Thanks.
