### ISSUE TITLE
Multi users sharing same s3 bucket 

### ISSUE THREAD

**Issue by anasos** [s3fs-fuse/s3fs-fuse#757]
Hi, 
Can multi users share the same S3 bucket with s3fs-fuse. I'm asking cause when differents users try to access or edit the same file i got permission errors.

**Comment by scottconrad88** [comment]
+1

**Comment by gaul** [comment]
Try specifying `-o umask=027` and `-o uid=1000` or similar in your mount flags.

**Comment by gaul** [comment]
Please reopen if the suggested workaround does not address your symptoms.
