### ISSUE TITLE
InvalidRequest Error while trying to connect to new Frankfurt Region

### ISSUE THREAD

**Issue by idvl** [s3fs-fuse/s3fs-fuse#76]
Hello,

we currently aren't able to connect to the S3 buckets of the new region (Frankfurt), the error message provided is following:
```
CheckBucket(2400): Check bucket failed, S3 response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId> ...
```

As far as I know the new region only supports the newest version of the Amazon API (V4), because it was deployed after jan. 2014: http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

Has anybody a clue how to enable V4 and thus enable support for new S3 regions?

Thanks!

**Comment by imrehg** [comment]
Just tried this as well on a bucket that happens to be in Frankfurt. Here's the result from the debug and running it in the foreground:

    set_moutpoint_attribute(3379): PROC(uid=1000, gid=1000) - MountPoint(uid=1000, gid=1000, mode=40755)
    FUSE library version: 2.9.3
    nullpath_ok: 0
    nopath: 0
    utime_omit_ok: 0
    unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
    INIT: 7.23
    flags=0x0003f7fb
    max_readahead=0x00020000
    s3fs_init(2650): init
    s3fs_check_service(2968): check services.
        CheckBucket(2367): check a bucket.
        RequestPerform(1572): connecting to URL http://viadrivers.s3.amazonaws.com/
    RequestPerform(1705): ### CURLE_HTTP_RETURNED_ERROR
    RequestPerform(1710): HTTP response code =400
    s3fs: Failed to access bucket.

**Comment by Halderian** [comment]
There is already an implementation for generating the signatures at 

https://github.com/bradclawsie/awsv4-cpp

It just needs to be implemented. 
Please fix this problem. Some peoble are waiting for this feature. It is open for nearly 4 months now.

**Comment by grzegorz-dubicki** [comment]
+1 vote for implementing this

**Comment by Halderian** [comment]
+1
This seems to work. But "us-east-1" is hard coded in src/s3fs.cpp in line 92. I changed it to "eu-central-1" to be able to mount the bucket on my Ubuntu 14.04. 
Thanks to @ggtakec!

**Comment by ggtakec** [comment]
Hi, all

I'm sorry for replying late.
I have pushed latest codes to dev_sv4 branch now.
It is cleanup codes and adding new "sigv2" option. Then s3fs supports old signature version 2.

@Halderian 
you can change end-point by endpoint option. please see man page or codes.

Please take care for that dev_sv4 branch does not support NSS/GnuTLS yet.
It support only openssl version.
I'll work for supporting NSS/GnuTLS, please wait a moment.

Regards,

**Comment by idvl** [comment]
Great ​news, thanks @ggtakec!

**Comment by ggtakec** [comment]
Hi, all

I merged codes to master branch.(please see #116 )
It supported following:
- Supported signature version 4(OpenSSL/NSS/GnuTLS)
- Added endpoint and sigv2 option
- Automatically select endpoint(region)/sigv2 as fault tolerant(*)

(*)
If you do not specify endpoint and sigv2 option, s3fs try to connect default("us-east-1") region with sig v4.
And if s3fs can not connect default region, s3fs retry to connect to your bucket's correct region automatically by checking error message from S3.
And at last, when s3fs failed to connect yet, s3fs retry to connect with sig v2.

I closed this issue, and if you find any bugs, please let me know and open new issue.

Regards,
