### ISSUE TITLE
Wordpress / Images

### ISSUE THREAD

**Issue by sibaberpollo** [s3fs-fuse/s3fs-fuse#772]
Friends. I have a wordpress whose wp-content directory (css, js and images), is mounted with s3fs. It happens that when we try to close the permissions in the bucket, the images are no longer available in the Wordpress administrator.

##########################################################################

s3fs#bckt-prod-nfinde:/wp-content/uploads    /usr/share/nginx/html/finde/wp-content/uploads/    fuse    use_cache=/tmp,allow_other    0    0

"Id": "Policy152762aqweqwe8181233262",
   "Version": "2012-10-17",
   "Statement": [
     {
       "Sid": "Stmt152qwe712321362qeqe",
       "Action": "s3: *",
       "Effect": "Allow",
       "Resource": [
         "arn: aws: s3 ::: bckt-prod-nfinde",
         "arn: aws: s3 ::: bckt-prod-nfinde / *"
       ],
       "Principal": {
         "AWS": [
           "876876878564546"
         ]
       }
     }
   ]
}

**Comment by tspicer** [comment]
Are your permissions the same as the ones used by Apache, Nginx, PHP-FPM? It is possible that something is happening where users are not aligned.

**Comment by Jeet-14** [comment]
principal should be whole ARN

**Comment by gaul** [comment]
Please try the suggested workarounds and reopen the issue with more details if the symptoms persist.
