### ISSUE TITLE
Requirement for operating system distribution version

### ISSUE THREAD

**Issue by ZVampirEM77** [s3fs-fuse/s3fs-fuse#773]
Hi all,

Does s3fs have any requirement for operating system distribution version.

**Comment by ggtakec** [comment]
We kept this issue open for a long time.
See https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes for a list of clearly supported operating systems.
I close this, but if there is an OS you want to support other than above, please create a new issue.
