### ISSUE TITLE
Fedora packaging

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#785]
It would be great if Fedora included `s3fs` in its package repository for parity with the Ubuntu package.  Can someone step forward to write a spec file and submit it to Red Hat?  I found this issue which is open:

https://bugzilla.redhat.com/show_bug.cgi?id=725292

@dreampuf has a spec file mentioned in #648 but never submitted a pull request.

**Comment by juliogonzalez** [comment]
If you are interested, I think I can take care of it, since I already have https://github.com/juliogonzalez/s3fs-fuse-rpm, including CI with docker containers.

**Comment by gaul** [comment]
@juliogonzalez It would be great if you could get Fedora to include `s3fs`!

Also it looks like SUSE already packages `s3fs`:

https://software.opensuse.org/package/s3fs

Could you add installation instructions to our `README.md`?

**Comment by juliogonzalez** [comment]
@gaul, about your request for SUSE and openSUSE, see #789.

I can also temporary add the instructions to use my repository, as it's able to build for Fedora, CentOS, Amazon Linux.

About adding the packages to Fedora, please see my comment at https://bugzilla.redhat.com/show_bug.cgi?id=725292#c31

I guess we should also submit it to [EPEL](https://fedoraproject.org/wiki/EPEL), to make it available for RHEL7/CentOS7 (as you can see at my repository RHEL6/CentOS6 is another story because of the old FUSE version), and that should make it also available for recent Amazon Linux versions.

**Comment by juliogonzalez** [comment]
I fixed several things after reviewing Fedora doc, see https://github.com/juliogonzalez/s3fs-fuse-rpm/commits/master

Submission is now ready at https://bugzilla.redhat.com/show_bug.cgi?id=1631988 (provided I did not miss any steps of the looooooooooong procedure for Fedora submissions).

I also added a webhook at https://github.com/juliogonzalez/s3fs-fuse-rpm, so for each commit for master will be built at copr: https://copr.fedorainfracloud.org/coprs/juliogonzalez/s3fs-fuse/

Koji build is working for the latest copr build: https://koji.fedoraproject.org/koji/taskinfo?taskID=29814931

Now I am waiting for review to see if I need to change anything, and trying to see if I can get a sponsor. I will present myself at Fedora's devel list and we'll see.

@gaul, can you assign this issue to me?

**Comment by gaul** [comment]
Awesome, thank you for pushing this forward!

**Comment by juliogonzalez** [comment]
s3fs-fuse is now submitted for:

- Fedora 27: https://bodhi.fedoraproject.org/updates/FEDORA-2018-c6b8690956
- Fedora 28: https://bodhi.fedoraproject.org/updates/FEDORA-2018-e986513c51
- Fedora 29: https://bodhi.fedoraproject.org/updates/FEDORA-2018-e986513c51
- EPEL7: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2018-9ad5351ee5

As soon as the submissions have enough karma, s3fs-fuse should make into F27, F28 and EPEL7.

F29 could take some more time as right now I think it's frozen in Beta state.

**Comment by juliogonzalez** [comment]
Good news:

Fedora 27:
```
[root@782d15bb8290 /]# cat /etc/fedora-release 
Fedora release 27 (Twenty Seven)
[root@782d15bb8290 /]# yum info s3fs-fuse
Last metadata expiration check: 0:01:19 ago on Sat Oct  6 20:08:15 2018.
Available Packages
Name         : s3fs-fuse
Version      : 1.84
Release      : 2.fc27
Arch         : x86_64
Size         : 241 k
Source       : s3fs-fuse-1.84-2.fc27.src.rpm
Repo         : updates
Summary      : FUSE-based file system backed by Amazon S3
URL          : https://github.com/s3fs-fuse/s3fs-fuse
License      : GPLv2+
Description  : s3fs is a FUSE file system that allows you to mount an Amazon S3 bucket as a
             : local file system. It stores files natively and transparently in S3 (i.e.,
             : you can use other programs to access the same files). Maximum file size=64GB
             : (limited by s3fs, not Amazon).
             : 
             : s3fs is stable and is being used in number of production environments, e.g.,
             : rsync backup to s3.
```
Fedora 28:
```
[root@60b47df2003f /]# cat /etc/fedora-release 
Fedora release 28 (Twenty Eight)
[root@60b47df2003f /]# yum info s3fs-fuse
Last metadata expiration check: 0:01:27 ago on Sat Oct  6 20:08:18 2018.
Available Packages
Name         : s3fs-fuse
Version      : 1.84
Release      : 2.fc28
Arch         : x86_64
Size         : 254 k
Source       : s3fs-fuse-1.84-2.fc28.src.rpm
Repo         : updates
Summary      : FUSE-based file system backed by Amazon S3
URL          : https://github.com/s3fs-fuse/s3fs-fuse
License      : GPLv2+
Description  : s3fs is a FUSE file system that allows you to mount an Amazon S3 bucket as a
             : local file system. It stores files natively and transparently in S3 (i.e.,
             : you can use other programs to access the same files). Maximum file size=64GB
             : (limited by s3fs, not Amazon).
             : 
             : s3fs is stable and is being used in number of production environments, e.g.,
             : rsync backup to s3
```
EPEL7 (test is latest CentOS7):
```
[root@13d94f614265 /]# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 
[root@13d94f614265 /]# yum info s3fs-fuse
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.airenetworks.es
 * epel: mirror.airenetworks.es
 * extras: mirror.airenetworks.es
 * updates: mirror.airenetworks.es
Available Packages
Name        : s3fs-fuse
Arch        : x86_64
Version     : 1.84
Release     : 2.el7
Size        : 240 k
Repo        : epel/x86_64
Summary     : FUSE-based file system backed by Amazon S3
URL         : https://github.com/s3fs-fuse/s3fs-fuse
License     : GPLv2+
Description : s3fs is a FUSE file system that allows you to mount an Amazon S3 bucket as a
            : local file system. It stores files natively and transparently in S3 (i.e.,
            : you can use other programs to access the same files). Maximum file size=64GB
            : (limited by s3fs, not Amazon).
            : 
            : s3fs is stable and is being used in number of production environments, e.g.,
            : rsync backup to s3.
```
As I commented before, Fedora 29 will take some more time, as fedora is currently on Beta Freeze state. s3fs-fuse should be added to the update repositories by the end of the month, when Fedora 29 is GA.

For more details, check https://fedoraproject.org/wiki/Releases/29/Schedule

**Comment by gaul** [comment]
@juliogonzalez The packaging is great news; thanks for leading this!  This will make s3fs more accessible to users.
