### ISSUE TITLE
S3FS-Issues Cache

### ISSUE THREAD

**Issue by SakshiGarg123** [s3fs-fuse/s3fs-fuse#787]
I ran the following commands to run the s3fs.

```
RUN apt-get -y install automake autotools-dev fuse g++ git libcurl4-gnutls-dev libfuse-dev libssl-dev libxml2-dev make pkg-config
RUN git clone https://github.com/s3fs-fuse/s3fs-fuse.git
RUN cd s3fs-fuse && ./autogen.sh && ./configure --prefix=/usr && make && make install.
```

After mounting though I didn't mention `use_cache=""` which should be by default false but executing `du -h` I saw that entire data was occupying space. Why is it so ?

**Comment by gaul** [comment]
s3fs uses the temporary directory to stage uploads.  The application writes to s3fs which writes to the temporary directory and on close s3fs uploads to S3.
