### ISSUE TITLE
Doc issue with option createbucket

### ISSUE THREAD

**Issue by ebarault** [s3fs-fuse/s3fs-fuse#788]
The main `Readme.md` states a non-existent `create_bucket` option.

As mentionned in https://github.com/s3fs-fuse/s3fs-fuse/issues/225, the right option is `createbucket`

This option is not present in the man, or in the "Fuse Over Amazon" doc.

It should also be mentionned that this option seems incompatible with `/etc/fstab` configuration: i cannot manage auto-mounting a volume when using the `createbucket` option in the `/etc/fstab` file

**Comment by ggtakec** [comment]
@ebarault Thanks for your kindness.
I added createbucket option explanation to [WIKI](https://github.com/s3fs-fuse/s3fs-fuse/wiki/Fuse-Over-Amazon#createbucket).
