### ISSUE TITLE
Installing on Ubuntu 14.10

### ISSUE THREAD

**Issue by edsadr** [s3fs-fuse/s3fs-fuse#81]
Hello

After run:

./configure --prefix=/usr --with-openssl 

you get:

./configure: line 4271: syntax error near unexpected token `common_lib_checking,'
./configure: line 4271:`PKG_CHECK_MODULES(common_lib_checking, fuse >= 2.8.4 libcurl >= 7.0 libxml-2.0 >= 2.6)'

All dependencies were installed according to the documentation

Regrads

Adrian

**Comment by movermeyer** [comment]
The Docker image link no longer works. Is it backed by a github repo by chance?

**Comment by movermeyer** [comment]
I had the same issue.
In my case, I was missing the pkg-config package.

    apt-get install pkg-config
    ./autogen.sh
Fixed it for me.

**Comment by muktaa** [comment]
@movermeyer - thanks for pointing out, please check if the docker image link is accessible now.
https://registry.hub.docker.com/u/ihealthtechnologies/s3-mount/

**Comment by movermeyer** [comment]
@muktaa Looks good now. Cheers.

**Comment by jmullee** [comment]
for me, what worked:
apt-get install build-essential ibcurl4-openssl-dev libxml2-dev pkg-config libssl-dev libfuse-dev
./autogen.sh # (re-run after installing packages)
./configure --with-openssl
./make
