### ISSUE TITLE
Cannot read files through S3 mount

### ISSUE THREAD

**Issue by hhg7** [s3fs-fuse/s3fs-fuse#814]
Hello,

I am attempting to read files on AWS, simply read them with a perl script. However, the mount I have on my Ubuntu system will hang when I try to even look at the contents of the file, e.g. `head file.txt` will never complete.

How can I read the files on the S3 mount?

I'm using s3fs 1.61 on Linux kernel 4.15.0-33-generic on Ubuntu 18.04.1 LTS with fuse version 2.9.7

**Comment by gaul** [comment]
Please reopen if you can demonstrate these symptoms on the latest release version, 1.85.
