### ISSUE TITLE
Can you force every file upload operation to be multi-part?

### ISSUE THREAD

**Issue by blidarescub** [s3fs-fuse/s3fs-fuse#816]
I have a scenario where I need every file to be uploaded in multi-part, because it triggers some events in SQS. Currently, only files bigger than 10MB are being uploaded in multi-part. I could not find any combination of command arguments that changes this.
Thanks

**Comment by gaul** [comment]
Could you set `-o multipart_size` to zero and see if this works?  Otherwise we might need some tweaks on this code path and we would accept PRs for this.

**Comment by kahing** [comment]
Files smaller than 5MB cannot use multipart upload

**Comment by gaul** [comment]
According to s3-tests, 1 byte MPUs work but 0 byte fail with `MalformedXML`.

**Comment by blidarescub** [comment]
@gaul As far as i remember it did not, the winning combo for me was this: `-o use_cache=/tmp -o allow_other -o uid=1000 -o singlepart_copy_limit=5 -o multipart_size=5 -o multireq_max=5`

**Comment by ggtakec** [comment]
s3fs internally has the lower limit of the multipart_size option.
Its value is `5`, which means `5MB`.
If it is necessary to be able to set a value smaller than this, we will be able to allow to exclude the lower limit.
However, even if it is possible to set a minimum value of 1 byte, it seems that s3fs creates a 0 byte file before first file upload, so it may not be possible to avoid the SQS action.
