### ISSUE TITLE
s3fs should use a .aws/credentials profile

### ISSUE THREAD

**Issue by jeremyjjbrown** [s3fs-fuse/s3fs-fuse#822]
I racking my brain as to why s3fs would ask for a custom formatted custom file for aws credentials when there is one right on every facile aws users system at ~/.aws/credentials.

I for one rotate my keys regulary using a tool. I think it would be wise to just support the default way of doing things.

**Comment by gaul** [comment]
Agreed that s3fs should add this and a flag to choose non-default profiles for consistency with the AWS CLI.  s3fs should continue to accept the current format.  Historically s3fs used its own format sine it predate the AWS CLI.
