### ISSUE TITLE
Using the `del_cache` option does not remove the cache directory completely.

### ISSUE THREAD

**Issue by CMCDragonkai** [s3fs-fuse/s3fs-fuse#827]
Running 1.84, and the `del_cache` option doesn't remove the entire cache directory. The directory is left with a `.BUCKET.mirror/` directory.

Not sure what that directory is for, but surely the `del_cache` option as documented is intended to delete the whole cache directory right?

Also I noticed that the documentation doesn't mention this, but you need to set an absolute path for `use_cache='/abspath'`.

**Comment by gaul** [comment]
@CMCDragonkai Could you open a pull request to fix the documentation?
