### ISSUE TITLE
"s3fs: specified passwd_file is not readable."

### ISSUE THREAD

**Issue by olalonde** [s3fs-fuse/s3fs-fuse#836]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on MacOS or BSD_

#### Version of s3fs being used (s3fs --version)
$ s3fs --version
V1.84(commit:unknown)

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_example: 2.9.4_

#### Kernel information (uname -r)
17.5.0

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
MacOS

#### s3fs command line used, if applicable
```
s3fs mybucket ~/Documents/mybucket -o passwd_file=~/.passwd-s3fs
```
### Details about issue

```
$ s3fs mybucket ~/Documents/mybucket -o passwd_file=~/.passwd-s3fs

s3fs: specified passwd_file is not readable.
$ whoami
olalonde
$ ll ~/.passwd-s3fs
-rw-------  1 olalonde  staff    62B Oct 11 10:27 /Users/olalonde/.passwd-s3fs
```

**Comment by olalonde** [comment]
Ah, it works if I use the full path `/Users/olalonde/.passwd-s3fs` instead of `~/.passwd-s3fs`...

**Comment by gaul** [comment]
The shell expands tildes but only when they are the leading character of a string.

**Comment by olalonde** [comment]
Makes sense... would be a good idea to update `-o passwd_file=~/.passwd-s3fs` in the README, maybe `-o passwd_file=$HOME/.passwd-s3fs`?

**Comment by IamMohitM** [comment]
The `passwd_file=~/.passwd-s3fs` will fail if the path has quotes surrounding it `passwd_file="~/.passwd-s3fs"`
