### ISSUE TITLE
mount fails on eu-central-1 hosting

### ISSUE THREAD

**Issue by logicfish** [s3fs-fuse/s3fs-fuse#84]
bash-4.2# /opt/bin/s3fs  -o allow_other -f -d  logicfish-crux-ports ~/mnt
    set_moutpoint_attribute(3291): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40755)
s3fs_init(2595): init
s3fs_check_service(2894): check services.
    CheckBucket(2228): check a bucket.
    RequestPerform(1467): connecting to URL http://logicfish-crux-ports.s3.amazonaws.com/
RequestPerform(1595): ### CURLE_HTTP_RETURNED_ERROR
RequestPerform(1600): HTTP response code =400
s3fs: Failed to access bucket.
bash-4.2#

**Comment by ggtakec** [comment]
Hi, logicfish
I'm sorry for replying late.
Please see #76 and #116, probably this issue is solved.
I'm going to close this issue, but if you have any problem yet, please post new issue.
Regards,
