### ISSUE TITLE
Can't mount S3 prefix which contains '.' in the path.

### ISSUE THREAD

**Issue by samuel281** [s3fs-fuse/s3fs-fuse#842]
#### Version of s3fs being used (s3fs --version)
1.84

#### Kernel information (uname -r)
4.14.62-65.117.amzn1.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami

#### s3fs command line used, if applicable
```
s3fs $BUCKET_NAME:"/notebook/firstname.lastname/" notebook -o rw,allow_other,iam_role=$ROLE,endpoint=eu-central-1,dbglevel=debug,curldbg -f
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
GET /notebook/firstname.lastname/ HTTP/1.1
host: aws-data-bonial-production-notebooks.s3.amazonaws.com
User-Agent: s3fs/1.84 (commit hash unknown; OpenSSL)
Accept: */*
Authorization: ***: ***
x-amz-date: 20181019T143640Z
x-amz-security-token: ***
< HTTP/1.1 404 Not Found
< x-amz-request-id: DB89775C4907FF0B
< x-amz-id-2: P4C//El7W4GQ8pZxGQkOujbaJwEkiAI6NZNNPd35OKqkJR3oopIL3aFDxI89CciLfEj0FsLD6Rs=
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Fri, 19 Oct 2018 14:36:40 GMT
< Server: AmazonS3
<
* Connection #1 to host ***-production-notebooks.s3.amazonaws.com left intact
[INF]       curl.cpp:RequestPerform(2082): HTTP response code 404 was returned, returning ENOENT
[DBG] curl.cpp:RequestPerform(2083): Body Text: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>notebook/firstname.lastname/</Key><RequestId>DB89775C4907FF0B</RequestId><HostId>***</HostId></Error>
[ERR] curl.cpp:CheckBucket(3104): Check bucket failed, S3 response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>notebook/firstname.lastname/</Key><RequestId>DB89775C4907FF0B</RequestId><HostId>***</HostId></Error>
[CRT] s3fs.cpp:s3fs_check_service(3780): bucket not found(host=https://s3.amazonaws.com) - result of checking service.
[DBG] curl.cpp:ReturnHandler(309): Return handler to pool: 31
[ERR] s3fs.cpp:s3fs_exit_fuseloop(3369): Exiting FUSE event loop due to errors
```
### Details about issue
Mounting S3 prefix is failing when it has '.' 
It works if I remove the dot.

**Comment by gaul** [comment]
I successfully mounted a similar directory via `s3fs bucket:/test.dir mnt/`.  Did you create this directory with s3fs or another tool?  If the latter the bucket will lack the directory object s3fs reads metadata from.

**Comment by ggtakec** [comment]
This issue is as same as #623 .
Please see for detail(which is same thing @gaul said):
https://github.com/s3fs-fuse/s3fs-fuse/wiki/FAQ#q-could-not-mount-with-specifying-the-path-under-bucket

I will close this, but if the problem persists, please reopen or post a new issue.
Thanks in advance for your assistance.
