### ISSUE TITLE
s3fs[2008]: segfault at 0 ip 0000000000423639 sp 00007fe075d006f0 error 4 in s3fs[400000+51000]

### ISSUE THREAD

**Issue by d3vnu11** [s3fs-fuse/s3fs-fuse#85]
Amazon Simple Storage Service File System V1.78 with OpenSSL
fuse-2.9.3
libcurl-devel-7.19.7-40.el6_6.1.x86_64
libcurl-7.19.7-40.el6_6.1.x86_64

Plenty of space on target dir partition.
Actually the problem is when I try to not use cache I get 
s3fs[2008]: segfault at 0 ip 0000000000423639 sp 00007fe075d006f0 error 4 in s3fs[400000+51000]

A problem with Libcurl ? It's a 29 gig ec2 instance the file is only 18gig for our tests.

**Comment by ggtakec** [comment]
I'm sorry about this Issue had been left at a long period of time.

If you have this problem yet, please try to use latest code.
("-f", "dbglevel" and "curldbg" options help to solve your problem.)
And if you found a problem, please post new issue.

Thanks in advance for your help.
