### ISSUE TITLE
digital ocean spaces compatibility

### ISSUE THREAD

**Issue by pjebs** [s3fs-fuse/s3fs-fuse#854]
Digital Ocean spaces claims to be S3 compatible in terms of their API and how it can be interfaced by external clients. Should s3fs work in theory?

**Comment by gaul** [comment]
Yes it should.  Please report back with your results.

**Comment by Niek** [comment]
Yes, I'm using it with DO Spaces. Just specify: ``-o url=https://ams3.digitaloceanspaces.com/`` or whatever your spaces endpoint is.

**Comment by nodje** [comment]
I got a Spaces bucket mounted on a local folder on Macos, but I can only see the 3 main folder a zero-bytes document.
Is there anything specific i should do, or is it just because the amount of sub-folder or fields in each folder is quite big?

**Comment by blitzprog** [comment]
I have the same problem as @nodje, can't access folders because they are 0-byte documents.

`----------  1 eduard eduard    0 Dec  8 17:46 documents`

**Comment by Gandalf-** [comment]
I was able to mount and access files on my SFO2 space with these options on Ubuntu 16.04.5 LTS and V1.79

I uploaded the files with s3cmd, and they all have private permissions.
```
s3fs bucket /mnt/bucket \
  -o passwd_file=$HOME/.passwd-s3fs \
  -o url=https://sfo2.digitaloceanspaces.com/ \
  -o uid=1000,gid=1000 \
  -o use_path_request_style
```

**Comment by gaul** [comment]
@Gandalf- could you mount with `-o umask=027` or try using master which provides a default when permissions do not exist?

**Comment by pjebs** [comment]
@blitzprog The problem with s3 is that there are no such thing as folders. They 'artificially' pretend 0 byte files are folders.

**Comment by gaul** [comment]
Please retest with 1.85 and reopen this issue if problems persist.

**Comment by mike503** [comment]
still an issue in s3cmd 2.0.2. out of 4 "directories" in the root of my bucket, 3 of them are 0 byte "documents" and are unable to view them as a hierarchy. only one behaves like a directory.
