### ISSUE TITLE
Access amazon using HTTPS

### ISSUE THREAD

**Issue by chrisgo** [s3fs-fuse/s3fs-fuse#86]
Can't seem to get the `url=https://s3.amazonaws.com` working

Using 1.78, Debian 7.x instructions (Vagrant using Virtualbox on Mac OSX)

`git clone https://github.com/s3fs-fuse/s3fs-fuse`
`cd s3fs-fuse/`
`./autogen.sh`
`./configure --prefix=/usr --with-openssl`
`make`
`sudo make install`

When I try to mount it using 

`sudo vi /etc/fstab`
`sudo mount /mnt/test-bucket`

with the` url=https://s3.amazonaws.com` => mount fails (shows the ???)

when I remove the `url=https://s3.amazonaws.com` from the fstab line

sudo mount /mnt/test-bucket succeeds

**Comment by ggtakec** [comment]
I'm sorry for replying late.

If you can, please run s3fs manually with "-d" and "-f" option, and check errors on display.
It seems that s3fs probably puts something error about ssl(openssl library).

thanks in advance for your help.
Regards,

**Comment by beamerblvd** [comment]
With `url=https://s3.amazonaws.com` I get these errors:

```
Feb 11 09:23:15 dns2 s3fs: init v1.78 (OpenSSL)
Feb 11 09:23:15 dns2 s3fs: ###curlCode: 51  msg: SSL peer certificate or SSH remote key was not OK
Feb 11 09:23:18 dns2 s3fs: init v1.78 (OpenSSL)
Feb 11 09:23:18 dns2 s3fs: ###curlCode: 51  msg: SSL peer certificate or SSH remote key was not OK
```

However, if I go to https://s3.amazonaws.com/anything in my browser the certificate appears to be perfect.

**Comment by ggtakec** [comment]
The curl error code 51 means that the SSL peer certificate error occurs when validation of the trust chain(not the actual certificate) fails.

Probably, I think the CA certs file which libcurl looks is different from which the browser you used looks.
So that, I recommend that you should update the CA certs files on your machine.(ex, /etc/ssl/certs)

Thanks in advance for your assistance.

**Comment by ggtakec** [comment]
I'm sorry for that this issue had been left at a long period of time.

If you have this problem yet, please try to use latest code.
If you keep to have this problem, please reopen this issue.

Thanks in advance for your help.
