### ISSUE TITLE
Disk space has been increasing and CPU load high

### ISSUE THREAD

**Issue by linux0x5c** [s3fs-fuse/s3fs-fuse#867]
s3fs version :  1.84
mount options: /usr/bin/s3fs#hbase /mnt/hbase/data fuse url=XXXX,endpoint=obs.cn-north-1.myhwclouds.com,noatime,rw,ensure_diskfree=30000 0 0

issue:
1.my root disk have lot of deleted about s3fs,and disk space has been increasing.
2.when my root disk space less than 30000MB,my CPU load become very very high,so that I can't work properly.

**Comment by Gandalf-** [comment]
The disk usage may be related to the findings in Issue #873
It appears that disk caching is always enabled, and has unbounded size.

**Comment by gaul** [comment]
Please test with the latest version 1.87.

**Comment by gaul** [comment]
Please reopen if symptoms persist.
