### ISSUE TITLE
bucket mounted by user01 successfully but all subfolders are owned by root so no access by user01

### ISSUE THREAD

**Issue by s4mx** [s3fs-fuse/s3fs-fuse#868]
### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
V1.84(commit:d9e89de) with OpenSSL

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
libfuse2 (= 2.9.2-4ubuntu4.14.04.1)

#### Kernel information (uname -r)
4.2.0-27-generic

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

#### s3fs command line used, if applicable
s3fs -o allow_other s3-bucket /s3mount/s3-bucket -o passwd_file=~/.passwd-s3fs
```
### Details about issue
user01@pbcg01:s3mount$ ll
drwxrwxrwx  1 user01 pbix    0 Dec 31  1969 s3-bucket

user01@pbcg01:s3mount$  ll s3-bucket/
total 5
drwxrwxrwx 1 xuem01 pbix    0 Dec 31  1969 ./
drwxrwsr-x 4 root   pbix 4096 Dec  4 17:47 ../
d--------- 1 root   root    0 Dec 31  1969 data/

**Comment by gaul** [comment]
When an object lacks permission s3fs assumes it has the most restrictive permissions, `000`.  Could you try mounting with `-o umask=027` provides a default permission?  Or try compiling from master which should also work around this symptom.

**Comment by gaul** [comment]
Can you retest with 1.85 and reopen this issue if symptoms persist?
