### ISSUE TITLE
unable to mount

### ISSUE THREAD

**Issue by nbecker** [s3fs-fuse/s3fs-fuse#869]
#### Version of s3fs being used (s3fs --version)
_example: 1.00_
Amazon Simple Storage Service File System V1.84(commit:d9e89de) with OpenSSL

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
_example: 2.9.4_
rpm -qi fuse
Name        : fuse
Version     : 2.9.7
Release     : 14.fc29
#### Kernel information (uname -r)
_command result: uname -r_
4.19.5-300.fc29.x86_64

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_command result: cat /etc/os-release_

fedora F29

#### s3fs command line used, if applicable
```
s3fs mount ndbecker-results ./mnt  -o dbglevel=info 
s3fs: unable to access MOUNTPOINT ndbecker-results: No such file or directory
```
#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
### Details about issue

Works with aws-cli:

 aws s3 ls ndbecker-results
                           PRE ALIGN_tdlc_176_fft_real_mrc_wiener_det_equal,dmrs=4/
2018-07-11 08:46:54       3753 run_align_tdlc_176_dmrs=2.py

But s3fs says:
s3fs mount ndbecker-results ./mnt  -o dbglevel=info 
s3fs: unable to access MOUNTPOINT ndbecker-results: No such file or directory

**Comment by gaul** [comment]
Instead of `s3fs mount ndbecker-results ./mnt` could you try `s3fs ndbecker-results ./mnt`?  If you pass `-f` to the original command line you should see:

```
s3fs: specified unknown third optioni(./mnt).
```

**Comment by nbecker** [comment]
Yes, s3fs ndbecker-results ./mnt does work.  Thanks!
