### ISSUE TITLE
Can't mount S3 bucket on Linux

### ISSUE THREAD

**Issue by lwg001** [s3fs-fuse/s3fs-fuse#872]
I have s3fs installed and ready to go.  I'm to the point where I need to mount the S3 bucket on the OS but I can't seem to get the paths right.

"s3fs mybucket /path/to/mountpoint -o passwd_file=${HOME}/.passwd-s3fs"

What is mybucket?  The directory that I want to mount it to is https://s3.console.aws.amazon.com/s3/buckets/cds-datalake/MODEL_VAR_DB/SourceData/temp/
Is mybucket the full path name?  

Any advice would be beneficial.

**Comment by swt2c** [comment]
It looks like cds-datalake is probably your bucket name.

**Comment by lwg001** [comment]
Thanks for the response, the only problem that I have with that is the Datalake folder is huge and I want a sub directory.  Is there any way to get a sub directory mounted?

**Comment by ggtakec** [comment]
I'm sorry for my late reply.

You can mount the directory in bucket to mount point as like to do as @gaul said.

I close this, but if there is an OS you want to support other than above, please create a new issue.
Thanks in advance for your assistance.
