### ISSUE TITLE
Writing/reading files by 2 programs

### ISSUE THREAD

**Issue by nikt12** [s3fs-fuse/s3fs-fuse#876]
#### Version of s3fs being used (s3fs --version)
V1.84

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
2.9.8

opensuse
```
### Details about issue
Hello, folks.
I have some question and it could be quite general, because I think that I don't understand everything.
I mounted bucket and tried to open there file and write to it first time (fopen() and fprintf() calls were invoked, after that file wasn't closed, program waiting for input).
After that I invoked 'cat <fullfilename path>' from second terminal and it ended without any output.
Then I attempt to write second time from first program (be aware, it was not closed after first write) and close it, after all these actions I have only second time written information.

I understand that if we will write from 2 programs to one file - only later attempt will be succeeded.
But why it happens (first written info disappeared) if we try to read file with 'cat' during another program keeping its file descriptor?

**Comment by nikt12** [comment]
@ggtakec What do you think about this issue?

**Comment by gaul** [comment]
s3fs does not flush a file until it is closed.  Generally there is high latency from the s3fs client to the S3 server so this batching improves performance.  You could try adding an `fsync`/`fdatasync` which should flush to S3.  However multi-client workloads are not well-supported; NFS is a better choice when you need fine-grained coordination.

**Comment by ggtakec** [comment]
I'm sorry for my late reply.

s3fs uploads a file to S3 when it flushes (closes) to the file.
That is, when the second program opens the file, the file has not yet been updated. Therefore the old contents are displayed.
If the first program closes the file, the file contents will be uploaded and updated.
In s3fs, `only later attempts will be succeeded` means `the last process to close(flush)`.
Also, as @gaul stated, I think that there are cases where s3fs does not provide enough care.

I will close this, but if the problem persists, please reopen or post a new issue.
Thanks in advance for your assistance.
