### ISSUE TITLE
support LTS versions like rhel6/centos6

### ISSUE THREAD

**Issue by f1-outsourcing** [s3fs-fuse/s3fs-fuse#878]
Would be nice if you take into account to support LTS versions like rhel6 and centos6.

**Comment by gaul** [comment]
Do these instructions work:

https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes#installing-on-centos-6-s3fs-version-174

I believe that RHEL 6 has an older FUSE which makes packaging it difficult.  @juliogonzalez might know more.

**Comment by juliogonzalez** [comment]
@f1-outsourcing, sadly s3fs-fuse can't officially support RHEL6/CentOS 6 anymore, as the fuse version there is breaking some basic functionality. That's the reason I am not even submitting `s3fs-fuse` package for CentOS6.

That said, you can build install an updated version of fuse (2.8.4 at least), but keep in mind the consequences, specially if you are using RHEL6.

I just updated all the instructions at https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes#fedora--centos--rhel. I even added a link to one of my personal repositories so you can create RPMs (in fact I am using that repository to submit the `s3fs-fuse` package for Fedora and EPEL -RHEL/CentOS-).

I hope this answers your question (if so, please close the issue)

**Comment by juliogonzalez** [comment]
@f1-outsourcing can this issue be closed?

**Comment by gaul** [comment]
Please reopen if the suggested workaround does not address your symptoms.
