### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by SimplySynced** [s3fs-fuse/s3fs-fuse#879]
I've gone through the few things people have posted.  I've been able to mount the s3 bucket and I can see the files in there on my ubuntu server.  However I'm trying to use a media server emby and it can see the mount but then I'm guessing its an issue were the permissions are not correct.  

drwx------ 1 root root 0 Dec 31  1969 s3
drwxr-xr-x 2 root root 0 Dec  5 10:24 tv

the TV works just fine.  I tried

root@BlackWidow:/mnt# chmod 755 s3
chmod: changing permissions of 's3': Input/output error

I have the right access and secret key.  I've mounted the directory using

s3fs streamtest /mnt/s3 -o passwd_file=${HOME}/.passwd-s3fs -o url=http://s3.wasabisys.com/ -o use_path_request_style

Is there anyway to get it to have the other permissions as I believe this is why I can not get emby to recognize it.

**Comment by postsal** [comment]
I also have the same issue,When I uploaded the file, I found that I can't modify it.

**Comment by gaul** [comment]
When an object lacks permission s3fs assumes it has the most restrictive permissions, `000`.  Could you try mounting with `-o umask=027` provides a default permission?  Or try compiling from master which should also work around this symptom.

**Comment by postsal** [comment]
thanks,according to your suggestion, i fixed it,Here is my commond : 
`s3fs <your-s3-bucket-name> <your-mount-point> -o url=<your-s3-endpoint>,allow_other,uid=`id -u`,umask=0000,mp_umask=0000`.

**Comment by gaul** [comment]
Could you test with the latest 1.85 and reopen this issue if symptoms persist?
