### ISSUE TITLE
How do I undo this?

### ISSUE THREAD

**Issue by myfitment** [s3fs-fuse/s3fs-fuse#880]
#### Version of s3fs being used (s3fs --version)
1.84

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
Not available

#### Kernel information (uname -r)
4.4.105-engineyard

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
NAME="Engine Yard Gentoo Linux"
ID=eygl
ID_LIKE=gentoo
VERSION_ID=2016.06
BUILD_ID=2016.06.018.final
PRETTY_NAME="Engine Yard Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="http://www.engineyard.com/"
SUPPORT_URL="https://support.cloud.engineyard.com/"
BUG_REPORT_URL="https://support.cloud.engineyard.com/"

#### s3fs command line used, if applicable
sudo s3fs <mybucket> /mnt/backups -o passwd_file=/etc/passwd-s3fs -o nonempty

#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
    set_moutpoint_attribute(3291): PROC(uid=0, gid=0) - MountPoint(uid=0, gid=0, mode=40700)
fuse: unknown option `dbglevel=info'

### Details about issue
How do I undo this? I had a directory /mnt/backups that contained a 38GB database backup file.

After running the above command, the user I am logged in as "not root" can no longer see the directory /mnt/backups at all. Doing an 'ls' inside of /mnt gives:

d?????????  ? ?    ?         ?            ? backups

So, that's pretty awful. As the root user, it shows up like this:

drwx------  1 root root      0 Jan  1  1970 backups

But if I go into the directory, it's empty.

And yet, the file isn't gone. I can still see its footprint using 'df -k'.

So my question is, how do I undo this s3fs command? At this point I just want it to go away in the hopes that it hasn't done anything destructive.

**Comment by gaul** [comment]
Can you double-check your s3fs command line?  The following does not contain a bucket name:

> sudo s3fs /mnt/backups -o passwd_file=/etc/passwd-s3fs -o nonempty

**Comment by gaul** [comment]
Please reopen if symptoms persist.
