### ISSUE TITLE
Are there known conflicts between s3fs-fuse and drupal s3fs module?

### ISSUE THREAD

**Issue by knightfoxapps** [s3fs-fuse/s3fs-fuse#881]
Hi Guys,

I have 1 server with s3fs-fuse running perfectly and it mounts as required. A second server is running Drupal 8 with the s3fs module but the second server cannot see content copied to the s3 bucket from server 1. Now I am thinking to also install s3fs-fuse on server 2 and mount the same s3 bucket as well. Could there be a conflict with the s3fs drupal module which we use for images?

Thanks,
E

**Comment by gaul** [comment]
This should work except that you need to set `-o stat_cache_expire=SECONDS` with some value for SECONDS.  Can you test and report back?

**Comment by gaul** [comment]
Please reopen if the suggested workaround does not address your symptoms.
