### ISSUE TITLE
s3fs autogen.sh install error

### ISSUE THREAD

**Issue by rosamdnb** [s3fs-fuse/s3fs-fuse#886]
--- Make commit hash file -------
--- Finished commit hash file ---
--- Start autotools -------------
/bin/grep: line 1: lrwxrwxrwx.: command not found
autom4te: need GNU m4 1.4 or later: /usr/bin/M4
aclocal: error: echo failed with exit status: 1
--- Finished autotools ----------

I am attempting to install on a RedHat EC2 instance and get the above error.

What am I doing wrong?

**Comment by juliogonzalez** [comment]
It seems to me that you don't have grep installed.

It's strange, since `grep` is even available at CentOS docker image as it's a basic tool, so maybe your instance got `grep`removed for some reason.

Try to install it back with:
```yum install grep```

**Comment by rosamdnb** [comment]
[root@Neo4J]# yum install grep
Loaded plugins: amazon-id, product-id, rhui-lb, search-disabled-repos, subscription-manager, versionlock
This system is not registered with an entitlement server. You can use subscription-manager to register.
Package grep-2.20-3.el7.x86_64 already installed and latest version
Nothing to do

**Comment by juliogonzalez** [comment]
It seems `/bin/grep: line 1: lrwxrwxrwx.: command not found` is misleading.

So far I am unable to reproduce this on CentOS7 with only the packages provided by the image + git + automake.

Is automake installed, as well as all required dependencies to build s3fs installed? It would also help if you tell the s3fs version you are trying to compile (I guess it's just `master` branch, from the Git repository) and the RHEL version

If you do not need s3fs from `master`, remember that the latest stable is available at the EPEL repositories.

**Comment by juliogonzalez** [comment]
That could fix it yes. But I wonder how is it that `aclocal` is present (as `autogen.sh` can't even run without it), while `m4` is absent.

`m4` is a dependency of the package `automake` that provides `aclocal`.

So basically if you remove the package `m4`, `automake` and `autoconf` are removed, and then `autogen.sh` just complains about `aclocal` being missing:

```
[root@15f18b5fa25a s3fs-fuse]# yum remove -q m4  

===============================================================================================================================================================================================================================================================================
 Package                                                           Arch                                                            Version                                                                Repository                                                      Size
===============================================================================================================================================================================================================================================================================
Removing:
 m4                                                                x86_64                                                          1.4.16-10.el7                                                          @base                                                          513 k
Removing for dependencies:
 autoconf                                                          noarch                                                          2.69-11.el7                                                            @base                                                          2.2 M
 automake                                                          noarch                                                          1.13.4-3.el7                                                           @base                                                          1.7 M

Transaction Summary
===============================================================================================================================================================================================================================================================================
Remove  1 Package (+2 Dependent packages)

Is this ok [y/N]: y

root@15f18b5fa25a s3fs-fuse]# ./autogen.sh 
--- Make commit hash file -------
--- Finished commit hash file ---
--- Start autotools -------------
./autogen.sh: line 39: aclocal: command not found
--- Finished autotools ----------
```


@rosamdnb I am curious: how are you managing the devel toolchain? With `yum`, or just building everything (including automake, autoconfig, m4, etc) manually?

**Comment by juliogonzalez** [comment]
@rosamdnb is this fixed?

**Comment by roonie007** [comment]
`yum install automake` solved this issue for me

**Comment by gaul** [comment]
Please reopen if the provided suggestion does not resolve your issues.  Also consider using the distribution packages to avoid having to compile s3fs yourself.

**Comment by yuvenation** [comment]
yum install automake worked for me too
