### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dgrnbrg** [s3fs-fuse/s3fs-fuse#887]
Hello, I was wondering when you're going to cut a new release on PyPI to support the standard AWS credentials?

Thank you!

**Comment by arnoldad** [comment]
Similarly for homebrew. Building from source works great, but obviously less convenient.

**Comment by gaul** [comment]
@ggtakec is the only one who can tag a release but you can help out the project by testing against master and reporting issues.

**Comment by pheanex** [comment]
How about adding a new milestone "1.8.5" and include all the issues we think should be solved before release?

**Comment by gaul** [comment]
#935 is a must-fix or must-revert issue; I am still evaluating a fix.

**Comment by gaul** [comment]
#935 fixed.  I would like 1.85 to include #967 but otherwise we should be ready to release.

**Comment by ggtakec** [comment]
We began preparing for the release of the new version.
#976
