### ISSUE TITLE
does s3fs supports versioned bucket?

### ISSUE THREAD

**Issue by hetzbh** [s3fs-fuse/s3fs-fuse#91]
Hi,

I would like to use Amazon's S3 versioned bucket, so if someone deletes a file, it caan be restored from the S3 panel.

Does s3fs supports versioned bucket?

**Comment by ggtakec** [comment]
I think s3fs can mount versioned bucket.
But if the object is removed and restored, you need to access S3 console on AWS.
Because s3fs does not have restoring function/utility.

Regards,

**Comment by ggtakec** [comment]
Please see #67 too.
I'm closing this issue, if you have more problem, please post new issue or reopen this issue.

Thanks in advance for your kindness.
