### ISSUE TITLE
Consider changing `-o notsup_compat_dir` default

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#927]
#571 added an optimization to disable the legacy `dirname_$folder$` checking.  Should s3fs default to the optimization on since most installations should use the `dirname/` format and have an option to check for the legacy folders instead?

**Comment by ggtakec** [comment]
@gaul 
Currently, I agree that I no longer need to search for the `_$folder$` object.

In addition to this, s3fs supports the `no directory object` case.
This is when there is no intermediate path `dir` or `dir/` and there is only a `dir/path` object.
I think we need to continue to support this pattern.

With the fix of #571 , `support_compat_dir flag` is defined in s3fs.cpp. However, this flag is also used to check the `no directory object` above.
So we need to think about the correspondence of the `no directory object` case with this issue as well.

I think we let s3fs not check the `_$folder$` object by default, but a case of `no directory object` should continue checking.

Please let me know your opinion about it.

**Comment by gaul** [comment]
We should also add a script to detect and convert buckets which use the older compat dirs.
