### ISSUE TITLE
man page and --help are inconsistent

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#929]
We should add some mechanism to keep these in sync if we cannot have a single source of truth.

**Comment by ggtakec** [comment]
@gaul Thanks

**Comment by gaul** [comment]
Can you repoen this issue?  I suspect we have other inconsistencies and need some kind of script to detect them.

**Comment by ggtakec** [comment]
@gaul OK, reopen this.
(We have to check the man page and help options, and WIKI.)

**Comment by gaul** [comment]
I believe that all options are now documented except for `createbucket`, `host`, and `servicepath`.  The first is hidden for only tests while the latter I am not sure what they do.
