### ISSUE TITLE
Forklift/ Permissions.

### ISSUE THREAD

**Issue by gfaulk09** [s3fs-fuse/s3fs-fuse#956]
### Details about issue

On MacOS, using forklift and Fuse to mount a drive that's over FTP. No problem mounting the drive, but having a problem with permissions. I know a little code, but in all honestly, I'm completely lost on what to put and where.

**Comment by gfaulk09** [comment]
Also, can't find the fuse.conf file under etc/

**Comment by gaul** [comment]
Please test again with 1.85 and reopen this issue if symptoms persist.
