### ISSUE TITLE
s3fs-fuse make issue

### ISSUE THREAD

**Issue by akhtar4ever** [s3fs-fuse/s3fs-fuse#963]
getting error while running make command 

### Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._
_Keep in mind that the commands we provide to retrieve information are oriented to GNU/Linux Distributions, so you could need to use others if you use s3fs on macOS or BSD_

#### Version of s3fs being used (s3fs --version)
_example: 1.00_

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
**pkg-config --modversion fuse
2.9.2**

#### Kernel information (uname -r)
_command result: uname -r_
 **uname -r
3.10.0-514.el7.centos.plus.i686**

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
_command result: cat /etc/os-release_
 **cat /etc/os-release
NAME="CentOS"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"**

#### s3fs command line used, if applicable
```
```
#### /etc/fstab entry, if applicable
```
```
#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
_if you execute s3fs with dbglevel, curldbg option, you can get detail debug messages_
```
```
### Details about issue

_While running make getting the below error:
######################################
In file included from addhead.h:24:0,
                 from s3fs.cpp:54:
/usr/include/regex.h:138:9: error: ‘VOID’ does not name a type
 typedef __REG_VOID_T re_void;
         ^
/usr/include/regex.h:298:1: error: ‘MODULE_SCOPE’ does not name a type
 MODULE_SCOPE int __REG_WIDE_COMPILE(regex_t *, __REG_CONST __REG_WIDE_T *, size_t, int);
 ^
/usr/include/regex.h:307:1: error: ‘MODULE_SCOPE’ does not name a type
 MODULE_SCOPE int __REG_WIDE_EXEC(regex_t *, __REG_CONST __REG_WIDE_T *, size_t, rm_detail_t *, size_t, regmatch_t [], int);
 ^
/usr/include/regex.h:309:1: error: ‘MODULE_SCOPE’ does not name a type
 MODULE_SCOPE re_void regfree(regex_t *);
 ^
/usr/include/regex.h:310:1: error: ‘MODULE_SCOPE’ does not name a type
 MODULE_SCOPE size_t regerror(int, __REG_CONST regex_t *, char *, size_t);_

**Comment by gaul** [comment]
@juliogonzalez does this look familiar?

@akhtar4ever EPEL now provides CentOS packages; do these work for you?  See README for instructions.

**Comment by juliogonzalez** [comment]
@gaul sorry, I didn't notice this.

@akhtar4ever, I assume you were using master before 1.85 was released (next time, please specify, as you didn't fill the filed for the  version)

I only check stable versions (while building RPMs), but at this moment:

- 1.84: [unable to reproduce](https://jenkins.juliogonzalez.es/job/s3fs-fuse-rpm-build-free/DISTRO=centos7,label=docker/12/)
- 1.85: [unable to reproduce](https://jenkins.juliogonzalez.es/job/s3fs-fuse-rpm-build-free/DISTRO=centos7,label=docker/11/)

@akhtar4ever: can you still reproduce, or can this bug be closed?

**Comment by gaul** [comment]
Please reopen if you can reproduce these symptoms.
