### ISSUE TITLE
fuse failed to exec fusermount: No such file or directory

### ISSUE THREAD

**Issue by xyzdcgan** [s3fs-fuse/s3fs-fuse#968]
s3fs mount s3 bucket on ec2 instance.

Using 3.0 s3fs 

while running 

s3fs -o use_cache=/tmp/cache mybucket /s3mnt

getting error

fuse: failed to exec fusermount: No such file or directory

also tried 

s3fs mybucket ${HOME}/s3image -o passwd_file=${HOME}/.passwd-s3fs

but getting same error also tried to debug and getting this 

s3fs.cpp:set_mountpoint_attribute(4329): PROC(uid=1000, gid=1000) - MountPoint(uid=1000, gid=1000, mode=40775)

Used this to mount s3 in ec2 and all steps worked only not able not mount

https://www.interserver.net/tips/kb/mount-s3-bucket-centos-ubuntu-using-s3fs/

**Comment by gaul** [comment]
Do you have the FUSE utilities installed?

**Comment by gaul** [comment]
Please reopen if the suggested workaround does not address your symptoms.
