### ISSUE TITLE
Debian Bug report - abuses AC_CHECK_FILE 

### ISSUE THREAD

**Issue by ggtakec** [s3fs-fuse/s3fs-fuse#979]
#### Version of s3fs being used (s3fs --version)
all version

#### Version of fuse being used (pkg-config --modversion fuse, rpm -qi fuse, dpkg -s fuse)
n/a

#### Kernel information (uname -r)
n/a

#### GNU/Linux Distribution, if applicable (cat /etc/os-release)
n/a

#### s3fs command line used, if applicable
n/a

#### /etc/fstab entry, if applicable
n/a

#### s3fs syslog messages (grep s3fs /var/log/syslog, journalctl | grep s3fs, or s3fs outputs)
n/a

### Details about issue
There is a bug report in debian.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923581
Since the incorrect instruction is specified in configure.ac, it should be corrected (a patch in bug report).

**Comment by gaul** [comment]
@ggtakec can we close this issue?

**Comment by ggtakec** [comment]
After fixing, I do not seem to have a problem, so I close it.
