### ISSUE TITLE
Is there any way to check if data is mounted already?

### ISSUE THREAD

**Issue by soolaugust** [s3fs-fuse/s3fs-fuse#986]
Hi,

I am trying to use s3fs-fuse docker image as init container in Kubernetes, as init container need to be completed status eventually. so is there any way to check if data is mounted already and stop s3fs-fuse process.

Any idea for this?

**Comment by soolaugust** [comment]
I solved by using `mount | grep s3fs`, current seems okay. If any better idea, please contact me. Thanks ❤️

**Comment by kahing** [comment]
There's also a `mountpoint` command

**Comment by gaul** [comment]
Does `-o nonempty` address this issue?

**Comment by soolaugust** [comment]
@kahing `mountpoint` is better, thx 👍 

@gaul `-o nonempty` will check if target directory is not empty. If not empty, will not mount. this is a little different from my situation, I need to check mount is successfully or not.

**Comment by gaul** [comment]
@soolaugust Would it help if s3fs had a mode that was similar to `-f` but only ran in background when the mount was successful?

**Comment by soolaugust** [comment]
@gaul I think this way would be helpful for other situations. As process in init container should exit eventually, so s3fs should exit instead of running in background in my situation.

**Comment by gaul** [comment]
This is a bit tricky since s3fs should only check in the foreground for interactive terminals.  When run headless, e.g., fstab, performing a network operation could stall the boot process.  Maybe checking `isatty` suffices?

**Comment by kahing** [comment]
Stalling the boot process is the right thing to do given that if you mount it in fstab you may need the data at boot time (or container start up time). NFS for instance has a bg mount option that you can adopt for the opposite behavior.

**Comment by soolaugust** [comment]
Thanks, I will check those ideas :)
