### ISSUE TITLE
Install / configure fails on ubuntu

### ISSUE THREAD

**Issue by lucheng1** [s3fs-fuse/s3fs-fuse#99]
This is almost the same issue as #81 but at a slightly different line number: 4270
./configure: line 4270: syntax error near unexpected token common_lib_checking,' 
./configure: line 4270:PKG_CHECK_MODULES(common_lib_checking, fuse >= 2.8.4 libcurl >= 7.0 libxml-2.0 >= 2.6)'

All the dependencies listed seem to check out including the following: 
pkg-config
libssl-dev

I checked the config.log and the only error I saw was error on gcc -V and -qversion option and I took those out and that made no difference.

**Comment by movermeyer** [comment]
I had the same issue.
In my case, I was missing the pkg-config package.

    apt-get install pkg-config
    ./autogen.sh
Fixed it for me.

**Comment by mpilon** [comment]
@lucheng1 tried everything -- yours worked.

**Comment by mrnafanya** [comment]
Thanks. That fix the issue for me.
