### ISSUE TITLE
build fail on Debian 8

### ISSUE THREAD

**Issue by gggeek** [s3fs-fuse/s3fs-fuse#990]
Hello

I tested building ver. 1.85 on a Debian 8 image (from aws base), and I get the following error message:

```
./configure: line 4965: syntax error near unexpected token `common_lib_checking,'
./configure: line 4965: `PKG_CHECK_MODULES(common_lib_checking, fuse >= ${min_fuse_version} libcurl >= 7.0 libxml-2.0 >= 2.6 )'
```

**Comment by gggeek** [comment]
ok, seems a bit more github search-fu was required. Installing pkg-config might be a step in the good direction...

**Comment by juliogonzalez** [comment]
Are you following https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes#debian--ubuntu ?

**Comment by gggeek** [comment]
That did the trick! Cheers, and double-plus thumbs up for instant response.
Do you think it is worth mentioning that page in the main readme file?

**Comment by juliogonzalez** [comment]
@gggeek, it is there.

Check https://github.com/s3fs-fuse/s3fs-fuse#compilation-and-installation-from-sources:

> These are generic instructions to compile from the master branch, and should work on almost any GNU/Linux, macOS, BSD, or similar.
>
> **If you want specific instructions for some distributions, check the [wiki](https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes).**
>
> Keep in mind using the pre-built packages when available.
>
> Ensure your system satisfies **build and runtime** dependencies for:

**Comment by gggeek** [comment]
doh. I am blind!

**Comment by juliogonzalez** [comment]
@gggeek maybe the instructions are there, but the README.md is now just too big. I just proposed addressing that at #993. 

If yoy think it's a good idea, feel free to support it with a vote at the description (:+1:)
