### ISSUE TITLE
s3fs not honoring _netdev option

### ISSUE THREAD

**Issue by gilbahat** [s3fs-fuse/s3fs-fuse#996]
Hi,

Using ubuntu xenial (latest as of time of writing) and fuse 2.9.4, I still manage to get this error, even though looking at the code it's supposed to be ignored.

$ sudo mount -a
fuse: unknown option _netdev' fuse: unknown option _netdev'
fuse: unknown option _netdev' fuse: unknown option _netdev'

my fstab:
//snipped
bucket-name-redacted /some/path s3fs auto,_netdev,allow_other,ro,uid=1000,gid=1000,iam_role,endpoint=eu-west-1 1 1
(3 more of these, that's why error appears 4 times)

$ ls -l /sbin/mount.s3fs
lrwxrwxrwx 1 root root 13 Apr 2 10:11 /sbin/mount.s3fs -> /usr/bin/s3fs

$ dpkg -l | grep fuse
ii fuse 2.9.4-1ubuntu3.1 amd64 Filesystem in Userspace
ii libfuse2:amd64 2.9.4-1ubuntu3.1 amd64 Filesystem in Userspace (library)

$ dpkg -l | grep s3fs
ii s3fs 1.82-1ubuntu16.04.1alindt amd64 FUSE-based file system backed by Amazon S3

this is annoying because the system fails to mount the volumes on startup when I remove this option (possibly some race condition) but sudo mount -a works. I figured _netdev could fix this but then I ran into this error...

libfuse claims this is an s3fs bug:
https://github.com/libfuse/libfuse/issues/390

this might be similar to https://github.com/s3fs-fuse/s3fs-fuse/issues/297, but a bit different nonetheless.
please advise

**Comment by ggtakec** [comment]
@gilbahat Thanks for your report.
s3fs does not ignore its _netdev option now.
I referred to the code of sshfs and tried to ignore some options as well.
This code is just before merging into master as PR.

If you can, try the master branch code after the merge.
Thanks in advance for your help.

**Comment by ggtakec** [comment]
@gilbahat I merged PR #1000 which fixed this problem.
Please try to use latest master branch code.
I'm closing this issue, but if this problem persists, please reopen this issue.
